;******************************************************************************
;*** Bank *********************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[BuildingTypes]
+				= AMBank
+				= CHBank

;------------------------------------------------------------------------------
; CITY15 (TS)
[AMBank]
;----- Text -----
Name				= 2nd National Bank
UIName				= name:bank_am
UIDescription			= desc:bank_am
Nominal				= yes
;----- Taxonomy -----
IsBase				= no
BaseNormal			= no
;----- Body ----
Strength			= 500
;----- Armor -----
Armor				= heavy
Spyable				= yes				; Thief/Spy can steal from it. 
Capturable			= yes
;----- Availability -----
Owner				= Neutral			; American, but not part of the armed forces. 
TechLevel			= -1
Cost				= 10000
;----- Score -----
Points				= 20				; ts: 5
;----- UI -----
; RadarInvisible		= yes
;----- Load -----
Storage				= 1000
CrateBeneath			= yes
CrateBeneathIsMoney		= yes
;----- Attach -----
Upgrades			= 999
;----- Damage & Destruction -----
DamageParticleSystems		= SmallGreySSys,BigGreySmokeSys
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris			= 8
;----- Produce -----
ProduceCashStartup		= 750
ProduceCashAmount		= 50
ProduceCashDelay		= 100 ; Frame delay between Amounts

;------------------------------------------------------------------------------
[CHBank]
;----- Text -----
UIName= Name:bank_ch
Name= Bank Swiss

