;
;
;

;------------------------------------------------------------------------------
[InfantryTypes]
+				= Ogre

;------------------------------------------------------------------------------
; Ogre
[Ogre]
;----- Text -----
Name				= Ogre
DisplayName			= object:ogre
UIName				= name:ogre
UIDescription			= desc:ogre
;----- Taxonomy -----
Category			= Soldier
NotHuman			= yes
;----- Gfx -----
; Image				= MUTANT3
;----- Body -----
Strength			= 350
Size				= 2					; Same as Brute. 
PhysicalSize			= 1
Weight				= 1.5
;----- Weapons -----
Primary				= Axe
Secondary			= Frenzy				; Trigger bloodaxe/atk plus/def minus. 
;----- Armor -----
Armor				= mail
Crushable			= no
; ImmuneToVeins			= yes					; They are quite heavy... 
;----- Availability -----
Side				= Neutral
Owner				= Neutral
House				= Incidental
TechLevel			= 1
Prerequisite			= OGFort
Cost				= 200
;----- UI -----
Pip				= green
OccupyPip			= PersonGreen
;----- AI -----
Fearless			= yes
ThreatPosed			= 15
;----- Perception -----
Sight				= 3
Cost=650
Points=5
;----- Sfx -----
VoiceSelect			= SelectOgre
VoiceMove			= CmdMovOgre
VoiceAttack			= CmdAtkOgre
VoiceFeedback			= FearOgre
VoiceDie			= DieOgre
;----- Attach -----
; AttachEffect.Types		= nearsight				; Stealth which is removed by any unit coming to within 2 cells of this unit. 
;----- Movement -----
Speed				= 4
Locomotor			= {4A582744-9839-11d1-B709-00A024DDAFD1}
MovementZone			= InfantryWood				; Can walk through trees. 
SpeedType			= FootWood
;----- Veterancy -----
EliteAbilities			= STRONGER, FIREPOWER
