;******************************************************************************
;*** Tank Light ***************************************************************
;******************************************************************************
; The RA-era Light Tank. 
; This unit is distinct from the Bradley. 
; Upgrades: Machine Gun, ATGM, Faster, Sight, Sensors, Target Laser/Painter, Sniper. 
; [TnkLgtAmph] and [TnkLgtLynx] derives from this. 

;------------------------------------------------------------------------------
[VehicleTypes]
+				= TnkLgt			; Tank Light Beagle, Rookie, Upgrade nul
+				= TnkLgt_a1			; Tank Light Beagle, Rookie, Upgrade Missile
+				= TnkLgt_e1			; Tank Light Beagle, Veteran, Upgrade nul
+				= TnkLgt_a1e1			; Tank Light Beagle, Veteran, Upgrade Missile

Terrain = Rock, Sand, NBRock, Ramp
UnitGroup			= FromFactory

DamageEffect			= MediumDamageFX
ChaosEffect			= MediumChaosFX
HawkEffect			= MediumHawkFX
AllowedToStartInMultiplayer	= yes
Starportable			= yes
CrateGift			= yes
CrateGoodie			= yes

;------------------------------------------------------------------------------
; Light Tank - VC's comment: Okies, so I put the T-34 to the Sov side, and this one goes into allied (where T-34 used to be).
; It's a simple side swap and everyone's happy! ('course it still requires me to change the vxl, because current LTNK voxel is crappy).
; Formerly LTNK, LightTank. 
; RA-era Light Tank
; Formerly [TankLight]. 
[TnkLgt]
$Inherits			= IFVBrad
Speed=9
Points=30
;----- Text -----
Name				= Tank Light
UIName				= name:tnk_lgt
UIDescription			= desc:tnk_lgt
DisplayName			= object:tnk_lgt
;----- Gfx -----
Image				= tnk_lgt				; ltnk
ZFudgeColumn			= 8
ZFudgeTunnel			= 13
;----- Taxonomy -----
Category			= AFV
;----- Body -----
Health				= 2400
Strength			= 300
Weight				= 3.5
Size				= 3
;----- Weapons -----
Primary				= CannonMM75
Elite				= CannonMM90
ElitePrimary			= CannonMM90
EliteSecondary			= 
NoAmmoWeapon			= 
OpportunityFire			= yes
TargetLaser			= yes
;----- Armor -----
Armor				= heavy
StormDamage			= 10
;----- Availability -----
Side				= Terran
Owner				= Allies			; British, French, Germans, Americans, Alliance
; House				= 
TechLevel			= 4				; 3
Prerequisite			= UNFactory
PrimaryBuilding			= UNFactory
; SecondaryBuilding		= 
Cost				= 700				; 550 ; 500
BuildTimeMultiplier=1.5;Individual control of build time
TechLevel=6
;----- Score -----
Points				= 25
;----- Load -----
Crewed				= yes
Ammo				= 1
;----- Turrets -----
Turret				= yes
TurretAttach			= UNLightTankTurret
;----- Perception -----
Sight				= 4;8
Sight				= 5						; 8
;----- Sfx -----
VoiceSelect			= GenAllVehicleSelect				; 25-I000,25-I002,25-I004,25-I006
VoiceMove			= GenAllVehicleMove				; 25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack			= GenAllVehicleAttackCommand			; 25-I014,25-I022,25-I024,25-I026
VoiceFeedback			= 
DieSound			= GenVehicleDie
MoveSound			= GrizzlyTankMoveStart
CrushSound			= TankCrush
;----- Movement -----
Locomotor			= Drive
MovementZone			= Destroyer
Terrain				= Rock, Sand, NBRock, Ramp
Speed				= 7						; 8
SpeedType			= Track						; Not sure what the default is, but since this derives from an armored car 
Tracked				= yes
ROT				= 5
IsTilter			= yes
; Accelerates			= no
Crushes				= yes
Crusher				= yes
;----- UI -----
IsSelectableCombatant		= yes
;----- AI -----
AiTank				= yes
ThreadPosed			= 15				; 40
TastyToWorms			= True
WormAttraction			= 7
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys, SmallGreySSys
DamageSmokeOffset		= 100, 100, 275
ExplosionType			= Explosion
Explosion			= TWLT070, S_BANG48, S_BRNL58, S_CLSN58, S_TUMU60
Debris				= DebrisLage
DebrisTypes			= TnkLgt, TnkLgtTur, TnkLgtBarl, ShellMM75, gastank, piece
DebrisMaximums			= 1, 1, 1, 2, 2, 4
DebrisMinimums			= 0, 0, 0, 1, 1, 2
MaxDebris			= 
MinDebris			= 
;----- Veterancy -----
; VeteranAbilities		= STRONGER,FIREPOWER,SIGHT,FASTER	; +ROF
; EliteAbilities		= SELF_HEAL,STRONGER,FIREPOWER,ROF




; Eligible upgrades: Auxiliary Drone, Nanite Repair, Autoloader, Charged Shot. 
; Has upgrades: Sight Machine Gun, ATGM, Faster, Sight, Sensors, Target Laser/Painter, Sniper. 

; Lynx Tank
; Formerly [LYNX]. 
[TnkLgtLynx]
;----- Text -----
Name				= Tank Light Lynx
UIName				= name:tnk_lynx
UIDescription			= desc:tnk_lynx
;----- Gfx -----
Image				= lynx
;----- Body -----
Strength			= 350				; ER, Tank Light is 300, Tank Liberator is 370. 
;----- Perception -----
Sight				= 8				; Has Sight upgrade. 
;----- Weapons -----
Primary				= CannonMM90
;----- Armor ----
Prerequisite			= EAWEAP
Prerequisite.RequiredTheaters=TEMPERATE,URBAN,NEWURBAN
TargetLaser=yes
Strength=300;200
Category=AFV
Armor=heavy
Turret=yes
IsTilter=yes
TooBigToFitUnderBridge=true
TechLevel=2
Sight=8;6
Speed=7;8
CrateGoodie=no
Crusher=yes
Owner=YuriCountry,Alliance,Empire
Cost=700;600
Soylent=700
Points=25
ROT=5
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=LasherTankSelect
VoiceMove=LasherTankMove
VoiceAttack=LasherTankAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=LasherTankMoveStart
CrushSound=TankCrush
MaxDebris=3
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=100, 100, 275
Weight=3.5
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
;ZFudgeColumn=8
;ZFudgeTunnel=13
Size=3
OpportunityFire=yes
BuildTimeMultiplier=1.5;Individual control of build time
Landable=yes

; drone stuff
Storage=1	; this is needed as per Ares hack, don't ask me why - eligible for additional drone
DeploysInto=JAPOWR

[TargetLaser]
Damage=0
ROF=0
Range=6
Projectile=Invisible;Invisible4
Speed=40
Warhead=TargetLaserWH
;Bright=yes
OmniFire=yes

[TargetLaserWH]
ElectricAssault=yes
Verses=100%,100,100%,100%,100%,100%,100%,100%,100%,100%,100%
InfDeath=5

; Lynx Tank
[LYNXA]
UIName=NOSTR:Lynx Tank
Name=Lynx Tank
Image=LYNXA
Prerequisite=JAWEAP
Prerequisite.RequiredTheaters=SNOW
Primary=75mm
TargetLaser=yes
Strength=300;200
Category=AFV
Armor=heavy
Turret=yes
IsTilter=yes
TooBigToFitUnderBridge=true
TechLevel=2
Sight=8;6
Speed=7;8
CrateGoodie=no
Crusher=yes
Owner=YuriCountry,Alliance,Empire
Cost=700;600
Soylent=700
Points=25
ROT=5
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=LasherTankSelect
VoiceMove=LasherTankMove
VoiceAttack=LasherTankAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=LasherTankMoveStart
CrushSound=TankCrush
MaxDebris=3
; origional - Locomotor={55D141B8-DB94-11d1-AC98-006008055BB5}
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Destroyer ;gs FLAW needs to be changed to this when The Flaw is fixed
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=100, 100, 275
Weight=3.5
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
;ZFudgeColumn=8
;ZFudgeTunnel=13
Size=3
OpportunityFire=yes
BuildTimeMultiplier=1.5;Individual control of build time

; drone stuff
Storage=1	; this is needed as per Ares hack, don't ask me why - eligible for additional drone

; Lynx Tank
[LYNXD]
UIName=NOSTR:Lynx Tank
Name=Lynx Tank
Image=LYNXD
Prerequisite=JAWEAP
Prerequisite.RequiredTheaters=DESERT
Primary=75mm
TargetLaser=yes
Strength=300;200
Category=AFV
Armor=heavy
Turret=yes
IsTilter=yes
TooBigToFitUnderBridge=true
TechLevel=2
Sight=8;6
Speed=7;8
CrateGoodie=no
Crusher=yes
Owner=YuriCountry,Alliance,Empire
Cost=700;600
Soylent=700
Points=25
ROT=5
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=LasherTankSelect
VoiceMove=LasherTankMove
VoiceAttack=LasherTankAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=LasherTankMoveStart
CrushSound=TankCrush
MaxDebris=3
; origional - Locomotor={55D141B8-DB94-11d1-AC98-006008055BB5}
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Destroyer ;gs FLAW needs to be changed to this when The Flaw is fixed
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=100, 100, 275
Weight=3.5
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
;ZFudgeColumn=8
;ZFudgeTunnel=13
Size=3
OpportunityFire=yes
BuildTimeMultiplier=1.5;Individual control of build time

; drone stuff
Storage=1	; this is needed as per Ares hack, don't ask me why - eligible for additional drone













;------------------------------------------------------------------------------
; Mastiff Medium Tank
; Grizzly Tank (ra2/yr)
; Formerly [tank_mastiff_a]. 
[TankLgt2]
;----- Text -----
Name				= Mastiff Battle Tank
UIName				= name:
UIDescription			= desc:
;----- Gfx -----
Image				= GTNK
Primary=105mm
TechLevel=2
Sight=8
Speed=7
MaxDebris=2
ThreatPosed=15	; This value MUST be 0 for all building addons
ElitePrimary=105mmE
