;******************************************************************************
;*** Tank Light ***************************************************************
;******************************************************************************
; The RA-era Light Tank. 
; This unit is distinct from the Bradley. 
; Upgrades: Machine Gun, ATGM, Faster, Sight, Sensors, Target Laser/Painter, Sniper. 
; [TnkLgtAmph] and [TnkLgtLynx] derives from this. 

;------------------------------------------------------------------------------
[VehicleTypes]
+				= TnkLgt			; Tank Light Beagle, Rookie, Upgrade nul
+				= TnkLgt_a1			; Tank Light Beagle, Rookie, Upgrade Missile
+				= TnkLgt_e1			; Tank Light Beagle, Veteran, Upgrade nul
+				= TnkLgt_a1e1			; Tank Light Beagle, Veteran, Upgrade Missile

Terrain = Rock, Sand, NBRock, Ramp
UnitGroup			= FromFactory

DamageEffect			= MediumDamageFX
ChaosEffect			= MediumChaosFX
HawkEffect			= MediumHawkFX
AllowedToStartInMultiplayer	= yes
Starportable			= yes
CrateGift			= yes
CrateGoodie			= yes
Landable			= yes
Locomotor			= Drive
IsSelectableCombatant=yes
ROT				= 5
Landable=yes
; drone stuff
ManualEntry			= no
Storage				= 1	; this is needed as per Ares hack, don't ask me why - eligible for additional drone
IsTilter=yes
TooBigToFitUnderBridge=true
OpportunityFire=yes
Crusher=yes
DieSound=GenVehicleDie
CrushSound=TankCrush
OpportunityFire=yes
DieSound				= GenVehicleDie
CrushSound				= TankCrush
ActivateSound				= RobotTankOnline
DeactivateSound				= RobotTankOffline
; PipScale				= Tiberium	; purely visual effect (tells the player this unit is eligible)

;------------------------------------------------------------------------------
; Tank, Light (RA)
; Okies, so I put the T-34 to the Soviet side, and this one goes into allied (where T-34 used to be (in RealAlert). 
; It's a simple side swap and everyone's happy! ('course it still requires me to change the vxl, because current LTNK voxel is crappy). 
; - vc
; Light Tank [1TNK] (RA)
; Formerly LTNK, LightTank, TankLight. 
; Subsumes 
[TnkLgt]
$Inherits			= IFVBrad
;----- Text -----
Name				= Tank Light
UIName				= name:tnk_lgt
UIDescription			= desc:tnk_lgt
DisplayName			= object:tnk_lgt
;----- Gfx -----
Image				= tnk_lgt				; ltnk
ZFudgeColumn			= 8
ZFudgeTunnel			= 13
;----- Taxonomy -----
Category			= AFV
;----- Body -----
Health				= 2400
Strength			= 300
Weight				= 3.5
Size				= 3
;----- Weapons -----
Primary				= CannonMM75
Elite				= CannonMM90
ElitePrimary			= CannonMM90
EliteSecondary			= 
NoAmmoWeapon			= 
; TargetLaser			= yes
;----- Armor -----
Armor				= heavy
StormDamage			= 10
;----- Availability -----
Side				= Terran
Owner				= Allies			; British, French, Germans, Americans, Alliance
; House				= 
TechLevel			= 4				; 3 ; 6
Prerequisite			= UNFactory
PrimaryBuilding			= UNFactory
; SecondaryBuilding		= 
Cost				= 700				; 550 ; 500
BuildTimeMultiplier		= 1.5				; Individual control of build time
;----- Score -----
Points				= 25
;----- Load -----
Crewed				= yes
Ammo				= 1
;----- Turrets -----
Turret				= yes
TurretAttach			= UNLightTankTurret
;----- Perception -----
Sight				= 4;8
Sight				= 5						; 8
;----- Sfx -----
VoiceSelect			= GenAllVehicleSelect				; 25-I000,25-I002,25-I004,25-I006
VoiceMove			= GenAllVehicleMove				; 25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack			= GenAllVehicleAttackCommand			; 25-I014,25-I022,25-I024,25-I026
VoiceFeedback			= 
DieSound			= GenVehicleDie
MoveSound			= GrizzlyTankMoveStart
CrushSound			= TankCrush
;----- Movement -----

;Accelerates=false ; ER, but we make all vehicles default to using acceleration. 


Locomotor			= Drive
MovementZone			= Destroyer
Terrain				= Rock, Sand, NBRock, Ramp
Speed				= 7						; 8
SpeedType			= Track						; Not sure what the default is, but since this derives from an armored car 
Tracked				= yes
; Accelerates			= no
Crushes				= yes
Crusher				= yes
TiltsWhenCrushes		= yes						; should be the only one who is Rookie crusher and tilts when crushes. I think?
;----- UI -----
IsSelectableCombatant		= yes
PipScale			= none
NoManualEnter			= yes						; 
;----- AI -----
AiTank				= yes
ThreadPosed			= 15				; 40
TastyToWorms			= True
WormAttraction			= 7
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys, SmallGreySSys
DamageSmokeOffset		= 100, 100, 275
ExplosionType			= Explosion
Explosion			= TWLT070, S_BANG48, S_BRNL58, S_CLSN58, S_TUMU60
Debris				= DebrisLarge
DebrisTypes			= TnkLgt, TnkLgtTur, TnkLgtBarl, ShellMM75, gastank, piece
DebrisMaximums			= 1, 1, 1, 2, 2, 4
DebrisMinimums			= 0, 0, 0, 1, 1, 2
MaxDebris			= 
MinDebris			= 
;----- Veterancy -----
; VeteranAbilities		= STRONGER, FIREPOWER, SIGHT, FASTER	; +ROF
; EliteAbilities		= SELF_HEAL, STRONGER, FIREPOWER, ROF

Speed=9
Points=30

;------------------------------------------------------------------------------
; Light Tank - Afterglow Version
; Light Assault Tank [1TNK] (Unknown Wars)
[TnkLgt2]
$inherits			= TnkLgt
;----- Text -----
Name				= Tank Light

TargetLaser=no
Primary=75mm		; still in the rules, not used
FireAngle=0		; needed to make barrel horrizontal
Secondary=Dragon	; why not? it's got a launcher
Strength=300
CrateGoodie=yes
Passengers=2		; let's make it like to movies
PipScale=Passengers	; from C&C, more like an IFV
Armor=heavy
Turret=yes
TechLevel=4
Sight=4
Speed=9
Owner=GDI,NOD
Cost=700
Points=60
ROT=5
Crusher=yes
SelfHealing=no
Crewed=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
Weight=1.5
MovementZone=Destroyer
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
AllowedToStartInMultiplayer=no
ZFudgeColumn=9
ZFudgeTunnel=15






;------------------------------------------------------------------------------
; Mastiff Medium Tank
; Grizzly Tank (ra2/yr)
; Formerly [tank_mastiff_a]. 
[TankLgt2]
;----- Text -----
Name				= Mastiff Battle Tank
UIName				= name:
UIDescription			= desc:
;----- Gfx -----
Image				= GTNK
Primary=105mm
TechLevel=2
Sight=8
Speed=7
MaxDebris=2
ThreatPosed=15	; This value MUST be 0 for all building addons
ElitePrimary=105mmE
