;******************************************************************************
;*** Cyborg Gunner ************************************************************
;******************************************************************************
; Penitent
; Criminal converted to a simple-minded attack cyborg. 
; I removed ImmuneToPoison, ImmuneToRadiation, ImmuneToPsionics. 
; Organic components should be damaged by poison and radiation. 
; Psionics should affect units which still have an organic brain, so set ImmuneToPsionics separately on those cyborgs which are supposed to be "slaved" to a CPU. 
; This is now the prototype. 
; "NOD" uses a version of this. 

;------------------------------------------------------------------------------
[InfantryTypes]
+				= CybgGunr
;D3984A946F31F

;------------------------------------------------------------------------------
; Human Cyborg Gunner
; Formerly SUCyborg_ArmGun, Cyborg_ArmGun, [CyborgGunner]. 
; Subsumes Strogg1 (Strogg Gunner). 
[CybgGunr]
$inherits			= Civilian
;----- Text -----
Name				= Cyborg Gunner
UIName				= name:cybg_gunr
UIDescription			= desc:cybg_gunr
;----- Taxonomy -----
Category			= Soldier
Organic				= no				; Difficult call. I'd say this guy has enough organic components remaining. 
NotHuman			= yes				; This isn't necessary, but we'll say it anyway. 
; Unnatural			= yes				; If anything, this unit is NATURAL, but we don't want it to mutate... 
Cyborg				= yes
;----- Display -----
Cameo				= CYBIICON
AltCameo			= cybiuico
Sequence			= E1Sequence
Crawls				= yes
Remapable			= yes
FireUp				= 2
PrimaryFireFLH			= 70,-30,120
Pip				= 
OccupyPip			= 
PixelSelectionBracketDelta	= -6
;----- UI -----
IsSelectableCombatant		= yes
;----- Body -----
Strength			= 300				; Lao Tze: 350
Size				= 2				; Reduced from 3 since this is no longer the Shrine. ~vc LaoTze might have been 3. 
;----- Weapons -----
Primary				= Minigun
ElitePrimary			= MinigunE
IFVMode				= GUNNER3
OccupyWeapon			= Minigun_Occ
; Occupier			= no	; too big to fit inside building!
;----- UI -----
IsSelectableCombatant		= yes
;----- AI -----
LeadershipRating		= 8
Fearless			= yes

ThreatPosed=5	; Lao Tze: 20
SpecialThreatValue		= 1
;----- Availability -----
Side				= Soviet
Owner				= Soviet
; House				= 
ForbiddenHouses			= PsiCorps, OmegaCorps
TechLevel			= 7						; 4
Prerequisite			= SUBarracks, SUFactory, SUCntrTek
AllowedToStartInMultiplayer	= yes
;----- Perception -----
Sight				= 5			; Lao Tze: 8
;----- Armor -----
Armor				= light_ts		; Was plate ; Lao Tze: heavy
Crushable			= no
TiberiumProof			= no			; No, but reduce damage. 
TiberiumHeal			= no			; This is not a mutant. 
Cost				= 650			; Lao Tze: 800
Soylent=600
Points=5
ImmuneToVeins			= yes			; Not heavy enough I think. 
ImmuneToPsionics		= yes			; Difficult call. The "Servitor" would be, since he is just a remote-controlled brainwired drone. The conventional "upgraded human" would retain an organic brain, and be susceptible. 
ImmuneToRadiation		= no			; No, but reduce damage. 
ImmuneToPoison			= no			; No, but reduce damage. 
;----- Audio -----
VoiceSelect			= SelectCyborg		; 22-I000, 22-I002, 22-I006
VoiceSelectDeactivated		= DeactivatedGeneric	; 22-I008, 22-I010, 22-I014, 22-I016, 22-I020
VoiceMove			= CmdMovCyborg		; 22-I008, 22-I010, 22-I014, 22-I016, 22-I020
VoiceAttack			= CmdAtkCyborg		; 22-I008, 22-I010, 22-I012, 22-I018
VoiceFeedback			= 
ActivateSound			= Online
DeactivateSound			= Offline
DieSound			= DieCyborg		; DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
CrushSound			= CrunchMetal		; squishy2 in TS, but this never comes up. 

RequiresStolenAlliedTech=yes
RequiresStolenSovietTech=yes
RequiresStolenThirdTech=yes
;----- Movement -----
Speed				= 4
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys
; DeathAnims=EXPLOMED
;----- Veterancy -----
; VeteranAbilities				= STRONGER,FIREPOWER,ROF,SIGHT,FASTER
; EliteAbilities				= SELF_HEAL,STRONGER,FIREPOWER,ROF,FASTER
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER,SENSORS,CRUSHER
EliteAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER,SENSORS,CRUSHER,EXPLODES,EMPIMMUNE

;------------------------------------------------------------------------------
; Cyborg Gunner with Tiberium mutation. 
[MutTibCybgGunr]
$inherits			= 
;----- Armor -----
TiberiumProof			= yes
TiberiumHeal			= yes

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Cyborg Gunner with upgrade HP + 50. 
[CybgGunr2]
$inherits			= CybgGunr
;----- Text -----
Name				= 
;----- Body -----
Strength			= 350
;----- Availability -----
Prerequisite			= 

TechLevel=4
Owner=Nod
Cost=650
Points=5

ThreatPosed=15	; This value MUST be 0 for all building addons
Elite=Vulcan3X
EliteAbilities=FASTER,STRONGER,FIREPOWER,SCATTER,ROF,SIGHT,SELF_HEAL
AllowedToStartInMultiplayer=no

;------------------------------------------------------------------------------
; Cyborg Gunner with Tiberium mutation. 
[MutTibCybgGunr]
$inherits			= 
;----- Armor -----
TiberiumProof			= yes
TiberiumHeal			= yes

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; LaoTze
[]
;----- Armor -----
Armor				= heavy_ra2

;------------------------------------------------------------------------------
; Cyborg Gunner with Tiberium mutation. 
[MutTibCybgGunr]
$inherits			= 
;----- Armor -----
TiberiumProof			= yes
TiberiumHeal			= yes

;------------------------------------------------------------------------------
; Human Cyborg Gunner Elite
; Gives Cyborg Heavy Gunner a second gun-arm. 
;[TechUpg1Cyborg]
[CyborgGunnerE2a]:[CyborgGunner]
;----- Text -----
Name				= Cyborg Gunner X2
;----- Weapons -----
Primary				= MinigunX2

;------------------------------------------------------------------------------
; Human Cyborg Gunner Elite (Remodel)
; Remodeled with a grenade launcher. 
; Formerly [CyborgGunnerE2]. 
[CyborgGunnerE2b]:[CborgGunnerE2a]
;----- Text -----
UIName				= Name:Strogg1
Name				= Strogg
;----- Weapons -----
Secondary			= GrenadeLauncher

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Cyborg Awakened
[Awakened]:[CybgGun]
;----- Text -----
Name				= Awakened
UIName				= name:cybg_2
UIDescription			= desc:cybg_2
;----- Body -----
Strength			= 
;----- Availability -----
House				= OmegaCorps
RequiredHouses			= OmegaCorps
ForbiddenHouses			= none

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
[Enlightened]:[Awakened]
;----- Text -----
Name				= Enlightened
UIName				= name:enlightened
;----- Body -----
;----- Weapons -----
Primary				= LasgunRed
ElitePrimary			= LasgatRed
