
; Drop: Vanilla american paradrop
; Drop Airborne: Deploys rifle infantry and missile infantry, plus vehicles. 
; Drop Commando: Deploys commandos and engineers, plus vehicles. 

;------------------------------------------------------------------------------
[SuperWeaponTypes]
+				= InvokeParadrop

;------------------------------------------------------------------------------
; Subsumes GermanParadropSpecial, RussianParadropSpecial. 
; Formerly [InvokeParadrop]. 
[InvokeDropInfy]
;----- Text -----
Name				= Paradrop Infantry
UIName				= name:drop_infantry
UIDescription			= desc:drop_infantry
;----- Taxonomy -----
Type				= ParaDrop
IsPowered=false
RechargeTime=4
Action=NewPara 	;check out the Adding custom Actions page to find out more about this SidebarImage=GPARICON
ShowTimer=no
DisableableFromShell=no
;----- Payload -----
;New Tags
ParaDropPlane			= B-16 
ParaDrop.Types			= ; DropInf=TRPR		; Trooper
; DropInfNum= 		; as AmericanParadropNum= flag up above in [Generals] section...

[GermanyHeavyDropSpecial]
UIName=Name:GermanHeavyDropSpecial
Name=German Paradrop
IsPowered=false
RechargeTime=4
Type=NewParaDrop 	;NewParaDrop is the type for AmericanParaDrop clones
Action=NewPara 	;check out the Adding custom Actions page to find out more about this SidebarImage=GPARICON
ShowTimer=no
DisableableFromShell=no
;New Tags
ParaDropPlane= 	; the paradrop plane 
DropInf=PFST		; Panzerfaust Trooper
DropInfNum=		; as AmericanParadropNum= flag up above in [Generals] section...

[GermanCommandoDropSpecial]
UIName=Name:GermanCommandoDropSpecial
Name=German Commando Paradrop
IsPowered=false
RechargeTime=4
Type=NewParaDrop 	;NewParaDrop is the type for AmericanParaDrop clones
Action=NewPara 	;check out the Adding custom Actions page to find out more about this SidebarImage=GPARICON
ShowTimer=no
DisableableFromShell=no
;New Tags
ParaDropPlane= 	; the paradrop plane 
DropInf=FRCK		; Flame Rocketeer
DropInfNum=		; as AmericanParadropNum= flag up above in [Generals] section...

; Vanilla's AmericanParadropSpecial. 
[USAInvokeParadrop]
UIName=Name:AmericanParadropSpecial
Name=American Paradrop
IsPowered=false
RechargeTime=4
Type=NewParaDrop ;NewParaDrop is the type for AmericanParaDrop clones
Action=NewPara ;check out the Adding custom Actions page to find out more about this SidebarImage=PARAICON
ShowTimer=no
DisableableFromShell=no
;New Tags
ParaDropPlane=B-16 ;the paradrop plane 
DropInf= ; as AmericanParadropInf= flag up above in [General] section...
DropInfNum= ; same here, for AmericanParadropNum= flag...

; Formerly AmericanHeavyDropSpecial. 
[InvokeParadropAirborne]
UIName=Name:AmericanHeavyDropSpecial
Name=American Heavy Paradrop
IsPowered=false
RechargeTime=4
Type=NewParaDrop ;NewParaDrop is the type for AmericanParaDrop clones
Action=NewPara ;check out the Adding custom Actions page to find out more about this SidebarImage=PARAICON
ShowTimer=no
DisableableFromShell=no
;New Tags
ParaDropPlane=B-16 ;the paradrop plane 
DropInf=RKETGUY
DropInfNum= ; AmericanParadropNum= flag...

; Formerly AmericanCommandoDropSpecial. 
; Drops Commandos plus Engies. 
[InvokeParadropCommando]
UIName=Name:AmericanCommandoDropSpecial
Name=American Commando Paradrop
IsPowered=false
RechargeTime=4
Type=NewParaDrop ;NewParaDrop is the type for AmericanParaDrop clones
Action=NewPara ;check out the Adding custom Actions page to find out more about this SidebarImage=PARAICON
ShowTimer=no
DisableableFromShell=no
;New Tags
ParaDropPlane=B-16 ;the paradrop plane 
DropInf= Commando, UNEngineer
DropInfNum= 3,2	; same here, for AmericanParadropNum= flag...



;------------------------------------------------------------------------------
; Medic Drop
; Drops 1 Cuban Medic. 
[CUInvokeDropMedic]
;----- Text -----
Name				= Invoke Drop Medic
UIName				= name:drop_medic
UIDescription			= desc:drop_medic
IsFlammable=yes
RadarColor=0,192,0
TemperateOccupationBits=4
SnowOccupationBits=7

;------------------------------------------------------------------------------
; Medic Drop II
; Drops 3 Cuban Medics. 
[CUInvokeDropMedic2]:[CUInvokeDropMedic]
Name=Tree
IsFlammable=yes
RadarColor=0,192,0
TemperateOccupationBits=4
SnowOccupationBits=4

;------------------------------------------------------------------------------
; Medic Drop III
; Drops 5 Cuban Medics. 
[CUInvokeDropMedic3]:[CUInvokeDropMedic2]

[TIBTRE02]
Name=Tiberium Tree
SpawnsTiberium=yes
RadarColor=192,192,0
IsAnimated=yes
LightVisibility=4000
LightIntensity=0.01
LightRedTint=0.01
LightGreenTint=1.5
LightBlueTint=0.01
AnimationRate=3
AnimationProbability=.003
Immune=yes

[TIBTRE03]
Name=Tiberium Tree
SpawnsTiberium=yes
RadarColor=192,192,0
IsAnimated=yes
LightVisibility=4000
LightIntensity=0.01
LightRedTint=0.01
LightGreenTint=1.5
LightBlueTint=0.01
AnimationRate=3
AnimationProbability=.003
Immune=yes

[VEINTREE]
Name=Veinhole Tree
Image=None
Armor=None
IsVeinhole=true
Strength=1000
