;
;
;
; Campaign unit, Maltese special. 
; AE bestows AE'1 and AE'2 on other infantry around it. 
; AE'1 and AE'2 is maintained while near the Hospitaller. 
; AE'1 is stackable, it reduces damage taken by the bearer. 
; AE'2 is not stackable, it deals damage to friendly Hospitaller units around the bearer within the same radius as their own AE has. 

;------------------------------------------------------------------------------
[InfantryTypes]
+				= LgnyHospitaller

;------------------------------------------------------------------------------
; Hospitaller
[LgnyHospitaller]:[Lgny]
;----- Text -----
Name				= Hospitaller
UIName				= name:hospitaller
UIDescription			= desc:hospitaller
;----- Weapons -----
Primary				= HospitallerCannon
Secondary			= HospitallerSword
;----- Attach -----
AttachEffect.Types		= AuraHospitaller
Prerequisite=NAHAND,RADAR
CrushSound=InfantrySquish
Strength=150
Armor=plate
TechLevel=8
Pip=red
Sight=6
Speed=4
Cost=600
Soylent=300
Points=30
IsSelectableCombatant=yes
VoiceSelect=DesolatorSelect
VoiceMove=DesolatorMove
VoiceAttack=DesolatorAttackCommand
VoiceFeedback=
VoiceSpecialAttack=DesolatorMove
DieSound=DesolatorDie
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=Infantry
;MovementZone=InfantryDestroyer ;GEF wow!!! copy paste bug from the original Disk Thrower!
ThreatPosed=20	; This value MUST be 0 for all building addons
Deployer=yes
DeployFire=yes
; DeployTime=.022  ; PCG; Unused for now.  Was maybe going to make its way in if we did
; a more explicit state machine for deploying b/c of autodeploy.
ImmuneToRadiation=yes
ImmuneToPsionics=no
Bombable=yes
AllowedToStartInMultiplayer=no
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Size=1
Fearless=yes
SelfHealing=yes
Crushable=no
ElitePrimary=RadBeamWeaponE
IFVMode=9
