
;------------------------------------------------------------------------------
[VehicleTypes]
6C8D7228D7BE4			= BlightHurler

;------------------------------------------------------------------------------
; Toxin Artillery
[BlightHurler]
Image=ARTIL;ARMH
;----- Name -----
UIName				= Name:ToxinArtillery
Name				= Blight-hurler

FireAngle=42

;----- GFX -----
;PipScale			= Ammo

;----- Base Attributes -----
Strength			= 200

;----- Weapons -----
Primary				= BlightCannon

;----- Armor -----
Armor				= heavy,corrosion_proof
ImmuneToRadiation		= yes
;ImmuneToVeins			= yes

;----- Load -----
;Ammo				= 6
;Reload				= 400

;----- Procuration -----
Owner				= Nod,YuriCountry
DoubleOwned=yes
Prerequisite			= FACTORY,TECH
;;RequiresStolenAlliedTech=yes
;RequiresStolenSovietTech=yes
;RequiresStolenThirdTech=yes

Category=LRFS
Turret=no
TechLevel=1;6
Sight=9
Speed=5
AllowedToStartInMultiplayer=no
Cost=1200
Points=35;25
CrateGoodie=yes
ROT=2;5
Crusher=yes
Crewed=yes
NoMovingFire=yes
VoiceSelect			= 25-I000,25-I002,25-I004,25-I006
VoiceMove			= 25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack			= 25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Crusher
ThreatPosed=10	; This value MUST be 0 for all building addons

;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys,SmallGreySSys
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
Explodes			= yes
DeathWeapon			= ChemTankExplode

Weight=3.5
EliteAbilities=SELF_HEAL
ZFudgeColumn=10
ZFudgeTunnel=14

IsTilter=yes
Crusher=yes
TooBigToFitUnderBridge=true
IsSelectableCombatant=yes
CrushSound=TankCrush
AllowedToStartInMultiplayer=no
MaxDebris=2
MovementZone=Normal

ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
BerserkFriendly=yes
Trainable=no
Size=3

[ChaosGun]
Damage=1000
ROF=75
Range=12
MinimumRange=6
Projectile=Ballistic
Speed=100
Warhead=PsychGasCreate2
Report=ApocalypseAttackGround
Anim=GUNFIRE
Bright=yes
Lobber=yes

[PsychGasCreate2]
CellSpread=2
PercentAtMax=1
Verses=100%,100%,100%,75%,75%,75%,0%,0%,0%,100%,100%
InfDeath=1
AnimList=CDGAS2
Psychedelic=yes

; Making all types for now, we can pick the ones we like, later. 
; artillery cannon
[TiberiumMortar]
Damage=150
ROF=110
Range=18
MinimumRange=5
Projectile=RadTurretShell2
Speed=10
Warhead=TiberiumMaker
Report=SeigeChopperAttackDeployed
Anim=GCMUZZLE
Lobber=yes

; artillery cannon
[VisceroidMortar]
Damage=150
ROF=110
Range=18
MinimumRange=5
Projectile=RadTurretShell2
Speed=10
Warhead=VisceroidMaker
Report=SeigeChopperAttackDeployed
Anim=GCMUZZLE
Lobber=yes

; artillery cannon
[RadiationMortar]
Damage=1
ROF=110
Range=18
MinimumRange=5
Projectile=RadTurretShell2
Speed=10
Warhead=RadSite
Report=SeigeChopperAttackDeployed
Anim=GCMUZZLE
Lobber=yes
RadLevel=100

; artillery cannon
[ChemMortar]
Damage=32;150
ROF=110
Range=18
MinimumRange=5
Projectile=RadBallistic
Speed=10
Warhead=Gas
Report=SeigeChopperAttackDeployed
Anim=GCMUZZLE
Lobber=yes

; Chem Deployed Artillery
[SE2K0016]
Name=Chem Deployed Artillery
Image=GAARTY
DamageParticleSystems=SparkSys,SmallGreySSys,BigGreySmokeSys
VoiceSelect=15-I004,15-I006,15-I008,15-I010,15-I012,15-I038,15-I040,15-I048
VoiceMove=15-I014,15-I016,15-I018,15-I020,15-I022,15-I024,15-I060
VoiceAttack=15-I026,15-I032,15-I044,15-I046,15-I050
Armor=heavy
Primary=SE2K0014
TechLevel=8
Strength=300
Sight=9
Cost=2800
Points=50
ThreatPosed=30
ROT=5.00
Nominal=yes
Trainable=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DamageSmokeOffset=500, 500, 400
MaxDebris=4
BaseNormal=no
Turret=yes
Artillary=yes
TogglePower=no
Crewed=yes
TurretAnimIsVoxel=true
TurretAnim=ART2TUR
TurretAnimX=-8
TurretAnimY=15
TurretAnimZAdjust=-20
HasStupidGuardMode=false
UndeploysInto=SE2K0013
EliteAbilities=SELF_HEAL,FASTER
