
;------------------------------------------------------------------------------
[AircraftTypes]
8329512981F75			= CBShell

;------------------------------------------------------------------------------
; V3 Rocket -- warhead invoked from code.  No weapons attached here.
[CBShell]

;[ReGenesisRocket]
UIName				= Name:RegenesisRocket
Name				= ReGenesis Barque

;----- GFX -----
Image				= BOMB;RKET8

FireAngle=1
Strength=50
Category=AirPower
Armor=special_2
Spawned=yes
MissileSpawn=yes
Missile.Custom=yes

;----- Weapons -----
;Primary				= VisceroidShellPuff
;Missile.Weapon=90mm

TechLevel=-1
Sight=1
RadarInvisible=no
Landable=yes
MoveToShroud=yes
Ammo				= 1 ;Aircraft are hard wired to require ammo
Speed=5;15
Owner=Neutral
Cost=50
Points=20
ROT=3
Crewed=no

;----- Damage & Destruction -----
Explodes			= yes
DeathWeapon			= BlightCannon
GuardRange=30
Explosion=DEMTEXP
MaxDebris=2

;----- Movement -----
Locomotor={B7B49766-E576-11d3-9BD9-00104B972FE8}
MovementZone=Fly
;FlightLevel			= 20
;CruiseHeight			= 20 
;HoverHeight			= 20

Missile.PauseFrames=0
Missile.TiltFrames=0
Missile.PitchInitial=0
Missile.PitchFinal=0.9
Missile.TurnRate=0
Missile.RaiseRate=1
Missile.Acceleration=1
Missile.Altitude=20
Missile.BodyLength=40
Missile.LazyCurve=yes

ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SmallGreySSys	; Sparks don't work well here.  SJM
AuxSound1=V3Attack ;Taking off
;AuxSound2=DROPDWN1 ;Landing
ImmuneToPsionics=yes
;VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
;EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
NoShadow=yes
Selectable=no
Trainable=no
DontScore=yes

InitialPayload.Types=BlightHurler
SizeLimit=999
Passengers=1

[VisceroidShellPuff]
Range=8
Projectile=Invisible
Warhead=Gas
