
;------------------------------------------------------------------------------
[BuildingTypes]
4ACF36BCBDF12			= CNBLDG04

;------------------------------------------------------------------------------
[CNBLDG04];JGSSHE
;----- Name -----
UIName				= Name:JGSSHE
Name				= Chinese Building
Nominal				= yes

;----- Base Attribute -----
Strength			= 1000

;----- Armor -----
Armor				= wood;concrete

;----- Procuration -----
Owner				= Neutral
DoubleOwned			= yes ;##TEST!##
TechLevel			= 1;-1
Insignificant			= yes
Points=5
MaxDebris=15
MinDebris=5
DebrisAnim=Dbris3sm,Dbris4lg,Dbris7sm,Dbris8sm,Dbris10sm,Dbris9lg,Dbris2sm,Dbris3lg,Dbris10lg
BaseNormal=no
Sight=6
ClickRepairable=no
CanBeOccupied=no
LeaveRubble=Yes
DieSound=MonumentCrumble
