;------------------------------------------------------------------------------
[BuildingTypes]
793412BCEF993			= CNBLDG03

;------------------------------------------------------------------------------
[CNBLDG03];CACHIN03
UIName				= Name:CNBLDG		; Name:JGSSHE
Name				= China Building C
Owner=Neutral
DoubleOwned=yes
TechLevel=0;-1
Strength=300
Insignificant=yes
Nominal=yes
Points=5
Armor=steel
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
BaseNormal=no
Sight=4
ClickRepairable=no
CanBeOccupied=no
RadarInvisible=yes
CanOccupyFire=no
LeaveRubble=no
