
; ******* Side Type List *******
; The combantants can be grouped according to side. This
; lists the sides and their respective member houses.
[Sides]
GDI		= Americans,AMAirforceGeneral,AMLaserGeneral,AMSuperweaponGeneral
Soviet		= Russians,RUGuardGeneral,Ukrainians
SovChina	= SovietChinese,SVChinaInfantryGeneral,SVChinaTankGeneral,SVChinaNukeGeneral
Confederation	= Confederation,LCLaserGeneral

ThirdSide	= Germans,British,French,Italians,Spaniards,Turks,Greeks

Nod		= Persians,Arabs,Africans

Alliance	= Chinese,Japanese,Koreans

YuriSide	= YuriCountry

Civilian=Neutral
Mutant=Special

; *** House (players) List ***
; Each side has some basic controls on how they behave (when
; controlled by the computer. Here is the list of available
; house types.
;
; PCG; WARNING; Do not remove, override or reorder the major 9 houses for skirmish
; or LAN game maps.  These need to go into the house types array first and without
; interruption by other types of houses, or we will get evil crashes.
[Countries]

; Americans
0		= GDI 											; Starts at zero because dialog returns 0 for first listing regardless of name
1		= Americans										; U.S.A.
2		= British										; U.K. and Commonwealth

; Third Power (now Europe)
3		= Germans										; E.U.
4		= British
5		= French
6		= Italians
7		= Spaniards
8		= Turkish
9		= Greeks

10		= Soviet										; Soviets
11		= Russians										; Russian Federation
12		= Russia										; Black Guard

7		= SovietChinese										; Chinese Soviet
8		= SovChinaInfantryGeneral
9		= SovChinaTankGeneral
10		= SovChinaNukeGeneral

11		= Confederation					; Latin Confederation

Z05=Hyperboreans
Z06=Lunatics

; Brotherhood
N00=Nod
N01=Persians
N02=Africans
N03=Arabs

; ASIANS
E00=Alliance
E01=Chinese	; Chinese Empire
E02=Japanese	; Japanese Shogunate
E03=Koreans	; Korean Kingdom

; MISC
C00=OTL		; Civilian Defense Force
N00=Natural	; Animals
N00=Neutral	; Civilians, and some factions
M00=Special	; Special critters: mutants, zombies, dinosaurs, giant ants
M91=YuriCountry

; ******* Country Statistics *******
; Certain countries have special adjustments to their unit and building
; values. These are global values that affect ALL units and buildings owned
; by that country. This applies only to multiplayer games and skirmish mode. In
; normal game play, all values are "1.0".

; Airspeed= 	multiplier to speed for all air units [larger means faster] (def=1.0)
; Armor= 	multiplier to armor strength for all units and buildings [larger means stronger] (def=1.0)
; Cost= 	multiplier to cost for all units and buildings [larger means costlier] (def=1.0)
; Firepower= 	multiplier to firepower for all weapons [larger means more damage] (def=1.0)
; Groundspeed= 	multiplier to speed for all ground units [larger means faster] (def=1.0)
; ROF= 		multiplier to Rate Of Fire for all weapons [larger means slower ROF] (def=1.0)
; BuildTime= 	multiplier to general object build time [larger means longer to build] (def=1.0)
; Color= 	color to use when displaying objects owned by this country [see color schemes]
; Multiplay= 	This house used as placeholder for multiplay house (def=no)?
; WallOwner= 	Will this house own walls that are placed near its buildings (def=yes)?
; SmartAI= 	Does it presume to have the smart AI logic already enabled (def=no)?

; Enough of theirs.  Here's the real stuff.  VeteranXXX can be used to make all units
; of that type start as veterans.  Please stay clear on the meaning of Infantry, Unit, and Aircraft.
; For % bonuses, the unit ones are made up up two words: the category and the type it applies to.
; Column A: Armor, Cost, Speed(units), BuildTime
; Column B: Aircraft, Units, Infantry, Buildings, Defenses
; Column C: Mult (to remind you that this is a straight multiplier instead of the formulas they used.)
; Exception is IncomeMult, which is applied when gaining money from refining ore only, but, well, it doesn't actually work.  Umm...sorry.  3/22 Maybe it does now...lemme check...yeah!  it works now!

; For armor, think of max strength being multiplied by the number (in reality, damage is divided by this since you can't change the max in Type)

;******************************************************************************
;*** ALLIES *******************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; Allied side
[GDI]
UIName=Name:GDI
Name=GDI
Suffix=G	; GENERIC Allies
Prefix=A	; Allied
Color=DarkBlue
MultiplayPassive=true
Side=GDI
SmartAI=yes

;------------------------------------------------------------------------------
; United States of America / American Empire
[Americans]
UIName=Name:Americans
Name=America
Suffix=US
Prefix=A
Color=DarkBlue
Multiplay=yes
Side=GDI
SmartAI=yes
VeteranInfantry=MISLGUY,JUMPGUY
VeteranUnit=HELI,CARRIER
VeteranAircraft=FALC
CostUnitsMult=.85

;------------------------------------------------------------------------------
; United Kingdom / Oceania
[British]
UIName=Name:British
Name=Great Britain
Suffix=UK
Prefix=A
Color=DarkBlue
Multiplay=yes
Side=GDI
SmartAI=yes
VeteranUnit=DRED

;------------------------------------------------------------------------------
; European Union
[French]
UIName=Name:French
Name=France
Suffix=EU
Prefix=A
Color=DarkBlue
Multiplay=yes
Side=GDI
SmartAI=yes
BuildTimeDefensesMult=.75
VeteranUnit=SHAD
;VeteranInfantry=GARD,EGRD

;******************************************************************************
;*** SOVIET *******************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; Soviet side
[Soviet]
UIName=Name:Soviet
Name=Soviets
Prefix=S	; Allied
Suffix=G	; GENERIC Soviet
Color=DarkRed
MultiplayPassive=true
Side=Soviet
SmartAI=yes

Crew=CONS
Engineer=SENGINEER
Technician=STECH
DefaultDisguise=CONS
SurvivorDivisor=250
AI.PowerPlants=SGPOWR,SGNRCT
AI.BaseDefenses=SGQUAD;,SGTSLA,SGFTUR,SGITUR,SGHAMR
ParaDrop.Types=CONS
ParaDrop.Num=9
ParaDrop.Aircraft=SCPLN	; Ilyushin Il-76
Parachute.Anim=PARAS
HunterSeeker=SHUNT	; should Soviets really get one? Use hacked Eastasian.
Sidebar.MixFileIndex=2	; Soviet
ToolTipColor=255,0,0
MessageTextColor=DarkRed
EVA.Tag=Russian

;------------------------------------------------------------------------------
; Russian Soviet Federative Soviet Republic ('Russian Federation')
[Russians]
UIName=Name:Russians
Name=Russia
Suffix=RU
Prefix=S
Color=DarkRed
Multiplay=yes
Side=Soviet
SmartAI=yes
;VeteranInfantry=YURI
;CostUnitsMult=.85

AI.PowerPlants=SGPOWR,SGNRCT

;MenuText.Status=
ListIndex=5
;RandomSelectionWeight=
File.Flag=rusi.pcx
LoadScreenText.Color=SovietLoad

;------------------------------------------------------------------------------
; Black Guard (Novaya Rossiya Elite Forces)
[BlackGuard]
UIName=NOSTR:Black Guard ;##TEST##	Name:BlackGuard
Name=Black Guard
Suffix=RU
Prefix=S
Color=Black
Multiplay=yes
Side=Soviet
SmartAI=yes

AI.PowerPlants=SGPOWR,SGNRCT

;MenuText.Status=
ListIndex=6
;RandomSelectionWeight=
File.Flag=blki.pcx
LoadScreenText.Color=SovietLoad

;------------------------------------------------------------------------------
; Chinese Soviet Republic ('Jiangxi-Fujian Soviet')
[Soviet_Chinese]
UIName=NOSTR:Chinese Soviet;Name:Chinese
Name=China
Suffix=CN
Prefix=S
Color=DarkRed
Multiplay=yes
Side=Soviet
SmartAI=yes
;VeteranInfantry=YURI
;CostUnitsMult=.85
LoadScreenText.Color=SovietLoad

;------------------------------------------------------------------------------
; Latin Confederation
[Confederation]
UIName=NOSTR:Latin Confederation;Name:Confederation
Name=Latin Confederation
Suffix=LA
Prefix=S
Color=DarkRed
Multiplay=yes
Side=Soviet
SmartAI=yes
;VeteranInfantry=IVAN
;SpeedUnitsMult=1.15
LoadScreenText.Color=SovietLoad

;******************************************************************************
;*** THIRD ********************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; German Empire
[Germans]
UIName=Name:Germans
Name=Germany
Suffix=G
Prefix=Z
Color=DarkGrey
Multiplay=yes
Side=ThirdSide
SmartAI=yes
VeteranUnits=PTHR,TIGR

;------------------------------------------------------------------------------
[Italians]
UIName=NOSTR:Italy

;------------------------------------------------------------------------------
[Spanish]
UIName=NOSTR:Spain

;------------------------------------------------------------------------------
[Turkish]
UIName=NOSTR:Turkey

;------------------------------------------------------------------------------
[Hyperborea]
UIName=NOSTR:Antarctica
Name=New Swabia
Suffix=HY
Prefix=X
Color=DarkSky
Multiplay=yes
Side=Third
SmartAI=yes
LoadScreenText.Color=ThirdLoad

;------------------------------------------------------------------------------
[Agartha]
UIName=NOSTR:Subterranea
Name=Hollow Earth
Suffix=AG
Prefix=X
Color=DarkSky
Multiplay=yes
Side=Third
SmartAI=yes
LoadScreenText.Color=ThirdLoad

;------------------------------------------------------------------------------
[Luna]
UIName=NOSTR:Luna
Name=Dark Side of the Moon
Suffix=LU
Prefix=X
Color=DarkSky
Multiplay=yes
Side=Third
SmartAI=yes
LoadScreenText.Color=ThirdLoad

;******************************************************************************
;*** BROTHERHOOD **************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; Brotherhood
[Nod]
UIName=Name:Nod
Name=Nod
Suffix=G	; GENERIC Nod
Prefix=N	; Nod
MultiplayPassive=true
Side=Nod
SmartAI=yes

;----- Art & Color -----
Color=DarkGreen
ToolTipColor=0,144,0
MessageTextColor=DarkGreen
Sidebar.MixFileIndex=4

;------------------------------------------------------------------------------
; Persian Empire
[Persians]
UIName=Name:Persians
Name=Persian Empire
Suffix=G
Prefix=N
Color=DarkGreen
Multiplay=yes
Side=Nod
SmartAI=yes
VeteranInfantry=ASSN
FirepowerUnitsMult=1.3	;+30% is a hefty bonus!

;------------------------------------------------------------------------------
; African Warlords
[Africans]
UIName=Name:Africans
Name=African Warlords
Suffix=G
Prefix=N
Color=DarkGreen
Multiplay=yes
Side=Nod
SmartAI=yes
VeteranUnit=PICK
BuildTimeInfantryMult=.75

;------------------------------------------------------------------------------
; Arab Union
[Arabs]
UIName=Name:Arabs
Name=Arab Union
Suffix=G
Prefix=N
Color=DarkGreen
Multiplay=yes
Side=Nod
SmartAI=yes
VeteranInfantry=TRST
IncomeMult=1.2

;******************************************************************************
;*** ASIANS *******************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; Eastasia
[Alliance]

;----- Name -----
UIName=Name:Alliance
Name=Asian Alliance
Prefix=E			; ASIAN
Suffix=G			; GENERIC Asian

;----- MP -----
Multiplay=yes
;MultiplayPassive=true
Side=Alliance

;----- Art & Color -----
Color=Gold
ToolTipColor=255,144,0
MessageTextColor=DarkGold
Sidebar.MixFileIndex=5

;----- Voices, Sounds & Music -----
EVA.Tag=Asian
;LoadingTheme=LOADING_ASIA

;----- Unit defaults -----
Crew=LITE
Engineer=HAX0R
Technician=HAX0R
SurvivorDivisor=100		; from TS/FS default, this fits this side quite well
DefaultDisguise=LITE

;----- AI -----
SmartAI=yes
AI.PowerPlants=EGPOWR
AI.BaseDefenses=EGSNTY
AI.BaseDefenseCounts=50,100,200

;----- Paradrops -----
ParaDrop.Types=JUMPGUY		; DeepStrike! with JJ troops
ParaDrop.Num=3
ParaDrop.Aircraft=FFLY
;Parachute.Anim=PARACHUTE_ASIA	; => "bamboo-and-silk pyramid", missing art

;----- HunterSeeker -----
HunterSeeker=FFLY

;------------------------------------------------------------------------------
; China
[Chinese]

;----- Text -----
UIName=Name:Chinese
Name=China
LoadScreenText.Name=Name:Chinese
Prefix=E
Suffix=C

MenuText.Status=
LoadScreenText.SpecialName=
LoadScreenText.Brief=loadbrief:China

;----- MP -----
Side=Alliance
Multiplay=yes
ListIndex=13				; Allies 1-3, Soviet 4-6, Third 7-9, Brotherhood 10-12, Eastasia 13-15
;RandomSelectionWeight=;regular

;----- Art -----
Color=Gold
LoadScreenText.Color=DarkGold
File.Flag=qini.pcx
File.LoadScreen=ls800china
File.LoadScreenPAL=

;----- Veteran Techs -----
VeteranInfantry=RKETGUY,HAX0R		; Rocket Man, Hacker
VeteranUnit=ECMT			; Hacker Tank

;----- Stat Multipliers -----
CostInfantryMult=.8

;----- AI -----
SmartAI=yes
AI.PowerPlants=EGPOWR

;------------------------------------------------------------------------------
; Japan
[Japanese]

;----- Text -----
UIName=Name:Japanese
Name=Japan
LoadScreenText.Name=Name:Japanese
Prefix=E
Suffix=J

MenuText.Status=
LoadScreenText.SpecialName=Name:YUKI	; Yukikaze
LoadScreenText.Brief=loadbrief:Japan

;----- Art -----
File.Flag=japi.pcx
Color=Gold
LoadScreenText.Color=DarkGold

File.LoadScreen=ls800japan
File.LoadScreenPAL=

;----- MP -----
Side=Alliance
Multiplay=yes
ListIndex=14				; Allies 1-3, Soviet 4-6, Third 7-9, Brotherhood 10-12, Eastasia 13-15
;RandomSelectionWeight=;regular

;----- Veteran Techs -----
VeteranInfantry=SHIN,HEVY		; ShadowHand, Light Mobile Suit
VeteranUnit=STNK,IMCH,MMCH		; Spider Tank, Medium Mobile Suit, Heavy Mobile Suit
CostInfantryMult=.8

;----- AI -----
SmartAI=yes
AI.PowerPlants=EGPOWR

;------------------------------------------------------------------------------
; Korea
[Koreans]

;----- Text -----
UIName=Name:Koreans
Name=Korea
LoadScreenText.Name=Name:Koreans
Prefix=E
Suffix=K

MenuText.Status=
LoadScreenText.SpecialName=
LoadScreenText.Brief=loadbrief:korea

;----- Art -----
File.Flag=kori.pcx
Color=Gold
LoadScreenText.Color=DarkGold

File.LoadScreen=ls800korea
File.LoadScreenPAL=

;----- MP -----
Side=Alliance
Multiplay=yes
ListIndex=15		; Allies 1-3, Soviet 4-6, Third 7-9, Brotherhood 10-12, Eastasia 13-15
;RandomSelectionWeight= ; regular

;----- Veteran Techs -----
VeteranInfantry=RKETGUY		; Rocket Man
VeteranUnit=MISLTNK		; Rocket Tank
CostInfantryMult=.8

;----- AI -----
SmartAI=yes
AI.PowerPlants=EGPOWR





;*** NEUTRAL ***

;------------------------------------------------------------------------------
[YuriCountry]

;----- Name -----
UIName=Name:Yuri
Name=Yuri

Prefix=Y
Suffix=G

;----- Art & Color -----
Color=Purple
ToolTipColor=Purple
LoadScreenText.Color=YuriLoad
MessageTextColor=Purple
;DialogBackground.Image=
;DialogBackground.Palette=

;----- Voices, Sounds & Music -----
EVA.Tag=Yuri
LoadingTheme=LOADING

Multiplay=yes
Side=ThirdSide

;----- AI -----
SmartAI=yes
AI.PowerPlants=YGPOWR

;Sidebar.MixFileIndex=sidec03.mix
Sidebar.YuriFileNames=yes

; *** NEUTRAL ***

; Jurassic Park wildlife
[Special]
UIName=Name:Special
Name=Jurassic Park
Suffix=JP
Prefix=J
Color=Green
Side=Mutant
SmartAI=yes
MultiplayPassive=true

[Neutral]
UIName=Name:Neutral
Name=Civilian
Suffix=CIV
Prefix=C
Color=Grey
MultiplayPassive=true
SmartAI=yes
Side=Civilian
