; SAM HEFRAG (blast fragmentation)
[EXPLOSIONF9B6DAA8FF89E]
CellSpread=.3
PercentAtMax=1
Wall=no	; overhead detonation should not damage overlays on the ground, which is unfortunately how this works. 
Wood=no	; " ditto
;Verses=100%,100%,100%,100%,100%,100%,0%,0%,0%,100%,100%
Verses=150%,80%,50%,100%,100%,20%,0%,0%,0%,100%,100%	; no buildings
;Versus.AirNone	; Gyrocopter
;Versus.AirFlak	; Rocketeer
;Versus.AirPlate	; Unused???
;Versus.AirLight	; Normal aircraft
;Versus.AirMedium	; Heavy bombers, Saucer
;Versus.AirHeavy	; The Zeppelin
InfDeath=3
AnimList=XGRYSML1,XGRYSML2,EXPLOSML
ProneDamage=100%