;------------------------------------------------------------------------------
; Formerly "HESplash". 
[Explosion_57D729634E617]
CellSpread			= 1.2
PercentAtMax			= .8
Wall				= yes
Wood				= yes
Verses				= 100%,100%,100%,90%,60%,70%,100%,100%,90%,25%,100%
Conventional			= yes
InfDeath			= 3
AnimList			= S_CLSN16,S_CLSN22,S_CLSN30,S_CLSN42,S_CLSN58
ProneDamage			= 50%
