
;------------------------------------------------------------------------------
[WeaponTypes]
FBF2DF4749C55		= ExplodeF5E1E3CDBF7CD

;------------------------------------------------------------------------------
; napalm covers large area with flames
; MigPyroMissileBurst
[ExplodeF5E1E3CDBF7CD]
Damage			= 15 ;down from 80
Projectile		= FireFragment
Range			= 6.5
ProjectileRange		= 2.5
Warhead			= Fire
Speed			= 20

Weapon MiGFirestormCreationWeapon
  DamageType = FLAME
  DeathType = BURNED
  FireOCL = OCL_MiGFirestorm
End

; thermobaric weapon
[InfernoCluster]
Damage=600
ROF=10;0;80
Range=6;2
Projectile=InfernoBits
Speed=10;14;35
Warhead=InfernoWH
Bright=yes
;FireOnce=yes

;Damage=80
;ROF=80
;Speed=20
