;------------------------------------------------------------------------------
; Honest John, Deviator
[Rocket99A811A2B252C]
Image			= MISL6
Color			= NeonRed;DarkOrange
Shadow			= no
Animates		= yes
Arcing			= yes
Inaccurate		= yes
Rotates			= yes
;ROT			= 4
Arm			= 10
High			= yes
VeryHigh		= yes
SubjectToWalls		= no
SubjectToElevation	= yes
SubjectToCliffs		= yes;no
IgnoresFirestorm	= yes
Proximity		= yes
Ranged			= yes
AirburstWeapon		= Dragon;ExplodeF5E1E3CDBF7CD
ShrapnelWeapon		= Dragon;ExplodeF5E1E3CDBF7CD
Splits			= yes
RetargetAccuracy	= 0
Cluster			= 8
ShrapnelCount		= 8
