
[InfantryTypes]
84221B9725C9C			= Marine

; Marine
[Marine]
UIName				= Name:Marine
Name				= Marine
Category			= Soldier
MovementZone=Infantry
CrushSound=SQUISH6
VoiceSelect=15-I000,15-I004,15-I012,15-I048
VoiceMove=15-I018,15-I024,15-I044
VoiceAttack=15-I044,15-I050,15-I044,15-I046
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
VoiceFeedback=15-I058,15-I064
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
Speed=5
ThreatPosed=10
Owner=Americans
DoubleOwned=yes
Prerequisite=
Primary=MP5
TechLevel=4
Strength=175
Sight=7
Cost=750
Points=5
PhysicalSize=1
ImmuneToVeins=yes
Fearless=yes
EliteAbilities=C4,SELF_HEAL


Image=Marine2 
Primary=M60E 
Occupier=yes ; I can Occupy UC buildings 
AllowedToStartInMultiplayer=no 
Prerequisite=GAPILE,RADAR 
CrushSound=InfantrySquish 
Strength=150 
Pip=white 
Armor=none 
;original>TechLevel=3 
Sight=5 
Speed=5 
Owner=British,French,Germans,Americans,Alliance 
;original>Cost=400 
Soylent=150 
Points=10 
IsSelectableCombatant=yes 
VoiceSelect=GISelect 
VoiceMove=GIMove 
VoiceAttack=GIAttackCommand 
VoiceFeedback=GIFear 
VoiceSpecialAttack=GIMove 
DieSound=GIDie 
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1} 
PhysicalSize=1 
MovementZone=Infantry 
ThreatPosed=10 ; This value MUST be 0 for all building addons 
ImmuneToVeins=yes 
ImmuneToPsionics=no 
Bombable=yes 
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER 
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF 
Size=1 
Crushable=yes 
DeploySound=GIDeploy 
UndeploySound=GIUndeploy 
ElitePrimary=M60EE 
IFVMode=2 
; fix 
OccupyWeapon=AlliedOccupyW 
; Mod 
TechLevel=2;was 1, now adjusted to 2, Flak Trooper will be 2...	; adjusted this to fix the sidebar - the Marine is supposed to appear next to the GI for Allies-only players, and before the Grenade Launcher when having captured the Sov side Barracks. 
Cost=250;w300, now is GI Cost +25%	; sorting via cost 

[M60EE] 
Damage=35 
ROF=15 
Range=6 
Projectile=InvisibleLow 
Speed=100 
Warhead=SA 
Report=GIAttack 
Anim=MGUN-N,MGUN-NE,MGUN-E,MGUN-SE,MGUN-S,MGUN-SW,MGUN-W,MGUN-NW 
