
Prerequisite=JAWEAP,JATECH
Primary=ZSU-23
Strength=2000
Category=AirPower
Armor=medium
TechLevel=10
Sight=8
RadarInvisible=no
MoveToShroud=yes
BalloonHover=yes ; ie never land
;OmniFire=yes ;GEF moving to weapon
Speed=5
JumpjetSpeed=5 ;params not defined use defaults (old globals way up top called Jumpjet controls)
JumpjetClimb=6 ; SJM increased from 2 so Kirov can get out of factory before doors close
JumpjetCrash=12 ; Climb, but down
JumpJetAccel=10
JumpJetTurnRate=2
JumpjetHeight=750
;JumpjetWobbles=.01 ; ! value of zero stop wobbles?  NO!  Wobbles of zero means div by 0 crash.  "How many wobbles would you like?"  "0"  "You must have wobbles!!!  I kill you!"
;JumpjetDeviation=1
JumpjetNoWobbles=yes ; Really small numbers on two lines above don't actually slow down the wobbling since it is the amplitude of a sinusoidal curve
Crashable=yes ; JJ plummets down like aircraft
PitchSpeed=.9
PitchAngle=0
Owner=Russians,Confederation,Africans,Arabs
Cost=2000
Soylent=2000
Points=100
ROT=10
SpeedType=Hover
Crewed=no
ConsideredAircraft=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=14
IsSelectableCombatant=yes
VoiceSelect=KirovSelect
VoiceMove=KirovMove
VoiceAttack=KirovAttackCommand
VoiceFeedback=
VoiceCrashing=KirovVoiceDie
DieSound=
CreateSound=KirovCreated
CrashingSound=KirovDie
ImpactLandSound=KirovCrash
Locomotor={92612C46-F71F-11d1-AC9F-006008055BB5} ;Jumpjet
MovementZone=Fly
ThreatPosed=30	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
AuxSound1=Dummy ;Taking off
AuxSound2=Dummy ;Landing
AllowedToStartInMultiplayer=no
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
SelfHealing=Yes
MoveSound=KirovMoveLoop
ElitePrimary=BlimpBombE
Parasiteable=no
Size=50
Bunkerable=no; Units default to yes, others default to no



[AAWP] 
UIName=Name:AERIALPLAT 
Name=AA Weapons Platform 
Image=AERIALPLAT 
Prerequisite=NAWEAP,NARADR,NATECH 
Primary=PlatformGun 
Strength=3500 
Category=AirPower 
Armor=medium 
TechLevel=10 
Sight=10 
RadarInvisible=no 
MoveToShroud=yes 
BalloonHover=yes ; ie never land 
Turret=yes 
Speed=1 
JumpjetSpeed=1 ;params not defined use defaults (old globals way up top called Jumpjet controls) 
JumpjetClimb=10 ; SJM increased from 2 so Kirov can get out of factory before doors close 
JumpjetCrash=1 ; Climb, but down 
JumpJetAccel=1 
JumpJetTurnRate=1 
JumpjetHeight=1000 
JumpjetNoWobbles=yes ; Really small numbers on two lines above don't actually slow down the wobbling since it is the amplitude of a sinusoidal curve 
;Crashable=yes ; JJ plummets down like aircraft 
PitchSpeed=.9 
PitchAngle=0 
Owner=Russians,Confederation,Germans 
Cost=2000 
Points=100 
ROT=10 
SpeedType=Hover 
Crewed=no 
ConsideredAircraft=yes 
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60 
MaxDebris=14 
IsSelectableCombatant=yes 
VoiceSelect=GenAllWaterSelect 
VoiceMove=GenAllWaterMove 
VoiceAttack=GenAllWaterAttackCommand 
VoiceFeedback= 
VoiceCrashing= 
DieSound= 
CreateSound= 
CrashingSound= 
ImpactLandSound= 
Locomotor={92612C46-F71F-11d1-AC9F-006008055BB5} ;Jumpjet 
MovementZone=Fly 
ThreatPosed=30	; This value MUST be 0 for all building addons 
DamageParticleSystems=SparkSys,SmallGreySSys 
AuxSound1=Dummy ;Taking off 
AuxSound2=Dummy ;Landing 
AllowedToStartInMultiplayer=no 
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER 
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF 
MoveSound=KirovMoveLoop 
ElitePrimary=PlatformGunE 
Parasiteable=no 
Size=50 
CanApproachTarget=no 
DefaultToGuardArea=yes 

; large anti-aircraft cannon 
[PlatformGun] 
Damage=20 
ROF=24 
Range=5.75 
Projectile=FlakProj 
Speed=40 
Warhead=SAMWH 
Report=RhinoTankAttack 
Anim=GUNFIRE 
Bright=yes 
Burst=2 

; large anti-aircraft cannon 
[PlatformGunE] 
Damage=18 
ROF=13 
Range=5.75 
Projectile=FlakProj 
Speed=40 
Warhead=SAMWH 
Report=RhinoTankAttack 
Anim=GUNFIRE 
Bright=yes 
Burst=2 


;------------------------------------------------------------------------------
; Sky Monitor
[Monitor];[HKADP]
;----- Name -----
UIName				= Name:Monitor
Name				= Monitor

;----- GFX -----
Image				= APLT

;----- Base Attributes -----
Strength			= 150			; Dune: 1200
Size				= 2
ConsideredAircraft		= yes
ADF				= true

;----- Turret -----
Turret				= yes
TurretAttach			= MonitorTurret		; HKADPGun
TurretAnim			= MonitorTurret
TurretAnimIsVoxel		= yes

;----- Weapons -----
Primary				= Gun_F6938D8DE7BAB
AirRangeBonus			= 2			; So the weapon matches the Range (which is 8) of the Harkonnen Air Defense Platform's weapon without the need to use a different weapon than the one the Shilka (ZSU-23) is using, despite that weapon having a range of 6 only. 
GetsHeightAdvantage		= FALSE
RangeIndicator			= 10
RangeMask			= 1
OpportunityFire			= yes
FireAngle			= -30

;----- Armor -----
Armor				= Aircraft
StormDamage			= 10
Parasiteable			= no
ProtectedDriver			= yes			; automaton

;----- Perception -----
Sight				= 8			; 20
ViewRange			= 4,8
Sensors				= yes			; new
SensorSight			= 20			; new

;----- Scoring -----
Score				= 2
Points				= 2

;----- Unit AI -----
Holdback			= true
CanApproachTarget		= no

;----- Procuration -----
House				= Alliance					; Harkonnen
Side				= Alliance
Owner				= Alliance,Chinese,Japanese,Koreans
TechLevel			= 6
Prerequisite			= EAHelipad
PrimaryBuilding			= EAHelipad
UnitGroup			= FromHelipad
Cost				= 1500
BuildTime			= 750
AllowedToStartInMultiplayer	= no

;----- Load -----
Crewed				= no					; fully automated weapon system

;----- Movement -----
Terrain				= Rock, Sand, NBRock, Ramp
CanFly				= yes
HeightOffset			= 8
TurnRate			= 0.2
ROT				= 2
Speed				= 2
JumpJetSpeed			= 2
JumpjetNoWobbles		= yes

CruiseHeight			= 2000
HoverHeight			= 2000
FlightLevel			= 2000

MoveToShroud			= yes
BalloonHover			= yes
PitchSpeed			= 0
PitchAngle			= 0
SpeedType			= Hover
Locomotor			= {92612C46-F71F-11d1-AC9F-006008055BB5} ;Jumpjet
MovementZone			= Fly
Bunkerable			= no

;----- House AI -----
Category			= AirPower
AiSpecial			= yes
AIThreat			= 80
ThreatPosed			= 80
IsSelectableCombatant		= yes

;----- Sounds -----
VoiceSelect			= DroneSelect
VoiceMove			= DroneMoveCommand
VoiceAttack			= DroneAttackCommand
MoveSound			= RocketeerMoveLoop
AuxSound1			= VectorjetTakeoff			; Taking off
AuxSound2			= VectorjetLanding			; Landing

;----- Damage & Destruction -----
Crashable			= no
ExplosionType			= AerialExplosion
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
Debris				= DebrisMedium
DamageEffect			= MediumDamageFX
DamageParticleSystems		= SparkSys,SmallGreySSys
ChaosEffect			= MediumChaosFX
HawkEffect			= MediumHawkFX

;----- Veterancy -----
VeterancyLevel			= 10 
ExtraDamage			= 25
VeterancyLevel			= 24
CanSelfRepair			= 1 
VeterancyLevel			= 48
ExtraDamage			= 50  
ExtraArmour			= 50

VeteranAbilities		= FIREPOWER
EliteAbilities			= SELF_HEAL,STRONGER,FIREPOWER

;------------------------------------------------------------------------------
[MonitorTurret]			; [HKADPGun]
TurretMinXRotation		= -40.0
TurretMaxXRotation		= 90.0
TurretMinYRotation		= -190.0
TurretMaxYRotation		= 190.0
TurretYRotationAngle		= 8.0
TurretXRotationAngle		= 8.0
TurretMuzzleFlash		= Muzzle3
