
; aircraft and ground heatseeker
[RocketB72A11CBB2173]	;// TS's AAHeatSeeker2
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
AA=yes
AG=yes
Image=MISL
ROT=8
High				= yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no

[Rocket ]	;// Just an elite version of the AAHeatSeeker2; not renamed from any preexisting proj. 
ProtoTypes			= RocketB72A11CBB2173
AttachedSystem			= RedSmokeSys

; aircraft and ground heatseeker
[AAHeatSeeker6000]
Shadow=yes
Image=LRMS

; aircraft and ground heatseeker
[AAHeatSeeker250]
Arm=2
High=no
Shadow=no
Proximity=yes
Ranged=yes
AA=no
AG=yes
ASW=yes

; aircraft and ground heatseeker
[AAHeatSeeker5]
Arm=2
High=yes
Shadow=yes
Proximity=yes
Ranged=yes
AA=yes
AG=no
ASW=no
Image=DRAGON
ROT=8