
; *** Particle List ***
;  This is a list of the various particle types in the game
;  These are usually objects of gassy nature: poison gas, smoke, fire, etc...
[Particles]
; These first three must be in this order!
1=GasCloud1
2=GasCloud2
3=FireStream
4=Spark
5=FirestormSpark
6=LargeGreySmoke
7=SmallGreySmoke
8=TestSmoke
9=GasCloudD1
10=GasCloudD2
11=SmallRailgunPart
12=LargeRailgunPart
13=GasCloudM1
14=GasCloudM2
15=WeldingSpark
16=LargeSpark
17=VirusCloud1
18=VirusCloud2
19=VirusCloudD1
20=VirusCloudD2
21=PsychCloud
22=PsychCloudD
23=LaserSpark
24=RailGunPart
25=Bullet
26=Flame
27=TibDmg
28=GasCloudSpecial
29=GasCloudSpecial2
30=TibDmg2
31=TinyRailgunPart
32=TinyRailgunPart2

; *** Particle System List **
; This is a list of the various types of particles systems available in the game
[ParticleSystems]
1=GasCloudSys
2=FireStreamSys
3=BigGreySmokeSys
4=SmallGreySSys
5=DebrisSmokeSys
6=SparkSys
7=FirestormSparkSys
8=TestSmokeSys
9=SmallRailgunSys
10=LargeRailgunSys
11=WeldingSys
12=LGSparkSys
13=PsychCloudSys
14=ObeliskLaserSys
15=LaserSparkSys
16=RailGunSys
17=MiniGunSys
18=DevisTSys
19=TibDmgSys
20=AltRailgunSys
21=AltRailgun2Sys

; **************************************************************************
; ************************ Particle Systems ********************************
; **************************************************************************
; *** Particle Systems ***
;
; HoldsWhat = type of particle (see below) that this system manages (required)
; Spawns = does this system spawn particles by itself (def = no)
; SpawnFrames = number of frames to wait before spawning another particle
; ParticleCap = maximum number of particles that can be in this system

[AltRailgunSys]
BehavesLike=Railgun
HoldsWhat=TinyRailgunPart
Spawns=yes
SpawnFrames=1
SpawnRadius=1
Slowdown=.002 ; Can be any number, .002 is a good value
ParticleCap=7
SpawnCutoff=10
SpawnTranslucencyCutoff=11

[AltRailgun2Sys]
BehavesLike=Railgun
HoldsWhat=TinyRailgunPart2
Spawns=yes
SpawnFrames=1
SpawnRadius=1
Slowdown=.002 ; Can be any number, .002 is a good value
ParticleCap=7
SpawnCutoff=10
SpawnTranslucencyCutoff=11


[MiniGunSys]
HoldsWhat=Bullet
BehavesLike=Fire
Lifetime=1

[Bullet]
Image=BULLET
Deacc=0
Velocity=300
BehavesLike=Fire
MaxEC=3
StartStateAI=1
EndStateAI=3
StateAIAdvance=1
Translucent50State=1
Translucent25State=2
DeleteOnStateLimit=no
Normalized=yes
FinalDamageState=3
Report=dummy 

[FireStreamSys]
HoldsWhat=FireStream
Spawns=yes
SpawnFrames=4
BehavesLike=Fire
Image=TWLT036
Lifetime=30 ; was 100



[RailGunPart]
BehavesLike=Smoke
MaxEC=30
Image=TORPEDO ; Short small anims are the best ones
Translucency=25
Velocity=5.0
Deacc=.05
WindEffect=0
DeleteOnStateLimit=yes
EndStateAI=20
StateAIAdvance=3 


[RailGunSys]
BehavesLike=Railgun
HoldsWhat=RailGunPart
Spawns=yes
SpawnFrames=1
SpawnRadius=1
Slowdown=.002 ; Can be any number, .002 is a good value
ParticleCap=7
SpawnCutoff=10
SpawnTranslucencyCutoff=11
SpiralRadius=6


[SmallRailgunSys]
HoldsWhat=SmallRailgunPart
BehavesLike=Railgun
SpiralRadius=6
ParticlesPerCoord=.1
SpiralDeltaPerCoord=.035
MovementPerturbationCoefficient=.3
PositionPerturbationCoefficient=20
VelocityPerturbationCoefficient=.6
Laser=yes
LaserColor=255,128,0

[LargeRailgunSys]
HoldsWhat=LargeRailgunPart
BehavesLike=Railgun
SpiralRadius=15
ParticlesPerCoord=.15
SpiralDeltaPerCoord=.03
MovementPerturbationCoefficient=.4
PositionPerturbationCoefficient=30
VelocityPerturbationCoefficient=.6
Laser=yes
LaserColor=25,20,255
;R,G,B for laser color

[ObeliskLaserSys]
HoldsWhat=LargeRailgunPart
BehavesLike=Railgun
SpiralRadius=15
ParticlesPerCoord=.0
SpiralDeltaPerCoord=.03
MovementPerturbationCoefficient=0
PositionPerturbationCoefficient=0
VelocityPerturbationCoefficient=0
Laser=yes
LaserColor=255,155,155;255,25,20
;R,G,B for laser color

[WeldingSys]
HoldsWhat=WeldingSpark
BehavesLike=Spark
ParticleCap=15;gs25
SparkSpawnFrames=20
LightSize=25
OneFrameLight=true
SpawnSparkPercentage=.4

[LaserSparkSys]
HoldsWhat=Spark
BehavesLike=Spark
ParticleCap=9;gs12
SparkSpawnFrames=1
LightSize=2	; SJM 07-12-2000: Made lighting more effective so that smaller radii may be used
SpawnSparkPercentage=1

[SparkSys]
HoldsWhat=Spark
BehavesLike=Spark
ParticleCap=6;gs12
SparkSpawnFrames=1
LightSize=15	; SJM 07-12-2000: Made lighting more effective so that smaller radii may be used
SpawnSparkPercentage=1

[FirestormSparkSys]
HoldsWhat=FirestormSpark
BehavesLike=Spark
ParticleCap=20;gs25
SparkSpawnFrames=1
LightSize=21
SpawnSparkPercentage=1

; this is the global gas system
[GasCloudSys]
HoldsWhat=GasCloud1
BehavesLike=Gas

; this is the global psych gas system
[PsychCloudSys]
HoldsWhat=PsychCloud
BehavesLike=Gas

; a system for large amounts of smoke (damaged buildings, destroyed things)
[BigGreySmokeSys]
HoldsWhat=LargeGreySmoke
Spawns=yes
SpawnFrames=2;10
SpawnRadius=10
Slowdown=.0025
ParticleCap=20;gs30
SpawnCutoff=15.0
SpawnTranslucencyCutoff=13.0
BehavesLike=Smoke
Lifetime=30

; a system for small amounts of smoke (damaged units)
[SmallGreySSys]
HoldsWhat=SmallGreySmoke
Spawns=yes
SpawnFrames=2;10
SpawnRadius=5
Slowdown=.0025
ParticleCap=7;gs8
SpawnCutoff=13.0
SpawnTranslucencyCutoff=12.5
BehavesLike=Smoke
Lifetime=30

; a system for small amounts of smoke (damaged units)
[TestSmokeSys]
HoldsWhat=TestSmoke
Spawns=yes
SpawnFrames=10
SpawnRadius=5
Slowdown=.0025
ParticleCap=7;gs15
SpawnCutoff=13.0
SpawnTranslucencyCutoff=12.5
BehavesLike=Smoke

[DebrisSmokeSys]
HoldsWhat=SmallGreySmoke
Spawns=yes
SpawnFrames=2
SpawnRadius=3
ParticleCap=7;gs15
SpawnCutoff=13.0
SpawnTranslucencyCutoff=13.0
BehavesLike=Smoke



[LGSparkSys]
HoldsWhat=LargeSpark
BehavesLike=Spark
ParticleCap=7;gs15
SparkSpawnFrames=5
LightSize=25
OneFrameLight=true
SpawnSparkPercentage=.2

; this is the global gas system
[TibDmgSys]
HoldsWhat=TibDmg
BehavesLike=Gas


; **************************************************************************
; *************************** Particles ************************************
; **************************************************************************
; *** Particles ***
;
; Image = Imagelist to use for particle
; Persistent = Does this particle stick around; should always be yes
; MaxDC = How many frames go by before this particle damages the things near it? (def = 0)
; MaxEC = How many frames does this object last (def = 0)
; Damage = How much damage does it do (def = 0)
; Warhead = What warhead to use for damage purposes (def = WARHEAD_NONE)
; StartFrame = what frame of image to start on? (def = 0)
; NumLoopFrames = how many frames form a single loop? (def = 1)
; WindEffect = to what degree does the wind affect his particle, 0 = not at all, 5 = a lot (def = 0)
; Velocity = speed at which particle travels (def = 0.0)
; Radius = how big is this particle? (used for attract/repel)
;
; BehavesLike, DeleteOnStateLimit, EndStateAI, StateAIAdvance are things that
; shouldn't be messed with

; the particle that makes up the fire stream of flamethrowers, and flame tanks

[FireStream]
Image=FLAMEALL
Deacc=0.01
Velocity=21.0
BehavesLike=Fire
MaxEC=500
MaxDC=3
Warhead=Fire
Damage=2
StartStateAI=1
EndStateAI=19
StateAIAdvance=6
Translucent50State=15
Translucent25State=10
DeleteOnStateLimit=yes
Normalized=yes
FinalDamageState=14
;Report=FlameTankAttack


[TinyRailgunPart]
BehavesLike=Smoke
MaxEC=30
Image=RAILP 
Translucency=25
Velocity=5.0
Deacc=.05
WindEffect=4
DeleteOnStateLimit=yes
EndStateAI=20
StateAIAdvance=3 

[TinyRailgunPart2]
BehavesLike=Smoke
MaxEC=30
Image=RAILP2
Translucency=25
Velocity=5.0
Deacc=.05
WindEffect=4
DeleteOnStateLimit=yes
EndStateAI=20
StateAIAdvance=3 

[TibDmg]
Image=TWNK1;gaslrgmk
MaxDC=60
MaxEC=448
Damage=5
Warhead=Gas
StartFrame=0
EndStateAI=11
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=3
;NextParticle=TibDmg2;GasCloud1
DeleteOnStateLimit=yes
NextParticleOffset=0,0,150


[TibDmg2]
Image=CLOUD1
MaxDC=2;0
MaxEC=10;0;0
Damage=50;5 ;gs
Warhead=TIBDMGWH
StartFrame=0
EndStateAI=28
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
;NextParticle=GasCloudD1
Velocity=20.0

[WeldingSpark]
BehavesLike=Spark
MaxEC=500
XVelocity=16
YVelocity=16
MinZVelocity=40
ZVelocityRange=15
ColorList=(0,128,255),(255,255,255),(200,200,150),(80,80,80),(0,0,0)
StartColor1=80,255,255
StartColor2=255,255,100
ColorSpeed=.13

[LaserSpark]
BehavesLike=Spark
MaxEC=500
XVelocity=10
YVelocity=10
MinZVelocity=40
ZVelocityRange=15
ColorList=(255,255,255),(200,200,80),(200,10,10),(0,0,0)
ColorSpeed=.13

[Spark]
BehavesLike=Spark
MaxEC=500
XVelocity=10
YVelocity=10
MinZVelocity=40
ZVelocityRange=15
ColorList=(255,255,255),(200,200,80),(200,10,10),(0,0,0)
ColorSpeed=.13

[FirestormSpark]
BehavesLike=Spark
MaxEC=500
XVelocity=16
YVelocity=16
MinZVelocity=40
ZVelocityRange=15
ColorList=(0,0,255),(255,255,255),(200,200,80),(200,10,10),(0,0,0)
ColorSpeed=.13

; Cloud of Poison Gas #1 Formation particle
[GasCloudM1]
Image=gaslrgmk
MaxDC=60
MaxEC=448
Damage=0
Warhead=Gas
StartFrame=0
EndStateAI=11
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=3
NextParticle=GasCloud1
DeleteOnStateLimit=yes
NextParticleOffset=0,0,150

; Cloud of Poison Gas #2 formation particle
[GasCloudM2]
Image=gaslrgmk
MaxDC=60
MaxEC=448
Damage=0
Warhead=Gas
StartFrame=0
EndStateAI=11
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=3
NextParticle=GasCloud2
DeleteOnStateLimit=yes
NextParticleOffset=0,0,150

; Cloud of Poison Gas #1
[GasCloud1]
;Image=WCCLOUD1 ;GEF fending off possible future asserts
Image=CLOUD1
MaxDC=60
MaxEC=1000
Damage=50;5 ;gs
Warhead=Gas
StartFrame=0
EndStateAI=28
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
NextParticle=GasCloudD1

; Cloud of Poison Gas #2
[GasCloud2]
;Image=WCCLOUD1 ;GEF fending off possible future asserts
Image=CLOUD2
MaxDC=60
MaxEC=1000
Damage=40
Warhead=Gas
StartFrame=0
EndStateAI=28
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
NextParticle=GasCloudD2


; Cloud of Poison Gas #2
[GasCloudSpecial]
;Image=WCCLOUD1 ;GEF fending off possible future asserts
Image=CLOUD3
MaxDC=6
MaxEC=100
Damage=40
Warhead=Gas
StartFrame=0
EndStateAI=28
Translucency=50
WindEffect=5
BehavesLike=Gas
StateAIAdvance=4
NextParticle=GasCloudSpecial2

[GasCloudSpecial2]
;Image=WCCLOUD1 ;GEF fending off possible future asserts
Image=CLOUD3D
MaxDC=60
MaxEC=50
Damage=10
Warhead=Gas
StartFrame=0
EndStateAI=12
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
DeleteOnStateLimit=yes


; Cloud of Poison Gas #1 Dissipation particle
[GasCloudD1]
;Image=WCCLOUD1 ;GEF fending off possible future asserts
Image=CLOUD1D
MaxDC=60
MaxEC=50
Damage=10
Warhead=Gas
StartFrame=0
EndStateAI=12
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
DeleteOnStateLimit=yes

; Cloud of Poison Gas #2 dissipating
[GasCloudD2]
;Image=WCCLOUD1 ;GEF fending off possible future asserts
Image=CLOUD2D
MaxDC=60
MaxEC=50
Damage=10
Warhead=Gas
StartFrame=0
EndStateAI=12
Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
DeleteOnStateLimit=yes

; Cloud of Poison Gas #1
[VirusCloud1]
Image=TXGASG
MaxDC=30;60
MaxEC=1000
Damage=5 ;gs
Warhead=VirusGas
StartFrame=0
EndStateAI=20;28
;Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
NextParticle=VirusCloudD1

; Cloud of Poison Gas #2
[VirusCloud2]
Image=LGRYSMK1
MaxDC=30;60
MaxEC=1000
Damage=10;40
Warhead=VirusGas
StartFrame=0
EndStateAI=20;28
;Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
NextParticle=VirusCloudD2

; Cloud of Poison Gas #1 Dissipation particle
[VirusCloudD1]
Image=TXGASG
MaxDC=60
MaxEC=50
Damage=5
Warhead=VirusGas
StartFrame=0
EndStateAI=20;12
;Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
DeleteOnStateLimit=yes

; Cloud of Poison Gas #2 dissipating
[VirusCloudD2]
Image=LGRYSMK1
MaxDC=60
MaxEC=50
Damage=5
Warhead=VirusGas
StartFrame=0
EndStateAI=20;12
;Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
DeleteOnStateLimit=yes

; Cloud of Poison Gas #1
[PsychCloud]
Image=TXGASR
MaxDC=20
MaxEC=50;1000
Damage=600;5 ;gs
Warhead=PsychGas
StartFrame=0
EndStateAI=20;28
;Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
NextParticle=PsychCloudD

; Cloud of Poison Gas #1 Dissipation particle
[PsychCloudD]
Image=TXGASR
MaxDC=60
MaxEC=50
Damage=10
Warhead=PsychGas
StartFrame=0
EndStateAI=20;12
;Translucency=50
WindEffect=0
BehavesLike=Gas
StateAIAdvance=4
DeleteOnStateLimit=yes

[LargeGreySmoke]
Image=LGRYSMK1
MaxEC=80
Translucency=50
Velocity=8.0
Deacc=.05
WindEffect=0
BehavesLike=Smoke
DeleteOnStateLimit=yes
EndStateAI=20
StateAIAdvance=4

[SmallGreySmoke]
Image=SGRYSMK1
MaxEC=80
Translucency=50
Velocity=9.0
Deacc=.05
WindEffect=0
BehavesLike=Smoke
DeleteOnStateLimit=yes
EndStateAI=20
StateAIAdvance=4

[TestSmoke]
Image=SGRYSMK1
MaxEC=80
Translucency=25
Velocity=6.0
Deacc=.05
WindEffect=0
BehavesLike=Smoke
DeleteOnStateLimit=yes
EndStateAI=20
StateAIAdvance=3

[SmallRailgunPart]
BehavesLike=Railgun
MaxEC=10 ;70
ColorList=(200,200,200),(150,150,150)
ColorSpeed=.03
Velocity=.4

[LargeRailgunPart]
BehavesLike=Railgun
MaxEC=15 ;70
ColorList=(25,70,205),(150,150,150)
ColorSpeed=.009
Velocity=.3

[LargeSpark]
BehavesLike=Spark
MaxEC=500
XVelocity=13
YVelocity=13
MinZVelocity=40
ZVelocityRange=15
ColorList=(255,255,255),(200,200,80),(200,10,10),(0,0,0)
ColorSpeed=.13
