
; *** Super Weapon List **
; This is a list of the various types of super weapons available in the game
[SuperWeaponTypes]
;1=MultiSpecial
;2=EMPulseSpecial
;3=FirestormSpecial
;4=IonCannonSpecial
;5=HuntSeekSpecial
;6=ChemicalSpecial
;7=IronCurtainSpecial
;8=LightningStormSpecial
;9=ChronoSphereSpecial
;10=ChronoWarpSpecial
;11=ParaDropSpecial

1=NukeSpecial
2=IronCurtainSpecial
3=LightningStormSpecial
4=ChronoSphereSpecial
5=ChronoWarpSpecial
6=ParaDropSpecial
7=AmericanParaDropSpecial
8=PsychicDominatorSpecial
9=SpyPlaneSpecial
10=GeneticConverterSpecial
11=ForceShieldSpecial
12=PsychicRevealSpecial
;
13=HunterSeekerSpecial
14=IonCannonSpecial
15=EMPulseSpecial
16=DropPodSpecial
17=FirestormSpecial
18=MultiSpecial
19=ChemicalSpecial
20=MultiSpecial2
21=DropPodSpecial2
; ******* Special Weapon types *******
; IsPowered -- does this super weapon become inoperative in a low power situation?
; RechargeVoice -- Voice to use when weapon is fully recharged and ready.
; ChargingVoice -- Voice to use when weapon begins charging.
; ImpatientVoice -- Voice to use when user clicks on weapon that isn't finished charging.
; SuspendVoice -- Voice to use when special weapon charging is suspended.
; RechargeTime -- time in minutes to recharge this special
; Range -- How big a circle will be drawn in targeting mode. The default is 0 which means no circle will be drawn -GEF
; LineMultiplier -- Higher number means more densly packed lines in targeting mode. The default is zero which means just one line. -GEF

; Chem weapon. The logic will fail if this weapon is 'powered'
[ChemicalSpecialxxx]
Name=Chemical Missile
IsPowered=false
RechargeVoice=00-I152
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=.3
Type=ChemMissile
SidebarImage=ChemIcon
Action=ChemBomb
ManualControl=yes
WeaponType=ChemLauncher
AuxBuilding=NAWAST

;This is the nuke special
[NukeSpecial]
UIName=Name:Nuke
Name=N U K E !!!
IsPowered=true
RechargeVoice=00-I154
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=0.1
;RechargeTime=10
Type=MultiMissile
SidebarImage=MLTIICON
Action=Nuke
WeaponType=NukeCarrier
ShowTimer=yes
DisableableFromShell=yes ; gs this determines which superweapons are turned off by the checkbox
AIDefendAgainst=yes;AI will use AISuperDefense system to decide to block this
Range=7
LineMultiplier=2





[IronCurtainSpecial]
UIName=Name:Iron
Name=Iron Curtain
IsPowered=true
RechargeVoice=00-I156
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=5
Type=IronCurtain
Action=IronCurtain
SidebarImage=IRCRICON
ShowTimer=yes
DisableableFromShell=yes ; gs this determines which superweapons are turned off by the checkbox
Range=1.4
LineMultiplier=3

[ForceShieldSpecial]
UIName=Name:ForceShield
Name=Force Shield
IsPowered=true
RechargeVoice=00-I156
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=5
Type=ForceShield
Action=ForceShield
SidebarImage=FORCICON
ShowTimer=no
DisableableFromShell=yes
SpecialSound=ForceShieldFading;gs wildcard sound hook.  In this case, play at ForceShieldDuration - ForceShieldPlayFadeSoundTime after firing
StartSound=ForceShieldStarting;gs no anim to hook this on to, so hook it here.
FlashSidebarTabFrames=120; default is always, put 0 for never, or a number for x
Range=3.4
LineMultiplier=3

[LightningStormSpecial]
UIName=Name:Storm
Name=Lightning Storm
IsPowered=true
RechargeVoice=00-I156
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=10
Type=LightningStorm
Action=LightningStorm
SidebarImage=BOLTICON
ShowTimer=yes
DisableableFromShell=yes ; gs this determines which superweapons are turned off by the checkbox
AIDefendAgainst=yes;AI will use AISuperDefense system to decide to block this
Range=7
LineMultiplier=2

[ChronoSphereSpecial]
UIName=Name:Chrono
Name=Chrono Sphere
IsPowered=true
RechargeVoice=00-I156
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=7
Type=ChronoSphere
Action=ChronoSphere
SidebarImage=CHROICON
PreClick=yes
ShowTimer=yes
DisableableFromShell=yes ; gs this determines which superweapons are turned off by the checkbox
Range=1.4
LineMultiplier=3

;Do we need a dummy weapon?
[ChronoWarpSpecial]
UIName=Name:Chrono2
Name=Chrono Warp
IsPowered=false
RechargeVoice=
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=1
Type=ChronoWarp
Action=ChronoWarp
SidebarImage=XXXXICON
PostClick=yes
PreDependent=ChronoSphere
Range=1.4
LineMultiplier=3

[ParaDropSpecial]
UIName=Name:Para
Name=Paratrooper Drop
IsPowered=false
RechargeVoice=
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=4
Type=ParaDrop
Action=ParaDrop
SidebarImage=PARAICON
ShowTimer=no
DisableableFromShell=no ; gs this determines which superweapons are turned off by the checkbox

[AmericanParaDropSpecial]
UIName=Name:APara
Name=American Paratrooper Drop
IsPowered=false
RechargeVoice=
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=4
Type=AmerParaDrop
Action=AmerParaDrop
SidebarImage=APARICON
ShowTimer=no
DisableableFromShell=no ; gs this determines which superweapons are turned off by the checkbox

[PsychicDominatorSpecial]
UIName=Name:YAPPET
Name=Lightning Storm
IsPowered=true
RechargeVoice=00-I156
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=10
Type=PsychicDominator
Action=PsychicDominator
SidebarImage=PDOMICON
ShowTimer=yes
DisableableFromShell=yes ; gs this determines which superweapons are turned off by the checkbox
Range=1.4
LineMultiplier=3

[SpyPlaneSpecial]
UIName=Name:SpyP
Name=SpyPlane Flyby
IsPowered=false
RechargeVoice=
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=4
Type=SpyPlane
Action=SpyPlane
SidebarImage=SPYPICON
ShowTimer=no
DisableableFromShell=no ; gs this determines which superweapons are turned off by the checkbox
FlashSidebarTabFrames=120; default is always, put 0 for never, or a number for x

[GeneticConverterSpecial]
UIName=Name:YAGNTC
Name=Genetic Converter
IsPowered=true
RechargeVoice=00-I156
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=5
Type=GeneticConverter
Action=GeneticConverter
SidebarImage=MUTEICON
ShowTimer=yes
DisableableFromShell=yes ; gs this determines which superweapons are turned off by the checkbox
Range=5
LineMultiplier=3

[PsychicRevealSpecial]
UIName=Name:PsyReveal
Name=Psychic Reveal
IsPowered=false
RechargeVoice=
ChargingVoice=
ImpatientVoice=                                  
SuspendVoice=
RechargeTime=4
Type=PsychicReveal
Action=PsychicReveal
SidebarImage=PSYRICON
ShowTimer=no
DisableableFromShell=no ; gs this determines which superweapons are turned off by the checkbox
FlashSidebarTabFrames=120; default is always, put 0 for never, or a number for x


[MultiSpecial]
UIName=NOSTR:Multi-Cluster Missile
Name=N U K E !!!
Type=MultiMissile
SidebarImage=MltiIcon
Action=Custom
Cursor.Frame=568
Cursor.Count=10
Cursor.MiniFrame=43
Cursor.MiniCount=10
NoCursor.Frame=538
NoCursor.Count=1
MiniFrame=2
MiniCount=1
RechargeTime=0.2
WeaponType=MultiLauncher;NukeCarrier
ShowTimer=yes
Text.Preparing=NOSTR:Preparing
AIDefendAgainst=yes;AI will use AISuperDefense system to decide to block this
Range=3.5
LineMultiplier=2
Nuke.TakeOff=INVISO
;Light.Enabled=no
SW.ActivationSound=MisslieLaunch
DisableableFromShell=yes
SW.AITargeting=Nuke

[ChemicalSpecial]
UIName=NOSTR:Chemical Missile
Name=N U K E !!!
Type=MultiMissile
SidebarImage=ChemIcon
Action=Custom
Cursor.Frame=558
Cursor.Count=10
Cursor.MiniFrame=43
Cursor.MiniCount=10
NoCursor.Frame=538
NoCursor.Count=1
MiniFrame=2
MiniCount=1
RechargeTime=0.1
;RechargeTime=10
WeaponType=ChemLauncher
ShowTimer=yes
Text.Preparing=NOSTR:Preparing
AIDefendAgainst=yes;AI will use AISuperDefense system to decide to block this
Range=7
LineMultiplier=2
Nuke.TakeOff=INVISO
Light.Enabled=no
SW.ActivationSound=MisslieLaunch
;AuxBuilding=NAWAST
DisableableFromShell=yes

[IonCannonSpecial]
UIName=NOSTR:Ion Cannon
Name=Ion Cannon
IsPowered=true
SidebarImage=IONCICON
ShowTimer=no
RechargeTime=7
Type=PsychicDominator
Action=Custom
Cursor.Frame=538
Cursor.Count=20
Cursor.MiniFrame=43
Cursor.MiniCount=10
NoCursor.Frame=537
NoCursor.Count=1
MiniFrame=2
MiniCount=1
Dominator.FirstAnim=IONBEAM
Dominator.FirstAnimHeight=0
Dominator.SecondAnim=RING1
Dominator.Capture=no
Dominator.FireAtPercentage=5
Light.Enabled=no
SW.Warhead=IonCannonWH
SW.Damage=600
SW.Range=5
SW.ActivationSound=NoSound
DisableableFromShell=yes
SW.AITargeting=Nuke
ShowTimer=yes

[HunterSeekerSpecial]
UIName=NOSTR:Hunter-Seeker
Name=N U K E !!!
Type=MultiMissile
SidebarImage=DetnIcon
Action=Custom
Cursor.Frame=89
Cursor.Count=10
Cursor.MiniFrame=43
Cursor.MiniCount=10
NoCursor.Frame=537
NoCursor.Count=1
MiniFrame=2
MiniCount=1
RechargeTime=7
WeaponType=HSLauncher
ShowTimer=yes
Text.Preparing=Preparing
Nuke.TakeOff=INVISO
SW.ActivationSound=DroidLaunch
SW.AffectsTarget=units,buidings
SW.AffectsHouse=enemy
SW.RequiresTarget=units
SW.RequiresHouse=enemy
Light.Enabled=no

[EMPulseSpecial]
UIName=Name:Iron
Name=E.M. Pulse
IsPowered=true
RechargeVoice=EVA_EMPReady;00-I156
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime5
Type=GenericWarhead
Action=Custom
Cursor.Frame=518
Cursor.Count=20
Cursor.MiniFrame=43
Cursor.MiniCount=10
NoCursor.Frame=538
NoCursor.Count=1
MiniFrame=2
MiniCount=1
SidebarImage=PulsIcon
DisableableFromShell=yes ; gs this determines which superweapons are turned off by the checkbox
SW.Warhead=EMPuls 
SW.Damage=100
EVA.SelectTarget=EVA_SelectTarget
EVA.Detected= 
EVA.Ready=EVA_EMPReady
EVA.Activated=
Text.Preparing=NOSTR:Charging

;[EMPulseSpecial]
;UIName=NOSTR:E.M. Pulse
;Name=E.M. Pulse
;IsPowered=true
;RechargeVoice=EVA_EMPReady
;ChargingVoice=
;ImpatientVoice=
;SuspendVoice=
;RechargeTime=0.5;4.5
;SidebarImage=PulsIcon
;Type=GenericWarhead

;Action=Custom
;Cursor.Frame=518
;Cursor.Count=20
;Cursor.MiniFrame=43
;Cursor.MiniCount=10
;NoCursor.Frame=538
;NoCursor.Count=1
;MiniFrame=2
;MiniCount=1
;EVA.Detected= 
;EVA.Ready=EVA_EMPReady
;EVA.Activated=
;SW.FireIntoShroud=no
;Range=1.8
;ShowTimer=yes
;SW.Warhead=EMPuls 

[FirestormSpecial]
UIName=NOSTR:
Name=Firestorm Defense
IsPowered=true
RechargeVoice=00-I162
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=3
Type=Firestorm
SidebarImage=FSTDICON
UseChargeDrain=true

;[DropPodSpecial]


;[DropPodSpecial2]
