; ******* Tiberium Varieties *******
; There are various kinds of tiberium. This lists their number and
; particulars.

[Tiberiums]
0=Riparius
1=Cruentus
2=Vinifera
3=Aboreus

; Name = display name
; Image = image to use [1=small, 2=large, 3=vine]
; Value = credit value per 'bail'
; Growth = growth rate
; Spread = spread rate
; Power = explosive power per 'bail' (def=0)
; Color = display color of the Tiberium
; Shard = crystal to fly off when chain reacting (def=none)

; This is Ore
[Riparius]
Name=Tiberium Riparius
Image=1
Power=4
Value=25
Growth=4300;2200
GrowthPercentage=90;.09
Spread=4300;2200
SpreadPercentage=90;.09
Color=NeonGreen			; **WARNING**: If you change this color, notify Bret_a

; These are Gems
[Cruentus]
Name=Tiberium Cruentus
Image=2
Value=70
Growth=10000
GrowthPercentage=0.01
Spread=10000
SpreadPercentage=0.01
Power=10
Color=NeonBlue			; **WARNING**: If you change this color, notify Bret_a
Debris=CRYSTAL1,CRYSTAL2,CRYSTAL3,CRYSTAL4

; This may also be ore - DB
[Vinifera]
Name=Tiberium Vinifera
Image=3
Value=40
Growth=10000
GrowthPercentage=.05
Spread=10000
SpreadPercentage=.05
Power=100
Color=NeonBlue		; **WARNING**: If you change this color, notify Bret_a
Debris=CRYSTAL1,CRYSTAL2,CRYSTAL3,CRYSTAL4

; This might be ore, I'm not certain - DB
[Aboreus]
Name=Tiberium Aboreus
Image=4
Value=30
Growth=10000
GrowthPercentage=.05
Spread=10000
SpreadPercentage=.05
Power=10
Color=NeonBlue		; **WARNING**: If you change this color, notify Bret_a
Debris=CRYSTAL1,CRYSTAL2,CRYSTAL3,CRYSTAL4