
; ***  Animation List ***
; This is the complete list of voxel animations available.
; VoxelAnims are meant to be flying debris.  Things like
; turrets and tires make good voxel anims.
[VoxelAnims]
1=PIECE
2=TIRE
3=GASTANK
4=SONICTURRET
5=4TNKTURRET
6=CRYSTAL01
7=CRYSTAL02
8=METEOR01
9=METEOR02
10=PEBBLE

; ******* Voxel Debris types *******
; Translucent = is the debris to be drawn with translucency (def=no)?
; Elasticity = "bounciness" of the object [should be 0.0 through 1.0] (def=0.75)
; MinAngularVelocity = minimum rate at which the debris is to spin in degrees (def=0.0)
; MaxAngularVelocity = maximum rate at which the debris is to spin in degrees (def=10.0)
; Duration = max number of frames to let the debris exist (def=30)
; MinZVel = minimum starting Z velocity (def=3.5)
; MaxZVel = maximum starting Z velocity (def=5.0)
; MaxXYVel = maximim starting lateral velocity (def=15.0)
; ShareBodyData = Get the voxel data from another Type's body voxel data (def = no)?
; ShareTurretData = Get the voxel data from another Type's turret voxel data (def = no)?
; ShareBarrelData = Get the VOXEL data from another Type's barrel voxel data (def = no)?
; ShareSource = name of the object to share voxel data from (def = none)
; VoxelIndex = voxel piece within the voxel data to use (def = 0)
; StartSound = sound to play when the voxel anim is created (def = VOC_NONE).
; BounceSound = sound to play when the voxel anim bounces (def = VOC_NONE).
; ExpireSound = sound to play when the voxel anim expires (def = VOC_NONE).
; BounceAnim = animation to launch when the voxel anim bounces (def = ANIM_NONE).
; ExpireAnim = animation to launch when the voxel anim expires (def = ANIM_NONE).
; TrailerAnim = animation to trail behind the object (usually smoke or flame)
; DamageRadius = the debris damages objects that it hits if they're closer than this distance
; Damage = amount of damage to apply to objects that are hit
; Warhead = warhead to use for damage purposes
; AttachedSystem = particle system to attach to the voxel anim
; Spawns = the particle spawned when this voxel debris explodes (def = none)
; SpawnCount = number of particles spawned [on average] (def = 0)

[PIECE]
Name=Scrap Metal Debris
Elasticity=0
MinAngularVelocity=5.0
MaxAngularVelocity=9.0
MinZVel=24.0
MaxZVel=28.0
MaxXYVel=15.0
Duration=75
Damage=5
ExpireAnim=TWLT036
DamageRadius=100
Warhead=TankOGas

[TIRE]
Name=Flying Tire
Elasticity=0.8
MinAngularVelocity=12.0
MaxAngularVelocity=24.0
MinZVel=28.0
MaxZVel=32.0
MaxXYVel=10.0
Duration=150

[GASTANK]
Name=Flying Gas Tank
Elasticity=0.0
MinAngularVelocity=9.0
MaxAngularVelocity=15.0
MinZVel=30.0
MaxZVel=35.0
MaxXYVel=8.0
Duration=100
ExpireAnim=TWLT036
Damage=20
DamageRadius=100
Warhead=TankOGas

[SONICTURRET]
Name=Disruptor Turret
ShareTurretData=yes
ShareSource=SONIC
Elasticity=0.0
MinAngularVelocity=10.0
MaxAngularVelocity=14.0
MinZVel=30.0
MaxZVel=38.0
MaxXYVel=8.0
Duration=100
ExpireAnim=TWLT026
Damage=90
DamageRadius=100
Warhead=TankOGas

[4TNKTURRET]
Name=Mammoth Tank Turret
ShareTurretData=yes
ShareSource=4TNK
Elasticity=0.0
MinAngularVelocity=10.0
MaxAngularVelocity=14.0
MinZVel=30.0
MaxZVel=38.0
MaxXYVel=8.0
Duration=100
ExpireAnim=TWLT036
Damage=30
DamageRadius=50
Warhead=TankOGas

[CRYSTAL01]
Name=TiberiumCrystal01
ShareTurretData=yes
ShareSource=SONIC
Elasticity=0.0
MinAngularVelocity=12.0
MaxAngularVelocity=24.0
MinZVel=28.0
MaxZVel=32.0
MaxXYVel=10.0
Duration=150
ExpireAnim=TWLT050
Damage=40
DamageRadius=100
Warhead=TankOGas
IsTiberium=true

[CRYSTAL02]
Name=TiberiumCrystal02
Image=GASTANK
Elasticity=0.0
MinAngularVelocity=12.0
MaxAngularVelocity=24.0
MinZVel=40.0
MaxZVel=45.0
MaxXYVel=18.0
Duration=150
ExpireAnim=TWLT050
Damage=40
DamageRadius=100
Warhead=TankOGas
IsTiberium=true

[METEOR01]
Name=Meteorite01
Image=MTRS
Elasticity=0.0
MinAngularVelocity=12.0
MaxAngularVelocity=30.0
MinZVel=-100.0
MaxZVel=-100.0
MaxXYVel=100.0
Duration=70
ExpireAnim=TWLT070
Damage=500
DamageRadius=300
Warhead=Meteorite
IsMeteor=true
Spawns=PEBBLE
SpawnCount=5

[METEOR02]
Name=Meteorite02
Image=MTRB
Elasticity=0.0
MinAngularVelocity=12.0
MaxAngularVelocity=30.0
MinZVel=-100.0
MaxZVel=-100.0
MaxXYVel=100.0
Duration=70
ExpireAnim=TWLT100
Damage=500
DamageRadius=300
Warhead=Meteorite
IsMeteor=true
IsTiberium=true
Spawns=PEBBLE
SpawnCount=7

[PEBBLE]
Name=TiberiumShard
Image=MTRB
Elasticity=0.0
MinAngularVelocity=12.0
MaxAngularVelocity=24.0
MinZVel=40.0
MaxZVel=45.0
MaxXYVel=18.0
Duration=150
ExpireAnim=TWLT036
Damage=20
DamageRadius=100
Warhead=TankOGas
IsTiberium=true
