
; Sonic Zap
[SonicGun]
Damage				= 4
AmbientDamage			= 10
ROF				= 120
Range				= 6
;Projectile			= Null
Projectile			= SonicBullet
Speed				= 100
Warhead				= SonicWarhead
Report				= DolphinAttack
IsSonic				= Yes

[SonicBullet]
Image				= SONICBULL
ROT				= 1
Acceleration			= 50
