
[InfantryTypes]
E6BC191765FBE			= FLYBUG

[FLYBUG]
Name				= Tiberium Flyer
Category=Soldier
Fearless=no
Primary=ClawAttack
;Prerequisite=GAPILE
Crushable=no
Strength=125
Armor=none
TechLevel=6
Sight=6
Pip=green
Speed=2
Owner=GDI;civilian could be better
DoubleOwned=yes
AllowedToStartInMultiplayer=yes
Cost=600
Points=5
VoiceSelect=15-I000,15-I004,15-I012,15-I048
VoiceMove=15-I018,15-I024,15-I044
VoiceAttack=15-I044,15-I050,15-I044,15-I046
VoiceFeedback=15-I058,15-I064
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=Fly; This needs to be None, like aircraft
ThreatPosed=15; This value MUST be 0 for all building addons
TiberiumProof=yes
TiberiumHeal=yes
ImmuneToVeins=yes
VeteranAbilities=ROF,FASTER,SIGHT
EliteAbilities=STRONGER,FIREPOWER

[ClawAttack]
Damage=65
ROF=80
Range=2
Speed=100
Warhead=Super
Report=LASTUR1;find a good sound for this
Projectile=Invisible

[AcidSpray]
