
;------------------------------------------------------------------------------
[BuildingTypes]
9BC21F3EB9596			= TowerWoodB

;------------------------------------------------------------------------------
;Allied Guard Tower/Civilian Lookout
[TowerWoodB]
Image=CAGTWR
;----- Name -----
UIName				= Name:GTWR
Name				= Guard Tower

;----- Base Attributes -----
Strength			= 200
IsBaseDefense			= yes

;----- Weapons -----
Primary				= 
;HasSpotlight			= yes

;----- Armor -----

;----- Perception -----
Sight				= 8

;----- Crew -----
Crewed				= no
CanBeOccupied			= yes
MaxNumberOccupants		= 2
CanOccupyFire			= yes

;----- Procuration -----
DoubleOwned			= yes
TechLevel			= 1
Prerequisite			= 
Adjacent=4
AIBasePlanningSide=0 ;gs 0 for Good, 1 for Evil
Armor=steel
BaseNormal=no
BuildCat=Combat
;Prerequisite=GACNST
Capturable=True
ClickRepairable=yes
Cost=250
DebrisAnim=Dbris3sm,Dbris4lg,Dbris4sm,Dbris6sm,Dbris7lg,Dbris7sm,Dbris8sm,Dbris10lg,Dbris10sm
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=15
MinDebris=5
Owner=British,French,Germans,Americans,Alliance

;----- Power -----
Powered				= no
Power				= -10	; from TD
Strength=500
AntiInfantryValue=30
AntiArmorValue=5
AntiAirValue=0

; guard tower
[GTWR]
Prerequisite=PYLE
Buildable=yes
Primary=Chaingun
Strength=400
Armor=wood
TechLevel=2
BuildLevel=7
Sight=3
Owner=GoodGuy
Cost=500
Crewed=yes
Sensors=yes

; rapid fire machine gun
[Chaingun]
Damage=25
ROF=50
Range=4
Projectile=Invisible
Speed=100
Warhead=HE
Report=GUN8
Explosion=2
Anim=MINIGUN
