
;------------------------------------------------------------------------------
[VehicleTypes]
+				= TnkMeteo

;------------------------------------------------------------------------------
; METBUG (Wargasmic Sun)
[XComet]
;----- Text -----
Name				= Meteor Invoker			; Invader ; Shared this name with the Covert Ops II mech unit. 
UIName				= name:xcomet
UIDescription			= desc:xcomet
;----- Taxonomy -----
Category			= LRFS					; Recon
;----- Gfx -----
; Image				= 1tnk
Image				= htnk
;----- Body -----
Strength			= 220					; Fragile, but resist crush damage. 
Weight				= -1
Size				= 5
;----- Turrets -----
Turret				= yes					; no
TurretAttach			= 
TurretAnim			= 
TurretAnimIsVoxel		= yes
TurretCount			= 1
IsChargeTurret			= yes
;----- Weapons -----
Primary				= MeteorMagnetA
Secondary			= MeteorMagnetB
Elite				= 
ElitePrimary			= 
EliteSecondary			= 
Range				= 9					; This was included in the orignal code! Range is not a valid Techno setting, but we used it to inspire the altered weapon range. 
;----- Armor -----
Armor				= MeteorArmor				; light
ImmuneToVeins			= yes
;----- Perception -----
Sight				= 6
;----- Availability -----
Side				= Scrin
Owner				= Nod
; House				= 
TechLevel			= 2
Prerequisite			= NAWEAP, NATECH			; naweap
Cost				= 2500					; 500
AllowedToStartInMultiplayer	= no
CrateGoodie			= yes
;----- Score -----
Points				= 25
;----- Audio -----
VoiceSelect			= SelectXComet
VoiceMove			= CmdMovXComet
VoiceAttack			= CmdAtkXComet
VoiceFeedback			= 
;----- Movement -----
Speed				= 10
Locomotor			= {4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone			= Destroyer				; Normal
ROT				= 8
IsTilter			= yes
;----- Damage & Destruction -----
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DebrisTypes			= xcomet, xcomettur, piece, mtrb, mtrs			; piece
DebrisMinimums			= 1, 0, 2, 1, 2
DebrisMaximums			= 1, 1, 4, 3, 5						; 4
MinDebris			= 
MaxDebris			= 3


ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
;----- Veterancy -----
EliteAbilities			= CRUSHER

TooBigToFitUnderBridge=true

Points=50
IsSelectableCombatant=yes
AllowedToStartInMultiplayer=no
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=3
ThreatPosed=40	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=100, 100, 275
Weight=3.5
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
Accelerates=false
ZFudgeColumn=8
ZFudgeTunnel=13
Size=3



; Mgmet
; [Mgmet] (Wargasmic Sun)
[MeteorMagnet]
;----- Payload -----
; Damage			= 50
Warhead				= Meteorite
;----- Availability -----
ROF				= 40
;----- Projection -----
Projectile			= InvisibleHigh			; Cannon
Speed				= -1				; 40
Range				= 6.00
;----- Display -----
Anim				= meteor_muzzle			; GUNFIRE
; Bright			= true


