
;------------------------------------------------------------------------------
[ArmorTypes]
+				= ArmorTank
+				= ArmorTank2

;------------------------------------------------------------------------------
; TankArmor (gen/zh)
Armor ArmorTank
[ArmorTank]
<ArmorTemplate
id				= "ArmorTank"					; ra3: "BaseTankArmor"
SideDamageScalar		= 			"110"
RearDamageScalar		= 			"120"
>

Armor				= CRUSH			50%			; Tanks are extra-hard to crush. 

Armor				= SMALL_ARMS		25%
<Armor
	Damage			= "GUN"
	Percent			=			"25"
	/>	

Armor				= GATTLING		10%			; resistant to gattling tank
Armor				= COMANCHE_VULCAN    	25%
Armor				= FLAME			25%
		<Armor
			Damage="FLAME"
			Percent="40" />
Armor				= RADIATION		50%			; Radiation does less damage to tanks. 
Armor				= MICROWAVE		0%

<Armor
	Damage			= "RADIATION"
	Percent			= 			"5"
	/>

Armor				= POISON		25%			; Poison does a little damage, just for balance reasons.  

Armor				= SNIPER		0%
<Armor
	Damage			= "SNIPER"
	Percent			=			"0"
	/>

Armor				= MELEE			0%			;tanks don't generally take much damage other than paint damage from MELEE weapons
<Armor
	Damage			= "MELEE"
	Percent			= 			"1"
	/>

Armor				= LASER			0%			; lasers are anti-personel and anti-projectile only (for point defense laser)

Armor				= LASER2
<Armor
	Damage			= "LASER2"					; big lasers, ra3: "PRISM"
	Percent			= 			"100"
	/>

Armor				= HAZARD_CLEANUP	0%			; Not harmed by cleaning weapons

Armor				= PARTICLE_BEAM		100%

Armor				= KILL_PILOT		100%			; Jarmen Kell uses against vehicles only. 

Armor				= SUBDUAL		0%      		; Capture type weapons are effective only against infantry.
										; We do not call this type "SURRENDER" (as in vanilla gen/zh). 
Armor				= SUBDUAL_MISSILE	0%
Armor				= SUBDUAL_VEHICLE	100%
Armor				= SUBDUAL_BUILDING	0%
End
	
		<Armor
			Damage="AUTO_CANNON"
			Percent="30" />
		<Armor
			Damage="IMPACT"
			Percent="75" />
		<Armor
			Damage="FLAK"
			Percent="100" />	

		<Armor
			Damage="ROCKET"
			Percent="100" />
		<Armor
			Damage="CANNON"
			Percent="100" />
		<Armor
			Damage="TESLA"
			Percent="100" />
		<Armor
			Damage="EXPLOSIVE"
			Percent="100" />
		<Armor
			Damage="CONCUSSIVE"
			Percent="100" />
		<Armor
			Damage="KI"
			Percent="95" />
</ArmorTemplate>
End

;------------------------------------------------------------------------------
; reduces damage some
; UpgradedTankArmor (gen/zh)
[ArmorTank2]:[ArmorTank]
Armor				= CRUSH			30%

Armor				= RADIATION		50%			; Radiation does less damage to tanks. 


Armor				= SMALL_ARMS		20%
Armor				= COMANCHE_VULCAN	20%
Armor				= FLAME			10%
Armor				= POISON		10%
End
