
; StructureArmor (gen/zh)
Armor ArmorStructure
Armor				= DEFAULT           100%    ; this sets the level for all nonspecified damage types
  Armor = SMALL_ARMS        50%
  Armor = GATTLING          10%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN   50%
  Armor = RADIATION         0%      ;Radiation does no damage to buildings.
  Armor = MICROWAVE         0%
  Armor = SNIPER            0%
  Armor = POISON            1%    ; Poison does a tiny amount to allow firing on empty buildings
  Armor = MELEE             0%
  Armor = LASER             0%    ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP    0%      ;Not harmed by cleaning weapons
  Armor = INFANTRY_MISSILE  50%
  Armor = PARTICLE_BEAM     200%  ;orbital beams should be devastating to buildings, but buildings have a lot of hitpoints so extra damage is good...
  Armor = KILL_PILOT        0%      ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER         0%    ;Capture type weapons are effective only against infantry.
  Armor = AURORA_BOMB       250%
  Armor = LAND_MINE         0%    ;buildings take no damage from mines
  Armor = FLAME             50%
;----- Subdual -----
Armor				= SUBDUAL			0%			; Surrender ; buildings are immune to normal damage from STUN weapons.
Armor				= SUBDUAL_MISSILE		0%
Armor				= SUBDUAL_VEHICLE		0%
Armor				= SUBDUAL_BUILDING		100%
End

Armor StructureArmorTough
  Armor = DEFAULT           100%    ; this sets the level for all nonspecified damage types
  Armor = Surrender         0%    ; buildings are immune to normal damage from STUN weapons.
  Armor = SMALL_ARMS        50%
  Armor = GATTLING          10%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN   50%
  Armor = RADIATION         0%      ;Radiation does no damage to buildings.
  Armor = MICROWAVE         0%
  Armor = SNIPER            0%
  Armor = POISON            1%    ; Poison does a tiny amount to allow firing on empty buildings
  Armor = MELEE             0%
  Armor = LASER             0%    ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP    0%      ;Not harmed by cleaning weapons
  Armor = INFANTRY_MISSILE  50%
  Armor = PARTICLE_BEAM     25%  ;orbital beams should be devastating to buildings, but buildings have a lot of hitpoints so extra damage is good...
  Armor = KILL_PILOT        0%      ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER         0%    ;Capture type weapons are effective only against infantry.
  Armor = AURORA_BOMB       250%
  Armor = LAND_MINE         0%    ;buildings take no damage from mines
  Armor = FLAME             50% 
  Armor = EXPLOSION         80%  ;makes these buildings more resistant to nuclear attacks, among other things
  Armor = SUBDUAL_MISSILE   0%
  Armor = SUBDUAL_VEHICLE   0%
  Armor = SUBDUAL_BUILDING  100%
End    

Armor GLAUpgradedStructureArmor
  Armor = DEFAULT           75%    ; this sets the level for all nonspecified damage types
  Armor = Surrender         0%    ; buildings are immune to normal damage from STUN weapons.
  Armor = SMALL_ARMS        40%
  Armor = GATTLING          7%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN   40%
  Armor = RADIATION         0%      ;Radiation does no damage to buildings.
  Armor = MICROWAVE         0%
  Armor = SNIPER            0%
  Armor = POISON            1%    ; Poison does a tiny amount to allow firing on empty buildings
  Armor = MELEE             0%
  Armor = LASER             0%    ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP    0%      ;Not harmed by cleaning weapons
  Armor = INFANTRY_MISSILE  40%
  Armor = PARTICLE_BEAM     150%  ;orbital beams should be devastating to buildings, but buildings have a lot of hitpoints so extra damage is good...
  Armor = KILL_PILOT        0%      ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER         0%    ;Capture type weapons are effective only against infantry.
  Armor = AURORA_BOMB       150%
  Armor = LAND_MINE         0%    ;buildings take no damage from mines
  Armor = FLAME             40% 
  Armor = SUBDUAL_MISSILE   0%
  Armor = SUBDUAL_VEHICLE   0%
  Armor = SUBDUAL_BUILDING  75%
End

Armor GLAUpgradedStructureArmorTough
  Armor = DEFAULT           75%    ; this sets the level for all nonspecified damage types
  Armor = Surrender         0%    ; buildings are immune to normal damage from STUN weapons.
  Armor = SMALL_ARMS        40%
  Armor = GATTLING          7%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN   40%
  Armor = RADIATION         0%      ;Radiation does no damage to buildings.
  Armor = MICROWAVE         0%
  Armor = SNIPER            0%
  Armor = POISON            1%    ; Poison does a tiny amount to allow firing on empty buildings
  Armor = MELEE             0%
  Armor = LASER             0%    ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP    0%      ;Not harmed by cleaning weapons
  Armor = INFANTRY_MISSILE  40%
  Armor = PARTICLE_BEAM     18%  ;orbital beams should be devastating to buildings, but buildings have a lot of hitpoints so extra damage is good...
  Armor = KILL_PILOT        0%      ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER         0%    ;Capture type weapons are effective only against infantry.
  Armor = AURORA_BOMB       150%
  Armor = LAND_MINE         0%    ;buildings take no damage from mines
  Armor = FLAME             40% 
  Armor = EXPLOSION         60%  ;makes these buildings more resistant to nuclear attacks, among other things
  Armor = SUBDUAL_MISSILE   0%
  Armor = SUBDUAL_VEHICLE   0%
  Armor = SUBDUAL_BUILDING  75%
End

Armor BaseDefenseArmor            ;used for anti-air base defenses.  Vulnerable to steatlh-fighter strikes. 
  Armor = DEFAULT             100%    ; this sets the level for all nonspecified damage types
  Armor = Surrender           0%    ; buildings are immune to normal damage from STUN weapons.
  Armor = SMALL_ARMS          50%
  Armor = GATTLING            25%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN     50%
  Armor = RADIATION           0%      ;Radiation does no damage to buildings.
  Armor = MICROWAVE           0%
  Armor = SNIPER              0%
  Armor = POISON              1%
  Armor = MELEE               0%
  Armor = LASER               0%    ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP      0%      ;Not harmed by cleaning weapons
  Armor = INFANTRY_MISSILE    25%
  Armor = PARTICLE_BEAM       200%  ;orbital beams should be devastating to buildings, but buildings have a lot of hitpoints so extra damage is good...
  Armor = KILL_PILOT          0%      ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER           0%    ;Capture type weapons are effective only against infantry.
  Armor = AURORA_BOMB         200%  ;Aurora can't vape a single base defense in one hit.
  Armor = STEALTHJET_MISSILES 250%  ;Watch out for those stealthjets
  Armor = JET_MISSILES        25%   ;Raptors, MIGs and Comanche's not so effective.  
  Armor = LAND_MINE           0%    ;buildings take no damage from mines
  Armor = FLAME               50% 
  Armor = SUBDUAL_MISSILE   0%
  Armor = SUBDUAL_VEHICLE   0%
  Armor = SUBDUAL_BUILDING  100%
End

Armor StingerSiteArmor  ;used for anti-air base defenses.  Vulnerable to steatlh-fighter strikes. 
  Armor = DEFAULT             100%   ; this sets the level for all nonspecified damage types
  Armor = SMALL_ARMS           50%
  Armor = GATTLING             30%   ;resistant to gattling tank
  Armor = COMANCHE_VULCAN      50%
  Armor = RADIATION             0%   ;Radiation does no damage to buildings.
  Armor = MICROWAVE             1%
  Armor = SNIPER              100%   ;***This is required for snipers to be able to attack and kill stinger soldiers! Must be > 0! (Value irrelevant since the soldiers will use their % to modify the damage)
  Armor = POISON              100%   ; Similarly, this lets the toxin tractor attack to kill the soldiers
  Armor = SURRENDER             0%   ;And this is for Flashbangs
  Armor = MELEE                 0%
  Armor = LASER                 0%   ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP        0%   ;Not harmed by cleaning weapons
  Armor = INFANTRY_MISSILE     25%
  Armor = PARTICLE_BEAM       200%   ;orbital beams should be devastating to buildings, but buildings have a lot of hitpoints so extra damage is good...
  Armor = KILL_PILOT            0%      ;Jarmen Kell uses against vehicles only.
  Armor = AURORA_BOMB         200%   ;Aurora can't vape a single base defense in one hit.
  Armor = STEALTHJET_MISSILES 250%   ;Watch out for those stealthjets
  Armor = JET_MISSILES         40%   ;Raptors, MIGs and Comanche's not so effective.  
  Armor = LAND_MINE             0%   ;buildings take no damage from mines
  Armor = FLAME                50% 
  Armor = SUBDUAL_MISSILE       0%
  Armor = SUBDUAL_VEHICLE       0%
  Armor = SUBDUAL_BUILDING    100%
End

Armor WallArmor
  Armor = DEFAULT           100%    ; this sets the level for all nonspecified damage types
  Armor = SURRENDER         0%      ; buildings are immune to normal damage from STUN weapons.
  Armor = SMALL_ARMS        6%
  Armor = GATTLING          6%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN   6%
  Armor = FLAME             0%  
  Armor = SNIPER            0%
  Armor = POISON            0%
  Armor = MICROWAVE         0%
  Armor = MELEE             0%
  Armor = LASER             0%    ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP    0%      ;Not harmed by cleaning weapons
  Armor = INFANTRY_MISSILE  25%
  Armor = PARTICLE_BEAM     100%    
  Armor = KILL_PILOT        0%      ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER         0%    ;Capture type weapons are effective only against infantry.
  Armor = AURORA_BOMB       300%
  Armor = SUBDUAL_MISSILE   0%
  Armor = SUBDUAL_VEHICLE   0%
  Armor = SUBDUAL_BUILDING  0%
End
