
;------------------------------------------------------------------------------
; ProjectileArmor (gen/zh)
; ProjectileArmor (ra3)
; Formerly [ProjectileArmor]. 
; Missiles are armored from basic damage. 
Armor ArmorProjectile
[ArmorProjectile]
<ArmorTemplate
id				= "ProjectileArmor"
;----- Default -----
Armor				= DEFAULT				25%			; This sets the level for all nonspecified damage types. 
Default				= "0"
				/>
;----- Impact -----
Armor				= FALLING				0%			; Projectiles are immune to falling damage. 
;----- Gun -----
Armor				= SMALL_ARMS				25%			; Gives Quad and gattling a little more punch. 
Armor				= GATTLING				25%			; resistant to gattling tank
;----- Chemical -----
Armor				= POISON				0%			; Poison no longer affects projectiles
;----- Fire -----
Armor				= FLAME					0%			; Radiation no longer affects projectiles (Caused napalm triggering issue)
;----- Energy -----
Armor				= LASER					100%			; Lasers are anti-personel and anti-projectile only (for point defense laser)
Armor				= MICROWAVE				0%
Armor				= RADIATION				0%			; Radiation no longer affects projectiles
  Armor = HAZARD_CLEANUP  0%      ;Not harmed by cleaning weapons
;----- Kill Pilot -----
Armor				= KILL_PILOT				0%			; Jarmen Kell uses against vehicles only.
;----- Subdual -----
Armor				= SUBDUAL				0% 			; SURRENDER ; Capture type weapons are effective only against infantry.
Armor				= SUBDUAL_MISSILE			100%
Armor				= SUBDUAL_VEHICLE			0%
Armor				= SUBDUAL_BUILDING			0%
End

;------------------------------------------------------------------------------
;*Be careful with this type, use in conjunction with KindOf = BALLISTIC_MISSILE to restrict targeting
;*to select weapons, because ballistic missile armor is weak! Weapons capable of targeting must have
;*AntiBallisticMissile = Yes set in the Weapon.ini.
; BallisticMissileArmor (gen/zh)
[
;----- Default -----
Armor				= DEFAULT				80%
Armor				= FALLING				0%      ;projectiles are immune to falling damage
Armor = HAZARD_CLEANUP  0%      ;Not harmed by cleaning weapons
Armor = KILL_PILOT      0%      ;Jarmen Kell uses against vehicles only.
  Armor = MICROWAVE         0%
  Armor = SURRENDER       0%      ;Capture type weapons are effective only against infantry.
  Armor = SUBDUAL_MISSILE   100%
  Armor = SUBDUAL_VEHICLE   0%
  Armor = SUBDUAL_BUILDING  0%
End
