
[plate]
Armor				= SNIPER		100%
<Armor
	Damage			= "SNIPER"
	Percent			=			"100%"
	/>
Armor				= TESLA			1000%



; SovietHeavyAntiVehicleInfantryArmor
[plate2]
Armor				= MELEE			100%
Armor				= SMALL_ARMS		150%
Armor				= AUTOCANNON		150%
Armor				= CANNON		10%
Armor				= ROCKET		10%
Armor				= FLAK			10%
Armor				= EXPLOSIVE		100%
Armor				= TESLA			50%			; Rubber shoes in motion! 
Armor				= LASER2		30%			; aka PRISM (ra3)
Armor				= RADIATION		100%

; SovietDesolatorInfantryArmor 
; Cyborg -- Full Conversion
; Formerly [ArmorCyborg]. 
; For the "regular" (part conversion) cyborgs, look up SkinCyborg. 
[plate2b]:[plate]
Armor				= FLAME			5%
Armor				= COLD			5%
Armor				= POISON		0%			; Also handled by "ImmuneToPoison". 
Armor				= RADIATION		0%			; Also handled by "ImmuneToRadiation". 
Armor				= SUBDUAL		0%			; subdual non-EMP (stun)
; Armor				= EMP			100%			; Address this by "ImmuneToEMP = no" on the unit itself. (Implicit in "Cyborg = yes"). 

20% Cannon, 20% Rocket, 150% Gun, 100% Melee, 100% Auto Cannon, 100% Explosive, 20% Flak, 100% Prism, 1000% Tesla
