;******************************************************************************
;*** Trike ********************************************************************
;******************************************************************************
; Speeder

;------------------------------------------------------------------------------
[VehicleTypes]
+				= Trike
+				= Trike_2
+				= Trike_3

;------------------------------------------------------------------------------
; half-way between the Bike and Trike, a bike with sidecar
[Cycl]:[Bike]

;------------------------------------------------------------------------------
; Trike
[Trike]:[Bike]
;----- Text -----
Name				= Speeder Trike
UIName				= name:trike
UIDescription			= desc:trike
;----- Taxonomy -----
Category			= Recon					; AFV
;----- Body -----
Strength			= 150
Size				= 2
;----- Turrets -----
Turret				= no
;----- Weapons -----
Primary				= TrikeGuns				; M60
Secondary			= TrikeGuns
Weapon1				= TrikeGuns
Weapon2				= TrikeGuns
EliteWeapon2			= TrikeMissileLauncher
Weapon3				= DropTrapBlast

Elite				= TrikeMissileLauncher
ElitePrimary			= TrikeMissileLauncher
; EliteSecondary		= TrikeMissileLauncher			; IvanBomber

;----- Armor -----
; "Boostable" means it can be affected by the "Nitro Boost" ability from the Workshop. 
Armor				= light, boostable			; light
;----- Availability -----
Side				= Forgotten
Owner				= Forgotten, Africans, Arabs, Iranians
DoubleOwned			= yes
; House				= 
; RequiredHouses		= 
; ForbiddenHouses		= 
; SecretHouses			= 
TechLevel			= 2
Prerequisite			= Factory
AllowedToStartInMultiplayer	= yes
CrateGoodie			= yes
CrateGift			= yes
;----- Movement -----
Speed				= 10

[Trike_2]
UIName				= Name:TRIKE
Name				= Trike
Prerequisite=YAWEAP
Strength=230
Armor=light
IsTilter=yes
Crusher=yes
TooBigToFitUnderBridge=true
TechLevel=4
Sight=7
Speed=10
MinDebris=1
CrateGoodie=yes
Owner				= Nod,Africans,Arabs;YuriCountry,UriArmy,Headquaters,Scorpion
AllowedToStartInMultiplayer	= yes
Cost=550
Soylent=275
BuildTimeMultiplier=1.1
Points=20
ROT=5
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=TrikeSelect
VoiceMove=TrikeMove
VoiceAttack=TrikeAttackCommand
VoiceFeedback=
CreateSound=TrikeCreate
DieSound=GenVehicleDie
CrushSound=TankCrush
MoveSound=TrikeMoveStart
MaxDebris=2
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=15
PixelSelectionBracketDelta=2
DamageParticleSystems=SparkSys,SmallGreySSys
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
ImmuneToVeins=yes
Size=3
ElitePrimary=TrikeGunE
EliteSecondary=TrikeMissile
OpenTopped=yes
Passengers=1
SizeLimit=1
EnterTransportSound=EnterTransport
LeaveTransportSound=ExitTransport
PipScale=Passengers
DamageSound=VehicleDamagedHeavy
Crewed=yes
