;******************************************************************************
;*** Armory *******************************************************************
;******************************************************************************
; Neutral placements use the Allied version. 

;------------------------------------------------------------------------------
[BuildingTypes]
+				= Armory
+				= Arsenal

;------------------------------------------------------------------------------
; Armory
[Armory]:[Depot]
;----- Text -----
Name				= Armory
UIName				= name:armory
UIDescription			= desc:armory
;----- Taxonomy -----
; Armory			= yes
;----- Gfx -----
; Image				= GAARMORY					; This fix is needed when changing the identifier. 
;----- Body -----
Strength			= 2000
;----- Weapons -----
SuperWeapons			= InvokeTechWpnInf2, InvokeTechWpnInf3, InvokeTechWpnInf4, InvokeTechAmrInf2, InvokeTechAmrInf3, InvokeTechAmrInf4
;----- Armor -----
Armor				= concrete
Capturable			= yes
Spyable				= yes
;----- Availability -----
Side				= Terran
Owner				= Allies, Soviet, Alliance
DoubleOwned			= yes
; House				= 
TechLevel			= 6
Prerequisite			= DEPOT, FACTORY				; RADAR
Cost				= 1500
Adjacent			= 2
;----- Score -----
Points				= 85
;----- Perception -----
Sight				= 6
;----- Load -----
Crewed				= yes
;----- Power -----
Power				= -200
TogglePower			= no
;----- Sfx -----
VoiceSelect			= SelectArmory
CaptureEvaEvent			= EVA_ArmoryCaptured				; Eva (and therefore 3way split) voice to use when captured
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys,SmallGreySSys,BigGreySmokeSys
DamageSmokeOffset		= 1500, 1055, 815
Explodes			= yes
Explosion			= TWLT070, S_BANG48, S_BRNL58, S_CLSN58, S_TUMU60
MaxDebris			= 5
;----- UI -----
BuildCat			= Tech
; PipScale			= Ammo
;----- AI -----
AIBuildThis			= yes
ThreatPosed			= 0


; Armory
[CAARMR]
Prerequisite=TECH,CNST
Strength=500
PipWrap=10
InitialAmmo=20
Ammo=20
Reload=100
Adjacent=3
TechLevel=9
Sight=5
Cost=2000 
Points=30
Power=-50
MaxDebris=15
MinDebris=5
DebrisAnims=DBRIS1LG,DBRIS1SM,DBRIS4LG,DBRIS4SM,DBRIS5LG,DBRIS5SM
ThreatPosed=10
DamageParticleSystems=SparkSys,SmallGreySSys,BigGreySmokeSys
DamageSmokeOffset=10,10,10
BaseNormal=yes
NeedsEngineer=yes
Unsellable=yes
WorkingSound=BarracksLoop
LeaveRubble=yes
RadarVisible=yes;gs put on radar even if insignificant and unowned (insignificant and owned is a UC building)

;------------------------------------------------------------------------------
; Armory 2
[Arsenal]:[Armory]
;----- Text -----
Name				= Arsenal
UIName				= name:arsenal
UIDescription			= desc:arsenal
;----- Weapons -----
SuperWeapons			= InvokeTechWpnVeh2,InvokeTechWpnVeh3,InvokeTechWpnVeh4,InvokeTechAmrVeh2,InvokeTechAmrVeh3,InvokeTechAmrVeh4
;----- Availability -----
Prerequisite			= Armory
Cost				= 1500
Adjacent			= 2
