;
;
;
; Armor I: 	+ 5 	(= (HP = 125)) (
; Armor II: 	+ 5 	(= (HP = 130)) (SHK)
; Armor III:	+ 20	(= (HP = 150)) (E2)

;------------------------------------------------------------------------------
[InfantryTypes]
+				= 
+				= 
+				= 

;------------------------------------------------------------------------------
[GIGrenadier]
;----- Text -----


;------------------------------------------------------------------------------
; Disc Thrower [E2] (ts)
; Armor III
[GIGrenadier2]:[GI]
;----- Text -----
Name				= Disc Grenadier
;----- Body -----
Strength			= 150
Primary=Grenade
Prerequisite=GAPILE
CrushSound=SQUISH6
Armor=none
TechLevel=2
Pip=green
Sight=7
Speed=4
Owner=GDI
Cost=200
Points=5
VoiceSelect=15-I000,15-I004,15-I012,15-I048
VoiceMove=15-I018,15-I024,15-I044
VoiceAttack=15-I044,15-I050,15-I044,15-I046
VoiceFeedback=15-I058,15-I064
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=InfantryDestroyer
ThreatPosed=15	; This value MUST be 0 for all building addons
EliteAbilities=SCATTER
ImmuneToVeins=yes
;----- Veterancy -----
; Elite				= ClusterGrenade

;------------------------------------------------------------------------------
; This unit appears in Covert Ops II _and_ another, unnamed rules.INI file, 
; which has a large overlap with Covert Ops II. This file includes "dim memory" units, 
; like the Grendel, Prometheus and Dragonfly. 
; I was long uncertayne whether it is indeed identical to Covert Ops II, due to the overlap, 
; and I had just overlooked that those "dim memory" units were in Covert Ops II. 
; However, I now find that the Prerequisite entry differs between Covert Ops II and this other file, 
; proving "inspiration"/ripping. 
; [CLGREN] (Covert Ops II, That Other File)
[GIGrenadier2]
;----- Text -----
Name				= Cluster Grenadier
;----- Gfx -----
Image				= E2
;----- Weapons -----
Primary				= ClusterGrenade
;----- Availability -----
Prerequisite			= UNBarracks			; GAPILE (Covert Ops II), GAWEAP (That Other File)

;------------------------------------------------------------------------------
; 's FCAIRCAV4 (ARRF AirCav4 M79)
[GIGrenadier]
Image=SEAL
Category=Soldier
Primary=M79             ;Vulcan3              
Secondary=Pistola
Prerequisite=FCORBK                                         ;The new sides Barraks.
CrushSound=SQUISH6
Strength=250
Armor=light
TechLevel=1
Pip=green
Sight=10
Speed=7
Owner=FCOR
AllowedToStartInMultiplayer=no                           ;Only allow one infantry unit 
Cost=300                                                  ;to start in Multiplayer. This is to insure
Points=5                                                  ;your new side will be givin at least one of its
VoiceSelect=15-I000,15-I004,15-I012,15-I048               ;own MCV.
VoiceMove=15-I018,15-I024,15-I044
VoiceAttack=15-I044,15-I050,15-I044,15-I046
VoiceFeedback=15-I058,15-I064
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=InfantryDestroyer
ThreatPosed=15	; This value MUST be 0 for all building addons
EliteAbilities=SCATTER
TiberiumProof=yes
TiberiumHeal=yes
ImmuneToVeins=yes

OccupyWeapon			= GrenadeLauncher_18222
EliteOccupyWeapon		= GrenadeLauncher_1D7B7

;------------------------------------------------------------------------------
; Heavy Grenadier - VERY COOL - original name (before introduced) was "Cluster grenadier"
; [betty] (techwar 1.7)
[Grenadier3]:[Grenadier2]
;----- Text -----
Name				= ; Heavy Grenadier
;----- Gfx -----
Image				= E2
;----- Body -----
Strength			= 300
;----- Weapons -----
Primary				= Betty1
;----- Availability -----
Prerequisite			= GAPILE, GADEPT, GATECH
Cost				= 1700
CrushSound=SQUISH6
TechLevel=6
Pip=green
;----- Veterancy -----
EliteAbilities			= faster, stronger, firepower, scatter, ROF, sight, self_heal
