;******************************************************************************
;*** Tank Mk. IV **************************************************************
;******************************************************************************
; Tank base type. This derives from the "battlewagon", and leads to tank, light. 

;------------------------------------------------------------------------------
+				= TnkRhmb
+				= TnkRhmb2


Category=AFV

;------------------------------------------------------------------------------
; Rhombos Tank
; _The_ Tank
; Formerly [TANK] (Mark V). [RhombosTank], [TnkRhomb]. 
; Rhombos Tank
[TnkRhmb]
;----- Text -----
Name					= Tank Rhombe
UIName					= name:tnk_rhomb
UIDescription				= desc:tnk_rhomb
;----- Body -----
Strength				= 300
;----- Turret -----
; Turret				= yes
;----- Weapons -----
Primary					= Cannon57mm_HE
Secondary				= MaximGun
Elite					= Cannon57mm_HEv3
ElitePrimary				= Cannon57mm_HEv3
;----- Armor -----
Armor					= heavy
;----- Load -----
Crewed					= yes
InitialPayload.Types			= RhombosTankMGDummy, RhombosTankFlamerDummy


IsTilter=yes
TooBigToFitUnderBridge=true
TechLevel=2
Sight=5
Speed=8
CrateGoodie=no
Crusher=yes
Cost=800
Soylent=700
Points=25
ROT=5
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=GenSovVehicleSelect
VoiceMove=GenSovVehicleMove
VoiceAttack=GenSovVehicleAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=RhinoTankMoveStart
CrushSound=TankCrush
Maxdebris=3
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Destroyer
ThreatPosed=40	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=100, 100, 275
Weight=3.5
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
ZFudgeColumn=8
ZFudgeTunnel=13
Size=3
OpportunityFire=yes
BuildTimeMultiplier=1.5;Individual control of build time
;----- AttachEffect -----
ShieldType				= ThreshholdFlammable,ThreshholdEMP
Flammable				= yes
Behavior				= FlammableUpdate ModuleTag_21
	AflameDuration			= 5000         ; If I catch fire, I'll burn for this long...
	AflameDamageAmount		= 3       ; taking this much damage...
	AflameDamageDelay		= 500       ; this often.
End

;------------------------------------------------------------------------------
; Rhombos (Turreted) 
[TnkRhmbTur]:[TnkRhmb]
;----- Text -----
Name					= Tank Rhombos (Turret)
;----- Turrets -----
Turret					= yes

;------------------------------------------------------------------------------
; Rhombos Scorpion
; Gains a back-mounted ballistic rocket. 
[TnkRhmb_Scorp]

;------------------------------------------------------------------------------
[TnkRhmb_Treb]

;------------------------------------------------------------------------------
[TnkRhmb_Bombard]
;----- Name -----
UIName				= Name:Tank_Rhombos_Bombard
Name				= Bombard Rhombos Tank

;----- Weapons -----
Primary				= TankBombard_HE
Secondary			= TankBombard_HEFRAG

;------------------------------------------------------------------------------
[RhombosTank_Trebuchet]
