;******************************************************************************
;*** AH-64 Apache *************************************************************
;******************************************************************************
; vg143153jkc

;------------------------------------------------------------------------------
[AircraftTypes]
; 1FAA7454ED95F
+				= Heli_AH-1Cobra			; AH-1
+				= Heli_AH-64Apache
+				= Heli_RAH-66Comanche
+				= Heli_XXXHarpy


;------------------------------------------------------------------------------
; Apache Chopper
; Formerly APACHE and HELI. 

Category			= AirPower
ConsideredAircraft		= yes

TooBigToFitUnderBridge		= true
Landable			= yes

JumpJet				= yes
;Locomotor			= {4A582746-9839-11d1-B709-00A024DDAFD1} ;flying
Locomotor			= {92612C46-F71F-11d1-AC9F-006008055BB5} ;jumpjet
MovementZone			= Fly
SpeedType			= Hover

; params not defined use defaults (old globals way up top)
JumpjetClimb			= 10
JumpjetCrash			= 40 ; Climb, but down
JumpJetAccel			= 12


JumpjetHeight			= 500
JumpjetWobbles			= .01
JumpjetDeviation		= 1

CrashingSound			= GenHelicopterDie
ImpactLandSound			= GenAircraftCrash

AuxSound1			= GenHelicopterTakeOff	; Taking off
AuxSound2			= GenHelicopterLanding	; Landing
MoveSound			= GenHelicopterMoveLoop

MoveToShroud=yes

Bunkerable=no
DeathWeapon=HelicopterCollision

Crashable			= yes
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DamageParticleSystems		= SparkSys,SmallGreySSys
MaxDebris=3

Side				= Allies
Owner				= Allies
; House				= 

;----- Dock -----
Dock				= ALHeliPad,SVHeliPad,ALAerodrome,AMAerodrome,Airfield,EAAirPad

;----- Load -----
Crewed				= yes
Survivor.Side0			= AllPilot
Survivor.Side1			= SovPilot
Survivor.Side2			= AllPilot
Survivor.Side3			= Dummy_
Survivor.Side4			= Terrorist
Survivor.PilotCount		= 1
Survivor.RookiePilotChance	= 25
Survivor.VeteranPilotChance	= 50
Survivor.ElitePilotChance	= 80

;Reload=160
ManualReload=yes
HoverAttack=yes
;BalloonHover=yes

Buildable			= yes
Prerequisite			= UNHeliPad

GuardRange			= 30
;----- UI -----
Cursor.Deploy			= Land
Cursor.NoDeploy			= NoLand

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Killer Egg
; This derives from Gyrocopter. 
; Formerly AH-64 Apache Attack Helicopter [Heli_AH-64Apache]. 
[Heli_
$inherits			= GYRO
;----- Text -----
Name				= AH-64 Apache
UIName				= name:heli_apache
UIDescription			= desc:heli_apache
;----- Visual -----
; Image				= APA64J
Image				= 
Voxel				= yes
Remapable			= yes
Cameo				= icon_apache
AltCameo			= icon_apache_2
;----- Body -----
Strength			= 125				; TD, Strength_RA = 225
Weight				= 
Size				= 
;----- Availability -----
Cost				= 1200
TechLevel			= 6
BuildLevel			= 10
AllowedToStartInMultiplayer	= no
CrateGoodie			= yes
;----- Weapons -----
Primary				= Vulcan
Secondary			= HellfireLauncher
Burst				= 2
;----- Armor -----
Armor				= ArmorAircraft2				; Was "light", unsupported by TD and RA. 
;----- Load -----
Ammo				= 15						; TD
;----- Movement -----
ROT				= 4
Speed				= 20						; Speed_td = 40
; MoveToShroud			= no
PitchSpeed			= .16
;----- Score -----
Points				= 20
;----- AI -----
ThreatPosed			= 15

;******************************************************************************
;*** UH-1 Iroquois ************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Longbow attack helicopter [HELI] (RA)
; Formerly [Heli_AH64Apache_2]. 
[Heli_UH-1Iroquois]
; $inherits			= Heli_AH64Apache
;----- Text -----
Name				= UH-1 Iroquois 
;----- Availability -----
Prerequisite			= hpad
TechLevel			= 9
;----- Body -----
Srength				= 225
;----- Weapons -----
Primary				= HeliRocket
Secondary			= MGun457
Elite				= 
ElitePrimary			= HeliRocket2
EliteSecondary			= MGun568
;----- Movement -----
Speed				= 16
;----- Score -----
Points				= 50
;----- Load -----
Ammo				= 6



;Harpy Vulcan Cannon
[HarpyClaw]
Damage=60
ROF=36
Range=5
Projectile=Invisible2
Speed=100
Warhead=SA
Report=BlackHawkAttack
OmniFire=yes

; air-to-surface homing missile (launched from helicopter)
[CobraRockets]
Damage				= 40
ROF				= 60
Range				= 4
Projectile			= CobraRocketP
Speed=30
;Warhead=ORCAAP
Warhead=TIGRAPE
;Report=ORCAMIS1
Report				= SeawolfAttack
Burst=2
OmniFire=yes

Projectile=HeatSeeker
Speed=30
Warhead=AP
Report=MISSILE6


[CobraRocketP]
Image=DRAGON
Arcing=true
High=yes
SubjectToWalls=no
SubjectToCliffs=no
SubjectToElevation=yes

; aircraft and ground heatseeker
[CobraRocketPzzz]
Arm=2
Shadow=no
;Proximity=yes
Proximity=no
Ranged=yes
AA=yes
AG=yes
Image=MISLORCA
ROT=60
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
CourseLockDuration=10

;******************************************************************************
;*** AH-1 Cobra ***************************************************************
;******************************************************************************
; Use this for vassals/allies. 

;------------------------------------------------------------------------------
; Cobra Chopper
; This was more or less a proof-of-concept unit for a TS mod. 
; It is probably unused. 
; Formerly [AH-1]. 
[Heli_AH-1Cobra]
$inherits			= Heli_UH-1Iroquois
;----- Text -----
Name				= AH-1 Cobra
UIName				= name:cobra
UIDescription			= desc:cobra
;----- Weapons -----
Primary				= HarpyClaw
Secondary			= CobraRockets
; ElitePrimary			= HarpyClawE
; EliteSecondary		= CobraRocketsE
Armor=light
TechLevel=4
Sight=2
RadarInvisible=yes
Landable=yes
MoveToShroud=yes
Dock=GAAIRC,NAHPAD,GAHPAD
Speed=14
PitchSpeed=.16
Cost=1000
Points=20
ROT=5
Ammo=12
Maxdebris=2
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
DefaultToGuardArea=yes

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Apache - Balance for ORCA Fighter
; Formerly [HELI]. 
[Heli_AH-64Apache]
;----- Text -----
Name				= Apache
UIName				= name:
UIDescription			= desc:
;----- Visual -----
; Image				= heli
;----- Weapons -----
Primary				= Hellfire
Secondary			= HarpyClaw

TechLevel=5
Sight=2
RadarInvisible=no
Landable=yes
MoveToShroud=no
Dock=GAHPAD,NAHPAD
PipScale=Ammo
Speed=20
PitchSpeed=.16
Owner=Americans
Cost=1000
Points=20
ROT=5
Ammo=5
Crewed=yes
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=4
VoiceSelect=30-I000,30-I002,30-I004,30-I006
VoiceMove=30-I014,30-I016,30-I018,30-I022
VoiceAttack=30-I022,30-I030,30-I034,30-I036
ThreatPosed=20	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
AuxSound1=ORCAUP1	;Taking off
AuxSound2=ORCADWN1	;Landing
;----- Veterancy -----
EliteAbilities=FASTER,STRONGER,FIREPOWER,SCATTER,ROF,SIGHT,SELF_HEAL
;VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
;EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF

;------------------------------------------------------------------------------
; Chrono Chopper
; OverWatch Comanche
; Formerly [CCHP] (Chrono Chopper). 
; Even before that, it was conceived as the "Chem Chopper" (which, I guess, is the Wasp). 
[ComancheCR]:[Comanche]
;----- Text -----
Name				= Chrono Chopper
UIName				= name:
UIDescription			= desc:
Image=APACHE
Prerequisite=NAHPAD
;----- Weapons -----
Primary				= ComancheTimegun
Secondary			= TenetClaw			; PoisonClaw
Strength=225
Category=AirPower
Armor=light
TechLevel=5
Sight=2
RadarInvisible=yes
Landable=yes
MoveToShroud=no
Dock=NAHPAD,GAHPAD
PipScale=Ammo
Speed=14
PitchSpeed=.16
Owner=Nod
Cost=1000
Points=20
ROT=5
Ammo=12
Crewed=yes
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=3
VoiceSelect=30-I000,30-I002,30-I004,30-I006
VoiceMove=30-I014,30-I016,30-I018,30-I022
VoiceAttack=30-I022,30-I030,30-I034,30-I036
;Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys

; Formerly [APClaw] (ChronoClaw stymphalid armour-busting shot)
[TenetClaw]
;----- Payload -----
Damage				= 60
ROF=36
Range=5
Projectile=Invisible2
Speed=100
Warhead=AP
Report=GUN18

;------------------------------------------------------------------------------
; TechWar v.1.7's LongBow Helicopter [longbow]
[Heli_AH-64_2]
$include				= Heli_AH-64
;----- Text -----
Name					= AH-64 Apache Hero
UIName					= name:gnrl_granger
UIDescription				= desc:gnrl_granger
;----- Body -----
Strength				= 600
;----- Weapons -----
Primary					= superhellfire
;----- Availability -----
RequiredHouses				= Airforce
Prerequisite				= GAHPAD

TechLevel=5
Sight=2
MoveToShroud=no
Dock=GAHPAD,NAHPAD
PipScale=Ammo
Speed=20
PitchSpeed=.16
Owner=GDI
Cost=3000
Points=20
ROT=6
Ammo=20
Crewed=yes
GuardRange=30
MaxDebris=20
VoiceSelect=30-I000,30-I002,30-I004,30-I006
VoiceMove=30-I014,30-I016,30-I018,30-I022
VoiceAttack=30-I022,30-I030,30-I034,30-I036
ThreatPosed=20

;TechLevel=6
;Sight=2
;RadarInvisible=yes
;Landable=yes
;MoveToShroud=yes
;Dock=GAAIRC,NAHPAD,GAHPAD
;PipScale=Ammo
;Speed=14
;PitchSpeed=.16
;Cost=1000
;Points=20
;ROT=5
;Ammo=12
;Maxdebris=2
;ThreatPosed=15	; This value MUST be 0 for all building addons

;******************************************************************************
;*** RAH-66 Comanche **********************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; Replaces Apache for Airforce General. 
; Subsumes SPEC (Spectre AT). 
; Formerly ComancheHeli. 
[Heli_RAH-66Comanche]
$inherits			= Heli_AH-64Apache
;----- Text -----
Name				= RAH-66 Comanche
UIName				= name:COMANCHE 
UIDescription			= desc:comanche
;----- Gfx -----
Image				= COMANCHE			; APACHE
;----- Body -----
Strength			= 220
;----- Weapons -----
Primary				= Chaingun; AngelfireCannon  
Secondary			= HellfirePod; SpectreMissile; ComancheLaser 
ElitePrimary			= ; AngelfireCannonE
EliteSecondary			= ComancheLaserE 
;----- Availability -----
RequiredHouses			= BlackOpsGeneral
; Prerequisite			= RADAR,UFO 
; RequiresStolenAlliedTech	= yes
Armor=medium 
TechLevel=8 
Sight=7 
Speed=14;22;17 
RadarInvisible=yes 
RadarVisible=no 
PitchSpeed=1.5 
JumpjetSpeed=35 
JumpjetClimb=25 
JumpjetCrash=40 
JumpJetAccel=17 
JumpJetTurnRate=10 
JumpjetHeight=800 
JumpjetWobbles=.01 
JumpjetDeviation=1 
Owner=Americans,Alliance,French 
Cost=1000;1540 
Soylent=725 
Points=20 
ROT=6 
Crewed=no 
ConsideredAircraft=yes 
IsSelectableCombatant=yes 
MoveToShroud=yes 
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60 
;MaxDebris=3 
VoiceSelect=SeigeChopperSelect 
VoiceMove=SeigeChopperMove 
VoiceAttack=SeigeChopperAttackAir 
VoiceCrashing=SeigeChopperVoiceDie 
CrashingSound=SeigeChopperDie 
DieSound= 
MoveSound=SeigeChopperMoveLoop 
ImpactLandSound=GenAircraftCrash 
Locomotor={92612C46-F71F-11d1-AC9F-006008055BB5} 
MovementZone=Fly 
DamageParticleSystems=SparkSys,SmallGreySSys 
ThreatPosed=55 
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER 
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF 
HoverAttack=yes 
OmniFire=yes	; gets ignored 
;Turret=yes 
OpportunityFire=yes	; this ensures he will attack air while on the run 
AllowedToStartInMultiplayer=no 
Crashable=yes 
SpeedType=Hover 
PreventAttackMove=yes 
TooBigToFitUnderBridge=true 
Bunkerable=no 
OpportunityFire=yes 
Size=15 
DeathWeapon=BlimpBomb 
DeathWeaponDamageModifier=.1 


Armor=light
TechLevel=5
Sight=2
RadarInvisible=yes
Landable=yes
MoveToShroud=no
Dock=NAHPAD,GAHPAD
;PipScale=Ammo
Speed=16
PitchSpeed=.16
Cost=1500
Points=20
ROT=5
Ammo=999999999999999999999999999999999999999999999999 ;makes it head back home after attack mission completed, but will never really run out of ammo
Crewed=yes
GuardRange=30
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=3
VoiceSelect=30-I000,30-I002,30-I004,30-I006
VoiceMove=30-I014,30-I016,30-I018,30-I022
VoiceAttack=30-I022,30-I030,30-I034,30-I036
Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys

;------------------------------------------------------------------------------
; Laser Comanche
; Replaces Apache for Laser General with Airforce General tech. 
; Replaces Comanche for Airforce General with Laser General tech. 
[HeliComanche_l]
;----- Text -----
Name				= Heli Comanche Laser

;------------------------------------------------------------------------------
; Stealth Comanche
; Black Ops
; Formerly HeliComancheSpectre
[HeliComanche_s]
;----- Text -----
UIName				= Name:heli_comanche_s			; "Comanche Ghostdancer"
Name				= Heli Comanche Stealth

;------------------------------------------------------------------------------
; Stealth Laser Comanche
; Black Ops
[HeliComanche_sl]:[HeliComanche_s]
;----- Text -----
UIName				= Name:heli_comanche_sl			; "Comanche Spectraldancer"
Name				= Heli Comanche Spectre Laser
;----- Weapons -----




;******************************************************************************
;*** Heli Harpy ***************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; Formerly HarpyAerodyne. 
[HeliHarpy]
$inherits			= Apache
;----- Text -----
UIName				= Name:HarpyAerodyne
Name				= Harpy Helicopter
;----- Body -----
Strength			= 225
;----- Availability -----
Prerequisite			= NAHPAD
;----- Weapons -----
Primary				= HarpyClaw
;----- Armor -----
Armor				= light
;----- Stealth -----
RadarInvisible			= yes
TechLevel=5
Sight=2
Landable=yes
MoveToShroud=no
Dock=NAHPAD,GAHPAD
PipScale=Ammo
Speed=14
PitchSpeed=.16
Owner=Nod
Cost=800
Points=20
ROT=5
Ammo=12
GuardRange=30
ThreatPosed=15

[FWFLBN]
Name=Flame Harpy
Primary=FireballLauncher
Cost=1200


; Crashed Harpy
; TS' CACRSH05
[HarpyCrash]:[GenericCrash]
UIName=Name:Harpy_Crashed
Name=Crashed Harpy


