;
;
;
; Subsumes Emperor's Rage, Frenzy. 
; Subsumes 
; Lv. 1: 		Grants +10% Speed, ROF, resistance to Suppression, for 10 sec. 
; Lv. 2: 		Grants +20% Speed, ROF, resistance to Suppression, for 20 sec. 
; Lv. 3: 		Grants +30% Speed, ROF, resistance to Suppression, for 30 sec. 
; Lv. 4 (Dare to Die): 	Grants +100% Speed, ROF, resistance to Suppression, for 20 sec. At the end of this timer, the boosted units are destroyed. 
; Lv. 5 (Kamikaze): 	As Lv. 4, but invokes Honorable Discharge at the end of the timer (explosion). 


;------------------------------------------------------------------------------
[WeaponTypes]
+				= 

;------------------------------------------------------------------------------
[SuperWeaponTypes]
+				= MeleeInfROFDummySpecial
+				= BanzaiSpecial





;------------------------------------------------------------------------------
; Amp Up
; Amphetamine and Adrenaline subsumed under this. 
; Airforce Command Superweapon 2
[FrenzySpecial];CombatDrugsSpecial
;----- Text -----
Name				= Frenzy		; Combat Drugs


Range				= 2.5			; Range for SW means AoE radial indicator. 

SW.FireIntoShroud=no
SW.AffectsHouse=team
SW.AITargeting=none

Cursor.Frame=422
Cursor.Count=9
Cursor.MiniFrame=-1
NoCursor.Frame=190
NoCursor.Count=1


;------------------------------------------------------------------------------
; Stormtrooper StimPack
; Reduces HP by 10 in exchange for ROF/Firepower bonus. 
; Formerly [BerzerkKit]. 
[CastFrenzy]
;----- Text -----
Name				= Frenzy
UIName				= name:frenzy		; Name:CombatDrugs
UIDescription			= desc:frenzy
;----- Taxonomy -----
Type				= GenericWarhead
;----- Display -----
SidebarImage			= icon_frenzy
; SidebarPCX			= drugicon.pcx
FlashSidebarTabFrames		= 120
ShowTimer			= no
;----- Audio -----
Report				= CombatDrugs
SW.Sound			= CombatDrugs
EVA.Detected			= none
EVA.Ready			= none
EVA.Activated			= none
EVA.Impatient			= EVA_NotReady
EVA.SelectTarget		= EVA_SelectTarget
;----- Payload -----
Damage				= 0
DamageType			= Organic
Warhead				= Frenzy
SW.Warhead			= Frenzy
SW.Damage			= 0
;----- Sequence -----
ROF				= 
RechargeTime			= 2.5
IsPowered			= false
DisableableFromShell		= no

;------------------------------------------------------------------------------
; Medicus Cyberneticus
[CastFrenzy2]
$inherits			= CastFrenzy


;------------------------------------------------------------------------------
; Melee Infantry ROF Bonus Dummy Special
; Basic Battle Spirit
; Simulates 1/3 ROF bonus for Japanese for any infantry switched to a melee weapon. 
; [MeleeInfROFDummySpecial]
[
;----- Text -----
Name				= Melee Infantry ROF Bonus Dummy Special
;----- Taxonomy -----
Type				= GenericWarhead
;----- Availability -----
SW.RequiredHouses		= Japanese
SW.AlwaysGranted		= yes
RechargeTime			= 0
;----- UI -----
Action				= 
ShowTimer			= no
SW.ShowCameo			= no
DisableableFromShell		= no
;----- Targeting -----
SW.AutoFire=yes
SW.ManualFire=no
SW.AITargeting=NoTarget
;----- Payload -----
SW.AffectsHouse			= owner
SW.AffectsTarget		= infantry			; This isn't really needed, as it is not supposed to affect all infantry, and so the warhead itself already restricts what types are affected. 
SW.Damage			= 0
SW.Warhead			= MeleeInfROFEffection

;------------------------------------------------------------------------------
; Banzai
[BanzaiSpecial]
;----- Text -----
Name				= Banzai Charge
UIName				= name:banzai
UIDescription			= desc:banzai
;----- Taxonomy -----
Type				= GenericWarhead
;----- Payload -----
Action				= CursorBanzai
SW.Warhead			= Banzai
;----- Sfx -----
RechargeVoice			= ReadyBanzai
ChargingVoice			= ChargingBanzai
ImpatientVoice			= 
SuspendVoice			= 
SpecialSound			= BanzaiFading
StartSound			= Banzai
;----- Sequence -----
RechargeTime			= 3
;----- UI -----
SidebarImage			= IconBanzai
ShowTimer			= yes
FlashSidebarTabFrames=120; default is always, put 0 for never, or a number for x
Range=3.4
LineMultiplier=3
