;******************************************************************************
;*** Missile Heat-Seeker ******************************************************
;******************************************************************************
;******************************************************************************
;*** Rocket, ballistic, inaccurate ********************************************
;******************************************************************************
; Rocket ballistic inaccurate
; This is used by the Grad, Hind, Katyusha, Venom Wasp Elite+. 
; A rocket "as simple as it gets" (ID: Rocket) with just an image also existed, but was deleted, as nothing uses it. 
; A non-inaccurate ballistic rocket also "as simple as it gets" (ID: BRocketLow) also existed, but was deleted, as nothing uses it.  
; A doublet non-inaccurate ballistic medium-level rocket (ID: BRocket and RocketProj) and high-altitude rocket (ID: BRocketHigh) also existed, but were deleted. 
; An unspecified header "Rocket.Arc" (Arcing Rocket) also existed, presumably intended to be stipulated into BRocket, or BRocketLow. 

;------------------------------------------------------------------------------
; Ballistic rocket, medium, inaccurate (default)
; Used by Katyusha, primitive rocket for scattering effect
; Formerly Rocket_2AACB6823EF83, BRocket.Prec-1, Rocket.Arc.Sct. 
; Ballistic missile, precision -1
; Formerly RocketHurricane. 
[RketHurricane]
;----- Text -----
Name				= Hurricane Rocket
UIName				= name:rocket_hurricane
UIDescription			= desc:rocket_hurricane
;----- Taxonomy -----
KindOf				= PROJECTILE SMALL_MISSILE
EditorSorting			= SYSTEM
;----- Body -----
Strength			= 10
Size				= 1
Body				= ActiveBody ModuleTag_02
	MaxHealth		= 100.0
	InitialHealth		= 100.0
	SubdualDamageCap	= 200
	SubdualDamageHealRate	= 100000
	SubdualDamageHealAmount	= 50
End
  Geometry = Sphere
  GeometryIsSmall = Yes
  GeometryMajorRadius = 2.0
Behavior			= PhysicsBehavior ModuleTag_06
	Mass			= 1
End

;----- GFX -----
Draw				= W3DModelDraw ModuleTag_01
Image				= MISL					; MISL2 ; MISSILE ; DRAGON ; RA_V2 ; MISL
Model				= EXStinger01
	DefaultConditionState
		Model		= EXStinger01
	End
	ConditionState		= JAMMED
		ParticleBoneSys	= None SparksMedium
	End
End
Remapable			= yes
OkToChangeModelColor		= yes
Color				= DarkGrey
Shadow				= no
NoShadow			= yes
Animates			= yes
; Translucent			= yes					; This is in TD, the benefit is unclear. 
IgnitionFX			= FX_BuggyMissileIgnition
Trailer				= smokey2
TrailerAnim			= smokey2				; Debris types use a different way to say the same thing. 
AttachedSystem			= PuffSmallGreySys
;----- Armor -----
ArmorSet
	Conditions		= None
	Armor			= ArmorProjDumb				; This says I can be intercepted by hard-kill, but I cannot be intercepted by soft-kill. ; ProjectileArmor
	DamageFX		= none
	End
Interceptable			= yes
Interceptable.DeleteOnIntercept	= no
;----- Availability -----
; Side				= 
; Owner				= Allies, Soviet, Third, Alliance, Forgotten
; House				= 
DoubleOwned			= yes
TechLevel			= 1
;----- Movement -----
; AA				= yes
Arcing				= yes
Inaccurate			= yes					; BulletType attribute -- this gets ignored on the aircraft type of course
; FlakScatter			= yes

Proximity			= no
AA				= yes
Arm				= 2
High				= no
SubjectToCliffs			= yes
SubjectToElevation		= yes
SubjectToWalls			= yes
SubjectToBuildings		= yes



High				= yes
SubjectToWalls			= no
SubjectToCliffs			= yes
SubjectToElevation		= yes

Ranged				= yes
FuelLifetime			= 1250
InitialVelocity			= 150                ; in dist/sec
IgnitionDelay			= 0
DistanceToTravelBeforeTurning 	= 20
Proximity			= yes					; ditto
Locomotor			= Rocket				; SET_NORMAL TankHunterMissileLocomotor
MovementZone			= Fly


;----- Movement -----
Behavior			= MissileAIUpdate ModuleTag_07
TryToFollowTarget		= yes;;;;;;;;;;;;no 
ROT				= 3;<- "good tracking" one, "bad tracking" one was 2. (Good tracking elite was 20)



End




Speed				= 25
Rotates				= yes
ROT				= 0					; 3
Arm				= 2
High				= yes
FireAngle			= 1
Landable			= no					; Was yes, why? Missile type should not land. 
MoveToShroud			= yes
;----- Load -----
Crewed				= no
Ammo				= 1					; Aircraft are hard wired to require ammo
;----- UI -----
Selectable			= no
;----- Veterancy -----
Trainable			= no
;----- AI -----
ThreatPosed			= 3					; A single rocket should be slightly higher than an armed civilian. 
GuardRange			= 10
;----- Perception -----
Sight				= 0.0				; RA2: 1
VisionRange			= 0.0

RadarInvisible			= no
RadarVisible			= no
;----- Score -----
Points				= 1
;----- Damage & Destruction -----
; begin Projectile death behaviors
Behavior			= InstantDeathBehavior DeathModuleTag_01
	DeathTypes		= NONE +DETONATED
	; we detonated normally.
	; no FX, just quiet destroy ourselves
	End
Behavior			= InstantDeathBehavior DeathModuleTag_02
	DeathTypes		= NONE +LASERED
	; shot down by laser.
	FX			= FX_GenericMissileDisintegrate
	OCL			= OCL_GenericMissileDisintegrate
	End

Behavior			= InstantDeathBehavior DeathModuleTag_03
	DeathTypes		= ALL -LASERED -DETONATED
	; shot down by nonlaser.
    	FX			= FX_GenericMissileDeath
	End
End




Ranged=yes
Proximity=no
AA=yes
High=yes
;VeryHigh=yes
SubjectToWalls=no;yes
SubjectToCliffs=no;yes
Inaccurate=yes

; This is the good tracking one.
[DragonAntiMechanicalP]

; This is the bad tracking one.

; This is the good tracking one. 
; Huo2 long3
Object DragonRocket
[Rocket25691DFF3DB2E]





;------------------------------------------------------------------------------
; Ballistic rocket, inaccurate (default), medium, elite (red trail)
; Formerly [Rocket_475B38822D261], [HurricaneRocket_e3]
[Misl2]
;----- Text -----
Name				= Missile Hurricane (Trail Red)
;----- Gfx -----
Image				= rocket_trailer_red
Color				= DarkRed

;------------------------------------------------------------------------------
; Rocket Hurricane version cluster
; A non-inaccurate version (ID: Rocket_99352D7819A9F) also existed, but was deleted as nothing uses it. 
; Formerly BRocket.Prec-1.Clus3.Hi, [RocketHurricane_e3c3]
[Misl
;----- Payload -----
Cluster				= 3

;------------------------------------------------------------------------------
; Rocket, ballistic, high, inaccurate
; Used by Missile Frigate, Cormorant, Hind. 
; Formerly Rocket_565A95961148C, RocketHurricane. 
; Subsumes FrigateRocket (ER's MFrigProj; Missile Frigate Rocket). 
[RocketHurricane_h]
;----- Movement -----
; SubjectToTrenches		= no				; Gunship can fire into trenches? 
SubjectToCliffs			= no

;------------------------------------------------------------------------------
; Rocket Hurricane version elite
; Formerly HindRocketPE, Rocket_2AACB6823EF83, RocketHurricane_e3, [RocketHurricane_e3h]. 
[Misl2h]
$inherits			= misl2
;----- Gfx -----
Image				= rket_trail_red

;------------------------------------------------------------------------------
; Rocket Hurricane version green-smoke
; Use this for the Wasp's weapon Elite and Master. 
[RketHurricane_Gas_Grn]:[RocketHurricane]
;----- Gfx -----
Color				= Green
Image				= rket_trail_gas_grn

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------

;------------------------------------------------------------------------------
; Asian Missilier
; This is the bad tracking one. 
; Formerly [RPGProj]. 
Object MislDragonet
[MislDragonet]
$inherits			= misl
;----- Text -----
Name				= Missile Dragonet
;----- Display -----
Image				= dragon
;----- Movement -----
ROT				= 2
AA				= yes
Proximity			= no
High				= no
SubjectToWalls			= yes
End

;------------------------------------------------------------------------------
; Asian Elite Missilier
; [RPGProjE]
Object MislDragonet2
[MislDragonet2]
$inherits			= MislDragonet
;----- Text -----
Name				= Missile Dragonet Elite
;----- Display -----
Image				= dragon2
;----- Movement -----
ROT				= 3
End

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; small homing missile (targets vehicles best)
; HeatSeeker_TD,RA
; Formerly [Rocket_73B416D3C964D], [MissileHeatSeeker]. 
[MislSeekrHeat]
$inherits			= Misl
;----- Text -----
Name				= Missile Heat-Seeker
UIName				= name:misl_heatseeker
UIDescription			= desc:misl_heatseeker
;----- Armor -----
Armor				= ArmorMislSmart		; Differentiated from 'dumb' missiles (i.e., ballistic). This can be jammed, etc. 
;----- Movement -----
ROT				= 5				; 8 ; 20 ; 60
; CourseLockDuration		= 10				; New, for jj types firing this when facing another way. 
AA				= yes
SubjectToElevation		= no
;----- GFX -----
Image				= DRAGON

;------------------------------------------------------------------------------
; aircraft-only heatseeker
; AAHeatSeeker (TS)
; Formerly [MissileHeatSeekerAA]. 
[MislSeekrHeatAA]
$inherits			= MislSeekrHeat
;----- Movement -----
AA				= yes
AG				= no

;------------------------------------------------------------------------------
; small homing missile (targets vehicles best)
; TS' HeatSeeker
; Formerly Rocket_2155F4BD273C3, MissileHeatSeeker_2. 
[MissileHeatSeeker2AG]:[MissileHeatSeeker]
;----- Movement -----
ROT				= 8
AA				= no

;------------------------------------------------------------------------------
; Formerly Rocket_44ACEAA285BAA, MissileHeatSeeker_2e3. 
; Missile with red trail
[MissileHeatSeeker2TrlRed]:[MissileHeatSeeker2]
;----- GFX -----
AttachedSystem			= PuffSmallRedSys

;------------------------------------------------------------------------------
; Missile with blue trail
; Formerly MLRSProjE. 
; Subsumes Rocket_4322D (Rocket HeatSeeker EMP). 
[MissileHeatSeeker2TrlBlu]:[MissileHeatSeeker]
;----- Text -----
Name				= Missile Heat-Seeker EMP
;----- Gfx -----
Image				= misl_emp			; misl2
Color				= NeonBlue

Cluster=5
Arm				= 200


;------------------------------------------------------------------------------
; AAHeatSeeker2 (ts)
[MissileHeatSeeker3]:[MissileHeatSeeker2]
AA				= yes
	SubjectToCliffs=no
	SubjectToElevation=no
	SubjectToElevation=no

;------------------------------------------------------------------------------
; AAHeatSeeker3 (RA2, unused)
; Formerly HeatSeeker2E. 
[MissileHeatSeeker3]
Image				= MISLE
ROT				= 16
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes

;------------------------------------------------------------------------------
; aircraft and ground heatseeker
; RA2's AAHeatSeeker2
; Formerly Rocket_1AC3376D26948. 
[MissileHeatSeeker4]:[MissileHeatSeeker3]
Proximity			= no
ROT				= 60
SubjectToWalls=no

;------------------------------------------------------------------------------
; aircraft and ground heatseeker
; Formerly Rocket_HeatSeeker3E. 
[MissileHeatSeeker4TrlRed]:[MissileHeatSeeker4]

