
; Soviet Cannon Emplacement
; Molots have a "dirty"
; Soviet Molot Cannon Emplacement is a replacement 

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
[SUTurCannon]
;----- GFX -----
Image				= EmplacementRadCannon
;----- Body -----
Strength			= 600
;----- Turret -----
Turret				= yes
TurretAnim			= RCAN
TurretAnimIsVoxel		= yes
;TurretAnimX=-8
TurretAnimY			= -20;-27
TurretAnimZAdjust		= -85
TurretROT			= 2
;----- Weapons -----
Primary				= CannonMM105
FireAngle			= 0
;----- Armor -----
Armor				= steel
ImmuneToPsionics		= no
;----- Perception -----
Sight				= 6;8
;----- Crew -----
Crewed				= yes
;----- AI -----
ThreatPosed			= 40
AntiInfantryValue		= 10
AntiArmorValue			= 15
AntiAirValue			= 0
End

;------------------------------------------------------------------------------
; Soviet Rad Cannon Turret
; Formerly [RadCannonEmplacement]. 
[SUTurCannonAtom]
$inherits			= SUTurCannon
;----- Text -----
Name				= Emplacement Cannon Radiation
UIName				= name:RadCannonEmplacement
UIDescription			= desc:

Primary				= JadeCannon

LightVisibility			= 600;400
LightIntensity			= 0.01
LightRedTint			= 0.01
LightGreenTint			= 1.5
LightBlueTint			= 0.01

Explodes=yes
DeathWeapon=DevastatorExplode
End
