

[Capture]
;----- Payload -----
Warhead				= Capturing
Abductor			= yes
; Abductor.ChangeOwner		= yes
; Abductor.AbductorBelowPercent	= 11%
;----- Projection -----
Projectile			= InvisibleLow
Speed				= -1
Range				= 1.5
CellRangefinding		= yes
OmniFire			= yes
;----- Audio -----
Report				= EnterTransport


[Capturing]
Verses				= 100%,100%,100%,0%,0%,0%,0%,0%,0%,0%,0%
