;******************************************************************************
;*** Porta EMP Raygun *********************************************************
;******************************************************************************
; Formerly PulseCannon_EMP. 
; Higher tiers are long-range tools. 
; Possible veterancy upgrades are longer range, longer duration, added spread, and added damage. 
; TS's EMPulseWeapon "disappeared", as we neither need 
; This weapon is distinct from the AMR firing EMP munitions. It is a beam weapon. 
