
[ToxinCatapult]
;----- Payload -----
Damage				= 40
Warhead				= Poison			; WaspWH
; RadLevel			= 100
;----- Sequence -----
ROF				= 103
;----- Projection -----
Projectile			= ToxinBall
Range				= 10
Speed				= 30
;----- Audio -----
Report				= CatapultLaunch


[ToxinCatapult2]
$inherits			= ToxinCatapult
;----- Payload -----
Damage				= 25			; Total: 50
ExtraWarheads			= Crush

Range=5
Projectile=WaspProjE
Speed=30
Warhead=WaspWH
Report=OspreyAttack


[ToxinCatapult3]
;----- Payloads -----
Damage				= 30			; Total: 99
ExtraWarheads			= Crush, Explosion



[AcidBall]
Arcing				= true
Inaccurate			= yes
Image				= ball_green

[AcidBall2]
$inherits			= ToxinBall
;Arcing=true
;Inaccurate=yes
;FlakScatter=yes
ROT=3
Image=MISLBIO
Cluster=3

[WaspWH]	; Venom Wasp's mutation warhead
CellSpread=5;2
PercentAtMax=1
Verses=100%,100%,100%,0%,0%,0%,0%,0%,0%,0%,0%
InfDeath=9
AnimList=DEMTEXP
;Particle=GasCloudSys
