;
;
;


;------------------------------------------------------------------------------
[WeaponTypes]
+				= LnchrMislCM88Scud

;------------------------------------------------------------------------------
; FROG launcher
; RA's SCUD
; Formerly [FROGLauncher], [LauncherFROG], [ShootFROG]. 
[ShootMislMM544Frog]
$inherits				= ShootMislMM122Katy
;----- Payload -----
Damage					= 200					; From V3RocketDamage. RA's SCUD is 600. 
PrimaryDamage				= 200.0
Warhead					= HE					; SCUDWH
RadiusDamageAffects			= ALLIES ENEMIES NEUTRALS NOT_SIMILAR	; "NOT_SIMILAR" is from xxx. I think it doesn't do any harm to have it here. 
;----- Sequence -----
ROF					= 400					; From V3's SpawnRegenRate. This is about 27 seconds. 
DelayBetweenShots			= 1
ClipSize				= 1					; how many shots in a Clip (0 == infinite)
; Uses a clip of one to get the Reloading modelcondition
ClipReloadTime				= 26666
;----- Projection -----
Projectile				= FROG
ProjectileObject			= FROG				; SCUDMissile
; note, these only apply to units that aren't the explicit target 
; (ie, units that just happen to "get in the way"... projectiles
; always collide with the Designated Target, regardless of these flags
ProjectileCollidesWith			= STRUCTURES
Speed					= 10
Range					= 10				; 18
MinimumRange				= 5.0				; 
MinimumAttackRange			= 125				; From Scud (gen/zh)
Spawner					= yes
;----- Audio -----
Report					= V3Attack
FireSound				= ScudLauncherWeapon
;----- Display -----
Anim					= V3TAKOFF
FireFX					= FX_ScudLauncherIgnition
ProjectileExhaust			= ScudMissileExhaust
VeterancyProjectileExhaust		= HEROIC HeroicScudMissileExhaust
DeathType				= EXPLODED

End

;------------------------------------------------------------------------------
[ShootMislMM544FrogD2]
$inherits				= ShootMislMM544Frog
;----- Payload -----
DamageType				= EXPLOSION
PrimaryDamageRadius			= 30.00
SecondaryDamage				= 25.00
SecondaryDamageRadius			= 60.00
Warhead					= Explosion_wd1.2
ExtraWarheads				= Explosion_wd2.4
ExtraWarheads.DamageOverride		= 25.00

;------------------------------------------------------------------------------
[ShootMislMM544FrogR2]
$inherits				= ShootMislMM544Frog
;----- Projection -----
Range					= 14.00
AttackRange				= 350.0
MinimumRange				= 08.00
MinimumAttackRange			= 200.0
ScatterRadiusVsInfantry			= 30.00

End

;------------------------------------------------------------------------------
; V3's rangefinder virtual weapon
; Formerly [V3Launcher], [LauncherFROG_2]. 
; Removed "Damage = 1" and "Warhead = Special". 
; Removed "ROF = 150", "Projectile = InvisibleHigh". 
[ShootMislMM544FrogR3]
$inherits				= ShootMislMM544FrogR2
;----- Projection -----
Range					= 18.00
AttackRange				= 450.0

End

;------------------------------------------------------------------------------
; Upg. Cadence 2, no real implementation. 
[ShootMislMM554FrogC2]
$inherits				= ShootMislMM544Frog
;----- Sequence -----
ClipReloadTime				= 10000				; This is 10 seconds. 
PreAttackDelay				= 500.0				; This is 0.5 seconds. 
PreAttackType				= PER_SHOT			; Do the delay every single shot. 

End

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Intercalated, this doesn't pre-exist in any game. 
; It has the attributes that SCUDLauncherGunToxin has over [ShootFROG], 
; but minus the toxin effects of SCUDLauncherGunToxin. 
; Use it as the base type for FROG that has an additional effect (and trades some damage for that). 
; Formerly [ShootFROG_2], [ShootMislMM544Frog2]. 
; A little bit of extra damage (SecondaryDamage = 25, in addition to base damage 200). 
[ShootMislMM544FrogD2R2]
$inherits				= ShootMislMM544Frog, ShootMislMM544FrogD2, ShootMissileMM544FrogR2, ShootMislMM544FrogC2

End

;------------------------------------------------------------------------------
; Gen/ZH's SCUDLauncherGunToxin
; Formerly [ShootFROG_2&Toxin]. 
[ShootMislMM544FrogR2&Tox]
$inherits				= ShootMislMM544Frog2
;----- Payload -----
ProjectileDetonationOCL			= OCL_PoisonFieldMedium
;----- Display -----
ProjectileDetonationFX			= WeaponFX_SCUDMissileDetonationToxin
;----- Attach -----
;  WeaponBonus				= PLAYER_UPGRADE DAMAGE 125%		; AP rockets upgrade for SCUD launcher does not apply to poison missiles

End

;------------------------------------------------------------------------------
; Gen/ZH's SCUDLauncherGunToxinPlusOne
; Gained from Salvage upgrade. 
Weapon ShootMislMM544FrogR3&Tox
[ShootMislMM544FrogR3&Tox]
$inherits				= ShootMislMM544FrogR2&Tox, ShootMislMM544FrogR3
;----- Projection -----
Range					= 18.00					; Upg. range 14 => 18
AttackRange				= 450.0
Projectile				= MislFrog2
ProjectileObject			= MislFrog2				; SCUDMissilePlusOne

End

;------------------------------------------------------------------------------
; Gen/ZH's SCUDLauncherGunToxinPlusTwo
; Gained from Salvage upgrade 2. This is a damage upgrade. 
Weapon ShootMislMM544FrogR3D
[ShootMislMM544FrogR3D3]
;----- Payload -----
Damage					= 250.0
PrimaryDamage				= 250.0
SecondaryDamage				= 50.0          
;----- Projection -----
Projectile				= MislFrog3
ProjectileObject			= MislFrog3				; SCUDMissilePlusTwo

End

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Formerly [TiberiumRocketLauncher]. 
[ShootFROG_Rad]
;----- Payload -----
Damage				= 0
Warhead				= Radiation_wd8
;----- Projection -----
Projectile			= FROG_Rad			; TiberiumRocket

;------------------------------------------------------------------------------
; RA's & Gen/ZH's SCUDLauncherGunExplosive 
; Formerly [TochkaLauncher], [LauncherFROG_2], [ShootFROG_2], [ShootMislMM544FROG2]. 
; Subsumes CINE_ScudLauncherGunExplosive. 
; Damage (total) = 350. 
[ShootMislMM544FrogD4]
$inherits				= 
;----- Payload -----
Damage					= 300.0
PrimaryDamage				= 300.0
PrimaryDamageRadius			= 50.00
SecondaryDamage				= 50.00
SecondaryDamageRadius			= 100.0    
ScatterRadiusVsInfantry			= 30.00				; When this weapon is used against infantry, it can randomly miss by as much as this distance.
DamageType				= EXPLOSION
Warhead					= Explosion_wd2			; (PrimaryDamageRadius = 50.00) = (CellSpread = 2). 
ExtraWarheads				= Explosion_wd4			; (SecondaryDamageRadius = 100.0) = (CellSpread = 4). 
ExtraWarheads.DamageOverride		= 50.00
;----- Projection -----
Projectile				= FROG
ProjectileObject			= FROG				; Was "SCUDMissile". 
Range					= 14
MinimumRange				= 8
AttackRange				= 350.0
MinimumAttackRange			= 200.0
;----- Gfx -----
ProjectileObject			= SCUDMissile
  ProjectileExhaust           = ScudMissileExhaust
  VeterancyProjectileExhaust  = HEROIC HeroicScudMissileExhaust
  ProjectileDetonationFX      = WeaponFX_SCUDMissileDetonationExplosive
  RadiusDamageAffects         = ALLIES ENEMIES NEUTRALS NOT_SIMILAR
  FireSound                   = ScudLauncherWeapon
;----- Sequence -----
; ScudStormDamageWeapon > DelayBetweenShots = 0, ClipSize = 0, ClipReloadTime = 0,, 
; SCUDLauncherGunExplosive > DelayBetweenShots = 1, ClipSize = 1. 
; Uses a clip of one to get the Reloading modelcondition
DelayBetweenShots			= 1
ClipSize				= 1
ClipReloadTime				= 10000		; how long to reload a Clip, msec
							; msec 10000 corresponds to 10 seconds, which corresponds to ROF = 150. 
							; However, we use Reload and SpawnRegen. 
PreAttackDelay				= 500
PreAttackType				= PER_SHOT	; Do the delay every single shot
;----- Upgrades -----
WeaponBonus				= PLAYER_UPGRADE DAMAGE 125%  ; AP rockets upgrade for SCUD launcher
End

Weapon CINE_SCUDLauncherGunExplosive
ScatterRadiusVsInfantry     = 30.0     ;When this weapon is used against infantry, it can randomly miss by as much as this distance.
  AttackRange                 = 350.0
  MinimumAttackRange          = 200.0
  PreAttackDelay              = 500
  PreAttackType               = PER_SHOT ; Do the delay every single shot
  DamageType                  = EXPLOSION 
  DeathType                   = EXPLODED
  FireFX                      = FX_ScudLauncherIgnition
  ProjectileObject            = CINE_SCUDMissile
  ProjectileExhaust           = ScudMissileExhaust
  VeterancyProjectileExhaust  = HEROIC HeroicScudMissileExhaust
  ProjectileDetonationFX      = WeaponFX_SCUDMissileDetonationExplosive
  RadiusDamageAffects         = ALLIES ENEMIES NEUTRALS
  FireSound                   = ScudLauncherWeapon
  DelayBetweenShots           = 1
  ClipSize                    = 1                ; how many shots in a Clip (0 == infinite)
  ClipReloadTime              = 10000            ; how long to reload a Clip, msec
  ; Uses a clip of one to get the Reloading modelcondition

  ; note, these only apply to units that aren't the explicit target 
  ; (ie, units that just happen to "get in the way"... projectiles
  ; always collide with the Designated Target, regardless of these flags
  ProjectileCollidesWith = STRUCTURES

  WeaponBonus = PLAYER_UPGRADE DAMAGE 125%  ; AP rockets upgrade for SCUD launcher
End

;------------------------------------------------------------------------------
; Gen/ZH's DEMO_SCUDLauncherGunExplosive. 
; Artillery General's Tochka Rockets
[]
;----- Gfx -----
ProjectileDetonationFX			= WeaponFX_DEMO_SCUDMissileDetonationExplosive

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; gen/zh's SCUDLauncherGunExplosivePlusOne
Weapon ShootMislMM544FrogNNN
[ShootMislMM544FrogNNN]
PrimaryDamageRadius         = 50.0      
SecondaryDamageRadius       = 100.0    
;----- Projection -----
Range				= 18
AttackRange			= 450.0
  MinimumAttackRange          = 200.0
  PreAttackDelay              = 500
  FireFX                      = FX_ScudLauncherIgnition
  ProjectileObject            = SCUDMissilePlusOne
  ProjectileExhaust           = ScudMissileExhaust
  VeterancyProjectileExhaust  = HEROIC HeroicScudMissileExhaust
  ProjectileDetonationFX      = WeaponFX_SCUDMissileDetonationExplosive
  RadiusDamageAffects         = ALLIES ENEMIES NEUTRALS NOT_SIMILAR
  FireSound                   = ScudLauncherWeapon
  DelayBetweenShots           = 1
  ClipSize                    = 1                ; how many shots in a Clip (0 == infinite)
  ClipReloadTime              = 10000            ; how long to reload a Clip, msec
  ; Uses a clip of one to get the Reloading modelcondition

  ; note, these only apply to units that aren't the explicit target 
  ; (ie, units that just happen to "get in the way"... projectiles
  ; always collide with the Designated Target, regardless of these flags
  ProjectileCollidesWith = STRUCTURES

  WeaponBonus = PLAYER_UPGRADE DAMAGE 125%  ; AP rockets upgrade for SCUD launcher
End

;------------------------------------------------------------------------------
; gen/zh's DEMO_SCUDLauncherGunExplosivePlusOne
[
;----- Gfx -----
ProjectileDetonationFX			= WeaponFX_DEMO_SCUDMissileDetonationExplosive
End

;------------------------------------------------------------------------------
; Formerly [FROGLauncherE]. 
[ShootFROG_xxx]:[ShootFROG_xxx]
;----- Payload -----
Damage					= 400
; Warhead				= SCUDEWH
;----- Projection -----
Speed					= 25

;------------------------------------------------------------------------------
; Gen/ZH's SCUDLauncherGunExplosivePlusTwo
; Formerly [TochkaLauncher_3], [LauncherFROG4]. 
; Damage (total) = 475. 
[ShootMislMM544FrogN-1]
$inherits				= 
;----- Payload -----
Damage					= 400.0
PrimaryDamage				= 400.0            
PrimaryDamageRadius			= 50.00
SecondaryDamage				= 75.00
SecondaryDamageRadius			= 100.0    
ExtraWarheads.DamageOverride		= 75.00
;----- Projection -----
ProjectileObject			= SCUDMissilePlusTwo
End

;------------------------------------------------------------------------------
; Gen/ZH's DEMO_SCUDLauncherGunExplosivePlusTwo
[ShootMislMM544FrogN]
$inherits				= ShootMislMM544N-1
  PreAttackDelay              = 500
  PreAttackType               = PER_SHOT ; Do the delay every single shot
  DamageType                  = EXPLOSION 
  DeathType                   = EXPLODED
  FireFX                      = FX_ScudLauncherIgnition
  ProjectileObject            = SCUDMissilePlusTwo
  ProjectileExhaust           = ScudMissileExhaust
  VeterancyProjectileExhaust  = HEROIC HeroicScudMissileExhaust
  ProjectileDetonationFX      = WeaponFX_DEMO_SCUDMissileDetonationExplosive
  DelayBetweenShots           = 1
  ClipSize                    = 1                ; how many shots in a Clip (0 == infinite)
  ClipReloadTime              = 10000            ; how long to reload a Clip, msec
End

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Gen/ZH's ScudStormWeapon
; Formerly [ScudLauncher]. 
[LnchrMislCM88Scud]
$inherits				= 
;----- Payload -----
PrimaryDamage				= 0				; not used for this weapon (it's "special")            
PrimaryDamageRadius			= 0				; not used for this weapon (it's "special")
DamageType				= EXPLOSION			; not used for this weapon (it's "special")
; RadiusDamageAffects			= ALLIES ENEMIES NEUTRALS
;----- Display -----
DeathType				= EXPLODED
;----- Projectile -----
Range					= -2
AttackRange				= 999999			; not used for this weapon (it's "special")
WeaponSpeed				= 99999				; not used for this weapon (it's "special")
Projectile				= ScudRocket
ProjectileObject			= ScudStormMissile

ProjectileExhaust = ScudMissileExhaust
FireFX = WeaponFX_ScudStormMissile
FireSound = ScudStormLaunch
ProjectileDetonationFX = ScudStormMissileDetonation
RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
DelayBetweenShots = Min:100 Max:1000
ClipSize = 9
ClipReloadTime = 10000 ; give it time to sink into the ground          
AutoReloadsClip = Yes
  ScatterRadius   = 0;changed to zero, unless you want to soften the results of the table below

  ; Instead of a purely random scatter distance, this will divide a clip evenly and randomly at these spots
  ; These specific points are an even distribution simulating a 150 ScatterRadius.
  ; With fewer entries than ClipSize, the extra will hit 0,0 as normal shots
  ; With extra entries, 9 of 12 could be used eg, and then you'd get a different nine next clip.

  ScatterTargetScalar = 120; replaces the ScatterRadius, above, for scaling this table, below
  ScatterTarget = X: 0.000 Y: 0.133
  ScatterTarget = X: 0.133 Y:-0.200
  ScatterTarget = X:-0.067 Y: 0.667
  ScatterTarget = X: 0.300 Y: 0.300
  ScatterTarget = X: 0.767 Y: 0.000       
  ScatterTarget = X: 0.500 Y:-0.567        
  ScatterTarget = X:-0.333 Y:-0.800        
  ScatterTarget = X:-0.600 Y:-0.1333        
  ScatterTarget = X:-0.567 Y: 0.433        

  PreAttackDelay = 3000 ; Give the missiles time to get up, since we can't watch the animation. (If too short, missiles will pop up)
  PreAttackType = PER_CLIP ; Do the delay the first shot of each clip
  AcceptableAimDelta = 180 ; Don't need to turn at all.
  ProjectileCollidesWith = STRUCTURES
End

;------------------------------------------------------------------------------
; Gen/ZH's Demo_ScudStormWeapon
[ScudLauncher_Arty]:[ScudLauncher]
;----- Projection -----
Projectile				= MissileScud2
ProjectileObject = Demo_ScudStormMissile
End

;------------------------------------------------------------------------------
; GC_Chem_ScudStormWeapon (Gen/ZH)
[LnchrScudToxin]
;----- Projection -----
Projectile				= MissileScudToxin
ProjectileObject			= GC_Chem_ScudStormMissile
End

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Gen/ZH's ScudStormDamageWeapon
; Damage (total) = 650. 
; Formerly [ScudCollision], [ShootScud], [ShootFROG_3] 
; (Unclear why this was re-classified as FROG-related, as it is the Scud Storm impact weapon. 
[
$inherits				= 
;----- Payload -----
Damage					= 500.0
PrimaryDamage				= 500.0
SecondaryDamage				= 150.0				; 50.0
SecondaryDamageRadius			= 200.0
ExtraWarheads				= Explosion_wd8			; (SecondaryDamageRadius_gen&zh = 200.00) = (CellSpread = 8)
ExtraWarheads.DamageOverride		= 150
;----- Projection -----
; Range					= 8
; AttackRange				= 200.0
WeaponSpeed				= 600
;----- Gfx -----
; FireFX				= ScudStormMissileDetonation	; This should be a warhead property. 
End

  PrimaryDamage = 500.0
  PrimaryDamageRadius = 50.0
  SecondaryDamage = 150.0 ;50.0
  SecondaryDamageRadius = 200.0 
  AttackRange = 200.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  WeaponSpeed = 600         ; dist/sec 
  FireFX = ScudStormMissileDetonation
  FireOCL = OCL_PoisonFieldLarge  ; So this weapon will do normal damage, and create this object
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 0               ; time between shots, msec
  ClipSize = 0                    ; how many shots in a Clip (0 == infinite)
  ClipReloadTime = 0              ; how long to reload a Clip, msec

;------------------------------------------------------------------------------
[ShootFROG_3&Toxin]:[ShootFROG_3]
;----- Payload -----
ExtraWarheads				= Explosion_wd8, Toxin
ExtraWarheads.DamageOverride		= 150, 0
FireOCL					= OCL_PoisonFieldLarge			; So this weapon will do normal damage, and create this object. 
End

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Gen/ZH's ScudStormDamageWeaponUpgraded
; Formerly [CollideScud2]. 
[ShootFROG_4]:[ShootFROG_3]
;----- Payload -----
; PrimaryDamageRadius			= 25.00
SecondaryDamage				= 200.0					; 100.0
; SecondaryDamageRadius			= 50.00
ExtraWarheads.DamageOverride		= 200.0
End

;------------------------------------------------------------------------------
[ShootFROG_4&Toxin]:[ShootFROG_4]
;----- Payload -----
FireOCL					= OCL_PoisonFieldUpgradedLarge  ; So this weapon will do normal damage, and create this object
End

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Chem_ScudStormDamageWeaponGamma (Gen/ZH)
; Formerly [CollideScud3PlusToxin]. 
[
PrimaryDamage = 550.0
PrimaryDamageRadius = 50.0 ;25.0
SecondaryDamage = 200.0 ;100.0
SecondaryDamageRadius = 200.0 ;50.0
  AttackRange = 200.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  WeaponSpeed = 600         ; dist/sec 
  FireFX = GC_Chem_WeaponFX_SCUDMissileDetonationAnthrax
  FireOCL = OCL_PoisonFieldGammaLarge  ; So this weapon will do normal damage, and create this object
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 0               ; time between shots, msec
  ClipSize = 0                    ; how many shots in a Clip (0 == infinite)
  ClipReloadTime = 0              ; how long to reload a Clip, msec
End

;------------------------------------------------------------------------------
; Gen/ZH's Demo_ScudStormDamageWeapon
; Formerly [ScudCollision_Arty]. 
[CollideScud4]
PrimaryDamage = 600.0
  PrimaryDamageRadius = 75.0
  SecondaryDamage = 150.0
  SecondaryDamageRadius = 200.0 
  AttackRange = 200.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  WeaponSpeed = 700         ; dist/sec 
  FireFX = Demo_ScudStormMissileDetonation
  ;NOTE: Removed the meta-physics for these missiles because it was causing some missles to stop and rotate in place.  
  ;I don't know how to fix this. - Comes 6/03
;  ShockWaveAmount   = 75.0 ; represents the shockwave amount. The larger the amount, the greater and more dramatic the shockwave effect    
;  ShockWaveRadius     = 75.0 ; should be no more than the primary/secondary damage radius, whichever is larger.
;  ShockWaveTaperOff  = 0.50    ; 0.33 means at the shockwave edge, the shockwave amount is 33%.
End
