;******************************************************************************
;*** Grenade Toss *************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[WeaponTypes]
+				= ThrowGrenade

;------------------------------------------------------------------------------
; LaoTze 24's SPETZBomber
; Doesn't seem to be 
; Formerly SpezGrenadeLauncher. 
[ThrowGrenade]
Damage=25
ROF=90
Range=5
Projectile=Grenade;GrenadeArcing
Speed=30
Warhead=SPETZBomb
Report=SpetzThrow
Lobber=yes

; hand grenade
[Grenade]
Damage=50
ROF=50
Range=3.25
Projectile=Lobbed
Speed=5
Warhead=HE
Explosion=5


; hand grenade
[Grenade]
Damage=50
ROF=60
Range=4
Projectile=Lobbed
Speed=5
Warhead=HE


;------------------------------------------------------------------------------
; hand grenade (discus)
[ThrowGrenade]
Damage				= 40
ROF=60
Range=4.5
Projectile=Grenade
Speed=5
Warhead=HE
Lobber=yes
Bright=yes
Report=Toss



[OldLobbed]
High=yes
Image=DISCUS
Bouncy=no
Inaccurate=yes

[OldGrenade]
Damage=50
ROF=60
Range=6
Projectile=OldLobbed
Warhead=HE
Speed=5

;------------------------------------------------------------------------------
; hand grenade (cluster)
[ClusterGrenadeThrow]
Damage=60
ROF=50
Range=4
Projectile=ClusterGrenade

; First stage of heavy grenadier weapon
; TechWar's Betty1
; Formerly [MultiGrenadeThrow]. 
[Throw
Damage				= 75
ROF				= 60
Range				= 6
MinimumRange			= 5
Projectile			= MultiGrenade
Speed				= 5
Warhead				= ORCAHE
Bright				= yes

;------------------------------------------------------------------------------
; Second/Last stage of heavy grenadier weapon
; TechWar's Betty2
; Formerly [Wpn_st2_of_Grenade_Multi]. 
[ThrowBomblet]
Damage				= 75
ROF				= 60
Range				= 6
Projectile			= Bomblet_of_Grenade_Multi
Speed				= 4
Warhead				= ORCAHE
Bright				= yes
Burst				= 2


;------------------------------------------------------------------------------
; Attaching charge to enemy tank. ELITE (tossed charge)
; Formerly [DemoChargeE], [ThrowGrenade_Mag]. 
[ThrowGrenadeMag]
Damage=140	; this is theirs, here is the new stuff w2500 ; a boatload  (get it?)
ROF=100
Range=4
Projectile=GrenadeMagnetic
Warhead=Mechanical
Report=Thumper
SabotageCursor=yes ;gs instead of normal fire cursor to avoid confusion

;------------------------------------------------------------------------------
; Formerly [AetheriteGrenade]. 
[ThrowGrenadeTib]:[ThrowGrenade]
;----- Payload -----
Damage				= 35
Warhead				= Tiberium
;----- Projection -----
Projectile			= GrenadeGrn

; Spetznaz Bomb
[SPETZBomb]
Verses=60%,60%,60%,20%,20%,20%,100%,100%,90%,30%,100%
AnimList=XGRYSML1,XGRYSML2,EXPLOSML,XGRYMED1,XGRYMED2,EXPLOMED,EXPLOLRG,TWLT070
ProneDamage=70%
InfDeath=2
CellSpread=.75
PercentAtMax=.5
