Sight=5
Cost=800
Points=25
Passengers=4
MaxDebris=9
DebrisTypes=PICK,TIRE,CARDEAD
DebrisMaximums=4,4,1

;------------------------------------------------------------------------------
[VehicleTypes]
; CCBBEB57C846B
+				= Car
+				= SUV_Guard

;------------------------------------------------------------------------------
; Civilian automobile
[Car]
;----- Text -----
UIName				= Name:Car
Name				= Automobile
Nominal				= yes
;----- Body -----
Strength			= 100
Size				= 4					; From TAXI. ~vxs, '22-1-4 
;----- Availability -----
Side				= Neutral				; "Side" really is Side. In games with added Countries or Houses, this is depreciated as a direct pointer in favor of an additional Owner layer. Side then only points from each [Country], to the [Side] the country belongs to. 
Owner				= Neutral
House				= Incidental
Prerequisite			= FACTORY
FactoryOwner			= Neutral
Cost				= 200
AllowedToStartInMultiplayer	= no
CrateGoodie			= yes
TechLevel			= 1				; -1
AllowedToStartInMultiplayer	= no
;----- AI -----
Category=Transport
ThreatPosed=0
SpecialThreatValue=1
;----- Armor -----
Armor				= light
;----- Load -----
Crewed				= yes			; Should be yes, since it moves. 
DeployTime			= 0.022
Passengers			= 4
SizeLimit			= 1			; 2
OpenTopped			= yes
;----- Perception -----
Sight				= 8
;---- GFX -----
PipScale=Passengers
ZFudgeColumn=10
ZFudgeTunnel=13
;----- Score -----
Points=20
;----- Load -----
Passengers			= 5
SizeLimit			= 2
Crewed				= yes
;----- Damage & Destruction -----
MinDebris				= 2
MaxDebris				= 3					; 4
DebrisMaximums				= 1, 4, 4, 1
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DamageParticleSystems=SparkSys,SmallGreySSys
MaxDebris=3
DebrisTypes=Car,GasTank,Tire,Piece
DebrisMaximums=1,1,4,4
;----- SFX -----
VoiceSelect=GenCarCommand
VoiceAttack=GenCarCommand
VoiceFeedback=GenCarCommand
MoveSound				= TruckMoveStart
DieSound=GenVehicleDie
CrushSound=TankCrush
;----- Movement -----
Locomotor			= Drive
MovementZone			= Normal
ROT				= 5
Speed				= 8
;----- Veterancy -----
VeteranAbilities=FASTER,STRONGER,ARMOR,CRUSHER;SELF_HEAL

;------------------------------------------------------------------------------
; European Car A
[EUROC]
UIName=Name:CAR
Name=European Car A

;------------------------------------------------------------------------------
; Sports Car
[STANG]
UIName=Name:CAR
Name=Sports Car

;------------------------------------------------------------------------------
; Black Sport Utility Vehicle
[SUV_B]
UIName=Name:CAR
Name=SUV Black

;------------------------------------------------------------------------------
; White Sport Utility Vehicle
[SUV_W]
UIName=Name:CAR
Name=SUV White

;------------------------------------------------------------------------------
; Guard SUV
[SUV_Guard]:[SUV_B]
;----- Name -----
UIName				= Name:SUV_Guard
Name				= Guard SUV

;------------------------------------------------------------------------------
; European Car A
; vanilla's EUROC
[EuroCar_A]:[Car]
Name				= European Car A

;------------------------------------------------------------------------------
; Sports Car
; vanilla's STANG
[MustangCar]
UIName				= Name:Car_Mustang
Name				= Sports Car

;------------------------------------------------------------------------------
; Black Sport Utility Vehicle
; vanilla's SUVB
[SUVBlack]
UIName				= Name:Wagon_SUV
Name				= SUV Black

;------------------------------------------------------------------------------
; White Sport Utility Vehicle
; vanilla's SUVW
[SUVWhite]
UIName				= Name:Wagon_SUV
Name				= SUV White

;------------------------------------------------------------------------------
; Taxi
; vanilla's TAXI
; 4 ride for the price of one. 
; Driver carries only 5 dollars in change. 
[TaxiCab]
UIName				= Name:Taxi
Name				= Taxi

;------------------------------------------------------------------------------
; Taxi
; vanilla's YCAB
; Formerly [YellowCab]. 
[CabYlw]
$inherits			= Cab
;----- Text -----
Name				= Cab Yellow

;------------------------------------------------------------------------------
; Black Cab
; vanilla's BCAB
; Formerly [BlackCab]. 
[CabBlk]
$inherits			= Cab
;----- Text -----
Name				= Cab Black

;------------------------------------------------------------------------------
; Police Car
; vanilla's COP
; Formerly [GuardsCar]. 
[CarGuards]
$inherits				= Car
;----- Text -----
Name					= Police Car
UIName					= name:pigcar
UIDescription				= desc:pigcar
;----- Taxonomy -----
Category				= Support		; Not really sure what to put here. Vanilla and MO has Transport. 
;----- Body -----
; Strength				= 125			; MO
;----- Weapons -----
; Primary				= Vulcan
; ElitePrimary				= VulcanE
;----- Availability -----
DoubleOwned				= yes
Prerequisite				= factory, capoli	; CDHQ
Cost					= 500
BuildTimeMultiplier			= 1.2
;----- Score -----
Points					= 20
;----- UI -----
IsSelectableCombatant			= yes
;----- AI -----
SpecialThreatValue			= 1
;----- SFX -----
VoiceSelect				= SelectInfUNGen			; GISelect
VoiceMove				= CmdMovInfUNGen			; GIMoveCommand
VoiceAttack				= CmdAtkInfUNGen			; GIAttackCommand
VoiceFeedback				= FearInfUNGen
AmbientSound				= SirenLoop
DieSound				= PoliceCarDie
;----- Damage & Destruction -----
DebrisTypes				= CarGuards, TIRE, PIECE, GASTANK

;------------------------------------------------------------------------------
; Guards Elite
; Presidential Escort
[CarGuards2]
$inherits				= CarGuards
;----- Text -----
Name					= Police Car Elite
;----- Perception -----
Sensors					= yes
DetectDisguise				= yes
;----- Weapons -----
Primary					= AWPE
OmniFire				= yes

;------------------------------------------------------------------------------
; Presidential Limo
; vanilla's LIMO
[Limo]
$inherits			= Car
;----- Text -----
Name				= Limo
UIName				= name:limo
UIDescription			= desc:limo
;----- Body -----
Strength			= 250			; armored car
SelfHealing			= yes
Size				= 6
;----- Weapons -----
Primary				= DummyWeapon		; Targets OpenTopped units. 
Secondary			= CIWSPrism		; Anti-missile
;----- Armor -----
Armor				= heavy
ImmuneToRadiation		= yes
ImmuneToPsionics		= yes
;----- Load -----
; Crewed with 2 Secret Service. 
Passengers			= 6
SizeLimit			= 1
InitialPayload.Types		= president, ssrv4			; Carries President, 5 Secret Service Masters, 2 Commando, 2 Medic Elite. 
InitialPayload.Nums		= 1, 2
;----- Attach -----
ShieldType			= shield_default			; 600 STR
