;******************************************************************************
;*** Defender *****************************************************************
;******************************************************************************
; The European Garrison Infantry is intended for use as crews of defensive installations. 
; They are equipped to quickly dig in and fortify an area. When not deployed, the Garrison uses a grenade launcher with a wide-area fragmentation grenade 
; that can arc over walls and is effective against infantry. When ordered to deploy, the Garrison Infantry digs in with a MG3, 
; a machine gun with an incredible rate of fire, capable of holding back waves upon waves of enemy infantry. 
; Beware of pitting the Defender offensively, however! 

;------------------------------------------------------------------------------
[InfantryTypes]
+				= Defender

;------------------------------------------------------------------------------
[Defender]
$inherits			= Trooper
;----- Text -----
Name				= Garrison Infantry
UIName				= name:defender
UIDescription			= desc:defender
;----- Body -----
Strength			= 230
;----- Weapons -----
; Primary			= GarrisonGrenadeLauncher
; Secondary			= SMG
; Elite				= GustafGun
; ElitePrimary			= GustafGun
; EliteSecondary		= MG3
WeaponCount			= 3
Weapon1				= GarrisonGrenadeLauncher
Weapon2				= M60
Weapon3				= M60
; EliteWeapon			= GustafGun
; EliteWeapon2			= MG3
; EliteWeapon3			= InterceptorAura
OccupyWeapon			= UCMG3
; EliteOccupyWeapon		= UCMG3E
;----- Armor -----
Armor				= plate
;----- AI -----
Fearless			= yes
;----- Movement -----
Speed				= 3
;----- Conversion -----
Deployer			= yes
DeployFire			= yes
DeployFireWeapon		= 1
;----- Veterancy -----
VeteranAbilities		= ARMOR, SIGHT, SENSORS
EliteAbilities			= ARMOR, SIGHT, SELF_HEAL, PSIONICSIMMUNE

;------------------------------------------------------------------------------
; Defender Veteran
[Defender2]
$inherits			= Defender
;----- Text -----
Name				= Garrison Infantry
UIName				= name:defender
UIDescription			= desc:defender
;----- Body -----
Strength			= 230
;----- Weapons -----
; Primary			= GarrisonGrenadeLauncher
; Secondary			= SMG
; ElitePrimary			= GustafGun
; EliteSecondary		= MG3
WeaponCount			= 3
Weapon1				= GarrisonGrenadeLauncher
Weapon2				= M60
Weapon3				= M60
OccupyWeapon			= UCMG3
; EliteOccupyWeapon		= UCMG3E
;----- Conversion -----
Deployer			= yes
DeployFire			= yes
DeployFireWeapon		= 1

