;******************************************************************************
;*** Medic ********************************************************************
;******************************************************************************
; Medics are unarmed ‘helper’ units that work in with infantry squads, 
; preserving their lives with much-needed shots of medicine. 
; They will automatically run over to other soldiers to tend their wounds. 
; Be careful, as Medics are comparatively expensive and often get caught up in crossfire. 
;
; Philippines train these as Elite. 

;------------------------------------------------------------------------------
[InfantryTypes]
+				= Medic

;------------------------------------------------------------------------------
; Medic
; Created by Lord Kal, 03/11/15 - 03/11/16. 
[Medic]:[Civilian]
;----- Text -----
Name				= Medic
UIName				= name:medic
UIDescription			= desc:medic
;----- Taxonomy -----
Category			= Soldier
;----- Art -----
Cameo				= icon_medic
Sequence			= MedicSequence
Remapable			= yes
FireUp				= 2
Crawls				= yes
PrimaryFireFLH			= 0,0,100
;----- Body -----
Strength			= 125				; standard level (10)
SelfHealing			= yes
;----- Weapons -----
Primary				= MediKit
;Secondary			= PistolGlock17
ElitePrimary			= MediKit_E
OccupyWeapon			= MediKit_Occ
EliteOccupyWeapon		= MediKit_Occ_E
IFVMode				= MEDIC

Primary=Heal
;Secondary=VirtualScanner	; Medic does not need this, he gets scan range from global setting up top. 
Occupier=yes
OccupyWeapon=UCHeal
EliteOccupyWeapon=UCEliteHeal

;----- Availability -----
Side				= 
Owner				= Allies
; House				= 
TechLevel			= 4
Prerequisite			= UNBarracks
PrerequisiteOverride		= Hospital			; any side can train this unit if owning a Hospital
Cost				= 600
AllowedToStartInMultiplayer	= no

;----- Perception -----
Sight				= 6

;----- Movement -----
Speed				= 4

;----- GFX -----
Pip				= white-red
OccupyPip			= PersonWhiteCrossRed									; PersonWhite
;Insignia.Rookie=HEALPIP
;Insignia.Veteran=HEALPIP1
;Insignia.Elite=HEALPIP2





;----- Scoring -----
Points				= 5

;----- SFX -----
VoiceSelect			= SelectMedic
VoiceMove			= CmdMovMedic
VoiceAttack			= 
VoiceSpecialAttack		= CmdHealMedic
VoiceFeedback			= 
VoiceDie			= GenInfantryDie
CrushSound			= InfantrySquish				; SQUISHY2
;----- AI -----
GuardRange			= 8
DefaultToGuardArea		= yes
ThreatPosed			= 0
SpecialThreatValue		= 1
LeadershipRating		= 3
PreventAttackMove		= yes
;----- UI -----
IsSelectableCombatant		= no
;----- Veterancy -----
; Trainable			= no			; Technical yes, but system won't allow for technical reasons (this unit does not deal damage/kill). 

;------------------------------------------------------------------------------
; Xrono Medic
[MedicXron]

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
[Medic2]
$include			= Medic
;----- Text -----
Name				= 
;----- Armor -----
Armor				= hazmat
; ImmuneToRadiation		= yes
; ImmuneToPsionics		= yes
; ImmuneToPsionicWeapons	= yes
; ImmuneToPoison		= yes
TiberiumProof			= yes

Primary=Heal
ElitePrimary=HealE
Prerequisite=GAPILE,RADAR
Pip=red
Armor=flak
TechLevel=4
Sight=8
Speed=6
Owner=British,French,Germans,Americans
Cost=500
Soylent=500
Points=5
;MoveToShroud=no
VoiceSelect=MedicSelect
VoiceMove=MedicMove
VoiceAttack=MedicAttackCommand
VoiceSpecialAttack=MedicAttackCommand
;VoiceFeedback=CivAllFear
;DieSound=CivAllDie
DefaultToGuardArea=yes
GuardRange=20
AllowedToStartInMultiplayer=no
