;
;
;
; Liberty Defender, Truth Defender, Avatar, Caturhasta Avatar. 

;------------------------------------------------------------------------------
[VehicleTypes]
+					= 
+					= LibertyWalker

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Liberty Defender
; Formerly [LibertyWalker]. 
[WlkrSentinel]
;----- Text -----
Name					= Liberty Prime
UIName					= name:LibertyPrime
UIDescription				= desc:

;----- Body -----
Strength				= 5000000
;----- Armor -----
Armor					= armor_sentinel		; LibertyDefenderArmor	; Only superweapons can damage it. 
TiberiumProof				= yes
ImmuneToVeins				= yes
ImmuneToPoison				= yes
ImmuneToRadiation			= yes
ImmuneToPsionics			= yes				; new
; Immune				= yes
;----- Availability -----
Side					= USA
Owner					= Americans
; House					= 
RequiredHouses				= Americans
TechLevel				= -1
Prerequisite				= 
BuildLimit				= -1
;----- Weapons -----
Primary=AtomicBombLaunch
Secondary=DummyWeapon; Use this against air. 
;----- Load -----
Passengers=1
InitialPayload.Types=LibertyLaserDummy

Sight=9
Speed=5
Cost=2000
Points=40
ROT=5
Crusher=yes
Crewed=no
Weight=3.5
VoiceSelect=
VoiceMove=
VoiceAttack=
VoiceFeedback=
Locomotor={55D141B8-DB94-11d1-AC98-006008055BB5}
MovementZone=Destroyer
ThreatPosed=50
DamageParticleSystems=SparkSys,SmallGreySSys
MaxDebris=30  ;was 10
Explosion=DEFD_EXP
AllowedToStartInMultiplayer=no
IsCoreDefender=yes
WalkRate=4
Primary=DEFOB
DamageSmokeOffset=0,0,550
Trainable=yes
EliteAbilities=SENSORS
ImmuneToVeins=yes
TiberiumProof=yes
TiberiumHeal=yes
SelfHealing=yes
NoMovingFire=true
;----- Power ----
PoweredBy				= 

[LibertyPrimeLaser]

[LibertyPrimeNukeToss]

;------------------------------------------------------------------------------
[WlkrSentinelHusk]

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Core Defender
; [DEFENDER] (fs)
[WlkrSentinel2]
$inherits				= WlkrSentinel
;----- Text -----
Name					= Core Defender
UIName					= name:
UIDescription				= desc:
;----- Taxonomy -----
Category				= AFV
NonVehicle				= yes				; new
Organic					= yes				; new
Cyborg					= yes				; new
IsCoreDefender				= yes
;----- Gfx -----
Normalized				= yes				; artfs.ini entry, moved up from [DEFD]. 
Remapable				= no
OkToChangeModelColor			= yes
Voxel					= no
Facings					= 8
StartStandFrame				= 0
WalkFrames				= 8				; artfs.ini entry
StartWalkFrame				= 8
FiringFrames				= 12
FiringSyncFrame1			= 8
FiringSyncFrame2			= 3
StartFiringFrame			= 72
PrimaryFireFLH				= 200,-200,450
SecondaryFireFLH			= 200,200,450
;----- Body -----
Strength				= 10000
SelfHealing				= yes				; SelfHealing to TS standard. 
Size					= 30				; arbitrarily high
Weight					= 35				; 3.5
;----- Weapons -----
Primary					= DEFOB
NoMovingFire				= yes
;----- Armor -----
Armor					= heavy, skin_mut_tib, cyborg	; heavy
TiberiumHeal				= yes
ImmuneToVeins				= yes
; ImmuneToPoison			= yes
; ImmuneToRadiation			= yes
;----- Perception -----
Sight					= 9
;----- Movement -----
Speed					= 5
ROT					= 5
MovementZone				= Destroyer
Locomotor				= {55D141B8-DB94-11d1-AC98-006008055BB5}
WalkRate				= 4
Crusher					= yes
MoveToShroud				= yes
;----- Availability -----
Owner					= Legion			; CABAL, was Civilian. 
Cost					= 2000
AllowedToStartInMultiplayer		= no
CrateGift				= no
CrateGoodie				= no
;----- Score -----
Points					= 40
;----- AI -----
ThreatPosed				= 50
;----- Sfx -----
UndeploySound				= COREUP1			; Moved up from DDEFD. 
;----- Damage & Destruction -----
DamageParticleSystems			= SparkSys,SmallGreySSys
DamageSmokeOffset			= 0, 0, 550
Explosion				= defd_exp
MaxDebris				= 30
;----- Veterancy -----
EliteAbilities				= SENSORS
;----- Power ----
PoweredBy				= CBCOR

;------------------------------------------------------------------------------
; auxiliary entity: 
; Core defender explosion
; [DEFD_EXP] (fs)
[ExplosionWlkrSentinel]
Normalized				= yes
Rate					= 350
Report					= EXPNEW05
Next					= TWLT100

;------------------------------------------------------------------------------
; Deployed Core Defender
; [DDEFD]
[
$inherits				= 
;----- Text -----
Name					= Defender (Deployed)
;----- Gfx -----
; Image					= DEFD				; No longer needed, this now loops back to its own entry. 
Remapable				= yes				; artfs.ini/DEFD entry. 
Buildup					= DEFDMK			; artfs.ini/DEFD entry. 
DemandLoadBuildup			= yes				; artfs.ini/DEFD entry. 
;----- Body -----
Strength				= 9999
Foundation				= 2x2				; artfs.ini/DEFD entry. 
Height					= 1				; artfs.ini/DEFD entry. 
;----- Perception -----
Sight					= 6
Sensors					= yes
;----- Armor -----
Armor					= concrete
Immune					= yes
;----- Availability -----
Cost					= 10000
Adjacent				= 2
;----- Score -----
Points					= 10000
;----- Damage & Destruction -----
DamageParticleSystems			= SparkSys,SmallGreySSys,BigGreySmokeSys
DamageSmokeOffset			= 375, 550, 500
Explosion				= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris				= 10
;----- Load -----
UndeploysInto				= DEFENDER
