;
;
;
; Liberty Defender, Truth Defender, Avatar, Caturhasta Avatar. 

;------------------------------------------------------------------------------
; Core Defender
[DEFENDER]
;----- Text -----
Name					= Core Defender
UIName					= name:
UIDescription				= desc:
;----- Taxonomy -----
Category				= AFV
NonVehicle				= yes				; new
Organic					= yes				; new
Cyborg					= yes				; new
IsCoreDefender				= yes				; new
;----- Body -----
Strength				= 10000
SelfHealing				= yes				; SelfHealing to TS standard. 
Size					= 30				; arbitrarily high
Weight					= 35				; 3.5
;----- Weapons -----
Primary					= DEFOB
NoMovingFire				= yes
;----- Armor -----
Armor					= heavy, skin_mut_tib, cyborg	; heavy
TiberiumProof				= yes
TiberiumHeal				= yes
ImmuneToVeins				= yes
; ImmuneToPoison			= yes
; ImmuneToRadiation			= yes
ImmuneToPsionics			= yes				; new
;----- Perception -----
Sight					= 9
;----- Movement -----
Speed					= 5
ROT					= 5
MovementZone				= Destroyer
Locomotor				= {55D141B8-DB94-11d1-AC98-006008055BB5}
WalkRate				= 4
Crusher					= yes
MoveToShroud				= yes
;----- Availability -----
Owner					= Legion			; CABAL, was Civilian. 
TechLevel				= 
Cost					= 2000
AllowedToStartInMultiplayer		= no
CrateGift				= no
CrateGoodie				= no
;----- Score -----
Points					= 40
;----- AI -----
ThreatPosed				= 50
;----- Damage & Destruction -----
DamageParticleSystems			= SparkSys,SmallGreySSys
DamageSmokeOffset			= 0, 0, 550
Explosion				= defd_exp
MaxDebris				= 30
;----- Veterancy -----
EliteAbilities				= SENSORS
