;******************************************************************************
;*** Lynx Tank ****************************************************************
;******************************************************************************
; Tank Type 15 Lynx
; Has upgrades: 
;	Armor III (Raise HP from 300 to 350), 
;	Sight (Raise Sight from 4 to 8). 
; Eligible for 
;	Auxiliary Drone, 
;	Nanite Repair, 
;	Autoloader, 
;	Charged Shot. 
; Ineligible upgrades: 
;	ATGM, 
;	Sniper, 
;	Machine Gun. 
; (Ineligible upgrades can still be granted from Crates or Scientists). 
; These tanks have less HP (350 vs 400, just 12.5%) than "Pigs", but do more damage (65 vs 60). 
; These differences are marginal, but one possible way to use them effectively is to use "Pigs" as "tank tanks" that tank enemy fire, while the Lynxes DD. 
; The greater (heavier) is the T-55 "Iron Pig". 
; The lesser (lighter) is the Tank Amphibious "Gavial". 
; This is neither the T-55, nor the Tank Amphibious, now. 


Machine Gun, Faster, Sensors. 

;------------------------------------------------------------------------------
[VehicleTypes]
;CAAEDD47B171D
+				= TnkLynx
+				= TnkLynx_a1
+				= TnkLynx_a2

BuildTimeMultiplier=1.5 ;Individual control of build time

;------------------------------------------------------------------------------
; Lynx Tank
; ER's LYNX (Lynx Tank)
; Also in RotE. 
; Formerly [LYNX], [LynxTank], [TankLynx], [TnkLynx]. 
[TnkLgtLynx]
$Inherits			= TnkLgt
;----- Text -----
Name				= Tank Light Lynx
UIName				= name:tnk_lynx
UIDescription			= desc:tnk_lynx
;----- Gfx -----
Image				= Lynx
; Insignia.Elite		= pip_lynx_elite
;----- Body -----
Strength			= 350			; ER, Tank Light is 300, Tank Jigsaw is 325, Tank Liberator is 370. 
							; Was 300 (Light Tank), 200, 220. ; Switch with Hover Tank. Was 180. Adapted from Robot Tank - previous 200 might have been mal-copied from Mirage Tank or IFV	; 300 for Light Tank
; ER defaults Weight to 3.5, which it can inherit. 
; Weight			= 2.5 
;----- Turret -----
TurretAttach			= LynxTurret
;----- Availability -----
; Asian vehicles should have no BuildTimeMultiplier (greater than 1). 
Owner				= Alliance
House				= Alliance, Chinese, Japanese, Koreans
TechLevel			= 3
Prerequisite			= AAFactory
AllowedToStartInMultiplayer	= yes
Cost				= 800;600;500				; 700 for Light Tank ; 800
BuildTimeMultiplier		= 1.5
Soylent				= 800;600				; 700 ; 800
; CrateGoodie			= no					; ER

Side				= Terran
; House				= 
TechLevel			= 2
; Prerequisite.RequiredTheaters	= temperate, urban, newurban
; Cost				= 600

;----- Weapons -----
Primary				= Cannon105mm_2				; ER's ATGUN & ATGUNAT ; Cannon90mm;75mm
; Secondary			= TargetLaserWeapon
ElitePrimary			= Cannon105mm_2E			; ER's ATGUNE & ATGUNATE ; Cannon90mmE;75mmE
; TargetLaser			= yes
;----- Procuration -----
Owner				= Alliance,Chinese,Japanese,Koreans,InfantryArmy,
Prerequisite			= AAFactory
; Prerequisite.RequiredTheaters	= TEMPERATE,URBAN,NEWURBAN
; Prerequisite.RequiredTheaters	= DESERT
; Prerequisite.RequiredTheaters	= SNOW
TechLevel=2
;----- Score -----
Points=25

MaxDebris=3
ThreatPosed=15	; This value MUST be 0 for all building addons
;----- AI -----
IsSelectableCombatant		= yes
ThreatPosed=40

IsGattling=yes
Gattling.Cycle=yes

TurretCount=1

WeaponCount=4

; 1st stage
Weapon1				= 90mm
Weapon2				= 90mm
EliteWeapon1			= DroneLauncher
EliteWeapon2			= DroneLauncher

; 2nd stage
Weapon3				= 90mm
Weapon4				= 90mm
EliteWeapon3			= 90mmE
EliteWeapon4			= 90mmE

WeaponStages=2
Stage1=1
Stage2=1000
EliteStage1=1
EliteStage2=1000

RateUp=1
RateDown=0

;----- Armor -----
Armor				= medium	; ER ; heavy
TechLevel=2
;----- Perception -----
Sight				= 8				; Has Sight upgrade. 
;----- SFX -----
VoiceSelect				= SelectTankLynx
VoiceMove				= CmdMovTankLynx
VoiceAttack				= CmdAtkTankLynx
; VoiceFeedback				= FearTankLynx
MoveSound				= LasherTankMoveStart
;----- Damage & destruction -----
Explosion				= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DamageParticleSystems			= SparkSys,SmallGreySSys
DamageSmokeOffset			= 100, 100, 275
MaxDebris=3
MinDebris=1
DebrisTypes				= TnkLgtLynx, TnkLgtLynxTur, TnkLgtLynxBarl, ShellMM75Puls, gastank, piece
					; LYNX, LYNXTUR, GASTANK, PIECE
DebrisMinimums=1,0,1,1
DebrisMaximums=1,1,1,2
;----- Movement -----
Speed				= 7;8;10
ROT				= 5; ER, was 10. Not sure what 10 was from. 

ThreatPosed=15

;----- Veterancy -----
VeteranAbilities			= STRONGER,FIREPOWER,SIGHT,FASTER;,SENSORS
EliteAbilities				= SELF_HEAL,STRONGER,FIREPOWER,ROF;,CLOAK_STOP,CRUSHER

;----- Spawn -----
Spawns					= Dragonfly
SpawnsNumber				= 1
SpawnRegenRate				= -1
SpawnReloadRate				= 250


; Perception
Sight=10;8;6

; Scoring
Points=25

; Controls
IsSelectableCombatant=yes
Landable=yes

;------------------------------------------------------------------------------
; Lynx Tank with upgrade Autoloader. 
[TnkLgtLynxA]
;----- Text -----
Name				= Lynx Tank (Upg.: Autoloader)
;----- Weapons -----
Primary				= CannonMM90x3
;----- Load -----
Ammo				= 3

;------------------------------------------------------------------------------
; Lynx Tank with upgrade Drone. 
; Formerly LynxTank_a1, [TankLynxTa1]. 
[TnkLgtLynxD]
;----- Text -----
Name				= Tank Light Lynx (Upg. Drone)
;----- Load -----
InitialPayload.Types		= DummyDrone
OpenTopped			= yes
;----- Procuration -----
Prerequisite			= AAFactory,TechDrone

;------------------------------------------------------------------------------
; Lynx Tank with AutoRepair Upgrade
; Formerly LynxTank_a2, LynxTankTa2.  
[TnkLynx_b1]:[LynxTank]
SelfHealing			= yes

;------------------------------------------------------------------------------
; Lynx Tank with 
[LynxTank_a3]
IsTilter=yes
TooBigToFitUnderBridge=true
TechLevel=2
Sight=8;6
Speed=7;8
CrateGoodie=no
Crusher=yes
Owner=YuriCountry,Alliance,Empire
Cost=700;600
Soylent=700
Points=25
ROT=5
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=LasherTankSelect
VoiceMove=LasherTankMove
VoiceAttack=LasherTankAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=LasherTankMoveStart
CrushSound=TankCrush
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=100, 100, 275
Weight=3.5
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
;ZFudgeColumn=8
;ZFudgeTunnel=13
Size=3
OpportunityFire=yes
BuildTimeMultiplier=1.5;Individual control of build time

