
; [CITY16] (ts)
[CAHOTL]
;----- Text -----
Name=Highrise Hotel
TechLevel=-1
Strength=500
Insignificant=yes
Nominal=yes
RadarInvisible=yes
Points=5
Armor=wood
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=8
DamageParticleSystems=SmallGreySSys,BigGreySmokeSys
IsBase=no
