;
;
;

;------------------------------------------------------------------------------
[Warheads]
+				= Water

;------------------------------------------------------------------------------
; Tsunami strikez
[Water]
; Verses			= 40%,20%,140%,260%,100%
AnimList			= H2O_EXP3,H2O_EXP2,H2O_EXP1
