;
;
;
; Forgotten's mobile refinery

;------------------------------------------------------------------------------
[VehicleTypes]
+				= RfnyMob
+				= RfnyMob_b

;------------------------------------------------------------------------------
[BuildingTypes]
+				= RfnyMobD
+				= RfnyMobD_b

;------------------------------------------------------------------------------
; Mobile Tiberium Refinery [DPROC] (TS Gold)
[RfnyMob]:
;----- Text -----
Name				= Refinery Mobile
UIName				= name:rfny_mob
UIDescription			= desc:rfny_mob
;----- Gfx -----
Image				= SUBTANK
ZFudgeColumn			= 8
ZFudgeTunnel			= 15
;----- Taxonomy -----
Category			= Support
;----- Body -----
Strength			= 400
Weight				= 3.5
Size				= 3; smin
ClickRepairable			= no						; Neither ClickRepairable, nor inherits SelfHealing from [SMIN]. Has to be repaired by Mechanic or vehicle. 
;----- Armor -----
Armor				= heavy
OmniCrushResistant		= yes						; Not included in TS Gold, but consistent with mobile buildings, and SMIN in particular. 
Parasiteable			= no
; ImmuneToVeins			= yes
ImmuneToPsionics		= yes
ImmuneToRadiation		= yes
;----- Perception -----
Sight				= 6
;----- Availability -----
Side				= Terran
Owner				= 
House				= 
RequiredHouses			= 
ForbiddenHouses			= 
SecretHouses			= 
TechLevel			= 6
Prerequisite			= DEPOT						; REFINERY, CENTER_TEK ; PROC, GATECH
Cost				= 1000
AllowedToStartInMultiplayer	= no
CrateGift			= yes
CrateGoodie			= yes
;----- Score -----
Points				= 20
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
VoiceSelect=SlaveMinerSelect
VoiceMove=SlaveMinerMove
VoiceAttack=SlaveMinerAttackCommand
VoiceHarvest=SlaveMinerHarvest
DieSound=GenVehicleDie
MoveSound=SlaveMinerMoveStart
CrushSound=TankCrush
DeploySound=SlaveMinerDeploy
VoiceDeploy=SlaveMinerDeployVoice
;----- Movement -----
ROT					= 5
Speed					= 5
Locomotor				= Drive
MovementZone				= Crusher
Crusher					= yes
Bunkerable				= no
;----- Load -----
Crewed					= yes
Storage					= 0				; Refinery, but no storage. 
DeploysInto				= RfnyMobD
DeployFacing				= 0
;----- AI -----
ThreatPosed				= 0
; moving brain to refinery to start
; Ugh.  Now that placed as building, problem arises from managing to get a SMIN as vehicle (Campaign map, crate).  Both get this listing now, and Brain transplant will check to make sure extra one is not created
ResourceGatherer			= yes
ResourceDestination			= yes
ToProtect				= yes; new
StupidHunt				= yes
;----- Damage & Destruction -----
DamageParticleSystems			= SparkSys, SmallGreySSys
Explosion				= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
; debris was rewritten
DebrisTypes				= 
DebrisMinimums				= 
DebrisMaximums				= 
MinDebris				= 
MaxDebris				= 

;------------------------------------------------------------------------------
[RfnyMob_b]
$Inherits				= RfnyMob
;----- Text -----
Name					= Refinery Mobile (No Harvester)
;----- Load -----
DeploysInto				= RfnyMobD_b

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Deployed Tiberium Refinery [PROC2] (TS Gold)
; TS Gold had Cost = 20, which makes no sense at all (adversely impacts veterancy). 
[RfnyMobD]
$Inherits				= RfnyMob
;----- Text -----
Name					= Refinery Mobile (Deployed)
;----- Gfx -----
Image					= NAREFN
;----- Taxonomy -----
IsBase					= no					; TS Gold omitted
BaseNormal				= no					; these two. 
Refinery				= yes
;----- Body -----
Bib					= yes
;----- Armor -----
Spyable					= yes
Capturable				= yes					; PROC2 is yes, YAREFN is no. 
;----- Availability -----
TechLevel				= -1
Adjacent				= 2
Unsellable				= yes					; Can be sold as a vehicle, but the building cannot be sold. 
;----- Score -----
Points					= 80
;----- Load -----
; FreeUnit				= HARV
FreeUnit				= LT_HARV
DockUnload				= yes
UndeploysInto				= RfnyMob_b				; The version which already has released its harvester. ; dproc
;----- UI -----
BuildCat				= Resource
TogglePower				= no
;----- AI -----
AIBuildThis				= yes					; So AI will construct this as a building (even though players can't). 
AIBasePlanningSide			= 2
;----- UI -----
BuildCat				= Resource
;----- Damage & Destruction -----
DamageParticleSystems				= SparkSys,SmallGreySSys,BigGreySmokeSys
DamageSmokeOffset				= 410, 100, 165
HalfDamageSmokeLocation1			= 0, 0, 0
DebrisAnims					= DBRIS1LG,DBRIS1SM,DBRIS4LG,DBRIS4SM,DBRIS5LG,DBRIS5SM
MaxDebris					= 8;10
; MinDebris=5

;------------------------------------------------------------------------------
; Version that has released its harvester. 
[RfnyMobD_b]
$Inherits					= RfnyMobD
;----- Load -----
UndeploysInto					= RfnyMobD_b
FreeUnit					= none
