;******************************************************************************
;*** Magician *****************************************************************
;******************************************************************************
; Promotes from Initiate. 

;------------------------------------------------------------------------------
[InfantryTypes]
+= Mage
+= Mage_

;------------------------------------------------------------------------------
; Magician [MAGI] from Justin Pereira's TechWar. 
[Mage]
;----- Text -----
Name				= Magician
UIName				= name:mage
UIDescription			= desc:mage
;----- Taxonomy -----
Category			= Soldier
;----- Body -----
; Strength			= 300				; tw 1.7
;----- Weapons -----
Primary				= Magic
;----- Perception -----
Sight				= 7
;----- Movement -----
MovementZone			= InfantryDestroyer
Speed				= 4
;----- Availability -----
Owner				= Neutral			; GDI
DoubleOwned			= yes
TechLevel			= 9
Prerequisite			= ; gapile, gatech

;------------------------------------------------------------------------------
; Arch Mage
[Mage2]

CrushSound=SQUISH6
Pip=green
Sight=7
Speed=4
Owner=GDI
Cost=1100
Points=5
VoiceSelect=15-I000,15-I004,15-I012,15-I048
VoiceMove=15-I018,15-I024,15-I044
VoiceAttack=15-I044,15-I050,15-I044,15-I046
VoiceFeedback=15-I058,15-I064
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
ThreatPosed=15
ImmuneToVeins=yes
Image=TRATOS
BuildLimit=1
EliteAbilities=FASTER,STRONGER,FIREPOWER,SCATTER,ROF,SIGHT,SELF_HEAL


; Magic used by the magician
; [Magic] (tw 1.7)
; This is not really non-elemental (non-elemental would not have a warhead). 
[Blast]
;----- Payload -----
Damage				= 500
AmbientDamage			= 400
DamageType			= MAGIC
Warhead				= 
;----- 
ROF=50
Range=2
Projectile=Invisible
Speed=30
Warhead=magicWH
AttachedParticleSystem=LGSparkSys
Report=scrin5b
Bright=yes


; Warhead for magician's magic
[MagicWH]
Spread=15
Verses=100%,100%,100%,100%,100%
InfDeath=5
Tiberium=yes
ProneDamage=100%
Sparky=yes
Wood=yes
Wall=yes
Rocker=yes
Bright=no
