;******************************************************************************
;*** Shiranui *****************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[VehicleTypes]
+				= ShiranuiFrigate

;------------------------------------------------------------------------------
; Frigate
[Frig]:[Corv]
;----- Text -----
Name				= Frigate
UIName				= name:frig
UIDescription			= desc:frig
;----- Body -----
Strength			= 600
Weight				= 3
Size				= 20
;----- Weapons -----
Primary				= CannonMM100X3
Secondary			= Friggapult
;----- Perception -----
Sight				= 7
Sensors				= yes
SensorsSight			= 8
;----- Sfx -----
VoiceSelect=GenAllWaterSelect
VoiceMove=GenAllWaterMove
VoiceAttack=GenAllWaterAttackCommand
VoiceFeedback=
SinkingSound=GenLargeWaterDie
MoveSound=DestroyerMoveStart
SinkingSound=GenLargeWaterDie
DieSound=GenSmallWaterDie 
MoveSound=DestroyerMoveStart; SeawolfMoveStart 

;------------------------------------------------------------------------------
; Sea Wraith
; Formerly SWRA, SEAW (SeaWraith), [ShiranuiFrigate]. 
[FrigShiranui]:[Frig]
;----- Text -----
Name				= Sea Wraith
UIName				= name:frig_shiranui			; shiranui
UIDescription			= desc:frig_shiranui
;----- Body -----
Strength			= 340
; SelfHealing			= yes					; Uncertain origin. 
;----- Turret -----
Turret				= no
;----- Weapons -----
Primary				= ShiranuiRktLnchr; SSMissile; RedEye2
Secondary			= ShiranuiRktLnchr_AA; RedEye2
ElitePrimary			= ShiranuiRktLnchr_AA; SSMissileE
EliteSecondary			= ShiranuiRktLnchr_AA_E
FireAngle=64
TargetLaser=yes

Primary=HoverMissile2 
Secondary=HoverMissile 
ElitePrimary=HoverMissile2e 
EliteSecondary=HoverMissilE 

;----- Availability -----
Side				= Alliance
Owner				= Alliance				; Alliance,Chinese,Japanese,Koreans,InfantryArmy,WalkerArmy,Room121,CyborgArmy,NinjaClan
; House				= 
; RequiredHouses		= 
; ForbiddenHouses		= 
; SecretHouses			= 
TechLevel			= 4;8
Prerequisite			= AAShipyard,AACommCenter
AllowedToStartInMultiplayer	= no
CrateGoodie			= yes

;----- Load -----
Crewed				= yes
;----- SFX -----
VoiceSelect=ShiranuiSelect
VoiceMove=ShiranuiMoveCommand
VoiceAttack=ShiranuiAttackCommand
VoiceFeedback=

;----- Stealth -----
RadarInvisible			= yes

Weight=3.5
ThreatPosed=40	; This value MUST be 0 for all building addons
ZFudgeColumn=9
ZFudgeTunnel=15

Sight=7
Speed=6


Sight=6
Speed=4
Points=60
ROT=5
Crusher=yes

Cost=1500
Points=30
Weight=3

ThreatPosed=15	; This value MUST be 0 for all building addons

TooBigToFitUnderBridge=true
OpportunityFire=yes
Size=20;30

Strength=400 
TechLevel=6 
Sight=8 
Speed=8 
Cost=600 
Points=20 
ROT=6 
Weight=2 
ThreatPosed=25	; This value MUST be 0 for all building addons 
NavalTargeting=1


; [ASWBomblet]
[Friggapult]
;----- Payload -----
Damage				= 30
Warhead				= HESplash
;----- Sequence -----
ROF				= 60
Burst				= 3
Burst.NoDelay			= yes
;----- Projection -----
OmniFire			= yes
Range				= 4
Projectile			= DepthCharge
ProjectileRange			= 8
Speed				= 30
Lobber				= yes
;----- Sfx -----
Report				= FlakTrackAttackGround
OmniFire=yes
