
;------------------------------------------------------------------------------
[Gryphon]
;----- Text -----
Name				= Gryphon
UIName				= name:gryphon
UIDescription			= desc:gryphon
;----- Taxonomy -----
Category			= AirPower
ConsideredAircraft		= yes
;----- Body -----
Strength			= 260
;----- Weapons -----
Primary				= GryphMislLnchrs
Secondary			= GryphChaingun
ElitePrimary			= GryphMislLnchrs2
EliteSecondary			= GryphChaingun2
;----- Scoring -----
Points=20;30

;----- AI -----
ThreatPosed=25



;----- Perception -----
Sight				= 2

;----- Dock -----
Dock				= UNAirPad,MobileAirPad_Deployed,SVAirPad,EUAirPad,AAAirPad,CVAerodrome

;----- Movement -----
PitchSpeed				= .16
MoveToShroud			= no
Points=20
ROT=5
Landable				= yes


MaxDebris=4

Locomotor={4A582746-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly
ThreatPosed=25

EliteAbilities=RADAR_INVISIBLE
Elite=ClusterBomb

;Spawned=yes
LeadershipRating=10
Selectable=yes

CanPassiveAquire=no
CanRetaliate=no
FlyBy=yes

ThreatAvoidanceCoefficient=1.0
LeadershipRating=10
Selectable=yes
;----- Sfx -----
VoiceSelect=30-I000,30-I002,30-I004,30-I006
VoiceMove=30-I014,30-I016,30-I018,30-I022
VoiceAttack=30-I022,30-I030,30-I034,30-I036
DamageParticleSystems=SparkSys,SmallGreySSys

;----- Veterancy -----
EliteAbilities=RADAR_INVISIBLE

MoveToShroud=yes
Dock=GADROP
PipScale=Ammo
Speed=12
PitchAngle=0
PitchSpeed=.16
;Cost=1600
Points=20
ROT=5
Ammo=2
Crewed=yes
GuardRange=30

;------------------------------------------------------------------------------
; FAIBOMBER (ORCA Fuel-Air Implosive Bomber)
; The original inspiration for the Flamingo Bomber - we found it again! 
[FlamingoBomber_E]
;----- Text -----
Name=Elite Flamingo Bomber;Orca Fuel-Air Implosion Bomber
Prerequisite=GAHPAD,GATECH,ARC

;----- Body -----
Strength				= 500
;----- Weapons -----
Primary=FAIB
Secondary=RedEye2   ;added to give them air-to-air attack
;----- Armor -----
Armor					= heavy
;----- Availability -----
TechLevel				= 10
Cost					= 3000

Sight=2
RadarInvisible=no
Landable=yes
MoveToShroud=no
Dock=GAHPAD,NAHPAD
PipScale=Ammo
Speed=16
PitchSpeed=.16
Points=20
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=4

AuxSound1=ORCAUP1	;Taking off
AuxSound2=ORCADWN1	;Landing
EliteAbilities=RADAR_INVISIBLE

;------------------------------------------------------------------------------
; TechWar's advbomber (Advanced Bomber)
; Formerly [ZhuqueBomber] ([FlamingoBomber] variant), now returned to a Gryphon variant. 
[Gryphon3]:[Gryphon2]
;----- Text -----
Name				= Gryphon
;----- Body -----
Strength			= 600
;----- Weapons -----
Primary				= advbomb
;----- Availability -----
TechLevel			= 8
Cost				= 3500
;----- Movement -----
Speed				= 12
;----- Load -----
Ammo				= 5
;----- Damage & Destruction -----
MaxDebris			= 28
;----- Veterancy -----
EliteAbilities=FASTER,STRONGER,FIREPOWER,SCATTER,ROF,SIGHT,SELF_HEAL

