;******************************************************************************
;*** Siege Tripod *************************************************************
;******************************************************************************
; Kitbashed from Mental Omega and Robot Storm. 
; This unit starts on Epic level. 

;------------------------------------------------------------------------------
[VehicleTypes]
+				= Centurion
+				= Centurion_2
+				= Centurion_3
+				= Centurion_4

;------------------------------------------------------------------------------
; Centurion: Voxel from YRArg, not ripped from MO!!! 
; Doesn't include the use of those aa guns on the turret's 'roof'. 
; Formerly [CNTR], [Centurion]. 
[WlkrSieg]
;----- Text -----
Name				= Walker Siege
UIName				= name:walker_siege
UIDescription			= desc:walker_siege
;----- Taxonomy -----
Category			= LRFS			; This used to be AFV - despite being hero unit, the LRFS setting is more accurate. 
;----- Body -----
Strength			= 1200			; Robot Storm
SelfHealing			= yes
Size				= 16
;----- Weapons -----
Primary				= Cannon_
Secondary			= VirtualScanner
ElitePrimary=CenturionCannonE
;----- Turrets -----
Turret				= yes
;----- GFX -----
IsSelectableCombatant		= yes
PixelSelectionBracketDelta	= 40
PipScale			= Passengers
Insignia.Rookie			= epic_sov		; new
;----- Armor -----
Armor				= heavy
Warpable			= no
OmniCrushResistant		= yes
ImmuneToVeins			= yes
ImmuneToPoison			= yes
ImmuneToPsionics		= yes
ImmuneToRadiation		= yes

IsTilter			= yes
TooBigToFitUnderBridge=true
TechLevel=10

;----- Perception -----
Sight				= 6			; Robot Storm
;----- Load -----
Passengers			= 3
SizeLimit			= 1
OpenTopped			= yes
;----- Availability -----
Side				= Soviet
Owner				= Soviet
; House				= 
Prerequisite			= SVFactory,SVTechCenter
Cost				= 1950
BuildLimit			= 1
CrateGoodie			= no
AllowedToStartInMultiplayer	= no
;----- Scoring ----- 
Points				= 200
;----- Sfx -----
VoiceSelect			= CenturionSelect
VoiceMove			= CenturionMoveCommand
VoiceAttack			= CenturionAttackCommand
VoiceFeedback			= 
DamageSound			= VehicleDamagedHeavy
EnterTransportSound		= EnterTransport
LeaveTransportSound		= ExitTransport
CreateSound			= CenturionCreated
MoveSound			= CenturionMoveLoop
DamageSound			= VehicleDamagedHeavy
DieSound			= NukeExplosion
;----- Movement -----
Speed				= 3
ROT				= 2
Locomotor			= {55D141B8-DB94-11d1-AC98-006008055BB5}	; <--- mech    drive ---> {4A582741-9839-11d1-B709-00A024DDAFD1} 
MovementZone			= CrusherAll
Accelerates			= no
Crusher				= yes
OmniCrusher			= yes
;----- AI -----
CanPassiveAquire		= yes
ThreatPosed			= 40
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys,SmallGreySSys
DamageSmokeOffset		= 100, 100, 275
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris			= 16
MinDebris			= 8
Weight=3.5
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
ZFudgeColumn=8
ZFudgeTunnel=13


BuildTimeMultiplier=1.25
BuildTimeMultiplier=1.325

;----- Power -----
; let's see if these work on units:  
Powered				= true 
PoweredUnit			= yes;powered by presence of building 
PoweredBy			= SVCommCenter
Power=-750 
ExtraPower=-1000 
Overpowerable=true 
TogglePower=yes 

;------------------------------------------------------------------------------
; Centurion 2nd Edition
; Formerly [Centurion_2]. 
[WlkrSieg2]:[WlkrSieg]
;----- Text -----
Name				= Walker Siege Mk. II
;----- Body -----
Strength			= 2300
;----- Perception -----
Sight				= 7
;----- Movement -----
Speed				= 4
;----- Availability -----
Cost				= 3500

;------------------------------------------------------------------------------
; Centurion 3nd Edition
[Centurion_3]:[Centurion]
;----- Health -----
Strength			= 3200

;----- Perception -----
Sight				= 8

;----- Procuration -----
Cost				= 4000
BuildLimit			= 2

;----- Scoring -----
Points				= 300

Centurion Siege Crawler Atomic Edition
4100


NukeCannon
CenturionNuke
CenturionAAGun
NukeCannonE
Heavy

;------------------------------------------------------------------------------
; Centurion Siege Walker Black Edition
[Centurion_4]:[Centurion_2]
UIName				= Name:BCNTR 
Name				= Centurion Siege Crawler Black Edition 
Prerequisite=NATECH,GATECH,CARUS03 
NegativePrerequisite=NATECH

;----- Weapons -----
Primary				= CenturionRailgun
Secondary				= Gattling

ElitePrimary				= CenturionRailgunE

SiegeLaser
SiegeAALaser

;----- Health -----
Strength=5000 
TechLevel=-1
Sight=10 
Speed=4  
Cost=5000 
Points=500 
Sensors=yes 
SensorsSight=10 
ROT=3
AllowedToStartInMultiplayer=no 
Explosion=PDFXCLD,TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60 
MinDebris=8 
DebrisTypes=CENTURRET,PIECE 
DebrisMaximums=1,15	; sum 16 
DebrisMinimums=1,7	; sum 8
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF,CLOAK 
BuildLimit=-1 
BuildTimeMultiplier=1.1 

