;******************************************************************************
;*** Pursuer ******************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[InfantryTypes]
+				= Pursuer

;------------------------------------------------------------------------------
; Lt. Scott Michael
[ScottMichael]:[Civilian]
Category=VIP
Armor=BPV
Pip=yellow
OccupyPip=PersonYellow

;------------------------------------------------------------------------------
; Hunter-Killer
; Formerly [TYRT]. 
; Differs from the Cyborg Gunner in that it is _also_ a mutant. 
[Pursuer]:[Zombie]
;----- Text -----
Name				= Pursuer
UIName				= desc:pursuer
UIDescription			= desc:pursuer
Nominal				= yes
UseOwnName			= yes
;----- Gfx -----
; Image				= ARND
;----- Taxonomy -----
Category			= Soldier
Unnatural			= yes
NotHuman			= yes
Cyborg				= yes

;----- Body -----
Strength			= 350						; 325
Size				= 2
SelfHealing			= yes
;----- Weapons -----
Weapon1				= RivetGun
IFVMode				= BIOGUN
IFVMode				= MISSILE
OccupyWeapon			= 
EliteOccupyWeapon		= 
;----- Armor -----
Armor				= skin_mutant, flak				; plate ; light
Crushable			= no
ImmuneToVeins			= no
ImmuneToPsionics		= yes
ImmuneToPsionicWeapons		= no
; ImmuneToRadiation		= yes
; ImmuneToPoison		= yes
; Parasiteable			= no
TiberiumProof			= yes
TiberiumHeal			= yes
;----- Perception -----
Sight				= 5						; 9
;----- Load -----
Ammo				= 10
;----- Availability -----
Owner				= Nod
Prerequisite			= NAHAND, NATECH
Cost				= 2500
BuildLimit			= -1						; 1 ; Moved to Pursuer Commander. 
AllowedToStartInMultiplayer	= no
;----- Score -----
Points				= 10
;----- UI -----
PixelSelectionBracketDelta	= -6
IsSelectableCombatant		= yes
;----- AI -----
ThreatPosed			= 30
Fearless			= yes
BerzerkAllowed			= yes
;----- Sfx -----
VoiceSelect			= SelectZombie
VoiceMove			= CmdMovZombie
VoiceAttack			= CmdAtkZombie
VoiceFeedback			= 
DieSound			= DieZombie
; CrushSound			= InfantrySquish				; squishy2
;----- Movement -----
Speed				= 5						; 6
MovementZone			= InfantryDestroyer
;----- Veterancy -----
Trainable			= no
EliteAbilities			= STRONGER
;----- Damage & Destruction -----
DamageParticleSys		= SysDropletsGreen
Explodes			= yes
; Explosion			= explosion_liquid_green			; biotexp
DeathWeapon			= Explode_Pursuer				; TyrantExplosion



;------------------------------------------------------------------------------
[Pursuer2]:[Pursuer]
;----- Text -----
Name				= Pursuer Lv. 2
;----- Weapons -----
Weapons				= Vulcan3
Weapon1				= Vulcan3

LeadershipRating=8
Sight=8
Speed=5
Cost=2100
Soylent=650
Points=50
ThreatPosed=25	; This value MUST be 0 for all building addons
SpecialThreatValue=1

;------------------------------------------------------------------------------
[Pursuer3]
;----- Text -----
;----- Weapons -----
Weapons				= Vulcan3, LnchrMislStinger
Weapon1				= Vulcan3
Weapon2				= LnchrMislStinger				; MultiCluster
; Primary			= Vulcan3
; Secondary			= LnchrMislStinger

;------------------------------------------------------------------------------
; Terminator Commander
; Formerly [Pursuer_Commander]. 
; This unit has all weapon upgrades of the Pursuer line, but still lacks armor. 
[Pursuer3]:[Pursuer2]
;----- Text -----
Name				= Pursuer Commander
UIName				= Name:Pursuer_Commander

;----- Weapons -----
Primary					= PursuerRocketLauncherE			; SuperCluster
Secondary				= PursuerLaserGun
Strength				= 450
Armor=heavy
TechLevel=10
Sight=7
Speed=3
Cost=3200
ThreatPosed=50
EliteAbilities=FIREPOWER

;------------------------------------------------------------------------------
; Penetrator
; Formerly [PursuerDriller]. 
; This unit has heavy armor, but no firearm (it has a drill). 
[Protector]
;----- Text -----
Name				= 
UIName				= name:
UIDescription			= desc:
;----- Body -----
Armor				= 500
;----- Weapons -----
Primary				= Drill
IFVMode				= DRILL
;----- Availability -----
Cost				= 1100
;----- Armor -----
Armor				= skin_mutant, plate

Prerequisite			= Habitat_A
AltPrerequisite			= Habitat_B
Pip				= rust
OccupyPip			= PersonRust
Sight				= 5
Speed				= 4
;----- AI -----
ThreatPosed			= 30

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Formerly Pursuer Commander. 
; Weapon upgrade: laser, missile, flamethrower
; Armor upgrade: armor
; I. e. this unit is the cross-product of the Pursuer, and the Protector. 
; Mutant cyborg (heavy armor) with long-ranged weapons. 
; I.e. this unit's CLASS is Cyborg Gunner, but the RACE is Mutant. 
[Plumbator]
;----- Text -----
Name					= Plumbator
UIName					= name:plumbator
UIDescription				= desc:plumbator
;----- Gfx -----
Image					= FTHROW
;----- Weapons -----
Weapons					= GatLaser,LnchrMislStinger,Flamethrower
Weapon1					= GatLaser
Weapon2					= LnchrMislStinger
Weapon3					= Flamethrower
Weapon4					= BioBomb

Prerequisite=NAHAND,NATECH
PrerequisiteOverride=CARUS01,CARUS03	; Any russian monument is sufficient to train Molotov

Deployer=yes
DeployFire=yes
UndeployDelay=10
LeadershipRating=8
CrushSound=InfantrySquish
Crushable=no
Strength=500
Armor=Plate
TechLevel=10
Pip=red
Sight=8
Speed=5
AllowedToStartInMultiplayer=no
Cost=2100
Soylent=650
Points=50
IsSelectableCombatant=yes
ThreatPosed=25	; This value MUST be 0 for all building addons
SpecialThreatValue=1
ImmuneToVeins=yes
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,SCATTER,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF,FASTER,CLOAK ; cloak is new
Size=1
IFVMode=13 ;This is the hidden/hero mode. Was '4' (for some reason).
DamageParticleSys=SparkSys
Explodes=yes
Explosion=TWLT100
DeathWeapon=BarrelExplosion

; Rivet Gun
[TyrantGun]
;----- Payload -----
Damage				= 30
Warhead				= Rivet

ROF				= 40
Burst				= 3
Range=6
Projectile=InvisibleLow
Speed=100
Warhead=TyrantWH
Report=ArnoldAttack
AssaultAnim=UCBLOOD;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)

; Rivet
[Rivet]:[SA]
InfDeath			= 1
AnimList			= s_bang34
Bullets				= yes
ProneDamage			= 0.55
AttachEffect.SpeedMult		= 0.80

; clone of (ARNIEWH)
[TyrantEWH]
Verses=200%,200%,100%,50%,50%,50%,75%,50%,25%,100%,100%
InfDeath=1
AnimList=PIFFPIFF,PIFFPIFF
Bullets=yes
ProneDamage=70%

Damage=80
ROF=40
Projectile=AAHeatSeeker3
Speed=30 ;40
Warhead=TyrantWH2
Report=GuardianGIDeployedAttack
MinimumRange=1

; Formerly [TyrantMissile]. 
[PursuerRocketLauncher]
Damage				= 80
ROF				= 250
Range				= 8
Projectile			= PursuerRocket
Speed				= 30
Warhead				= HE
Report				= RocketTakeoff1
MinimumRange			= 1

[PursuerRocketLauncherE]:[PursuerRocketLauncher]
Damage				= 30
Projectile			= PursuerRocketE

[PursuerRocket]
Shadow				= no
Arm				= 170;2
Proximity			= yes
Ranged				= yes
ROT				= 8
Image				= DRAGON
IgnoresFirestorm		= yes
AA				= yes

[PursuerRocketE]:[PursuerRocket]
Cluster				= 10
Airburst			= yes
AirburstWeapon			= PursuerRocketLauncher

[TyrantMissileE]
Damage=160
ROF=20
Range=8
Burst=4
Projectile=AAHeatSeeker3
Speed=40
Warhead=TyrantEWH2
Report=GuardianGIDeployedAttack
MinimumRange=1

[TyrantWH2]
CellSpread=1.2
PercentAtMax=.8
Wall=yes
Wood=yes
Verses=100%,100%,100%,90%,60%,70%,100%,100%,90%,25%,100%
Conventional=yes
InfDeath=3
AnimList=S_CLSN16,S_CLSN22,S_CLSN30,S_CLSN42,S_CLSN58
ProneDamage=50%

[TyrantEWH2]
CellSpread=1.2
PercentAtMax=.8
Wall=yes
Wood=yes
Verses=100%,100%,100%,90%,60%,70%,100%,100%,90%,25%,100%
Conventional=yes
InfDeath=9
AnimList=S_CLSN16,S_CLSN22,S_CLSN30,S_CLSN42,S_CLSN58
ProneDamage=50%
Bright=yes
CombatLightSize=150%
CLDisableRed=yes
CLDisableBlue=yes


; clone of (ARNIEWH)
[TyrantWH]
Verses=200%,200%,100%,0%,0%,0%,75%,50%,25%,100%,100%
InfDeath=1
AnimList=PIFFPIFF,PIFFPIFF
Bullets=yes
ProneDamage=70%

; clone of (ARNIEWH)
[TyrantEWH]
Verses=200%,200%,100%,50%,50%,50%,75%,50%,25%,100%,100%
InfDeath=1
AnimList=PIFFPIFF,PIFFPIFF
Bullets=yes
ProneDamage=70%


[TyrantWH2]
CellSpread=1.2
PercentAtMax=.8
Wall=yes
Wood=yes
Verses=100%,100%,100%,90%,60%,70%,100%,100%,90%,25%,100%
Conventional=yes
InfDeath=3
AnimList=S_CLSN16,S_CLSN22,S_CLSN30,S_CLSN42,S_CLSN58
ProneDamage=50%

[TyrantEWH2]
CellSpread=1.2
PercentAtMax=.8
Wall=yes
Wood=yes
Verses=100%,100%,100%,90%,60%,70%,100%,100%,90%,25%,100%
Conventional=yes
InfDeath=9
AnimList=S_CLSN16,S_CLSN22,S_CLSN30,S_CLSN42,S_CLSN58
ProneDamage=50%
Bright=yes
CombatLightSize=150%
CLDisableRed=yes
CLDisableBlue=yes

; clone of (ARNIEWH)
[TyrantEWH]
Verses=200%,200%,100%,50%,50%,50%,75%,50%,25%,100%,100%
InfDeath=1
AnimList=PIFFPIFF,PIFFPIFF
Bullets=yes
ProneDamage=70%

[TyrantMissile]
Damage=80
ROF=40
Range=8
Burst=1
Projectile=AAHeatSeeker3
Speed=30 ;40
Warhead=TyrantWH2
Report=GuardianGIDeployedAttack
MinimumRange=1

[TyrantMissileE]
Damage=160
ROF=20
Range=8
Burst=4
Projectile=AAHeatSeeker3
Speed=40
Warhead=TyrantEWH2
Report=GuardianGIDeployedAttack
MinimumRange=1

[TyrantWH2]
CellSpread=1.2
PercentAtMax=.8
Wall=yes
Wood=yes
Verses=100%,100%,100%,90%,60%,70%,100%,100%,90%,25%,100%
Conventional=yes
InfDeath=3
AnimList=S_CLSN16,S_CLSN22,S_CLSN30,S_CLSN42,S_CLSN58
ProneDamage=50%

[TyrantEWH2]
CellSpread=1.2
PercentAtMax=.8
Wall=yes
Wood=yes
Verses=100%,100%,100%,90%,60%,70%,100%,100%,90%,25%,100%
Conventional=yes
InfDeath=9
AnimList=S_CLSN16,S_CLSN22,S_CLSN30,S_CLSN42,S_CLSN58
ProneDamage=50%
Bright=yes
CombatLightSize=150%
CLDisableRed=yes
CLDisableBlue=yes



