;
;
;
; This unit is not used by Mercenaries, but by insurgents. 
; This is a Light Tank type. It cannot receive 

;------------------------------------------------------------------------------
[VehicleTypes]
+				= TnkScorp
; 58D2E16EBBEAC

;------------------------------------------------------------------------------
; Hydra (PPG Tankette) - Voxel: TX1138
; Scorpion Tank
; Formerly [SCORP], [ScorpionTank]. 
[TnkScorp]:[TnkLgt]
;----- Text -----
Name				= Tank Scorpion			; Hydra Tank
UIName				= name:tnk_scorp		; Name:HydraTank
UIDescription			= desc:tnk_scorp
;----- Gfx -----
Image				= tnk_scorp			; HYDR
;----- Taxonomy -----
BaseNormal			= no
TickTank			= yes
;----- Body -----
Strength			= 350				; 200
;----- Weapons -----
Primary				= ScorpionGuns
ElitePrimary			= ScorpionGunsE
Primary=ScorpionCannon
ElitePrimary=ScorpionCannonE
; MobileFire			= no
; NoMovingFire			= yes
;----- Armor -----
Armor				= light
;----- Availability -----
Owner				= Forgotten, Nod
Cost				= 1400
Prerequisite			= FACTORY				; NODFACTORY
;----- Load -----
; Ammo				= 8
; PipScale			= Ammo
;----- Sfx -----
VoiceSelect			= FlakTrackSelect			; NVEH2_SEL1,NVEH2_SEL2,NVEH2_SEL3,NVEH2_SEL4 ; ORIGINAL_WAS_CHANGED, new voice. ; 25-I000,25-I002,25-I004,25-I006
VoiceMove			= FlakTrackMove				; NVEH2_MOV1,NVEH2_MOV2,NVEH2_MOV3,NVEH2_MOV4 ; 25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack			= FlakTrackAttackCommand		; NVEH2_ATCK1,NVEH2_ATCK2,NVEH2_ATCK3,NVEH2_ATCK4,NVEH2_ATCK5 ; 25-I014,25-I022,25-I024,25-I026

VoiceSelect=NVEH2_SEL1,NVEH2_SEL2,NVEH2_SEL3,NVEH2_SEL4 ; ORIGINAL_WAS_CHANGED, new voice.
VoiceMove=NVEH2_MOV1,NVEH2_MOV2,NVEH2_MOV3,NVEH2_MOV4
VoiceAttack=NVEH2_ATCK1,NVEH2_ATCK2,NVEH2_ATCK3,NVEH2_ATCK4,NVEH2_ATCK5

VoiceFeedback			= 
DieSound			= GenVehicleDie
MoveSound			= FlakTrackMoveStart
DeploySound			= SUBDRIL1 ; Added drill sounds when it burrows
UndeploySound			= SUBDRIL1
;----- Movement -----
Speed				= 
MovementZone			= Crusher

Cost=800
Points=25

MaxDebris=4
DebrisTypes=TIRE
DebrisMaximums=6
ThreatPosed=10	; This value MUST be 0 for all building addons
SpecialThreatValue=1
ZFudgeColumn=10
ZFudgeTunnel=13
Size=3

Speed=7
Owner				= Atlas,POW
MaxDebris=4
Weight=3.5
ZFudgeColumn=9
ZFudgeTunnel=15
Prerequisite			= NAWEAP,NAHAND;STR0004
TechLevel=7
Strength=460
Sight=7
Points=60
ThreatPosed=40
SelfHealing=yes
Sensors=yes
TargetLaser=yes
EliteAbilities=FIREPOWER,STRONGER

Image=HYDR
Prerequisite=NAWEAP,NAHAND
TechLevel=6
Sight=5
Speed=8
Cost=800
Size=3
;----- Veterancy -----
Trainable			= yes			; Should be defined despite defaulting to yes, since several deployed types (buildings) derive from this type. 

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Tank Scorpion (Upgrade Armor)
[TnkScorp_Ta1]
;----- Text -----
Name				= Tank Scorpion (Upgrade Armor)
;----- Body -----
Strength			= 370
;----- Armor -----
Armor				= heavy

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Tank Scorpion (Upgrade Burrow)
; [TTNK] (Tick Tank) (ts) (xxxmodxxx)
[TnkScorp_Tb1]:[TnkScorp]
;----- Text -----
Name				= Tank Scorpion (Upgrade Burrow)
;----- Availability -----
Prerequisite			= FACTORY, TechBurrow

Primary=90mm
TechLevel=2 ;3 ; ORIGINAL_WAS_CHANGED_TECH_LEVEL
Sight=5
Speed=6
Cost=800
Points=35 ; ORIGINAL_WAS_CHANGED_POINTS_SYSTEM. Gives bit less points than deployed form (-10).
MaxDebris=4
DebrisTypes=TTNKTURRET,DEB10LG,DEB7LG,DEB3LG,DEB4LG,DEB5SM ; ORIGINAL_WAS_CHANGED, added voxel debris
DebrisMaximums=1,1,1,1,1,1
;----- Load -----
DeploysInto			= TnkScorp_Tb1D				; GATICK
ThreatPosed=25	; This value MUST be 0 for all building addons
Weight=3 ; ORIGINAL_WAS_CHANGED_WEIGHT_CLASS
EliteAbilities=SENSORS
Elite=120mmxTick ;120mmx ; ORIGINAL_WAS_CHANGED, Tick Tank version of 120mmx.
AccelerationFactor=0.01
ZFudgeColumn=8
ZFudgeTunnel=13
AllowedToStartInMultiplayer=no ; ORIGINAL_WAS_CHANGED_NEW_SIDE


; [GATICK] (Deployed Tick Tank)
;----- Text -----
Name				= Tank xxx (Deployed)
;----- Armor -----
Armor				= concrete				; In addition to the hp bonus, it gains a better armor type. 
;----- Availability -----
TechLevel			= -1 ;5 ; ORIGINAL_WAS_CHANGED, changed tech level to -1 since this is not built...
Points=45 ; ORIGINAL_WAS_CHANGED_POINTS_SYSTEM. Gives bit more than undeployed form (+10).
Cost=800
Sight=5
Primary=90mm
Elite=120mmxTick ;120mmx ; ORIGINAL_WAS_CHANGED, Tick Tank version of 120mmx.
TurretAnim=TTNKDEPTUR ; ORIGINAL_WAS_CHANGED, uses a new turret voxel.
TurretAnimIsVoxel=true
TurretAnimX=1  ; ORIGINAL_WAS_CHANGED, adjusted for new voxel.
TurretAnimY=13 ; ORIGINAL_WAS_CHANGED, adjusted for new voxel.
TurretAnimZAdjust=-20
ThreatPosed=25 ;30 ; ORIGINAL_WAS_CHANGED, same threat as mobile form so AI doesn't favor deployed as targets.
MaxDebris=4
DebrisTypes=TTNKTURRET,DEB10LG,DEB7LG,DEB3LG,DEB4LG,DEB5SM ; ORIGINAL_WAS_CHANGED, added voxel debris
DebrisMaximums=1,1,1,1,1,1
DamageSmokeOffset=500, 500, 400
TogglePower=no
EliteAbilities=SENSORS
HasStupidGuardMode=false
StartFacing=2 ; ORIGINAL_WAS_CHANGED, so the turret starts facing east.
Capturable=false ; ORIGINAL_WAS_CHANGED_MECHANIC, makes sure Mutant Mechanics can't capture this.
;----- Load -----
UndeploysInto			= TTNK

;------------------------------------------------------------------------------
[TnkScorp_Tc1]
;----- Weapons -----
Primary				= CannonMM90
;----- Movement -----
MovementZone			= Destroyer

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
[TnkScorp_Tm1]
;----- Text -----
Name				= Tank Scorpion (Upgrade Missile)
;----- Weapons -----
Secondary			= ScorpionRocketLauncher
EliteSecondary			= ScorpionRocketLauncherE
Secondary=ScorpionRocket
EliteSecondary=ScorpionRocketE

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Manticore APT
; Anti-Infantry Tank (RockMod)
; Formerly [AIT], [Manticore]
[TankManticore]:[TnkScorp]
;----- Text -----
Name				= Anti Personnel Tank
UIName				= name:tnk_manticore
UIDescription			= desc:tnk_manticore
;----- Weapons -----
Primary				= Gun_B4392CAB7B92E
Secondary			= RocketLauncher_168FA

ElitePrimary			= Gun_4BD75B8113FFE
EliteSecondary			= RocketLauncher_5AC39
;----- Body -----
Strength			= 200

;----- Armor -----
Armor				= heavy
ImmuneToVeins			= yes

;----- Turrets & Barrels -----
Turret				= yes
FireAngle			= 0

IsTilter=no
TooBigToFitUnderBridge=true
Sight=6

;----- Procuration -----
Owner				= Confederation
RequiredHouses			= Cubans
TechLevel			= 6
;Prerequisite			= GAWEAP,GADEPT
Cost				= 800
CrateGoodie			= yes

Points=25

;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys,SmallGreySSys
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60

;----- SFX -----
VoiceSelect			= 15-I000,15-I006,15-I040,15-I042
VoiceMove			= 15-I024,15-I044
VoiceAttack			= 15-I006,15-I046
VoiceFeedback			= 
MaxDebris=2

;----- Movement -----
Locomotor			= {55D141B8-DB94-11d1-AC98-006008055BB5}
MovementZone			= Crusher					; Normal
;Accelerates=false
Speed				= 8
ROT				= 5

ThreatPosed=15	; This value MUST be 0 for all building addons

;----- Veterancy -----
EliteAbilities			= VEIN_PROOF


;------------------------------------------------------------------------------


; Sabretooth Battletaxi - Voxel: lefthand
[SABR]
UIName=Name:HYDRATRAN
Name=Sabertooth Battletaxi
Image=SABER
Prerequisite=NAWEAP,NAHAND
Strength=200
Category=Transport
Armor=heavy
DeployTime=.022
TechLevel=6
Sight=5
PipScale=Passengers
Speed=8
CrateGoodie=yes
Owner=Russians,Germans,Confederation
;RequiredHouses=Confederation
AllowedToStartInMultiplayer=no
Cost=2500
Points=25
ROT=5
Crusher=yes
Passengers=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=4
DebrisTypes=TIRE
DebrisMaximums=6
SpeedType=Amphibious
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=AmphibiousCrusher
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
SpecialThreatValue=1
ZFudgeColumn=10
ZFudgeTunnel=13
SizeLimit=2
Primary=SaberCannon
ElitePrimary=SaberCannonE

OpenTopped=yes

;-----Gattling stuff-------
;GEF There is a _lot_ of stuff in this section, hope it's worth it

;Do I have a gattling gun or not
IsGattling=yes

;How weapons does it have? Currently, all Gattling Units have had anti-air
;capability, so the mechanics currently depends on having twice the number
;of stages in weapons, alternating anti-ground first, and anti-air second.
;will be>TurretCount=1
WeaponCount=8;yr>6

Weapon1=AGGattling
EliteWeapon1=AGGattlingE
Weapon2=AAGattling
EliteWeapon2=AAGattlingE
Weapon3=AGGattling2
EliteWeapon3=AGGattling2E
Weapon4=AAGattling2
EliteWeapon4=AAGattling2E
Weapon5=AGGattling3
EliteWeapon5=AGGattling3E
Weapon6=AAGattling3
EliteWeapon6=AAGattling3E

;How many stages does this gattling gun have, and how long does it
;take to progress through these stages;
WeaponStages=3
Stage1=200
Stage2=400
;This last stage is used to determine what the maximum fireing timer can be. Once it
;hits this it will stop increasing. If this is larger than the previous stage, then
;it will have a grace period once the unit stops firing before it needs to drop
;down to the lower weapon.
Stage3=600

EliteStage1=100
EliteStage2=200
EliteStage3=300

;How many increments or decrements does the timer get per frame?
;If RateDown is zero, then it overrides the previous stage vaules,
;causing the tank to instantly go to zero when it stops firing
;if it can't find a new target
RateUp=1
RateDown=50


;-----End Gattling stuff-------


[VehicleTypes]
+				= DryadAPC

; Mirage Transport
; Voxel created by ArgCmdr (argcmdr2@hotmail.com) in Nod scheme from Scorpion Tank model in the C&C: Generals beta. 
[DryadAPC]
;----- Name -----
UIName				= Name:APC_Dryad
Name				= Dryad Transport

;----- Procuration -----
Prerequisite.RequiredTheaters	= TEMPERATE,SNOW,URBAN,LUNAR,NEWURBAN
Owner				= Allies,Americans,British,French,Germans,Dutch,Hellenes,Italians,Spaniards,Turks,AirFleet,LaserArmy,EUTankArmy,TurtleArmy
RequiredHouses			= Hellenes
TechLevel			= 6
Prerequisite			= EUFactory,Any_Radar
Cost				= 1200
AllowedToStartInMultiplayer	= no
CrateGoodie			= yes

;----- Base Attributes -----
Strength			= 200

;----- AI -----
Category			= Transport
CanApproachTarget		= no
CanPassiveAquire		= no					; Do not want it giving away position. 

;----- Armor -----
Armor				= heavy

;----- Weapons -----
Primary				= TankMakeupKit
Secondary			= DryadRocketLauncher

EliteSecondary			= DryadRocketLauncher_E
;MobileFire=no
;NoMovingFire=yes
AirRangeBonus			= 4

;----- Turrets -----
Turret				= no

;----- GFX -----
Image				= tank_scorp_un

;----- Visibility -----
RadarInvisible			= yes
RadarVisible			= no
CanDisguise=yes
DisguiseWhenStill		= yes

Sight=5
Speed=8
Points=25
ROT=5
Crusher=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60

;----- SFX -----
VoiceSelect			= GenVehSelect				; MirageTankSelect
VoiceMove			= GenVehMoveCommand			; MirageTankMoveCommand
VoiceAttack			= GenVehAttackCommand			; MirageTankAttackCommand
VoiceFeedback			= 
DieSound			= GenVehicleDie
MoveSound			= FlakTrackMoveStart

MaxDebris=4
DebrisTypes=TIRE
DebrisMaximums=6

;----- Movement -----
SpeedType			= Track
Locomotor			= {4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone			= Crusher

ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
SpecialThreatValue=1
ZFudgeColumn=10
ZFudgeTunnel=13
Size=3


IsTilter=yes
Crusher=yes
TooBigToFitUnderBridge=true
TechLevel=9
Sight=9
Speed=7
CrateGoodie=yes
Owner=British,French,Germans,Americans,Alliance
Cost=1000
Soylent=1000
Points=25
ROT=5
IsSelectableCombatant=yes

Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60

MaxDebris=2
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys;gs the sparks look cool, but the smoke gives it away too easily    ,SmallGreySSys
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
Size=3

; Dryad APC (desert pattern)
; Voxel created by ArgCmdr (argcmdr2@hotmail.com) in GDI scheme from Scorpion Tank model in the C&C: Generals beta. 
[DryadAPC_DES]:[DryadAPC]
;----- GFX -----
Image				= tank_scorp_un_d

;----- Procuration -----
Prerequisite.RequiredTheaters	= DESERT


[DryadRocketLauncher]
Damage				= 60
ROF				= 70
Range				= 6
MinimumRange			= 1
Projectile			= DryadRocket
Speed				= 40
Warhead				= HEAT
Report				= SeawolfAttack

[DryadRocketLauncher_E]:[DryadRocketLauncher]
Damage				= 75
Range				= 8
Speed				= 70
Burst				= 2

[DryadRocket]
Image				= DRAGON
ROT				= 16
High				= yes
SubjectToWalls			= no
SubjectToCliffs			= yes
SubjectToElevation		= no

