;******************************************************************************
;*** Hospital *****************************************************************
;******************************************************************************
; Hospital Lv. 1: Infantry has to be sent inside to heal (TS style). 
; Hospital Lv. 2: Has a small healing aura. 
; Hospital Lv. 3: Can project a healing aura anywhere on the map. 
; Hospital Lv. 4: Infantry gains self heal. 
; Notably, these are qualitative increases, not quantitative increases. 
; Quantitative increases form a different dimension of upgrades. 
; Drop Crate Heal becomes available in conjunction with airport. 
; Drop Medics becomes available in conjunction with airport to Cuba only. 

;------------------------------------------------------------------------------
[BuildingTypes]
+				= CAHospital

;------------------------------------------------------------------------------
; Civilian Hospital
; CAHOSP (RA2/YR)
; Formerly [CAHospital]. 
[Hospital]
;----- Text -----
Name				= Hospital
UIName				= name:hospital
UIDescription			= desc:hospital
Nominal				= yes
;----- Taxonomy -----
Hospital			= yes				; gs old TS way
;----- Body -----
Strength			= 800
;----- Armor -----
Armor				= concrete
Capturable			= yes
;----- Availability -----
; Side				= Neutral			; Not sure how to parse Side for Neutral. 
; House				= 
Owner				= Neutral
TechLevel			= -1
Cost				= 3000				; New, for veterancy. 
Unsellable			= yes
;----- Score -----
Points				= 5
; Insignificant			= yes
;----- Perception -----
Sight				= 6
RadarVisible			= yes				; gs put on radar even if insignificant and unowned (insignificant and owned is a UC building)
;----- Damage & Destruction -----
DamageParticleSystems		= SmallGreySSys,BigGreySmokeSys
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris			= 6
DebrisAnim			= Dbris3sm,Dbris4lg,Dbris4sm,Dbris6sm,Dbris7lg,Dbris7sm,Dbris8sm,Dbris9lg,Dbris10lg,Dbris10sm
LeaveRubble			= yes
;----- Sfx -----
VoiceSelect			= SelectHospital
CaptureEvaEvent			= EVA_HospitalCaptured		; Eva (and therefore 3way split) voice to use when captured
;----- Load -----
Crewed				= yes
NeedsEngineer			= yes
;----- Attach -----
InfantryGainSelfHeal		= 1				; one 'unit' of SelfHealInfantryAmount per SelfHealInfantryFrames

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Cuban Hospital
[CUHospital]:[Hospital]
;----- Text -----
Name				= Hospital Cuban
;----- Weapons -----
SuperWeapon1			= InvokeDropMedic
; SuperWeapon2			= DeployLazaretto		; Deploys a small M.A.S.H. (medical) tent at target Medic. 
;----- Availability -----
Owner				= Confederation
RequiredHouses			= Cubans
