
; Libya Death Hand
[LYMSLO]
;----- Text -----
Name				= Death Hand Missile Silo
UIName				= name:dedhand
UIDescription			= desc:dedhand
Nominal				= yes
BuildCat=Combat
;----- Taxonomy -----
IsTemple			= yes
NukeSilo			= yes
;----- Gfx -----
ChargedAnimTime			= 1				; Here, put an animation that attaches a decloaking effect. 
;----- Stealth -----
Cloakable			= yes				; So this stays cloaked until ChargedAnimTime. 
								; (Upgraded, it stays cloaked until firing.)
;----- Body -----
Strength			= 1000
;----- Weapons -----
; SuperWeapon			= ChemicalSpecial
;----- Armor -----
Armor				= concrete
ImmuneToPsionics		= no
;----- Availability -----
Side				= Terran
Owner				= Soviet
; House				= Gaddafi
RequiredHouses			= Libyans
TechLevel			= 10
Prerequisite			= NATECH,NACNST

Adjacent=2
Sight=4
AIBasePlanningSide=1 ;gs 0 for Good, 1 for Evil
;Cost=5000
Points=30
;Power=-200
Crewed=yes
Capturable=false

MaxDebris=15
MinDebris=5
DebrisAnim=Dbris3sm,Dbris4lg,Dbris4sm,Dbris6sm,Dbris7lg,Dbris7sm,Dbris8sm,Dbris9lg,Dbris10lg,Dbris10sm
ThreatPosed=0 ; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,LGSparkSys
SpecialThreatValue=1
RevealToAll=yes
HasStupidGuardMode=false
Spyable=yes
;----- Damage & Destruction -----
DeathWeapon			= DeathHandBomb
Explodes			= yes
Explosion			= TWLT070, S_BANG48, S_BRNL58, S_CLSN58, S_TUMU60
ExplosionType			= ExplosionLarge
AIBuildThis=yes
ProtectWithWall=yes
BuildLimit=1
