;
;*** Chrono Laser Tank
;
; Or Laser Chrono Tank. 

Gladiator Tank

;------------------------------------------------------------------------------
[VehicleTypes]
+				= TnkWarp
+				= TnkWarp2

;------------------------------------------------------------------------------
; Phase Tank
; Formerly [PhaseTank], [TnkPhas]. 
[TnkWarp]:[TnkAbrm]
;----- Text -----
Name				= Tank Warp
DisplayName			= object:tnk_phas
UIName				= name:tnk_phas
UIDescription			= desc:tnk_phas
;----- Gfx -----
Image				= tank_phase
;----- Taxonomy -----
Category			= AFV
;----- Body -----
Strength			= 500			; Heavy Tank equivalent
Size				= 0
Weight				= 0
;----- Weapons -----
Primary				= PhaseCannon
Elite				= PhaseCannonE
ElitePrimary			= PhaseCannonE
;----- Armor -----
Armor				= armor_phase		; heavy
;----- Availability -----
ForbiddenHouses			= TimePatrol
TechLevel			= 8
Prerequisite			= UNFactory, UNCntrTek
Cost				= 1700
;----- Movement -----
Locomotor			= Jumpjet
MovementZone			= Fly
SpeedType			= Wing
Speed				= 5
ROT				= 2
IsTilter			= no
Crusher				= no
TooBigToFitUnderBridge		= false
;----- Perception -----
Sight=8

Points=25
ROT=5

;----- Sfx -----
VoiceSelect			= 32-I000
VoiceMove			= CHRONOSND
VoiceAttack			= 32-I002,32-I004,32-I006
VoiceFeedback=32-I008
VoiceDie=32-I008

ThreatPosed=15	; This value MUST be 0 for all building addons

DamageParticleSystems=SparkSys,SmallGreySSys
Explosion			= xplo_fase				; ring1
MaxDebris=2
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
ImmuneToVeins=yes
OpportunityFire=yes
BuildTimeMultiplier=1.5;Individual control of build time
;----- Attach -----
AttachEffect.AttachTypes	= phasefx

Primary=ShockCannon
MoveToShroud=no
Strength=300
Category=AFV
DeployTime=.022
TypeImmune=yes
Armor=light
Turret=no
IsTilter=yes
TechLevel=7
Sight=5
Speed=5
CrateGoodie=yes
Owner=GDI
AllowedToStartInMultiplayer=no
Cost=750
Points=25
ROT=6
Crusher=yes
NoMovingFire=yes
MaxDebris=4
ThreatPosed=30	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
Weight=3.5
EliteAbilities=SELF_HEAL
AutoCrush=no
Accelerates=false
ZFudgeColumn=10
ZFudgeTunnel=14

;------------------------------------------------------------------------------
; Tank Chrono
; Formerly [CTNK]. 
; Subsumes [CHRONO] (Warp Tank, TS Balance lineage). 
[TnkWarp2]:[TankWarp]
;----- Text -----
Name				= Tank Xrono
UIName				= name:tnk_xron
UIDescription			= desc:tnk_xron
;----- Gfx -----
Image				= tnk_xron				; tnk_abrm
;----- Body -----
;----- Availability -----
RequiredHouses			= TimePatrol
Prerequisite			= UNFactory,UNBldgTek
Armor=heavy
Turret=yes
IsTilter=yes
Crusher=yes
TooBigToFitUnderBridge=true
TechLevel=2
Sight=8
Speed=7
Points=25
ROT=5
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=GenAllVehicleSelect
VoiceMove=GenAllVehicleMove
VoiceAttack=GenAllVehicleAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=GrizzlyTankMoveStart
CrushSound=TankCrush
;----- Movement -----
Locomotor				= 
MovementZone				= 
ThreatPosed=15	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Accelerates=false
OpportunityFire=yes
BuildTimeMultiplier=1.5;Individual control of build time

; phase cannon
[PhaseCannon]
Damage				= 100
ROF				= 70
Range				= 7
Projectile			= PhaseProj
Seed				= 100
Warhead				= AP
Report				= MirageTankAttack
Bright=yes
Anim=VTMUZZLE

[ChronoCannonE]
Damage=150
ROF=80
Range=9
Projectile=ChronoCannonP
Speed=100
Warhead=ChronoBeam
Report=MirageTankAttack
Bright=yes
Anim=VTMUZZLE

Damage=36
ROF=50
Range=6.75
Speed=40
Warhead=AP
Report=120MMF
Anim=GUNFIRE

[PhaseProj]
Image				= ball_blu2
Inviso				= no			; yes
Trajectory			= straight
High				= yes
SubjectToWalls			= no
SubjectToCliffs			= no
SubjectToElevation		= yes

















[CNTK]
Name=Centurion Tank
UIName=Name:CNTK
Primary=CenturionLaser
Secondary=CenturionLaser
ElitePrimary=CenturionLaserE
EliteSecondary=CenturionLaserE
Buildable=yes
Owner=Americans
;RequiredHouses=
;ForbiddenHouses=
;SecretHouses=
TechLevel=13
Prerequisite=FACTORY
;PrerequisiteOverride=
Crusher=yes
;OmniCrusher=
Crushable=no
OmniCrushResistant=no
Armor=
ImmuneTo=
MovementZone=
MovementRestrictedTo=
Locomotor=
SpeedType=Hover

; Originally created by metalmario (Greg Edwards). 
[LTNK]
Name				= Laser Tank
Category=AFV
Primary=LaserFire3
Secondary=none
Strength=350
CrateGoodie=yes
Armor=light
Turret=yes
TechLevel=4
Sight=6
Speed=7
Owner=Nod
Prerequisite=NODFACTORY
Cost=850
Points=60
ROT=5
Crusher=yes
Crewed=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
Weight=2
MovementZone=Destroyer
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
AllowedToStartInMultiplayer=yes
AccelerationFactor=0.01
ZFudgeColumn=9
ZFudgeTunnel=15
EliteAbilities=FASTER,SELF_HEAL
Elite=LaserFire3E

[LASTAN]
Prerequisite=NAWEAP,NATECH,NATMPL
Image=MCV
Primary=SuperLaser
Secondary=BAZOOKA
Strength=800
Category=AFV
Armor=heavy
TechLevel=10
BuildLimit=1
Sight=8
Speed=3
Owner=NOD
AllowedToStartInMultiplayer=no
Cost=5000
Trainable=no
SelfHealing=yes
Points=25
ROT=3
Crusher=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=6
Locomotor={55D141B8-DB94-11d1-AC98-006008055BB5}
MovementZone=Destroyer
ThreatPosed=80	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=300, 300, 425
TiltsWhenCrushes=false
BuildLimit=1
Weight=3.5
Accelerates=false
ZFudgeColumn=12
ZFudgeTunnel=15
ZFudgeBridge=25
