;******************************************************************************
;*** Bird *********************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[InfantryTypes]
+				= Eagl
+				= EaglCybg
+				= Ravn
; 57CD677B63931

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Animal Eagle
[Eagl]
;----- Text -----
Name				= Eagle
UIName				= name:eagl
UIDescription			= desc:eagl
DisplayName			= object:eagl
Nominal				= yes
;----- Taxonomy -----
Category			= none
Natural				= yes
NotHuman			= yes
Organic				= yes					; Needed for when spawned. 
NonVehicle			= yes					; Might be needed when spawned. 
;----- Body -----
Strength			= 12
Size				= 1
PhysicalSize			= 1
Weight				= .1
;----- Perception -----
Sight				= 10
;----- Armor -----
Armor				= none
;----- Weapons -----
Primary				= EagleEye				; Dive not possible in engine. 
;----- Availability -----
Owner				= Natural
;----- Score -----
Points				= 1
;----- Movement -----
Locomotor			= Fly
MovementZone			= Fly
SpeedType			= Winged
Speed				= 6
;----- UI -----
Pip				= gold
OccupyPip			= cape_bird_gold

AllowedToStartInMultiplayer=no
Cost=150
Soylent=100
;----- Sfx -----
VoiceSelect			= SelectEagle
VoiceMove			= CmdMovEagle
VoiceAttack			= CmdAtkEagle
VoiceFeedback			= FearEagle
DieSound			= DieEagle

ThreatPosed=2	; This value MUST be 0 for all building addons
Size=2
IFVMode=12
Trainable=no
Natural=yes
;
Prerequisite=CAZOO
SpeedType=Amphibious
MovementZone=AmphibiousDestroyer

;------------------------------------------------------------------------------
[EaglCybg]
;----- Text -----
Name				= Improved Raven
;----- Taxonomy -----
Cyborg				= yes

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Nevermore the Raven
[Ravn]
$Inherits			= Eagl
;----- Text -----
Name				= Raven
UIName				= name:raven
UIDescription			= desc:raven
DisplayName			= object:raven
;----- UI -----
Pip				= black
OccupyPip			= cape_bird_black
VoiceSelect=ChimpSelect
VoiceMove=ChimpMove
VoiceAttack=ChimpAttackCommand
VoiceFeedback=ChimpFear
VoiceSpecialAttack=ChimpMove
DieSound=ChimpDie
AmbientSound=ChimpAmbient

ThreatPosed=2	; This value MUST be 0 for all building addons
IFVMode=12
Trainable=no

Fearless=no
Primary=ClawAttack
;Prerequisite=GAPILE
TechLevel=6
Sight=6
Pip=green
Speed=2
Points=5
VoiceSelect=15-I000,15-I004,15-I012,15-I048
VoiceMove=15-I018,15-I024,15-I044
VoiceAttack=15-I044,15-I050,15-I044,15-I046
VoiceFeedback=15-I058,15-I064
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
MovementZone=Fly; This needs to be None, like aircraft
ThreatPosed=15; This value MUST be 0 for all building addons
TiberiumProof=yes
TiberiumHeal=yes
ImmuneToVeins=yes
VeteranAbilities=ROF,FASTER,SIGHT
EliteAbilities=STRONGER,FIREPOWER
