
;------------------------------------------------------------------------------
; Claymore Web Node
; Formerly [SWEB]. 
[HiveTrap]
;----- Text -----
Name				= Spiderweb
UIName				= name:claymore_web
UIDescription			= desc:claymore_web
;----- AI -----
AttackFriendlies		= yes

;----- Perception -----
Sensors				= yes
SensorSight			= 10
;----- Weapons -----
Primary				= WebLauncher
;----- Armor -----
Armor				= 


	Cloakable=yes
	SensorArray=yes
	HasRadialIndicator=true
	RadialColor=0,200,0
	CloakRadiusInCells=25
