
; electric rules' ELECProj
; tech war's SUPPLASPROJ (Super Plasma Projectile)
[BallPulsWht2]
$Inherits			= BallPulsWht
;----- Text -----
Name				= Ball Pulse White 2
;----- Gfx -----
Image				= BallPulsWht2				; SUPPLASPROJ; electric rules: PULSBALL
Trailer				= supplastrail				; Game reads this when the section is recursively loaded into art by being its own art entry. 
;----- Body -----
;----- Armor -----
;----- Movement -----
Arcing				= yes
Floater				= yes; electric rules

[PulsPr]
Arcing=true
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=yes
Shadow=no
;ROT=1
AA=no
AG=yes
Image=CHROBALL
Acceleration=1 ;10
