;******************************************************************************
;*** Grenade ******************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[Animations]
+				= Grenade

;------------------------------------------------------------------------------
; Second stage of heavy grenadier grenade
; TechWar's Bet2
; Formerly [Bomblet_of_Grenade_Multi]. 
[Bomblet]

High				= yes
Image				= 120MM
Bouncy				= yes
Arcing				= yes
Floater				= yes

;------------------------------------------------------------------------------
; lobbed tumbling grenade
[Grenade];GrenadeProj_rr
;----- Text -----
Name				= Grenade
UIName				= name:grenade
UIDescription			= desc:grenade
;----- Body -----
Strength= 10
;----- Gfx -----
Image				= canister;GRENP
Animates			= yes
Frames				= 8
FirersPalette			= yes
;----- Movement -----
High				= yes
SubjectToCliffs			= yes
SubjectToElevation		= yes
SubjectToWalls			= no			; Red Rescurrection is yes. 
SubjectToTrenches		= no
SubjectToBuildings		= yes
Arcing				= yes
Inaccurate			= yes
Bouncy				= yes
Elasticity			= .2			; Should be less than Discus. 
;----- Fuze -----
Arm				= 2
Ranged				= yes
Proximity			= yes

;------------------------------------------------------------------------------
; Formerly [Grenade_C1FD419228FCF]. 
Cluster				= 4			; 10


; First stage of heavy grenadier grenade
; TechWar's Bet1
; Formerly [Grenade_Multi]. 
; Subsumes [Grenade_C1FD419228FCF] (Grenade Cluster). 
[GrenadeMlti]
$inherits			= Grenade
;----- Text -----
Name				= Grenade Multi
UIName				= name:grenade_mlti
UIDescription			= desc:grenade_mlti
;----- Gfx -----
; Image				= 120MM
;----- Movement -----
; Floater			= yes
; VeryHigh			= yes
;----- Payload -----
Cluster				= 5
Airburstweapon			= betty2
