;******************************************************************************
;*** Grenade ******************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[Animations]
+				= Grenade

;------------------------------------------------------------------------------
; Second stage of heavy grenadier grenade
; TechWar's Bet2
; Formerly [Bomblet_of_Grenade_Multi]. 
[Bomblet]
;----- Text -----
Name				= Bomblet
UIName				= name:bomblet
UIDescription			= desc:bomblet
;----- Gfx -----
Image				= bomblet		; 120MM
Animates			= yes
Frames				= 8
FirersPalette			= yes
;----- Body -----
Strength			= 1
;----- Movement -----
High				= yes
Bouncy				= yes
Arcing				= yes
Floater				= yes

;------------------------------------------------------------------------------
; lobbed tumbling grenade
; GrenadeProj_rr
[Grenade]
$inherits			= Bomblet
;----- Text -----
Name				= Grenade
UIName				= name:grenade
UIDescription			= desc:grenade
;----- Gfx -----
Image				= canister		; GRENP
;----- Movement -----
High				= yes
SubjectToCliffs			= yes
SubjectToElevation		= yes
SubjectToWalls			= no			; Red Rescurrection is yes. 
SubjectToTrenches		= no
SubjectToBuildings		= yes
Inaccurate			= yes
Elasticity			= .2			; Should be less than Discus. 
;----- Fuze -----
Arm				= 2
Ranged				= yes
Proximity			= yes

;------------------------------------------------------------------------------
; First stage of heavy grenadier grenade
; TechWar's Bet1
; Formerly [Grenade_Multi]. 
; Subsumes [Grenade_C1FD419228FCF] (Grenade Cluster). 
[GrenadeMlti]
$inherits			= Grenade
;----- Text -----
Name				= Grenade Multi
UIName				= name:grenade_mlti
UIDescription			= desc:grenade_mlti
;----- Gfx -----
; Image				= 120MM
;----- Movement -----
; Floater			= yes
; VeryHigh			= yes
;----- Payload -----
; Cluster			= 5			; Was 4, was 10. Adapted to integrate Bet1 (tw 1.7). 
; Airburstweapon		= betty2
ShrapnelWeapon			= 
ShrapnelCount			= 
