;******************************************************************************
;*** Missile Nova *************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Nova Missile (flying up)
; [HKDeathHand] (ebfd)
; Formerly [NovaRocket]. 
[MislNova]
$inherits			= MislScud
;----- Text -----
Name				= Missile Nova
UIName				= name:misl_nova
UIDescription			= desc:misl_nova



PrimaryBuilding = HKPalace    
Cost = 0
BuildTime = 5184
Speed = 40
Resource = DeathHandBomb
ExplosionType = DeathHandSplat 
Size = 3     
Terrain = Rock, Sand, NBRock, Ramp 
AiSpecial=TRUE




;----- Name -----
UIName				= Name:Rocket_Nova
Name				= Nova Missile
;----- Taxonomy -----
Category			= AirPower
UnitGroup			= FromHKPalace
DeathHand			= yes
Fighter				= yes
;----- Visual -----
Image				= rocket_nova						; topol	; svicbmrocket
Color				= orange
Shadow				= yes
NoShadow			= no
FirersPalette			= yes



;----- Weapons -----
FireAngle= 1
Primary=NukePayload
Armor=special_2
;RA2>Spawned=yes
;RA2>MissileSpawn=yes
TechLevel=7	;RA2>TechLevel=-1	; Cyberian Dawn | NCoder: This was allways really only intended as an experiment. Never thought it would end up as a true buildable part of my mod...
Sight=0	;RA2>Sight=1
RadarInvisible=no
Landable=yes
MoveToShroud=yes
Ammo=1 ;Aircraft are hard wired to require ammo
Speed=15
;----- Armor -----
ImmuneToPsionics		= yes
CanDie				= FALSE
;----- Availability -----
Side				= Soviet
Owner				= Soviet						; Soviet, Russians, Belorussians, Ukrainians, Kazakhs
; House				= Harkonnen
;----- Procuration -----
Owner				= 
TechLevel			= 10
Prerequisite			= SURocketSilo
;----- Movement -----
MovementZone			= Fly
Locomotor			= Rocket
Arm				= 2
High				= yes
VeryHigh			= yes
Ranged				= yes
ROT				= 3							; 4
Acceleration			= 1
Vertical			= yes							; Not a missile or a projectile.  Just go up until...
IgnoresFirestorm		= yes
SubjectToWalls			= no
SubjectToCliffs			= no
SubjectToElevation		= no
CruiseHeight			= 20000	; identical to detonation altitude of the SW's projectile
DetonationAltitude		= 30000;20000; All this does is create the downward pointing one over the target
; FlyBy				= yes
; FlyBack			= yes
Arm				= 2
Proximity			= yes

Prerequisite=NAMISL
FireAngle=1
Strength=50

Primary=NukePayload
Armor=special_2
;RA2>Spawned=yes
;RA2>MissileSpawn=yes
TechLevel=7	;RA2>TechLevel=-1	; Cyberian Dawn | NCoder: This was allways really only intended as an experiment. Never thought it would end up as a true buildable part of my mod...
Sight=0	;RA2>Sight=1
RadarInvisible=no
Landable=yes
MoveToShroud=yes
Ammo=1 ;Aircraft are hard wired to require ammo
Speed=15
Cost=1000
Points=20
ROT=3
Crewed=no
Explodes=no
GuardRange=30
;RA2>Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=2	; < Cyberian Dawn: had the usual miszpelling common in Red Alert 2. I fixed it.

ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SmallGreySSys	; Sparks don't work well here.  SJM
AuxSound1=V3Attack ;Taking off

;----- UI -----
Selectable			= no
;----- Veterancy -----
Trainable			= no



;----- Base Attributes -----
Strength			= 600

;----- Audio -----
AuxSound1			= RocketICBMTakeoff ;Taking off

CruiseHeight=20000	; identical to detonation altitude of the SW's projectile
;----- Weapons -----
Primary				= NukePayload
Proximity			= yes
;----- Armor -----
Armor				= special_2

TechLevel=7	;RA2>TechLevel=-1	; Cyberian Dawn | NCoder: This was allways really only intended as an experiment. Never thought it would end up as a true buildable part of my mod...
Sight=0	;RA2>Sight=1
RadarInvisible=no
Landable=yes
MoveToShroud=yes

;----- Body -----
Strength=50

;------------------------------------------------------------------------------
; Formerly TOPOL (Topol ICBM). 
[Rocket_Nova]:[FROG]
[MislNovaMRV]
;----- Text -----
Name				= Missile Nova MRV
UIName				= name:misl_nova_mrv
UIDescription			= desc:misl_nova_mrv
;----- Payload -----
Cluster				= 10						; 8 ; 9

;------------------------------------------------------------------------------
; MIRV
; Formerly [NovaRocketE]. 
; Subsumes [NovaAirburstP]. 
[MislNovaMIRV]
$inherits			= MislNovaMRV
;----- Text -----
Name				= Missile Nova MIRV
UIName				= name:misl_nova_mirv
UIDescription			= desc:misl_nova_mirv
;----- Weapons -----
Primary				= NovaAirburst
Airburst			= yes
AirburstWeapon			= NovaCluster

Dropping			= yes
Ranged				= yes
ROT				= 4

;------------------------------------------------------------------------------
; Formerly [NukeMissile2]. 
[ShootMislNova]
;----- Payload -----
Damage				= 600
Warhead				= NUKE
Range=30
Projectile=GiantNukeDown  ;MultiMissile
Speed=10
RadLevel=500
Warhead=NUKE
Report=

; Formerly [NovaWeapon]. 
[ShootMislNova2]
$inherits			= ShootMislNova
;----- Payload -----
Damage=1000

;------------------------------------------------------------------------------
; Formerly [NovaAirburst]. 
[ShootMislNovaMIRV]
$inherits			= ShootMislNova
;----- Payload -----
Damage				= 0
Warhead				= Radiation
;----- Projection -----
Projectile			= NovaAirburstP
; Range				= .55

; Formerly [NovaClusterP]. 
[IRVMislNova]
Arm=2
Shadow=no
Proximity=yes
Ranged=yes
Image=DRAGON
ROT=60

;******************************************************************************
;*** Rocket R-7 Semyorka ******************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; R-7 Semyorka - Going Up
; [GiantNukeUp] (ra2/yr)
; Formerly [Rocket_DDA4F_Up]
[RketSemyorkaUp]
;----- Text -----
Name				= Missile Semyorka
UIName				= name:misl_semyorka
UIDescription			= desc:misl_semyorka
;----- 
Arm				= 2
Shadow				= no
Image				= NKMSLUP
Acceleration			= 1
Vertical			= yes				; Not a missile or a projectile.  Just go up until...
DetonationAltitude		= 20000				; All this does is create the downward pointing one over the target
FirersPalette			= yes

;------------------------------------------------------------------------------
; R-7 Semyorka - Coming Down
; [GiantNukeDown] (ra2/yr)
; Formerly [Rocket_DDA4F_Down], [RketSemyorkaDn]. 
[RketSemyorka_Dn]
$inherits			= RketSemyorka_Up
Image				= NKMSLDN
DetonationAltitude		= 30000				; //like blimp bomb

;******************************************************************************
;*** DongFeng 3 Missile *******************************************************
;******************************************************************************

;------------------------------------------------------------------------------
; Kaiten Missile (DongFeng 3) - Going Up
; Formerly [DongFengRocket_Up]. 
[RketDongfengUp]:[RketSemyorkaUp]
;----- Text -----
Name				= Rocket DongFeng 3 (Up)
;----- Gfx -----
Image				= rket_dongfeng3_up			; DF-4UP


; Kaiten Missile (Dong Feng 4?) - Going Up
[NukeUp]
Arm=2
Shadow=no
Image=DF-4UP
Acceleration=1
Vertical=yes ; Not a missile or a projectile.  Just go up until...
DetonationAltitude=20000; All this does is create the downward pointing one over the target
FirersPalette=yes

; Kaiten Missile (Dong Feng 4?) - Coming Down
[NukeDown]
Arm=2
Shadow=no
Image=DF-4DN
Acceleration=1
Vertical=yes ; //like blimp bomb
DetonationAltitude=30000;
FirersPalette=yes

;------------------------------------------------------------------------------
; Kaiten Missile (DongFeng 3) - Coming Down
; Formerly [DongFengRocket_Down]. 
[RketDongfengDn]:[RketSemyorkaDn]
;----- Text -----
Name				= Rocket DongFeng 3 (Down)
;----- Gfx -----
Image				= rket_dongfeng3_dn



