;******************************************************************************
;*** Cruiser Amikiri **********************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[VehicleTypes]
+				= AmikiriCruiser

;------------------------------------------------------------------------------
; Formerly [AmikiriCruiser]. 
[CrusAmikiri]
$inherits			= DestLuyang
;----- Text -----
Name				= 
UIName				= name:
UIDescription			= 
;----- Visual -----
Image				= crus_amikiri
Remapable			= yes
OkToChangeModelColor		= yes
Cameo				= 
AltCameo			= 
ZFudgeColumn			= 9
ZFudgeTunnel			= 15
PrimaryFireFLH			= 
SecondaryFireFLH		= 
;----- Body -----
Strength			= 700
Weight				= 8.5
Size				= 10
SelfHealing			= yes
;----- Turrets -----
Turret				= no
; TurretCount			= 1
; TurretAttach			= jpCrusTurret
; TurretAnim			= jpCrusTur
; TurretAnimIsVoxel		= yes
; TurretROT			= 5
;----- Weapons -----
Primary				= Torpedo
Secondary			= TorpedoM
Elite				= TorpedoE
ElitePrimary			= TorpedoE
EliteSecondary			= TorpedoS
;----- Availability -----
TechLevel			= 9
Prerequisite			= AAShipyard, AACenterTek
Cost				= 2750
;----- Score -----
Points				= 60
;----- Movement -----
Speed				= 4
;----- Perception -----
Sight				= 6
;----- AI -----
ThreatPosed			= 40
