;******************************************************************************
;*** Grenadier ****************************************************************
;******************************************************************************
; Grenade Launcher, existed at least since v. 2008-9-25. 
; Updated to Conscript/Grenadier, 2026-6-3. This unit had not been updated in years, 
; even as the Conscript Grenadier RPG was introduced and the format of the other infantry changed. 
; Moved in the Conscript_Grenadier section from conscript.INI. 

;------------------------------------------------------------------------------
[InfantryTypes]
+				= SUGrenadier

;------------------------------------------------------------------------------
; Grenade Launcher
; Formerly Grenade Launcher [Conscript_Grenadier]. 



; grenadier
[E2]
Primary=Grenade
Strength=50
Armor=none
TechLevel=1
Sight=4
Speed=5
Owner=soviet
Cost=160
Points=10
Explodes=yes


[ConsGren]
$Inherits			= Cons
;----- Text -----
Name				= Conscript Grenadier
UIName				= name:cons_gren
UIDescription			= desc:cons_gren
;;----- Body -----
; Strength			= 150
;----- Weapons -----
Primary				= GrenadeLauncher
ElitePrimary			= GrenadeLauncherE
;----- Availability -----
; RequiredHouses		= Confederation
TechLevel			= 2	;w/1	; lowered the TechLevel to adjust the sidebar - the Grenade Launcher is supposed to appear before the Flak Trooper.
;TechLevel=3
Prerequisite			= subarracks, radar
Speed=5

Cost=275	;w/300;w/250
Soylent=75
;Cost=400
;Soylent=150
Points=10
MovementZone			= InfantryDestroyer			; GEF wow!!! copy paste bug from the original Disk Thrower!
ThreatPosed=10 ; This value MUST be 0 for all building addons
IFVMode				= GRENADES
AllowedToStartInMultiplayer	= no

[SpezBomber]
Damage				= 900;250
ROF				= 70
Range				= 1.5
CellRangefinding		= yes
Projectile			= Invisible
Warhead				= SpezBomb;Mechanical
Report				= SealPlaceBomb
SabotageCursor			= yes

[SpezBomber_E]
Damage				= 900
ROF				= 70
Range				= 4
Projectile			= Grenade
Warhead				= SpezBomb
Report				= GrenadeLaunch
SabotageCursor			= yes

;------------------------------------------------------------------------------
; Grenade Launcher
[SUGrenadier]:[Conscript]
UIName				= Name:Grenadier
Name				= Grenadier
Image				= infy_grenadier_2
;----- Base Attributes -----
Strength			= 150
;----- Weapons -----
Primary				= GrenadeLauncher
ElitePrimary			= GrenadeLauncherE
IFVMode				= GRENADELAUNCHER
;----- Procuration -----
Prerequisite			= NAHAND,RADAR
TechLevel=2	;w/1	; lowered the TechLevel to adjust the sidebar - the Grenade Launcher is supposed to appear before the Flak Trooper.
;TechLevel=3
Owner				= Russians,Confederation,Germans
RequiredHouses			= Confederation				; Introduced at a later version. 
Cost=275	;w/300;w/250
Soylent=75
;Cost=400
;Soylent=150
AllowedToStartInMultiplayer	= no
Sight=5
ThreatPosed=10 ; This value MUST be 0 for all building addons
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
;----- Scoring -----
Points				= 10

;----- Movement -----
Speed				= 5
MovementZone			= InfantryDestroyer


[RPGREN]
Name=RPG Grenadier
Image=E2
Category=Soldier
Primary=RPGGrenadier
Prerequisite=GAWEAP
CrushSound=SQUISH6
Strength=150
Armor=none
TechLevel=2
Pip=green
Sight=7
Speed=4
Owner=GDI
Cost=200
Points=5
VoiceSelect=15-I000,15-I004,15-I012,15-I048
VoiceMove=15-I018,15-I024,15-I044
VoiceAttack=15-I044,15-I050,15-I044,15-I046
VoiceFeedback=15-I058,15-I064
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=InfantryDestroyer
ThreatPosed=15	; This value MUST be 0 for all building addons
EliteAbilities=SCATTER
ImmuneToVeins=yes
