;******************************************************************************
;*** Barbarian ****************************************************************
;******************************************************************************
; Berserker gains the ability to Berserk, which increases attack, decreases defense, and makes him, well, Berzerk. 
; Higher tiers make him gradually lose HP while Berserk is active, Darkside (Dread Spikes & expend HP to attack & EnDrain). 

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
[InfantryTypes]
+				= Barbar			; Barbarian
+				= Barbar2			; Barbarian Veteran
+				= Viking			; Viking 
+				= Viking2			; Viking Veteran
+				= Berserk			; Berserker
+				= Berserk2			; Berserker Veteran
+				= Berserk3			; Berserker Elite
; 8CC9341C51877

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Barbarian
[BARB]
$inherits			= Civilian
;----- Text -----
Name				= Barbarian
UIName				= name:
UIDescription			= desc:
;----- Taxonomy -----
Category			= Soldier
;----- Body -----
Strength			= 125
;----- Weapons -----
Primary				= BarbaricBlade
;----- Armor -----
Armor				= pelt
;----- Availability -----
Side				= Neutral
Owner				= 
; House				= 
TechLevel			= 0
Prerequisite			= TWCT
;----- UI -----
Pip				= beige
OccupyPip			= person_beige
Sight=5
Speed=4
Cost=100
Soylent=20
Points=5
IsSelectableCombatant=yes
;----- Sfx -----

ThreatPosed=5 ; This value MUST be 0 for all building addons
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
ElitePrimary=M1CarbineE
IFVMode=2

;------------------------------------------------------------------------------
[Barbarian2]
$inherits			= Barbarian
;----- Text -----
Name				= Barbarian Veteran
;----- Gfx -----
Insignia			= 

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Vandal
[VNDL]
$inherits			= Barbarian
;----- Text -----
Name				= Vandal
UIName				= name:vndl
UIDescription			= desc:vndl
;----- Body -----
;----- Weapons -----
Primary				= VandalSword
Secondary			= VandalTorch				; Critical hit incinerates. 

;------------------------------------------------------------------------------
; Vandal Veteran
; Higher rate of setting fire to buildings. 
[VNDL2]
$inherits			= VNDL
;----- Text -----
Name				= Vandal Veteran
;----- Attach -----
AttachEffect.Types		= BonusCritVandal

;------------------------------------------------------------------------------
; Vandal Elite
[VNDL3]
$inherits			= VNDL2
;----- Text -----
Text				= Vandal Elite
;----- Attach -----
AttachEffect.Types		= BonusCritVandal, AuraVandalElite			; AuraVandalCmdr

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Viking
[VIKG];VKNG
$inherits			= VNDL
;----- Text -----
Name				= Viking
UIName				= name:viking
UIDescription			= desc:viking
;----- Gfx -----
; Image				= CONS
Pip				= white
OccupyPip			= person_white
;----- Body -----
Strength			= 130
;----- Weapons -----
Primary				= VikingAxe
Secondary			= Hammer				; Construction tool. 
;----- Armor -----
Armor				= mail
;----- Availability -----
; Available to civilization Norse, all houses. 
; Side				= 
Owner				= Norse
; House				= 
Prerequisite			= barracks

Sight=5
Speed=4
Cost=300
Soylent=50
Points=5
IsSelectableCombatant=yes
;----- Sfx -----
VoiceSelect			= SelectNorse
VoiceMove			= CmdMovNorse
VoiceAttack			= CmdAtkNorse
VoiceFeedback			= FearNorse
DieSound			= DieNorse
ThreatPosed=5 ; This value MUST be 0 for all building addons
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
AllowedToStartInMultiplayer=no
IFVMode=3

;------------------------------------------------------------------------------
[Viking2]
$inherits			= Viking
;----- Text -----
Name				= Viking Veteran

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Berserk
[BRZK]
$inherits			= VKNG
;----- Text -----
Name				= Berserk
UIName				= name:berserk
UIDescription			= desc:berserk
;----- Body -----
Strength			= 140
Size				= 1
PhysicalSize			= 1
Weight				= 0.12
SelfHealing			= yes
;----- Weapons -----
Primary				= BerzerkAxe
Secondary			= BerzerkKit
Assaulter=no ; I clear out UC buildings
Prerequisite=NAHAND
CrushSound=InfantrySquish
Strength=130
Armor=Plate
TechLevel=5
Pip=white
Sight=6
Speed=4
Owner=Russians,Confederation,Africans,Arabs
Cost=500
Soylent=125
Points=5
IsSelectableCombatant=yes
VoiceSelect=TeslaTroopSelect
VoiceMove=TeslaTroopMove
VoiceAttack=TeslaTroopAttackCommand
VoiceFeedback=TeslaTroopFear
VoiceSpecialAttack=TeslaTroopMove
DieSound=TeslaTroopDie
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=Infantry
;MovementZone=InfantryDestroyer ;GEF wow!!! copy paste bug from the original Disk Thrower!
ThreatPosed=20 ; This value MUST be 0 for all building addons
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
ImmuneToVeins=yes
Size=1
AllowedToStartInMultiplayer=no
ElitePrimary=ElectricBoltE
IFVMode=6

;------------------------------------------------------------------------------
; Berserk Veteran

;------------------------------------------------------------------------------
; Berserk Elite

;------------------------------------------------------------------------------
; Berserk Heroic
[Brzk4]
$inherits				= Brzk3
;----- Text -----
Name					= Berserk Heroic
;----- Display -----
Insignia				= 
;----- Weapons -----
WeaponN+1				= Warcry

;------------------------------------------------------------------------------
; Berserk Legendary
; Gains Warcry Aura. 
[Brzk5

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; The perfect dark knight
; Proof of concept -- epitome/paragon
[DARK5]
$inherits			= DARK4			; BRZK
;----- Text -----
Name				= Dark Knight Grand Master
UIName				= name:
UIDescription			= desc:
;----- Body -----
Strength			= 666
;----- Weapons -----
Primary				= BloodSaber			; Expend HP to deal additional damage, drain HP. 
Secondary			= BloodSaberNonOrganic		; 

Prerequisite=Barracks
CrushSound=InfantrySquish
LeadershipRating=3
Strength=75
Armor=none
TechLevel=1
Sight=4
BombSight=4 ; detecting ivan's little friends
Speed=4
Pip=Blue
Engineer=yes
Owner=Russians,Confederation,Africans,Arabs,British,French,Germans,Americans,Alliance
ForbiddenHouses=Russians,Confederation,Africans,Arabs
AllowedToStartInMultiplayer=no
Cost=500
Soylent=100
Points=5
IsSelectableCombatant=no
VoiceSelect=EngAllSelect
VoiceMove=EngAllMove
VoiceAttack=EngAllMove
VoiceFeedback=EngAllFear
VoiceSpecialAttack=EngAllAttackCommand
VoiceEnter=EngAllMove
VoiceCapture=EngAllAttackCommand
DieSound=EngAllDie
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=Infantry
ThreatPosed=0 ; This value MUST be 0 for all building addons
SpecialThreatValue=1 ; this should be between 0 and 1
ImmuneToVeins=yes
GuardRange=9
Size=1
PreventAttackMove=yes
IFVMode=1
Trainable=no



; Infantry smashing by Brute
[BerzerkPunch]
Damage=100
ROF=30
Range=1.4
Speed=100
Warhead=BerzerkWH
Report=BruteSmashAttack
Projectile=InvisibleLow
FireInTransport=no;can't fire out of the BattleFortress
Anim=BERZERKANIM
Bright=yes

; Fire by Brute
[BerzerkPunchE]
Damage=100
ROF=20
Range=1.4
Speed=100
Warhead=BerzerkWH
Report=BruteSmashAttack
Projectile=InvisibleLow
;IsElectricBolt=true
;AssaultAnim=UCELEC;the anim to play when a UC building is cleared (assaulters need this on their primary weapon)
FireInTransport=no;can't fire out of the BattleFortress
Anim=BERZERKANIM
Bright=yes

; Tank smashing by Brute
[BerzerkSmash]
Damage=100;150
ROF=30
Range=1.1
Speed=100
Warhead=BerzerkWH2
Report=BruteSmashAttack
Projectile=InvisibleLow
FireInTransport=no;can't fire out of the BattleFortress
Anim=BERZERKANIM
Bright=yes

; Tank smash by Brute
[BerzerkSmashE]
Damage=100
ROF=20
Range=1.1
Speed=100
Warhead=BerzerkWH2
Report=BruteSmashAttack
Projectile=InvisibleLow
FireInTransport=no;can't fire out of the BattleFortress
Anim=BERZERKANIM
Bright=yes

[BerzerkWH]
Verses=100%,100%,100%,0%,0%,0%,30%,30%,20%,200%,100%
InfDeath=10
;GEF Unles we decide to put it back in DirectRocker=yes
Wall=yes
Wood=yes
Psychedelic=yes
Bright=yes
CLDisableGreen=true
CLDisableBlue=true
CombatLightSize=50%
;Particle=RedSparkSys

[BerzerkWH2]
;Verses=0%,0%,0%,100%,20%,100%,0%,0%,0%,0%,0%
InfDeath=10
Wall=yes
Wood=yes
Rocker=yes
DirectRocker=yes
MinDebris=1
MaxDebris=3
Psychedelic=yes
Bright=yes
CLDisableGreen=true
CLDisableBlue=true
CombatLightSize=50%
;Particle=RedSparkSys

Verses=100%,100%,100%,100%,100%,100%,100%,100%,100%,100%,100%
CellSpread=5
PercentAtMax=1

[BerzerkBomb]
Projectile=Invisible
Damage=225
Warhead=BerzerkBombWH
Anim=MININUKE
Range=1.5
ROF=10
Suicide=yes

[BerzerkBombWH]
CellSpread=1.5
PercentAtMax=.4
Verses=140%,120%,80%,100%,70%,60%,40%,25%,10%,60%,80%
;Sparky=yes
;Fire=yes
Bright=yes
CLDisableGreen=true
CLDisableBlue=true
AnimList=CDGAS
InfDeath=1
Psychedelic=yes
;Particle=RedSparkSys
