;******************************************************************************
;*** Manazuru Dropship ********************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[AircraftTypes]
+				= AADropship

;------------------------------------------------------------------------------
; Kalinin K-7
; Formerly AADropship (Manazuru Dropship). 
; Should use bombs against hard ground targets,, and gun against soft ground targets, and air. 





;------------------------------------------------------------------------------
; Bomber Flamingo
; (This name was re-assigned.)
[BmbrFlamingo]
;----- Text -----
Name				= Bomber Flamingo
UIName				= name:bmbr_flamingo
UIDescription			= desc:bmbr_flamingo
;----- Taxonomy -----
Category			= AirPower
IsConsideredAircraft		= yes
;----- Gfx -----
Image				= JAVL
;----- Body -----
Strength			= 260				; Seems comparable in size and armor to Orca Bomber, even if locomotion vastly different. 
Size				= 5
Weight				= 3.5
Points				= 25
;----- Perception -----
Sight				= 0				; Was 3 (Manazuru), should be 0 for call-in aircraft (except Spy Plane). 
;----- Weapons -----
Primary				= DropBomb
Secondary			= CannonAutoMM30
ElitePrimary			= FlamingoRockets
;----- Armor -----
Armor				= aircraft2
; ImmuneToPsionics		= yes
; ImmuneToRadiation		= yes
Armor				= ArmorBioplane
ImmuneToEMP			= yes
ImmuneToPsionics		= yes
;----- Availability -----
Side				= Soviet
Owner				= Soviet,Alliance
; House				= 
TechLevel			= -1
; Prerequisite			= GADROP
Cost				= 1600				; For experience and scoring calculation. 
Spawned				= yes
;----- Score -----
Points				= 30
;----- UI -----
Selectable			= yes
PipScale			= Ammo
;----- AI -----
CanPassiveAquire		= no
CanRetaliate			= no
LeadershipRating		= 10
ThreatAvoidanceCoefficient	= 1.0
GuardRange			= 30
;----- Perception -----
Sight				= 0
;----- Movement -----
Speed				= 12			; Lowered for bombing run success, was 20, 30. 
Locomotor			= Fly
MovementZone			= Fly
FlyBy				= yes
Landable			= no
MoveToShroud			= yes


Landable			= yes
Speed				= 18
PitchSpeed			= .4
FlightLevel			= 1600
ROT				= 2


;----- Sfx -----
; Share voiceset with Badger (only a few lines are needed for call-in units). 
VoiceSelect			= VoiceSelectBadger
VoiceFeedback			= VoiceFearBadger
MoveSound			= PDPlaneMoveLoop			; IntruderMoveLoop
AuxSound1			= DropshipTakeoff			; Taking off
AuxSound2			= DropshipLanding			; Landing
DieSound			= GenAircraftDie
VoiceCrashing			= VoiceDieBadger
CrashingSound			= PDPlaneDie
ImpactLandSound			= GenAircraftCrash
;----- Load -----
Crewed				= yes
Survivor.Side2			= UNPilot				; Zombie
Survivor.PilotCount		= 1; 3
Survivor.RookiePilotChance	= 100
Survivor.VeteranPilotChance	= 100
Survivor.ElitePilotChance	= 100
Ammo				= 2

FlightLevel=2450
Cost=1600
PitchAngle=0
RollAngle=0	;i remember this works
TurnAngle=0	;??? let's test
;----- Damage & Destruction -----
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DamageParticleSystems		= SparkSys,SmallGreySSys
MinDebris			= 2
MaxDebris			= 5
DeathWeapon			= Collision

Explodes			= yes
DeathWeapon			= ChemBombZ
;----- Veterancy -----
; Trainable			= no

;------------------------------------------------------------------------------
; Bio Bomber
[BomberZhen]
;----- Text -----
Name				= Bomber Zhenniao
;----- Body -----
Strength			= 500
;----- Weapons -----
Primary				= ChemBomb
Secondary			= ChemBomb
Elite				= ChemBombZ
ElitePrimary			= ChemBombZ
EliteSecondary			= ChemBombA

PitchAngle=0



[CraneBomber]
;----- Name -----
UIName				= Name:Manazuru
Name				= Manazuru Dropship
;----- GFX -----
Image				= crane			; lifter_manazuru
;----- Taxonomy -----
Category			= AirLift
IsDropship			= yes
Carryall			= yes
;----- UI -----
PipScale			= Passengers
;----- Load -----
Ammo				= 0
Passengers			= 10
;----- Weapons -----
Primary				= WeaponDummy

; Manazuru gun
[ManazuruGun]
Damage				= 50;1 ;was 50
ROF				= 0;50
Range				= 6
Projectile			= ManazuruBullet_1
Speed				= 100
Warhead				= SA
Report				= GIAttackDeployed
Anim				= GUNFIRE

[DropShell]
Image=NULL
ROT=100
;Arcing=true
AA=yes ;no
SubjectToElevation=no
SubjectToCliffs=no
SubjectToWalls=no




;------------------------------------------------------------------------------
[DummyPayloadNapalm]
Name				= Dummy Payload Napalm

Primary				= HellBomb;EMPulseBomb
Spawned=yes
LeadershipRating=10
Selectable=no
RadarInvisible=no
Sight=0
Landable=no
MoveToShroud=yes
PitchAngle=0
Speed=30
Owner=British,French,Germans,Americans,Alliance,Russians,Confederation,Africans,Arabs,YuriCountry
Points=30
ROT=2
Crewed=yes
Ammo=1
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=5
ThreatPosed=0
DamageParticleSystems=SparkSys,SmallGreySSys
ImmuneToPsionics=yes
CanPassiveAquire=no
CanRetaliate=no
MoveSound=PDPlaneMoveLoop
DieSound=
VoiceFeedback=BadgerVoiceDying
CrashingSound=PDPlaneDie
MinDebris=2
VoiceCrashing=BadgerVoiceDie
ImpactLandSound=GenAircraftCrash
Fighter=yes
ElitePrimary=EMPulseBomb
Trainable=no
DeathWeapon=BlimpBombEffect
DeathWeaponDamageModifier=.1
FlyBy=true
ThreatAvoidanceCoefficient=1.0
ImmuneToEMP=yes
Survivor.Side2=APILOT
Survivor.PilotCount=1
Survivor.RookiePilotChance=100
Survivor.VeteranPilotChance=100
Survivor.ElitePilotChance=100
