;
;
;
; This unit is distinct from the Bradley. 
; Upgrades: Machine Gun, ATGM, Faster, Sight, Sensors, Target Laser/Painter, Sniper

;------------------------------------------------------------------------------
[VehicleTypes]
+				= TnkLgt			; Tank Light Beagle, Rookie, Upgrade nul
+				= TnkLgt_a1			; Tank Light Beagle, Rookie, Upgrade Missile
+				= TnkLgt_e1			; Tank Light Beagle, Veteran, Upgrade nul
+				= TnkLgt_a1e1			; Tank Light Beagle, Veteran, Upgrade Missile

;------------------------------------------------------------------------------
; Light Tank - VC's comment: Okies, so I put the T-34 to the Sov side, and this one goes into allied (where T-34 used to be).
; It's a simple side swap and everyone's happy! ('course it still requires me to change the vxl, because current LTNK voxel is crappy).
; Formerly LTNK, LightTank. 
; RA-era Light Tank
; Formerly [TankLight]. 
[TnkLgt]:

Speed=9
Points=30

;----- Text -----
Name				= Tank Light
UIName				= name:tank_lgt
UIDescription			= desc:tank_lgt
;----- Gfx -----
Image				= ltnk
ZFudgeColumn			= 8
ZFudgeTunnel			= 13
DamageEffect			= MediumDamageFX
ChaosEffect			= MediumChaosFX
HawkEffect			= MediumHawkFX
;----- Taxonomy -----
Category			= AFV
UnitGroup			= FromFactory
;----- Body -----
Health				= 2400
Strength			= 300
Weight				= 3.5
Size				= 3
;----- Weapons -----
Primary				= CannonMM75
Elite				= CannonMM90
ElitePrimary			= CannonMM90
EliteSecondary			= 
NoAmmoWeapon			= 
OpportunityFire			= yes
TargetLaser			= yes
;----- Armor -----
Armor				= heavy
StormDamage			= 10
;----- Availability -----
Side				= Allies
Owner				= Allies			; British, French, Germans, Americans, Alliance
; House				= 
TechLevel			= 4				; 3
Prerequisite			= UNFactory
PrimaryBuilding			= UNFactory
; SecondaryBuilding		= 
Cost				= 700				; 550 ; 500
AllowedToStartInMultiplayer	= yes
Starportable			= yes
CrateGift			= yes
CrateGoodie			= yes
BuildTimeMultiplier=1.5;Individual control of build time
TechLevel=6
;----- Score -----
Points				= 25
;----- Load -----
Crewed				= yes
Ammo				= 1
;----- Turrets -----
Turret				= yes
TurretAttach			= UNLightTankTurret
;----- Perception -----
Sight				= 4;8
Sight				= 5						; 8
;----- Sfx -----
VoiceSelect			= GenAllVehicleSelect				; 25-I000,25-I002,25-I004,25-I006
VoiceMove			= GenAllVehicleMove				; 25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack			= GenAllVehicleAttackCommand			; 25-I014,25-I022,25-I024,25-I026
VoiceFeedback			= 
DieSound			= GenVehicleDie
MoveSound			= GrizzlyTankMoveStart
CrushSound			= TankCrush
;----- Movement -----
Locomotor			= Drive
MovementZone			= Destroyer
Terrain				= Rock, Sand, NBRock, Ramp
Speed				= 7			; 8 
ROT				= 5
Tracked				= yes
IsTilter			= yes
; Accelerates			= no
Crushes				= yes
Crusher				= yes
TooBigToFitUnderBridge		= yes
;----- UI -----
IsSelectableCombatant		= yes
;----- AI -----
AiTank				= yes
ThreadPosed			= 15				; 40
TastyToWorms			= True
WormAttraction			= 7
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys, SmallGreySSys
DamageSmokeOffset		= 100, 100, 275
ExplosionType			= Explosion
Explosion			= TWLT070, S_BANG48, S_BRNL58, S_CLSN58, S_TUMU60
Debris				= DebrisLage
DebrisTypes			= TnkLgt, TnkLgtTur, TnkLgtBarl, ShellMM75, gastank, piece
DebrisMaximums			= 1, 1, 1, 2, 2, 4
DebrisMinimums			= 0, 0, 0, 1, 1, 2
MaxDebris			= 
MinDebris			= 
;----- Veterancy -----
; VeteranAbilities		= STRONGER,FIREPOWER,SIGHT,FASTER	; +ROF
; EliteAbilities		= SELF_HEAL,STRONGER,FIREPOWER,ROF

;------------------------------------------------------------------------------
; Mastiff Medium Tank
; Grizzly Tank (ra2/yr)
; Formerly [tank_mastiff_a]. 
[TankLgt2]
;----- Text -----
Name				= Mastiff Battle Tank
UIName				= name:
UIDescription			= desc:
;----- Gfx -----
Image				= GTNK
Primary=105mm
TechLevel=2
Sight=8
Speed=7
MaxDebris=2
ThreatPosed=15	; This value MUST be 0 for all building addons
ElitePrimary=105mmE
