;
;
;

;------------------------------------------------------------------------------
; [VesselTypes]
[VehicleTypes]
+				= CorvTsla
+				= FrigTsla
+				= CorvRad
+				= FrigRad

;------------------------------------------------------------------------------
[Corv]
;----- Text -----
Name				= Corvette
UIName				= name:corv
UIDescription			= desc:corv
;----- Taxonomy -----
Category			= Vessel				; AFV
Naval				= yes
;----- Body -----
Strength			= 360
Weight				= 5					; Frigate is 3 in ER, but since vehicle weight is normally 3.5, this seems too low. 
;----- Turrets -----
Turret				= yes
;----- Weapons -----

NavalTargeting			= 5
OpportunityFire			= yes
;----- Armor -----
Armor				= heavy					; wood
;----- Availability -----
Side				= Soviet
Owner				= Soviet
; House				= Russians
; RequiredHouses		= Russians
TechLevel			= 5
Prerequisite			= SUShipyard,SURadar
Cost				= 
AllowedToStartInMultiplayer	= no
CrateGoodie			= yes
;----- Perception -----
Sight				= 5

Points=60

;----- Load -----
Crewed				= yes				; ER is no. 

;----- Sfx -----
VoiceSelect			= GenSovWaterSelect
VoiceMove			= GenSovWaterMove
VoiceAttack			= GenSovWaterAttackCommand
VoiceFeedback			= 
DieSound			= GenSmallWaterDie
MoveSound=DestroyerMoveStart
MaxDebris=4
;----- Movement -----
Locomotor			= Ship				; {4A582741-9839-11d1-B709-00A024DDAFD1}
SpeedType			= Float
MovementZone			= Water
; MovementRestrictedTo		= Water
Speed				= 6
ROT				= 6
Crusher				= yes				; Frigate is no in ER, as ships usually are in ra2, but I don't know why. 
;----- AI -----
ThreatPosed			= 15
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys,SmallGreySSys
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
;----- Veterancy -----
VeteranAbilities		= STRONGER,FIREPOWER,ROF,SIGHT,FASTER
EliteAbilities			= SELF_HEAL,STRONGER,FIREPOWER,ROF

;------------------------------------------------------------------------------
; Tesla Ship
; Formerly [TeslaShip]. 
[CorvTsla]:[Corv]
;----- Text -----
Name				= Corvette Tesla
UIName				= name:corv_tsla			; name:TeslaShip
UIDescription			= desc:corv_tsla
;----- Weapons -----
Primary				= ShipBolt
ElitePrimary			= ShipBoltE
;----- Veterancy -----

;------------------------------------------------------------------------------
; Rad Corvette
[CorvRad]
;----- Text -----
Name				= Corvette Rad
UIName				= name:corv_rad
UIDescription			= desc:corv_rad

;------------------------------------------------------------------------------
; ER's TESLAFRIG (Tesla Frigate)
[FrigTsla]:[CorvTsla]
;----- Text -----
Name				= Frigate Tesla
UIName				= name:frig_tsla
UIDescription			= desc:frig_tsla
;----- Gfx -----
Image				= TESLFRIG
;----- Body -----
Strength			= 600
Weight				= 3
Size				= 20
;----- Perception -----
Sight				= 7
Sensors				= yes
SensorsSight			= 8
;----- Availability -----
Cost				= 1200
CrateGoodie=no
AllowedToStartInMultiplayer=no
Points=20
IsSelectableCombatant=yes

ThreatPosed=25

