;
;
;

;------------------------------------------------------------------------------
[Countries]
+				= Yugoslavians

;------------------------------------------------------------------------------
; Not Yugoslavs. ;)
[Yugoslavians]
;----- Text -----
Name				= Yugoslavians
UIName				= name:yugoslavians
UIDescription			= desc:yugoslavians
Prefix				= SU
Suffix				= YU				; Changed Yuri to YA. 
;----- Gfx -----
Color				= DarkRed
Multiplay			= yes
Side				= Nod
SmartAI				= yes
