
; Haymaker [HAY_MAK] (Butcher v16)
; Cyborg Missile - not the same as Missilier Cyborg. 
; Just like Cyborg Gun is not Gunner Cyborg. 
[CybgMisl]
;----- Text -----
UIName				= name:cybg_misl
UIDescription			= desc:cybg_misl
Name				= Haymaker Missile Cyborg
Category=Soldier
Prerequisite=GAPILE,CLK_DEP
Primary=BikeMissile
CrushSound=SQUISHY2
Crushable=no
TiberiumProof=yes
TiberiumHeal=yes
Fearless=yes
Cyborg=yes
Pip=white
Strength=300
Armor=light
TechLevel=2
Sight=5
Speed=4
Owner=GDI
Cost=1500
Points=5
VoiceSelect=22-I000,22-I002,22-I006
VoiceMove=22-I008,22-I010,22-I014,22-I016,22-I020
VoiceAttack=22-I008,22-I010,22-I012,22-I018
VoiceFeedback=
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=Infantry
DamageParticleSystems=SparkSys
ThreatPosed=15
EliteAbilities=STRONGER FASTER FIREPOWER
ImmuneToVeins=yes
Image=CYBORG
Cloakable=yes
Elite=M1Carbine
