;******************************************************************************
;*** Rocketeer ****************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[InfantryTypes]
+				= Rocketeer

;------------------------------------------------------------------------------
[Rocketeer]:[GI]
;----- Text -----
Name				= Rocketeer
UIName				= name:Rocketeer
UIDescription			= desc:rocketeer
;----- GFX -----
Image				= infy_jumpjet_un
Pip				= bluesky
OccupyPip			= PersonBlueSky
;----- Taxonomy -----
ConsideredAircraft		= yes
;----- Body -----
Strength			= 125					; Has more HP than the AA JumpJet infantry, but less armor. 
;----- Weapons -----
Primary				= RocketeerGun
; Elite				= JumpGunE
; ElitePrimary			= RocketeerGun_E
; EliteSecondary		= JumpGrenade
;----- Availability -----
ForbiddenHouses			= SteelTalons, Spectrum, Stronghold, TankArmy
Prerequisite			= UNBarracks, radar
TechLevel			= 3
;----- Perception -----
Sight				= 8

Crushable=yes;no
;OpportunityFire=yes ;gs Doesn't work because will fly backwards to point towards it and never shoot
Armor=none;light
TechLevel=3;6
;Sight=6
Sight=8;6
Speed=9;8
AllowedToStartInMultiplayer=no
Cost=600;700
Soylent=300
Points=15;5

Pip=white
Speed=9
;----- Audio -----
VoiceSelect			= RocketeerSelect
VoiceMove			= RocketeerMove
VoiceAttack			= RocketeerAttackCommand
VoiceFeedback			= RocketeerFear
VoiceSpecialAttack		= RocketeerMove
DieSound			= 
CrashingSound			= RocketeerDie
ImpactLandSound			= RocketeerCrash
MoveSound			= RocketeerMoveLoop
;----- AI -----
Fearless			= yes
;----- Movement -----
MovementZone			= Fly				; This needs to be None, like aircraft
Speed				= 
SpeedType			= Hover
BalloonHover			= yes				; ie never land
HoverAttack			= yes
Locomotor			= Jumpjet
JumpJet				= yes
JumpjetSpeed			= 30				; params not defined use defaults (old globals way up top called Jumpjet controls)
JumpjetClimb			= 20				; HY increase climb speed; used to be 10
JumpjetCrash			= 25				; Climb, but down
JumpJetAccel			= 10
JumpJetTurnRate			= 10
JumpjetHeight			= 500
JumpjetWobbles			= .01
JumpjetDeviation		= 1
JumpjetNoWobbles		= yes ; the wobbling is in the Hover sequence of the art, instead of being programmer art/ sine wave
Landable			= yes
DeployToLand			= yes				; New synthesis attribute. 
;----- Damage & Destruction -----
DamagedParticleSystem		=				; new 
Crashable			= yes
ThreatPosed=15	; This value MUST be 0 for all building addons
;----- Veterancy -----
VeteranAbilities		= STRONGER,FIREPOWER,ROF,SIGHT,FASTER
EliteAbilities			= SELF_HEAL,STRONGER,FIREPOWER,ROF
; EliteAbilities		= C4,STRONGER			; Where is this from? 
;----- Resource -----
IsSimpleDeployer		= yes
ConvertDeploy.Type		= RocketeerL

;------------------------------------------------------------------------------
[RocketeerL]
$inherits			= Rocketeer
;----- Text -----
Name				= Rocketeer (Landed)
;----- Weapons -----
Primary				= JumpGunGround
Secondary			= JumpGunGround
Elite				= JumpGunGround
ElitePrimary			= JumpGunGroundE
; EliteSecondary		= JumpGrenadeE
;----- Resource -----
ConvertDeploy.Type		= Rocketeer
;----- Movement -----
MovementZone			= Infantry
Locomotor			= Walk
Speed				= 3
SpeedType			= Foot

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Rocketeer Heroic
[Rocketeer]
;----- Text -----
Name				= Rocketeer Heroic
;----- Body -----
Strength			= 575

;----- Weapons -----
Primary				= 20mm
ElitePrimary			= 20mmE
