;******************************************************************************
;*** Tower Guard Concrete *****************************************************
;******************************************************************************
; Upgrades from the Tower Guard Wood. 
; Has a spotlight, machine gun, and alarm. 

;------------------------------------------------------------------------------
[BuildingTypes]
+				= TowrWood
+				= TowrWood2
+				= TowrBrik
+				= TowrConc			; CA0014
+				= TowrConc2			; GASPOT

TechLevel=6
Cost=500
TargetLaser=yes
Adjacent=3
AIBuildThis=yes

;------------------------------------------------------------------------------
; Soviet Brick Guard Tower
[TowrBrik]
;----- Taxonomy -----
IsBase= no
BaseNormal= no
IsBaseDefense			= yes
;----- UI -----
BuildCat			= Combat
;----- Load -----
Crewed				= yes				; This has caused some debate...
;CanBeOccupied=yes
;MaxNumberOccupants=2
;DistributedFire=yes

;------------------------------------------------------------------------------
; The short and stout one. 
; Used by civvie groups (Forgotten/Scavengers) in urban settings. 
; This is a difficult one to place, because it should exist both as a purely benign civilian structure, 
; and when owned by one of those groups, it should be armed. 
; CA0014 (TS), arctic maps only. 
; ArgCmdr's Observation Tower
; Formerly [Tower_Concrete_1], [TowerConc1]. 
; Re-subsumes [CA0022]. 
; SHP: ArgCmdr
[TowrConc1]
$inherits			= TowrBrik
;----- Text -----
UIName				= Name:Tower_Conc
Name				= Observation Tower A
Nominal				= yes

UIName=Name:CA0014
Name=RA2 Observation Tower B

UIName=Name:CA0014
Name=RA2 Observation Tower A
;Name=Observation Tower
;----- Gfx -----
Image				= caotwr
; Cameo				= icon_towrobsv
;----- Body -----
Strength			= 300
;----- Weapons -----
Primary				= Vulcan
ElitePrimary			= VulcanE

Primary=VulcanCannon
Primary=Para
Secondary=M1CarbineE

;----- Armor -----
Armor= steel; heavy (ts)
;----- Availability -----
Owner				= Special;Neutral,OTL,Scavengers
TechLevel			= 2;1;-1
Prerequisite			= Outpost
Cost				= 500
;----- Scoring -----
Points= 5
;----- Damage & Destruction -----
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
;TibSun>MaxDebris=0

;LeaveRubble=yes
;Sight=6 ; UC base values
Sight=9 ; Let's see if that works.

IsTrench			= Tunnel
Power				= -10
RadarInvisible=yes
Armor				= concrete			; steel, TS: heavy
Armor				= steel				; TS: heavy
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DebrisAnim=Dbris3sm,Dbris4lg,Dbris4sm,Dbris6sm,Dbris7lg,Dbris7sm,Dbris8sm,Dbris10lg,Dbris10sm
MaxDebris			= 15				; TS: 0
MinDebris=5
DamageParticleSystems=SmallGreySSys,BigGreySmokeSys

;Prerequisite.Lists=2
RadarInvisible=yes
Points=5
Armor=steel		; TibSun>heavy
;TibSun>MaxDebris=0
;
;Selectable=no
ClickRepairable=no
Prerequisite=CACOMD

;------------------------------------------------------------------------------
; Guard Tower
; GASPOT (TS)
; Formerly [TowerConcrete], [TowerGuardConc], [TowrConc]. 
; Formerly derived from TowrWood, now intercalated TowrConc. 
[TowrConc2]
$inherits			= TowrConc
;----- Text -----
Name				= Tower Concrete
UIName				= name:towr_conc
UIDescription			= desc:towr_conc
;----- Gfx -----
HasSpotlight			= true				;; Causes IE 
;----- Body -----
Strength			= 400
;----- Perception -----
Sight				= 

Points=50
