;******************************************************************************
;*** Buggy ********************************************************************
;******************************************************************************
;******************************************************************************
;*** Quad *********************************************************************
;******************************************************************************
; This is now disentangled from the Buggy and subsumes the Smuggler Quad of Dune. It's just a basic ATV. 
; Buggy 1: Rocket Buggy (Gen/ZH; HP = 120)
; Buggy 2: DPV (TD; HP = 140)
; Buggy 3: Attack Buggy (TS; HP = 220)
; Upgrades: 

;------------------------------------------------------------------------------
[VehicleTypes]
+				= Quad
+				= BggyGun_1
+				= BggyPyro
+				= BggyToxin
+				= BggyLasr
+				= BggyRkets
; 75B986CAEADA9

;------------------------------------------------------------------------------
; Dune's SMQuad (Smuggler Quad)
; Formerly [Quad]. 
[Bggy]:[Trik]
;----- Text -----
Name				= Raider
UIName				= name:raider
UIDescription			= desc:raider
;----- Taxonomy -----
Category			= Recon				; AFV
UnitGroup			= FromFactory
;----- Gfx -----
Image				= bggy
DamageEffect			= MediumDamageFX
ChaosEffect			= MediumChaosFX
HawkEffect			= MediumHawkFX
;----- Body -----
Health				= 1000
Strength			= 125
Size				= 2
;----- Turrets -----
Turret				= yes
TurretAttach			= ORAPCBase
;----- Weapons -----
Primary				= 
;----- Armor -----
Armor				= light_dune
Armour				= light
StormDamage			= 10
ImmuneToVeins			= yes
;----- Perception -----
Sight				= 
ViewRange			= 4,14,InfRock
;----- Availability -----
Side				= 
Owner				= Nod,Arabs,Africans,Persians,Kurds
DoubleOwned			= yes
House				= Incidental
TechLevel			= 5
; Prerequisite			= NAWEAP
Starportable			= true
Cost				= 1200
BuildTime			= 589
CrateGoodie			= yes
ReinforcementValue		= 7
;----- Score -----
Score				= 3
;----- AI -----
AiTank				= true
AIThreat			= 60
TastyToWorms			= true
WormAttraction			= 6


IsSelectableCombatant=yes

IsTilter=yes
TechLevel=2
Sight=6
Speed=10
Cost=500
Points=25
ROT=8

;----- Sfx -----
VoiceSelect			= SelectRaider
VoiceMove			= CmdMovRaider
VoiceAttack			= CmdAtkRaider
VoiceFeedback			= FearRaider

;----- Movement -----
ROT				= 
TurnRate			= 0.175
Speed				= 6.0
SpeedType			= Wheel
Locomotor			= Drive
Terrain				= Rock, Sand, NBRock, Ramp
MovementZone			= Normal

ThreatPosed=10	; This value MUST be 0 for all building addons
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys,SmallGreySSys
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
ExplosionType			= Explosion
Debris				= DebrisMedium
DebrisTypes			= TIRE
DebrisMaximums			= 4
MaxDebris			= 3
;----- Veterancy -----
VeterancyLevel			= 6
ExtraDamage			= 50
VeterancyLevel			= 14
ExtraArmour			= 50  
VeterancyLevel			= 28
CanSelfRepair			= 1

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Attack Buggy
; Buggy (TD)
; Formerly [Buggy]. 
[Bggy2]:[Bggy]
;----- Text -----
Name				= Raider II				; Buggy
UIName				= name:buggy
UIDescription			= desc:buggy
;----- Body -----
Strength			= 140
;----- Turrets -----
Turret				= no
;----- Weapons -----
Primary				= M60
ElitePrimary			= M60_E
EliteSecondary			= RaiderGrenadeLauncher
Ammo				= 1
NoAmmoWeapon			= 0
;----- Armor -----
Armor				= light
;----- Procuration -----
Owner				= Nod,CobraCell,ScorpionCell,SpiderCell
TechLevel			= 2
Prerequisite			= NDFactory

IsTilter=yes
TechLevel=2
Sight=6
Speed=10
CrateGoodie=yes
Owner=Nod
Cost=500
Points=25
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
;----- Veterancy -----
; EliteOptions			= CRUSHER, FIREPOWER, FASTER
EliteAbilities			= CRUSHER

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Raider Buggy
; Formerly [BuggyGun_1], [Bggy2Gun]. 
; Subsumes [Buggy_2] (empty section). 
[Bggy3]:[Bggy2]
;----- Text -----
Name				= Attack Buggy
UIName				= Name:Buggy_Gun
UIDescription			= desc:
;----- Gfx -----
Image				= bggy3
;----- Body -----
Strength			= 220
;----- Weapons -----
Primary				= RaiderCannon
Elite				= RaiderCannonE
ElitePrimary			= RaiderCannonE
;----- Armor -----
Armor=light
Turret=yes
IsTilter=yes
TechLevel=2
Sight=6
Speed=10
CrateGoodie=yes
Owner				= Nod,Scavengers
Cost				= 500;750
Points=25
PipScale=Passengers
Passengers=3
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
;----- Sfx -----
VoiceSelect			= SelectVehUSAGeneric	; 25-I000,25-I002,25-I004,25-I006
VoiceMove			= CmdMovVehUSAGeneric	; 25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack			= CmdAtkVehUSAGeneric	; 25-I014,25-I022,25-I024,25-I026
VoiceFeedback			= 
MaxDebris			= 9				; 3
DebrisTypes			= BuggyGun_1,PIECE,TIRE		; TIRE
DebrisMaximums			= 1,4,4				; 4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
ImmuneToVeins=yes
IsSelectableCombatant=yes
Size=3

;------------------------------------------------------------------------------
; This Buggy has a heavy sniper rifle installed on the roof. 
; Formerly "SNIPEBGGY", Buggy_Sniper, [BuggySniper]. 
[BggySniper]:[Bggy]
;----- Text -----
Name				= Buggy Sniper
UIName				= Name:bggy_snipr
UIDescription			= desc:bggy_snipr
;----- Weapons -----
Primary				= Sniper
Secondary			= RaiderCannon
Elite				= SniperTower
ElitePrimary			= AMR
EliteSecondary			= RaiderCannonE2
;----- Availability -----
Prerequisite			= NAWEAP,NATECH
Cost				= 800
;----- Turrets -----
Turret				= yes
IsTilter=yes
TechLevel=2

MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
ThreatPosed=10

;------------------------------------------------------------------------------
; Grenade Buggy
; Formerly "Buggy_Grenades", [BggyGren]. 
[Bggy3Gren]:[Bggy]
;----- Text -----
Name				= Grenade Buggy
UIName				= Name:bggy_gren
UIDescription			= desc:bggy_gren
;----- Weapons -----
Primary				= RaiderGrenadeLauncher
Secondary			= RaiderGun
ElitePrimary			= RaiderGrenadeLauncher_E
EliteSecondary			= RaiderGun_E

NoAmmoWeapon	= 1

;----- Load -----
Ammo			= 1
Reload		= 30

Turret=yes
IsTilter=yes
TechLevel=2
Sight=6
Speed=10
CrateGoodie=yes
Owner=Scavengers
Cost=500
Points=25
ROT=8
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
DieSound=GenVehicleDie
MoveSound=FlakTrackMoveStart
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
ImmuneToVeins=yes
Size=3
OpportunityFire=yes

;------------------------------------------------------------------------------
; Attack Buggy, gun and chem grenades
; Formerly [BuggyGun_2]. 
[Bggy3GrenTox]:[Bggy3Gren]
Name			= Attack Buggy 2
Prerequisite=NAWEAP
Primary=RaiderCannon
Secondary=GRNCHEM
Explodes		= 
DeathWeapon		= 
DebrisTypes		= BuggyGun_1,Piece,Tire,GasTank
DebrisMaximums		= 1,4,4,2

;------------------------------------------------------------------------------
; Mortar Buggy
[Buggy_Mortar]:[Buggy]
;----- Text -----
UIName				= Name:Buggy_Mortar
Name				= Mortar Buggy
;----- Base Attributes -----
Strength			= 120

;----- Weapons -----
Primary				= 

;----- Load -----
InitialPayload.Types		= Mujahid
InitialPayload.Num		= 1
NoManualDeploy			= yes
OpenTopped			= yes
Crewed				= yes


IsTilter=yes
TechLevel=2
Sight=6
Speed=10
Cost=500
Points=25
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
ImmuneToVeins=yes



; Rocket Buggy (Rocket Pods Upgrade)
[Buggy_Rockets_A1]:[Buggy_Rockets]
UIName				= Name:Buggy_Rockets
Name				= Rocket Buggy (Rocket Pods Upgrade)

;----- Procuration -----
Prerequisite			= Workshop,Tech_RocketPods

;----- Load -----
Ammo=6
Reload=100


[BuggyRockets]
Name=Attack Buggy3
Prerequisite=NAWEAP
Primary=BFM                   ;RaiderCannon
;Secondary=GRNCHEM
Category=Recon
Strength=220
Armor=light
Turret=yes
IsTilter=yes
TechLevel=2
Sight=6
Speed=10
CrateGoodie=yes
Owner=Nod
Cost=750
Points=25
PipScale=Passengers
Passengers=3
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=9
DebrisTypes=DBGGY,PIECE,TIRE
DebrisMaximums=1,4,4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
ImmuneToVeins=yes

; Rocket Attack Buggy
; [SAMBGGY]
; Formerly [Buggy_Rockets]. 
[BggyMisl]
;----- Text -----
Name				= Buggy SAM
Prerequisite=NAWEAP,NATECH
Primary=RedEye
Category=Recon
Strength=220
Armor=light
Turret=yes
IsTilter=yes
TechLevel=2
Sight=6
Speed=10
CrateGoodie=yes
Owner=Nod
Cost=800
Points=25
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
ImmuneToVeins=yes
Elite=RedEye2

;------------------------------------------------------------------------------
; Rocket Buggy
; Formerly "RKBGY", "RocketBuggy", "Buggy_Rockets". 
[BggyRkets]:[Bggy]




Prerequisite=NAWEAP
Primary=HummerTOW
IsTilter=yes
TechLevel=2
Sight=6
Speed=10
Cost=500
Points=25
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
;
IsSelectableCombatant=yes
Size=3




;----- Text -----
Name				= Rocket Buggy
UIName				= name:bggy_rkets
UIDescription			= desc:bggy_rkets
;----- Taxonomy -----
Category			= LRFS
;----- Body -----
Strength			= 120
;----- Weapons -----
Primary				= LnchrMislFagot			; QassamRocketLauncher
ElitePrimary			= LnchrMislFagotE2			; QassamRocketsE;MedusaRockets3E
Turret=yes
;----- Availability -----
Owner				= Nod,Arabs,Africans,Persians,Kurds
Prerequisite			= Workshop
Prerequisite.Negative		= Tech_BuggyRocketPods

TechLevel=2
Sight=6
Speed=10
CrateGoodie=yes
Owner=British,Arabs,Africans
Cost=900
Points=25
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
PipScale=Ammo
Ammo=6
Reload=100

;------------------------------------------------------------------------------
; Flame Buggy
; Angolan Special
; Formerly FlameBuggy. 
; Upgrades: Oil Squirt, Flamethrower, Nitro Boost, Flame Trail
[BggyPyro]:[Bggy]
;----- Text -----
Name				= Buggy Flame
UIName				= Name:Buggy_Pyro
UIDescription			= desc:buggy_pyro
;----- Availability -----
RequiredHouses			= Angolans
Prerequisite			= Workshop,BuggyTech,PyroTech
Cost				= 700
;----- Weapons -----
Primary				= MolotovThrower			; FlamerVeh
Secondary			= SquirtOil
ElitePrimary			= FlameThrower				; FlamerVehE2
EliteSecondary			= SquirtOilE2
;----- Damage & Destruction -----
DeathWeapon			= FuelExplosion

;------------------------------------------------------------------------------
; Toxin Buggy
; Formerly [ToxinBuggy], [BuggyToxin]. 
[BggyToxin]:[Bggy]
;----- Text -----
Name				= Buggy Toxin
UIName				= name:bggy_toxin
UIDescription			= desc:bggy_toxin
;----- Availability -----
Prerequisite			= Workshop,BuggyTech,ChemTech
Primary				= ChemSpray
ElitePrimary			= ChemSpray_E
Cost				= 600
;----- Damage & Destruction -----
DamageParticleSystems		= SparkSys,SmallGreenSSys

;------------------------------------------------------------------------------
; Buggy Laser
; Formerly [LaserBuggy]. 
[BggyLasr]:[Bggy]
UIName				= Name:Buggy_Laser
Name				= Laser Buggy
Prerequisite			= Workshop,BuggyTech,LaserTech
Primary				= WagonLaserCannon
ElitePrimary			= WagonLaserCannon_E

;******************************************************************************
;*** Blast Buggy **************************************************************
;******************************************************************************
; Special. 

;------------------------------------------------------------------------------
; Bomb Buggy
; Formerly [DBGGY], [BlastBuggy], [Buggy_Blast]. 
[BggyBlst]:[Bggy]
;----- Text -----
Name				= Buggy Blast
UIName				= name:bggy_blst
UIDescription			= desc:bggy_blst
;----- Taxonomy -----
Category			= AFV				; Not really "A", but we are in a bind, there is no better fit. 
;----- GFX -----
Image				= buggy_blast
;----- Body -----
Strength			= 200				; Explosives easily triggered. Not too fragile now. Was 110. ; Was 100. ; This baby is fragile! ; Was 220. 
;----- Turrets -----
Turret				= no
;----- Weapons -----
Primary				= Suicide
; Secondary			= SuicideCharge
Primary				= SuicideAttack
;----- Load -----
Ammo				= -1
Crewed				= no

;----- Availability -----
Owner				= 
; House				= 
RequiredHouses			= 
ForbiddenHouses			= 
Prerequisite			= 
AllowedToStartInMultiplayer	= no

DeployTime=.022	;x
TechLevel=2
Sight=6;8
PipScale=Passengers ;x
Speed=10;8
Cost=500
Soylent=100	;x
Points=25
ROT=8;5
Crusher=no
IsSelectableCombatant=yes
;----- Sfx -----
VoiceSelect				= SelectTerrorist
VoiceMove				= CmdMovTerrorist
VoiceAttack				= CmdAtkTerrorist
VoiceFeedback				= 
DieSound				= 
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
SpecialThreatValue=1
ZFudgeColumn=10
ZFudgeTunnel=13
;Bombable=no
Size=4
Trainable=no

; Buggy Blast Stealth
[BggyBlstStlh]:[BggyBlstStlh]
IsTilter=yes
TechLevel=2
Sight=6
Speed=10
CrateGoodie=yes
Owner=Nod
Points=25
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
ImmuneToVeins=yes

Strength=220
Armor=light
Turret=no
IsTilter=yes
TechLevel=2
Sight=6
Speed=10
CrateGoodie=yes
Owner=Nod
Points=25
ROT=8
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=3
DebrisTypes=TIRE
DebrisMaximums=4
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=10	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=CRUSHER
ImmuneToVeins=yes
;----- Damage & Destruction -----
DeathWeapon			= 
