;
;
;

;------------------------------------------------------------------------------
[SuperWeaponTypes]
+				= DrillSpecial
+				= DrillPodSpecial

;------------------------------------------------------------------------------
[DrillSpecial]
;----- Text -----
Name				= Drill Pod
UIName				= name:
UIDescription			= desc:
;----- Taxonomy -----

;------------------------------------------------------------------------------
[DrillPodSpecial]
;----- Text -----
Name				= Drill Pod
UIName				= name:
UIDescription			= desc:
;----- Taxonomy -----
Type				= UnitDelivery				; DropPod
IsPowered=true
RechargeVoice=00-I506
ChargingVoice=
ImpatientVoice=
SuspendVoice=
RechargeTime=8.75 ;7 ; ORIGINAL_WAS_CHANGED, increased since they give you free elite infantry.
Action=DropPod
SidebarImage=PODSICON
