;******************************************************************************
;*** Depot ********************************************************************
;******************************************************************************
; Regularly receives a money crate. 
; Can drop Supply Crate. 
; When also controlling Armory, Depot grants the ability to drop Ammo and repair packs. 
; When also controlling Hospital, Depot grants the ability to drop medipacks. 
; This is Supply Depot (gen) x Depot (sc) x Service Depot (td/ra/ts/ra2) x Depot (2140). 

;------------------------------------------------------------------------------
[BuildingTypes]
+				= UNDepot

;------------------------------------------------------------------------------
; Depot
[UNDepot]
;----- Text -----
Name				= Depot
UIName				= name:depot
UIDescription			= desc:depot
;----- Body -----
Strength			= 1000
Bib				= yes
NumberImpassableRows=3 ; This is the fix to the Repair depots are flat and RadioContact/Enter means I can drive on you assumption.  It counts from game west
;----- Weapons -----
SuperWeapons			= SupplySpecial, RepairSpecial
;----- Armor -----
Armor				= wood
Spyable				= yes				; steal
Capturable			= yes
ImmuneToPsionics		= no
Drainable			= yes
;----- Availability -----
Owner				= Allies
TechLevel			= 1
; Prerequisite			= GAWEAP, GACNST, PROC
Adjacent			= 2
Cost				= 1000
;----- Score -----
Points				= 25
;----- Perception -----
Sight				= 2
;----- UI -----
BuildCat			= Resource
PipScale			= Tiberium
;----- Load -----
Crewed				= yes
Helipad				= yes
HoverPad			= yes
Crewed				= yes
UnitRepair			= yes
UnitReload			= yes
FreeUnit			= UNTruck
DockUnload			= yes
; Refinery			= yes
NumberOfDocks			= 1
Storage				= 60;80
;----- Power -----
Power				= -10
MaxDebris=2
ThreatPosed=0	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,LGSparkSys
DamageSmokeOffset=700, 700, 500
TogglePower=no

;----- AI -----
; WantsExtraSpace		= yes
ResourceDestination		= yes
; AIBuildThis			= yes
AIBasePlanningSide		= allies				; 0
; HasStupidGuardMode		= false					; Presumably this alerts docked aircraft? It has no effect here. 
;----- Damage & Destruction -----
Explodes			= yes
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
; DamageParticleSystems		= SparkSys,SmallGreySSys,BigGreySmokeSys
DamageSmokeOffset=270, 580, 260

Strength=1200
TechLevel=6
Adjacent=2
Sight=5
Cost=800
Points=80
Power=-25
DebrisAnims=DBRIS1LG,DBRIS1SM,DBRIS4LG,DBRIS4SM,DBRIS5LG,DBRIS5SM
MaxDebris=8
MinDebris=4
ThreatPosed=0	; This value MUST be 0 for all building addons

TechLevel=5
Sight=5
Cost=500
Points=70
Power=-10
MaxDebris=4
ThreatPosed=0	; This value MUST be 0 for all building addons
DamageSmokeOffset=75, 270, 140


; Asia Supply Depot
; Formerly CNDepot (Chinese Supply Depot). 
[AADepot]
;----- Text -----
Name				= Asian Supply Depot
;----- Availability -----
Owner				= Alliance,Chinese,Japanese,Koreans,InfantryArmy,CyberArmy,WalkerArmy,NinjaClan,Room121
Prerequisite			= AACommCenter,POWER
AIBasePlanningSide		= ASIA
;----- Load -----
FreeUnit			= AATruck

Strength=400
Sight=6
Adjacent=2
Armor=wood
Points=80
MaxDebris=8
DamageParticleSystems=SmallGreySSys,BigGreySmokeSys
Cost=2000
Soylent=300
Power=-50
ThreatPosed=0	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys,BigGreySmokeSys


; storage silo
; TS's NASILO
[GGSilo]
UIName				= Name:Silo
Name				= Silo 
Prerequisite=NAWEAP
Image= NAMISL
Strength=300
Armor=wood
TechLevel=1
Adjacent=2
Sight=2
Owner=GDI,Nod
Cost=150
Points=25
Power=-10
MaxDebris=2
PipScale=Tiberium
ThreatPosed=0	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,LGSparkSys
DamageSmokeOffset=700, 700, 500
TogglePower=no

