;******************************************************************************
;*** Wheat Weevil Sentry Drone ************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[VehicleTypes]
+				= DronSnty
+				= DronSntyHvr
+				= DronProt

;------------------------------------------------------------------------------
; Allied GDT 50 Sentry Drone
; Formerly [UNSentryDrone]. 
[DronSntyNutcase]
;----- Text -----
Name				= Drone Sentry Nutcase		; Wheat Weevil Sentry Drone
UIName				= name:dron_snty
UIDescription			= desc:dron_snty
;----- Taxonomy -----
Category			= Recon
;----- Availability -----
Side				= Terran
Owner				= Allies, Americans
; House				= 
TechLevel			= 4
Prerequisite			= UNFactory
CrateGoodie			= yes
;----- Body -----
Strength			= 100
Size				= 2
;----- Weapons -----
Primary				= DetectDrone
Secondary			= DetectDrone
NavalTargeting=6
;----- Armor -----
Armor				= LightAutomaton
ImmuneToPoison			= yes
ImmuneToPsionics		= yes
ImmuneToRadiation		= yes
; Parasiteable			= no
;----- Turrets -----
Turret				= yes
;----- Movement -----
Speed				= 4
SpeedType			= Track
Locomotor			= Drive
MovementZone			= Normal

Tracked				= yes
IsTilter			= yes
Bunkerable			= no
Crusher				= no
;----- Load -----
Crewed				= no
ProtectedDriver			= yes
Sight=4
Cost=500
Soylent=500
Points=20
ROT=40
AllowedToStartInMultiplayer=no
IsSelectableCombatant=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
;----- Sfx -----
VoiceSelect=GenDroneSelect
VoiceAttack=GenDroneAttackCommand
VoiceMove=GenDroneMoveCommand
VoiceFeedback=
DieSound=GenDroneDie
MoveSound=LightTankMove
MaxDebris=2
;----- AI -----
DefaultToGuardArea		= yes
ThreatPosed=25 ; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
Weight=.5
AccelerationFactor=5 ; really fast
DeaccelerationFactor=5 ; This is TS's mizspelingg knot min
ZFudgeColumn=8
ZFudgeTunnel=13
Accelerates=false
;----- Veterancy -----
Trainable			= no

;------------------------------------------------------------------------------
[DronSntyA1]
;----- Body -----
Strength			= 

;------------------------------------------------------------------------------
[DronSntyB1]
;----- Weapons -----
Primary				= SentryDroneGun

;------------------------------------------------------------------------------
; Drone Sentry Nutcase, upgrades Weapon, Armor. 
[DronSntyA1B1]

;------------------------------------------------------------------------------
; Defender (mo)
[DronProt]
$inherits			= DronSnty
;----- Text -----
Name				= 
