;
;
;

;------------------------------------------------------------------------------
[VehicleTypes]
+				= Harvester

;------------------------------------------------------------------------------
; Weed-eater vehicle
; Weed Eater [WEED] (ts)
[Harvester]
$inherits			= truk
;----- Text -----
Name				= Weed Collector
UIName				= name:weat
UIDescription			= desc:weat
;----- Taxonomy -----
;;; UnitGroup			= FromSilo
;----- Visual -----
Image				= TEST
;----- 
Prerequisite=NAWEAP;,NAWAST
Primary=ChaosStreamLauncher
ToProtect=yes
Category=Support
Strength=600
Armor=heavy
Dock=NAWAST
Turret=yes
TechLevel=10
Sight=4
Weeder=yes
Speed=5
Owner=Soviet,Russians,Chinese,Confederation
AllowedToStartInMultiplayer=no
PipScale=Tiberium
Storage=7
Cost=1400
Points=55
ROT=5
Crusher=yes
Crewed=yes
SelfHealing=yes
MaxDebris=6
DebrisTypes=PIECE,CRYSTAL01,CRYSTAL02
DebrisMaximums=2,1,1
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
Weight=3.5
Size=3
MovementZone=Crusher
DeathWeapon=ChaosEruption
Explodes=yes
OpportunityFire=yes
VeteranAbilities=ARMOR,STRONGER,FASTER,FIREPOWER
EliteAbilities=ARMOR,STRONGER,FASTER,FIREPOWER
ThreatPosed=0	; This value MUST be 0 for all building addons
ThreatAvoidanceCoefficient=.6
DamageParticleSystems=SparkSys,BigRedSmokeSys
ImmuneToVeins=yes
ZFudgeColumn=7
ZFudgeTunnel=12

Prerequisite=NAWEAP;,NAWAST
Primary=ChaosStreamLauncher
ToProtect=yes
Category=Support
Strength=600
Armor=heavy
Dock=NAWAST
Turret=yes
TechLevel=10
Sight=4
Weeder=yes
Speed=5
Owner=Soviet,Russians,Chinese,Confederation
AllowedToStartInMultiplayer=no
PipScale=Tiberium
Storage=7
Cost=1400
Points=55
ROT=5
Crusher=yes
Crewed=yes
SelfHealing=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=WeederSelect
VoiceMove=WeederMove
VoiceAttack=WeederAttackCommand
VoiceFeedback=
DieSound=DemoTruckDie
MaxDebris=6
DebrisTypes=PIECE,CRYSTAL01,CRYSTAL02
DebrisMaximums=2,1,1
Weight=3.5
Size=3
Explodes=yes
OpportunityFire=yes
VeteranAbilities=ARMOR,STRONGER,FASTER,FIREPOWER
EliteAbilities=ARMOR,STRONGER,FASTER,FIREPOWER
ThreatPosed=0	; This value MUST be 0 for all building addons
ThreatAvoidanceCoefficient=.6
DamageParticleSystems=SparkSys,BigRedSmokeSys
ImmuneToVeins=yes
ZFudgeColumn=7
ZFudgeTunnel=12
