;
;
;
; Khitan Freesword

;------------------------------------------------------------------------------
[InfantryTypes]
+				= FLCH			; Khitan Freesword
+				= FLCH2			; Khitan Freesword Veteran
+				= FLCH3			; Khitan Freesword Elite
+				= FLCH4			; Khitan Freesword Hero
+				= FLCH5			; Khitan Freesword Master
+				= FLCH6			; Khitan Freesword Legendary

;------------------------------------------------------------------------------
; Khitan Mercenary
; When dealing damage to a unit (not shield), leave a DoT effect. 
[FLCH]
;----- Text -----
Name				= Khitan Falchion
UIName				= name:falchion
UIDescription			= desc:falchion
;----- Taxonomy -----
Category			= Soldier
Infantry			= yes
UnitGroup			= FromIMBarracks
Cyborg				= yes
;----- Body -----
Strength			= 130
;----- Weapons -----
Primary				= Falchion
Secondary			= Vulcan3
;----- Armor -----
Armor				= plate
ImmuneToVeins			= yes
;----- Availability -----
Side				= Terran
Owner				= Neutral
House				= Imperial
RequiredHouses			= Koreans
TechLevel			= 2
Prerequisite			= Embassy
Cost				= 300
;----- Sfx -----
VoiceSelect			= 15-I000,15-I004,15-I012,15-I048
VoiceMove			= 15-I018,15-I024,15-I044
VoiceAttack			= 15-I044,15-I050,15-I044,15-I046
VoiceFeedback			= 15-I058,15-I064
VoiceDie			= DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
CrushSound			= crunch
;----- UI -----
Pip				= blue
Sight=7
Speed=4
Owner=GDI
Points=5
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
Sensors=no
MovementZone=InfantryDestroyer
ThreatPosed=15	; This value MUST be 0 for all building addons
ImmuneToVeins=yes
;----- Veterancy -----
EliteAbilities			= FIREPOWER
VeterancyLevel			= 6 
ExtraDamage			= 50
VeterancyLevel			= 16
ExtraArmour			= 50
VeterancyLevel			= 32
CanSelfRepair			= 1
;----- Damage & Destruction -----
; Explodes			= yes

StormDamage=138
PrimaryBuilding = IMBarracks
Terrain = Rock, Sand, NBRock, InfRock, Ramp
Cost = 300
BuildTime = 432
Size = 1
Speed = 6.0      
TurnRate = 0.2     
TurretAttach = IMSardaukarGun   
Armour = BPV, 50, InfRock
Health = 900
ViewRange = 12
AiFoot = TRUE
TechLevel = 3
ChaosEffect = SmallChaosFX
HawkEffect = SmallHawkFX
TastyToWorms = True
WormAttraction = 4
Crushable = TRUE
CanMoveAnyDirection = TRUE
CrateGift = TRUE
CanBeDeviated = FALSE
ExplosionType = CrushedInfantry
AIThreat = 70
CanBeRepaired = FALSE

;------------------------------------------------------------------------------
; Khitan Falchion Veteran
[FLCH2]
$Inherits			= FLCH
;----- Text -----
Name				= Khitan Freesword Veteran
;----- Body -----
Strength			= 150
;----- Armor -----
Armor				= light

;------------------------------------------------------------------------------
; Khitan Falchion Elite
; Gains shield. 
[FLCH3]
$Inherits			= FLCH2
;----- Text -----
Name				= Khitan Freesword Elite
;----- Attach -----

;------------------------------------------------------------------------------
; Khitan Falchion Heroic
; Options: double attack, added effect: chain lightning
[FLCH4]
$Inherits			= FLCH3
;----- Text -----
Name				= Khitan Freesword Heroic
TechLevel=-1
RadarInvisible=yes
Points=5
Armor=heavy
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
DamageParticleSystems=SmallGreySSys,BigGreySmokeSys
IsBase=no
LightVisibility=2300
LightIntensity=0.02
LightRedTint=0.01
LightGreenTint=0.26
LightBlueTint=0.01


[CYBORG]
Name=Cyborg
Nominal=yes
Category=Soldier
Prerequisite=NAHAND
Primary=Vulcan3
CrushSound=SQUISHY2
Crushable=no
TiberiumProof=yes
TiberiumHeal=yes
Fearless=yes
Cyborg=yes
Pip=white
Strength=300 ; w350
Armor=light
TechLevel=4
Sight=5
Speed=4
Owner=Nod
Cost=650
Points=5
Sensors=no
VoiceSelect=22-I000,22-I002,22-I006
VoiceMove=22-I008,22-I010,22-I014,22-I016,22-I020
VoiceAttack=22-I008,22-I010,22-I012,22-I018
VoiceFeedback=
VoiceDie=DEDMAN1,DEDMAN2,DEDMAN2,DEDMAN4,DEDMAN5,DEDMAN6
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=Infantry
DamageParticleSystems=SparkSys
ThreatPosed=15	; This value MUST be 0 for all building addons
EliteAbilities=STRONGER
ImmuneToVeins=yes





; Khitan Falchion Master
; Aura converts all Khitan Freesword to Khitan Freesword Veteran. 
; Reflects damage. 
[CA0018]
Name=Solar Panel
TechLevel=-1
Strength=200
Insignificant=yes
Nominal=yes
RadarInvisible=yes
Points=5
Armor=light
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
DamageParticleSystems=SmallGreySSys,BigGreySmokeSys
IsBase=no
LightVisibility=2300
LightIntensity=0.02
LightRedTint=0.01
LightGreenTint=0.01
LightBlueTint=0.26
