;******************************************************************************
;*** Psychotronner ************************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[InfantryTypes] 
+				= Psychotronner


Owner				= Soviet,Russians,Belorussians,Ukrainians,Kazakhs,TankArmy,ArtilleryArmy,NukeArmy,SteelCossacks,BlackGuards,YuriArmy,HeadQuarters,RoguePsykers,ScorpionCell


;------------------------------------------------------------------------------
; Psychotronic Infantry
; Formerly [Psychotronner]. 
[ConsPsych]:[Conscript]
;----- Text -----
Name				= Conscript Psychotron			; Psychotronic Warrior
UIName				= name:cons_psych
UIDescription			= desc:cons_psych
;----- GFX -----
Image				= CLEG					; ##TEMP##
;----- UI -----
Pip				= purple
;----- AI -----
LeadershipRating		= 8
;----- Armor -----
Armor				= tinfoil
Crushable			= no
;----- Weapons -----
Primary				= PsychotronPulse			; directed attack
Secondary			= PsychotronWave			; area attack
ElitePrimary			= PsychotronPulse_E
EliteSecondary			= PsychotronWave_E
IFVMode				= PSYCHOTRON

Points=50

;----- Availability -----
; ForbiddenHouses		= YuriArmy,HeadQuarters,ScorpionCell
TechLevel			= 9
Prerequisite.Lists		= 2
Prerequisite.List1		= SUBarracks,SUTechCenter,Tech_Psionics
Prerequisite.List2		= YABarracks
RequiredHouses			= BlackGuards,RoguePsykers							; Psi Corps, no matter if loyalist or Chaos. 
AllowedToStartInMultiplayer=no
Cost=1000
Soylent=500

;----- SFX -----
VoiceSelect=YuriSelect
VoiceMove=YuriMove
VoiceAttack=YuriAttackCommand
VoiceFeedback=
VoiceSpecialAttack=YuriMove
DieSound=YuriDie
CrushSound			= InfantrySquish

ThreatPosed=22
SpecialThreatValue=1
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
;----- Perception -----
; DetectDisguise		= yes
Deployer=yes;
DeployFire=yes;
UndeployDelay=75;
