;
;
;

;------------------------------------------------------------------------------
[VehicleTypes]
+				= MekPromet

;------------------------------------------------------------------------------
; Prometheus Firestorm Artillery Mech
; Formerly PROM, [Prometheus]. 
[MekPromet]
$Inherits			= MekKyojin
;----- Text -----
Name				= Walker Prometheus
UIName				= name:mek_promet
UIDescription			= desc:mek_promet
;----- Taxonomy -----
Category			= LRFS
;----- Gfx -----
Image				= MMC2
;----- Body -----
; Strength			= 300
;----- Weapons -----
Primary				= PrometheusHowitzer
Elite				= 155mmxx				; Taken out - it was waaay to powerful up there. 
ElitePrimary			= 155mmxx
FireAngle			= 64					; Vertical		; 80
; TargetLaser			= yes
;----- Armor -----
Armor				= light					; heavy
;----- Availability -----
TechLevel			= 13
Prerequisite			= UNFactory, UNDockBay			; GAWEAP, GADROP
Sight				= 9					; 8
Speed				= 5					; 4
CrateGoodie=yes
Crusher=yes
Crewed=yes
Owner=GDI
Cost				= 2600					; 975
Points=25
ROT				= 2					; 5
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=4
Locomotor={55D141B8-DB94-11d1-AC98-006008055BB5}
MovementZone=Destroyer
ThreatPosed=40	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=100, 100, 275
Weight=3.5
EliteAbilities=SENSORS
Accelerates=false
ZFudgeColumn=8
ZFudgeTunnel=13


; Firestorm Mech
[FSMEC]
Name=Prometheus
FireAngle=80
Primary=FirestormCannon
Elite=155mmx6
Category=AFV
Armor=heavy
Turret=yes
IsTilter=no
TargetLaser=yes
TooBigToFitUnderBridge=true
TechLevel=3
Sight=8
Speed=4
CrateGoodie=yes
Crusher=yes
Owner=GDI
Cost=2600
Points=25
ROT=5
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=4
Locomotor={55D141B8-DB94-11d1-AC98-006008055BB5}
MovementZone=Destroyer
ThreatPosed=40	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
DamageSmokeOffset=100, 100, 275
Weight=3.5
EliteAbilities=SENSORS
Accelerates=false
ZFudgeColumn=8
ZFudgeTunnel=13
;Elite=155mmx6 ; put out - it was waaay to powerful up there

[FirestormCannon]
Projectile=ClusterBallistic
Damage=80 ;165 ;w760 w500
Range=18
Report=120MMF
Warhead=FirestormWH
ROF=200
Lobber=yes

; arcing ballistic projectile
[ClusterBallistic]
High=yes
Image=120MM
Arcing=true
Cluster=9
