;******************************************************************************
;*** ATV Cougar ***************************************************************
;******************************************************************************
; It's Ocelot -> Caracal -> Serval -> (Lynx ->) Cougar -> Jaguar. 

;------------------------------------------------------------------------------
[VehicleTypes]
+				= TankPuma

;------------------------------------------------------------------------------
; Tank Cougar
; Formerly [TankPuma]. 
[TnkCugr]
$inherits			= ATVOcelot
;----- Text -----
Name				= Tank Cougar
UIName				= name:tnk_cugr
UIDescription			= desc:tnk_cugr
;----- Body -----
Strength			= 385
;----- Turrets -----
Turret				= yes
TurretAttach			= TnkCugrTur
TurretCount			= 1
TurretAnim			= TnkCugrTur
;----- Weapons -----
Primary				= CannonMM90
;----- Armor -----
Armor				= ArmorTank
;----- Availability -----
Owner				= Confederation, Brazil, Cuba, Venezuela
TechLevel			= 3
Prerequisite			= 
Cost				= 1100
AllowedToStartInMultiplayer	= yes
CrateGoodie			= yes

IsTilter=yes
Sight=5
Speed=6
Cost=1100
Points=25
ROT=5
Crusher=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
;----- Sfx -----
VoiceSelect			= SelectVehLatin			; 25-I000,25-I002,25-I004,25-I006
VoiceMove			= Cmd25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack			= 25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=3
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Destroyer
ThreatPosed=25	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
Weight=3.5
EliteAbilities=EXPLODES
ZFudgeColumn=8
ZFudgeTunnel=13
