;
;
;
; There are two related states here that should not be confused: 
;  - Initiative: 
;	This is what *allows* units to strike first. 
;  - First Strike: 
;	Striking first. It's a status that is lost when attacking or taking weapon damage (because in both cases, one isn't striking first anymore). 
;	Semantically, it exists WHEN striking first. 
;	However, the way the code works is that it is a permanent latent status that is only removed when the conditions change 
; 	so that striking first is no longer possible. 
;	Accurately, it should probably be called "TheNextAttackCanBeAFirstStrike". 

;------------------------------------------------------------------------------
; [AttachEffectTypes]
; On second thought, ShieldType is ideal for this. We can specify Respawn In Combat = no, 
; and it natively supports preventing weapons firing on its host in broad swathes (per armor/warhead), 
; rather than specifying per-weapon (or per root) that the attachment prevents firing. 
[ShieldTypes]
+				= Initiative2

;------------------------------------------------------------------------------
; First Strike
[Initiative_Gain_1]
Strength			= 1
InitialStrength			= 1
Armor				= Initiative2
Respawn				= 0.0
Respawn.Rate			= 0.0
Respawn.RestartInCombat		= no
Respawn.RestartInCombatDelay	= 0
; Respawn.Anim			= fx_firststrike		; Now passes through another AttachEffect for "am I firing?" check, since RestartInCombat only checks for "am I being hit?", 
								; before the unit gains Initiative/First Strike, so the animation shouldn't play yet when just this stage of the process happens. 
Respawn.Weapon			= GainInitiative
BracketDelta=0                              ; integer - pixels

AbsorbPercent			= 1.00
PassPercent			= 1.00
ReceivedDamage.Minimum		= 9999
AllowTransfer			= yes

;------------------------------------------------------------------------------
[]

;------------------------------------------------------------------------------
[Initiative_Gain_2]
Duration				= -1
DiscardOn				= firing, receiveddamage
PenetratesIronCurtain			= yes
PenetratesForceShield			= yes
ExpireWeapon				= GainFirstStrike
ExpireWeapon.TriggerOn			= discard
ExpireWeapon.CumulativeOnlyOnce		= false
ExpireWeapon.UseInvokerAsOwner		= false

;------------------------------------------------------------------------------
[]




;------------------------------------------------------------------------------
; Jaguar Strike
; Jaguar Assault Infantry and Jaguar Tank have 10% attack bonus, 
; Subsumes [TankJaguarFirstStrikeBonus]. 
[FirstStrike]
Duration				= -1
DiscardOn				= receiveddamage, firing
; DiscardOn.LandTypes			= clear, road, water, rock, wall, tiberium, beach, rough, ice, railroad, tunnel, weeds
FirepowerMultiplier			= 1.25
; Crit.Multiplier			= 999.0				; Use extrachance. 
Crit.ExtraChance			= 1.00
Crit.AllowWarheads			= FirstStrikeAdd2		; Interacts only if unit has chain ExtraWarheads = FirstStrikAdd1 / Crit.Warhead = FirstStrikeAdd2. 
PenetratesIronCurtain			= yes
PenetratesForceShield			= yes
; Cloakable				= 
Animation				= anim_firststrike		; AEFXJaguarFS
Animation.OfflineAction			= Hides
Animation.TemporalAction		= Hides
Animation.DrawOffsetN			= 0,0

;------------------------------------------------------------------------------
; Bloody
; Formerly [JaguarStrikeState2]. 
[Bloodied]
Duration				= 125			; Was -1. We no longer use DiscardOn.Firing.Count higher than 1, the effect should last a fixed time after scoring a First Strike. 
Cumulative				= yes
Cumulative.MaxCount			= 4			; This can be another vector for upgrade. 
PenetratesIronCurtain			= yes
PenetratesForceShield			= yes
AffectTypes				= InfJagr, TnkJagr
Animation				= anim_bloodied
Animation.ResetOnReapply=false                     ; boolean
Animation.OfflineAction=Hides                      ; AttachedAnimFlag (None, Hides, Temporal, Paused or PausedTemporal)
Animation.TemporalAction=None                      ; AttachedAnimFlag (None, Hides, Temporal, Paused or PausedTemporal)
Animation.UseInvokerAsOwner=false                  ; boolean
Animation.HideIfAttachedWith=                      ; List of AttachEffectTypes
Animation.DrawOffsetN=0,0                          ; X,Y, pixels relative to default
Animation.DrawOffsetN.RequiredTypes=               ; List of AttachEffectTypes
CumulativeAnimations=                              ; List of AnimationTypes
CumulativeAnimations.RestartOnChange=true          ; boolean
Tint.Color				= 
Tint.Intensity				= 
Tint.VisibleToHouses			= all
FirepowerMultiplier			= 1.10
SpeedMultiplier				= 1.10
ROFMultiplier				= 1.10
Crit.Multiplier				= 1.10
Crit.ExtraChance			= 0.10




; napalm and fire in general
[Fire]
CellSpread=.5
PercentAtMax=.5
Wood=yes
Verses=600%,500%,200%,60%,30%,5%,150%,100%,2%,200%,100%
;Verses=600%,148%,59%,6%,2%
InfDeath=4
Sparky=no
Fire=no
ProneDamage=600%

; napalm and fire in general, that doesn't set other things on fire (weird, but necessary)
[Fire2]
CellSpread=.5
PercentAtMax=.5
Wood=yes
Verses=600%,500%,200%,60%,30%,5%,150%,100%,2%,200%,100%
;Verses=600%,148%,59%,6%,2%
InfDeath=4
Sparky=no
Fire=no
ProneDamage=600%

; anti-infantry rifle bullet (single shot -- very effective verses infantry)
[HollowPoint]
Verses=200%,100%,100%,1%,1%,1%,1%,1%,1%,1%,100% ; see note in comments above about 1%
InfDeath=1
AnimList=PIFF
ProneDamage=100%
Bullets=yes

; anti-infantry rifle bullet (single shot -- very effective verses infantry)
[HollowPoint2]
Verses=100%,100%,100%,0%,0%,0%,0%,0%,0%,100%,100%
InfDeath=1
AnimList=PIFF
ProneDamage=100%
Bullets=yes

[HollowPoint3]
Verses=100%,100%,100%,2%,2%,2%,2%,2%,2%,100%,100%
InfDeath=1
AnimList=PIFF
ProneDamage=100%
Bullets=yes

; special case damage effect (do not use for regular weapons)
[Super] ; this is used when something in the code needs to do "absolute damage"
Verses=100%,100%,100%,100%,100%,100%,100%,100%,100%,100%,100%
Tiberium=yes
ProneDamage=100%
Sparky=no
InfDeath=2
AnimList=XGRYSML1,XGRYSML2,EXPLOSML,XGRYMED1,XGRYMED2,EXPLOMED,EXPLOLRG,TWLT070
