;
;
;
; There are two related states here that should not be confused: 
;  - Initiative: 
;	This is what *allows* units to strike first. 
;  - First Strike: 
;	Striking first. It's a status that is lost when attacking or taking weapon damage (because in both cases, one isn't striking first anymore). 
;	Semantically, it exists WHEN striking first. 
;	However, the way the code works is that it is a permanent latent status that is only removed when the conditions change 
; 	so that striking first is no longer possible. 
;	Accurately, it should probably be called "TheNextAttackCanBeAFirstStrike". 

;------------------------------------------------------------------------------
; [AttachEffectTypes]
; On second thought, ShieldType is ideal for this. We can specify Respawn In Combat = no, 
; and it natively supports preventing weapons firing on its host in broad swathes (per armor/warhead), 
; rather than specifying per-weapon (or per root) that the attachment prevents firing. 
[ShieldTypes]
+				= Initiative2

;------------------------------------------------------------------------------
[Initiative2]
Strength			= 1
InitialStrength			= 1
Armor				= Initiative2
Respawn				= 0.0                                 ; floating point value, percents or absolute
Respawn.Rate			= 0.0                            ; floating point value, ingame minutes
Respawn.RestartInCombat		= no
Respawn.RestartInCombatDelay=0              ; integer, game frames
Respawn.Anim=                               ; List of AnimationTypes
Respawn.Weapon=                             ; WeaponType
BracketDelta=0                              ; integer - pixels
Pips=-1,-1,-1                               ; integer, frames of pips.shp (zero-based) for Green, Yellow, Red
Pips.Building=-1,-1,-1                      ; integer, frames of pips.shp (zero-based) for Green, Yellow, Red
Pips.Background=                            ; filename - including the .shp/.pcx extension
Pips.Building.Empty=                        ; integer, frame of pips.shp (zero-based) for empty building pip
Pips.HideIfNoStrength=false                 ; boolean
IdleAnim=                                   ; AnimationType
IdleAnim.ConditionYellow=                   ; AnimationType
IdleAnim.ConditionRed=                      ; AnimationType
IdleAnimDamaged=                            ; AnimationType
IdleAnimDamaged.ConditionYellow=            ; AnimationType
IdleAnimDamaged.ConditionRed=               ; AnimationType
IdleAnim.OfflineAction=Hides                ; AttachedAnimFlag (None, Hides, Temporal, Paused or PausedTemporal)
IdleAnim.TemporalAction=Hides               ; AttachedAnimFlag (None, Hides, Temporal, Paused or PausedTemporal)
BreakAnim=                                  ; List of AnimationTypes
HitAnim=                                    ; List of AnimationTypes
HitFlash=false                              ; boolean
HitFlash.FixedSize=                         ; integer
HitFlash.Red=true                           ; boolean
HitFlash.Green=true                         ; boolean
HitFlash.Blue=true                          ; boolean
HitFlash.Black=false                        ; boolean
BreakWeapon=                                ; WeaponType
AbsorbPercent=1.0                           ; floating point value
PassPercent=0.0                             ; floating point value
ReceivedDamage.Minimum=-2147483648          ; integer
ReceivedDamage.Maximum=2147483647           ; integer
AllowTransfer=                              ; boolean
ImmuneToBerserk=no                          ; boolean
ImmuneToCrit=no                             ; boolean
Tint.Color=                                 ; integer - Red,Green,Blue
Tint.Intensity=0.0                          ; floating point value
Tint.VisibleToHouses=all                    ; List of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|neutral|all)






; First Strike
[FirstStrike]
Duration				= -1
DiscardOn				= receiveddamage
PenetratesIronCurtain			= yes
PenetratesForceShield			= yes
ExpireWeapon				= RemoveFirstStrike
ExpireWeapon.TriggerOn			= discard
ExpireWeapon.CumulativeOnlyOnce		= false
ExpireWeapon.UseInvokerAsOwner		= false


; Jaguar Strike
; Jaguar Assault Infantry and Jaguar Tank have 10% attack bonus, 
[FirstStrike2]
$inherits				= FirstStrike
FirepowerMultiplier			= 1.25
Crit.Multiplier=1.0                                ; floating point value
Crit.ExtraChance=0.0                               ; floating point value
Crit.AllowWarheads=                                ; List of WarheadTypes
Crit.DisallowWarheads=                             ; List of WarheadTypes


;------------------------------------------------------------------------------
; Two-stage weapon, because 
[JaguarStrike]
RevengeWeapon=                                     ; WeaponType
RevengeWeapon.AffectsHouse=all                     ; List of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|neutral|all)
RevengeWeapon.UseInvokerAsOwner= false



;------------------------------------------------------------------------------
[TankJaguarFirstStrikeBonus]
Duration			= -1
DiscardOn			= receiveddamage, firing
DiscardOn.Firing.Count		= 2
; DiscardOn.LandTypes		= clear, road, water, rock, wall, tiberium, beach, rough, ice, railroad, tunnel, weeds
PenetratesIronCurtain		= yes
PenetratesForceShield		= yes
Animation			= AEFXJaguarFS
Animation.OfflineAction		= Hides
Animation.TemporalAction	= Hides
Animation.DrawOffsetN		= 0,0
Tint.Color			= 
Tint.Intensity			= 
Tint.VisibleToHouses		= all
; FirepowerMultiplier		= 1.25
; Cloakable			= 
Crit.Multiplier			= 1.0
Crit.ExtraChance=0.0                               ; floating point value


; napalm and fire in general
[Fire]
CellSpread=.5
PercentAtMax=.5
Wood=yes
Verses=600%,500%,200%,60%,30%,5%,150%,100%,2%,200%,100%
;Verses=600%,148%,59%,6%,2%
InfDeath=4
Sparky=no
Fire=no
ProneDamage=600%

; napalm and fire in general, that doesn't set other things on fire (weird, but necessary)
[Fire2]
CellSpread=.5
PercentAtMax=.5
Wood=yes
Verses=600%,500%,200%,60%,30%,5%,150%,100%,2%,200%,100%
;Verses=600%,148%,59%,6%,2%
InfDeath=4
Sparky=no
Fire=no
ProneDamage=600%

; anti-infantry rifle bullet (single shot -- very effective verses infantry)
[HollowPoint]
Verses=200%,100%,100%,1%,1%,1%,1%,1%,1%,1%,100% ; see note in comments above about 1%
InfDeath=1
AnimList=PIFF
ProneDamage=100%
Bullets=yes

; anti-infantry rifle bullet (single shot -- very effective verses infantry)
[HollowPoint2]
Verses=100%,100%,100%,0%,0%,0%,0%,0%,0%,100%,100%
InfDeath=1
AnimList=PIFF
ProneDamage=100%
Bullets=yes

[HollowPoint3]
Verses=100%,100%,100%,2%,2%,2%,2%,2%,2%,100%,100%
InfDeath=1
AnimList=PIFF
ProneDamage=100%
Bullets=yes

; special case damage effect (do not use for regular weapons)
[Super] ; this is used when something in the code needs to do "absolute damage"
Verses=100%,100%,100%,100%,100%,100%,100%,100%,100%,100%,100%
Tiberium=yes
ProneDamage=100%
Sparky=no
InfDeath=2
AnimList=XGRYSML1,XGRYSML2,EXPLOSML,XGRYMED1,XGRYMED2,EXPLOMED,EXPLOLRG,TWLT070
