;******************************************************************************
;*** Tank Centurion III *******************************************************
;******************************************************************************

;------------------------------------------------------------------------------
[VehicleTypes]
+				= 

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Ecumene Lazer Tank (Alien Tank)
; Formerly [TankCent]. 
; Subsumes [ALNTK] (Scrin Tank, balace for Hover MLRS in TS: Balance). 
; Land mode: stronger laser, can attack ground targets only. 
[TnkCntrnLaserHovr]

FireAngle=32
Primary=TankPlasma
Armor=wood
Points=30
ROT=5
Crusher=no
MaxDebris=4
ThreatPosed=25	; This value MUST be 0 for all building addons
EliteAbilities=SELF_HEAL
ZFudgeColumn=12
ZFudgeTunnel=15

;----- Text -----
Name					= Tank Centurion
DisplayName				= object:tnk_cent
UIName					= name:tnk_
UIDescription				= desc:tnk_
;----- Gfx -----
Image					= 
ZFudgeColumn				= 8
ZFudgeTunnel				= 13
DamageEffect				= MediumDamageFX
ChaosEffect				= MediumChaosFX
HawkEffect				= MediumHawkFX
;----- Taxonomy -----
Category				= AFV
UnitGroup				= FromHangar
;----- Body -----
Strength				= 230
Weight					= 2.3
Size					= 5
;----- Weapons -----
Primary					= CenturionLaser
Secondary				= CenturionLaser
ElitePrimary				= CenturionLaser_e2
EliteSecondary				= CenturionMissiles
TargetLaser				= yes
OpportunityFire				= yes
;----- Armor -----
Armor					= armor_laser
StormDamage				= 10
;----- Turrets -----
Turret					= yes
TurretAttach				= ECLaserGunDual
;----- Availability -----
Side					= Special
Owner					= Special
House					= Special
RequiredHouses				= Special
SecretHouses				= Special
TechLevel				= 7
Prerequisite				= DockBay					; FACTORY,RADAR
PrimaryBuilding				= DockBay
Cost					= 1100						; Should be more than [HVR]_ts > Cost = 900. 
AllowedToStartInMultiplayer		= yes
CrateGoodie				= yes
;----- Score -----
Points					= 65
;----- Load -----
Crewed					= yes
InitialPayload.Types			= LaserDummy,ElectroDummy
InitialPayload.Nums			= 2
;----- Perception -----
Sight					= 7					; Was 8, uncertain provenance. 
;----- UI -----
IsSelectableCombatant			= yes
;----- AI -----
ThreatPosed				= 40
;----- Sfx -----
VoiceSelect				= SelectTnkCntrn			; 25-I000,25-I002,25-I004,25-I006
VoiceMove				= CmdMovTnkCntrn			; 25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack				= CmdAtkTnkCntrn			; 25-I014,25-I022,25-I024,25-I026
VoiceFeedback				= 
VoiceCrashing				= CrashTnkCntrn
MoveSound				= PrismTankMoveStart
DamageSound				= VehicleDamagedHeavy
CrushSound				= TankCrush
CrashingSound				= 
ImpactLandSound				= GenVehicleDie
DieSound				= GenVehicleDie
AuxSound1				= Dummy ;Taking off
AuxSound2				= Dummy ;Landing
;----- Movement -----
Speed					= 7.00					; Was 5, uncertain provenance. 
SpeedType				= Hover
Locomotor				= Hover
MovementZone				= AmphibiousDestroyer
Terrain					= Rock, Sand, NBRock, Ramp
MoveToShroud				= yes					; This might be necessary for flight mode. 
TooBigToFitUnderBridge			= yes
PitchSpeed				= 0.90
PitchAngle				= 0.00
Accelerates				= no
IsTilter				= no
Crusher					= yes
;----- Load -----
Crewed					= yes
;----- Attach -----
;----- Veterancy -----
; VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER,CRUSHER
; EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
VeterancyLevel				= 10
ExtraDamage				= 25
VeterancyLevel				= 24
CanSelfRepair				= 1
VeterancyLevel				= 48
ExtraDamage				= 50
ExtraArmour				= 50
;----- Damage & Destruction -----
Crashable			= yes
DamageParticleSystems		= SparkSys,SmallGreySSys
DamageSmokeOffset		= 100, 100, 275
ExplosionType			= AerialExplosion
Explosion			= TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
Debris				= DebrisMedium
DebrisTypes			= 
MinDebris			= 2
MaxDebris			= 8
;----- Availability -----
Cost				= 1500
BuildTime			= 750




;----- Score -----
Score				= 2
Points				= 2; 100


Speed = 2

TurnRate = 0.2     


TechLevel = 6

ViewRange = 4, 8
AiSpecial = TRUE
GetsHeightAdvantage = FALSE
AIThreat = 80
RangeIndicator = 10
RangeMask = 1

ThreatPosed=30

;------------------------------------------------------------------------------
; Tank Centurion Laser (Flying)
; Flight Mode: laser becomes weaker, only able to attack aerial targets. 
[TnkCntrnLasrFly]:[TnkCntrnLasrHovr]
;----- Text -----
Name				= Tank Centurion Laser (Flying)
;----- Taxonomy -----
Category			= AirPower
ConsideredAircraft		= yes
;----- Weapons -----
Primary				= CenturionLaserGunsB
; Secondary			= CenturionLaserCannon
;----- Armor -----
Armor				= ArmorAircraft
Armour				= Aircraft
;----- Availability -----
MovementZone			= Fly
TechLevel			= -1
;----- Movement -----
CanFly				= TRUE
HeightOffset			= 8
Locomotor			= Jumpjet
JumpjetSpeed			= 7
JumpjetClimb			= 8
JumpjetCrash			= 30
JumpJetAccel			= 10
JumpJetTurnRate			= 5
JumpjetHeight			= 750
; JumpjetWobbles		= .01
; JumpjetDeviation		= 1
JumpjetNoWobbles		= yes
BalloonHover			= yes
Bunkerable			= no
;----- Perception -----
Sight				= 8
;----- Sfx -----
MoveSound			= KirovMoveLoop

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Tank Centurion Tesla (Hover)
[TnkCntrnTslaHovr]:[TnkCntrnLasrHovr]
;----- Text -----
Name				= Tank Centurion Electro (Hover)
UIName				= name:
UIDescription			= desc:
;----- Weapons -----
Primary				= TeslaGuns
Secondary			= TeslaBlast
;----- Movement -----
Locomotor			= Hover
SpeedType			= Hover

;------------------------------------------------------------------------------
; Tank Centurion Tesla (Fly)
[TnkCntrnTslaFly]:[TnkCntrTslaHovr]
;----- Text -----
Name				= Tank Centurion Tesla (Flying)
;----- Taxonomy -----
Category			= AirPower
ConsideredAircraft		= yes
;----- Weapons -----
Primary				= TeslaGuns
Secondary			= TeslaBlasts
;----- Availability -----
TechLevel			= -1

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Tank Centurion Sonic (Hover)
[TnkCntrnSonicHovr]
;----- Text -----
Name				= Tank Centurion Sonic (Hover)
;----- Weapons -----
Primary				= SonicCannon

;------------------------------------------------------------------------------
; Tank Centurion Sonic (Flying)
[TnkCntrnSonicFly]:[TnkCntrnSonicHovr]
;----- Text -----
Name				= 
;----- Taxonomy -----
Category			= AirPower
ConsideredAircraft		= yes
;----- Weapons -----
Primary				= SonicCannonB
Secondary			= SonicCannonC
;----- Availability -----
TechLevel			= -1

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Tank Centurion Rad (Hover)
[TnkCntrnRadHovr]:[TnkCntrnLasrHovr]
;----- Text -----
Name				= Tank Centurion Rad (Hover)
UIName				= name:
UIDescription			= desc:
;----- Availability -----

;------------------------------------------------------------------------------
; Tank Centurion Rad (Landed)
[TnkCntrRadEmpc]:[TnkCntrRadHovr]
;----- Text -----
Name				= Tank Centurion Rad (Land)
;----- Weapons -----
Primary				= RadEruption

;------------------------------------------------------------------------------
; Tank Centurion Rad (Fly)
[TnkCntrnRadFly]
;----- Text -----
Name				= Tank Centurion Rad (Fly)
;----- Weapons -----
Primary				= 

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Tank Centurion Missile (Hover)
[BLUELAMP]
Name=Blue Light Post
Image=GALITE
Strength=600
Armor=wood
TechLevel=-1
Nominal=yes
Sight=0
Points=30
Power=0
Crewed=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=1
LightVisibility=4000
LightIntensity=0.01
LightRedTint=0.01
LightGreenTint=0,01
LightBlueTint=0.7
ThreatPosed=0	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,LGSparkSys
AlphaImage=NONE
Powered=true
Insignificant=yes




