;******************************************************************************
;*** Dog Husky ****************************************************************
;******************************************************************************
; Husky and Demo Husky. 

;------------------------------------------------------------------------------
[InfantryTypes]
+				= DogHusky
+				= DogHusky_Blast
+				= DogShep
+				= DogRtwl
+				= DogCybg
+				= DogMutTib
+				= DogMutPsy
+				= DogMutYur
+				= DogMutDrog
; 64A129C667F9C			= MDOG

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
; Attack dog
; RA2/YR's DOG
; Subsumes DOGJUMP
[DogHusky]
;----- Text -----
Name				= Husky			; Attack Dog
UIName				= name:dog
UIDescription			= desc:dog_husky
Nominal				= yes
;----- Gfx -----
Image				= DOGP			; Hmm...Requires an Image entry to get at Rotates=.  Violates the same name default rule
FirersPalette			= yes
Shadow				= no
;----- Taxonomy -----
Category			= Soldier
NotHuman			= yes
Natural				= yes
IsCanine			= yes
Doggie				= yes



[ADOG]
Name=Attack Dog
Image=ADOG
Primary=DogJaw
Secondary=DogDetect
Elite=MetalJaw
Sensors=yes
CrushSound=SQUISHY2
Strength=250
Armor=light
Fearless=no
Trainable=no
Pip=green
TechLevel=3
Sight=4
Owner=GDI,Nod
AllowedToStartInMultiplayer=no
Cost=300
Points=5
VoiceSelect=IDOGSELA
VoiceMove=IDOGMOVA
VoiceAttack=IDOGATTA,IDOGATCA
VoiceFeedback=IDOGFEA,IDOGFEB,IDOGFEC
VoiceDie=IDOGDIEA
ThreatPosed=25	; This value MUST be 0 for all building addons

Prerequisite=BARRACKS,KENNL


;----- Body -----
Strength			= 100
Size				= 1
PhysicalSize			= 1
;----- Weapons -----
MultiWeapons			= yes
; Primary			= BadTeeth
; Secondary			= DetectDog		; VirtualScanner
Weapon1				= LungeDog
Weapon2				= BiteDog
Weapon3				= DetectDog
NavalTargeting			= 6
; InitialGuardWeapon		= DogDetect		; use this weapon as range override for guardArea purposes
; SelfProtectRange		= 4			; if a potential threat comes closer than this, allways use the attack weapon rather than Detect, even if not ordered to attack
;----- Armor -----
Armor				= none
; ImmuneToPsionics		= yes
ImmuneToVeins			= yes			; VeinProof
ReselectIfLimboed=yes ; If selected when limbo and attacking infantry, reseect when unlimbo
RejoinTeamIfLimboed=yes ; If in a team when limbo shooting infantry, write it down and try to rejoin when unlimbo
DefaultToGuardArea=yes ; the much awaited dog default to move and attack when resting

Pip=white
;----- Perception -----
Sight				= 9
DetectDisguise=yes
;----- Availability -----
Owner				= Soviet
ForbiddenHouses			= Allies,ThirdArmy,Alliance,Forgotten
TechLevel			= 2
Prerequisite			= Barracks
CrateGoodie=yes
;----- AI -----
Fearless			= yes
GuardRange			= 30
LeadershipRating		= 7
;----- Sfx -----
CrushSound			= InfantrySquish			; squishy2



Cost=200

Points=10
IsSelectableCombatant=yes
VoiceSelect=DogSelect
VoiceMove=DogMove
VoiceAttack=DogAttackCommand
VoiceFeedback=DogFear
VoiceSpecialAttack=DogMove
DieSound=DogDie
;----- Movement -----
Speed				= 8
MovementZone			= Infantry
Locomotor			= Walking
ROT				= 8					; requires to use Rotates
Arm				= 2

Proximity=yes
Ranged=yes

SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes


ThreatPosed=20	; This value MUST be 0 for all building addons
Bombable=yes
AllowedToStartInMultiplayer=no
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER,SCATTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
;GEF going to be two dogs now DoubleOwned=Yes
IFVMode=0
Trainable=no



; dog barks at intruder
; [DogDetect]
[DetectDog]
;----- Payload -----
; Damage			= 1			; 2
Warhead				= Barking		; DummyWarhead
ROF=32;0
Range=10 ;7
Projectile=Invisible
Speed=100
Report=IDOGSELA
Bright=no

[JUMP]
;Image=DRONP ;Hmm...Requires an Image entry to get at Rotates=.  Violates the same name default rule
Image=DRON
AA=no
Arm=2
ROT=8 ;requires to use Rotates
Shadow=no
Proximity=yes
Ranged=yes
FirersPalette=yes ; Borrows the convertClass from the firing unit - gets house color too
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes



[ADOGJUMP]
Image=ADOGP ;Hmm...Requires an Image entry to get at Rotates=.  Violates the same name default rule
AA=no
;AN=no
Arm=2
ROT=8 ;requires to use Rotates
Shadow=no
Proximity=yes
Ranged=yes
FirersPalette=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=yes

;------------------------------------------------------------------------------
[HuskyBlast]:[Husky]
;----- Text -----
UIName=Name:dog_husky_blast
Name= Husky Blaster
;----- Weapons -----
Secondary= Suicide
;----- Damage & Destruction -----
Explodes= yes
DeathWeapon= Explosives

;------------------------------------------------------------------------------
; Heavy Dog
; Wolfenstein-ish Attack Dog - Best thing to fit a Nazi-themed side!
;  Praised be thy, YRArg for supplying me with this wonderful shp!
; Now this is a different tier of dog, rather than a replacement. 
; It uses a regular bite attack that deals higher damage to big game. 
; Formerly [GDOG] (TTP, 2008). 
[DogRtwl]
;----- Text ----
Name				= Dog Rottweiler
UIName				= name:dog_rtwl
;----- Gfx -----
Image				= DOGO
;----- Weapons -----
Primary				= DogJaw2				; BeyondTeeth
Secondary=VirtualScanner
NavalTargeting=6
Prerequisite=Barracks
LeadershipRating=7
CrushSound=InfantrySquish
Strength=100
Armor=none
ReselectIfLimboed=yes ; If selected when limbo and attacking infantry, reseect when unlimbo
RejoinTeamIfLimboed=yes ; If in a team when limbo shooting infantry, write it down and try to rejoin when unlimbo
DefaultToGuardArea=yes ; the much awaited dog default to move and attack when resting
TechLevel=2
Pip=white
Sight=9
DetectDisguise=yes
Speed=8
;----- Availability -----
Side				= 
Owner				= ; Chinese,Ukrainians,Spanish,Turkish,Irish,Persians,Kurds
; House				= 
ForbiddenHouses=Russians,Confederation,Chinese,Ukrainians,Africans,Arabs,Persians,Kurds,Americans,Alliance,French,Polish,British
Cost=200
Soylent=50
Points=10
IsSelectableCombatant=yes
VoiceSelect=DogSelect
VoiceMove=DogMove
VoiceAttack=DogAttackCommand
VoiceFeedback=DogFear
VoiceSpecialAttack=DogMove
DieSound=DogDie
ThreatPosed=20	; This value MUST be 0 for all building addons
AllowedToStartInMultiplayer=no
Size=1
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER,SCATTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
ImmuneToPsionics=yes
IFVMode=0
Trainable=no

;------------------------------------------------------------------------------
; Tiberian Hound
; Formerly [MDog]. 
[DogMutTib]
;----- Text -----
Name				= 
UIName				= name:Drog				; Mad Dog
Name				= Mad Dog
Nominal				= yes
;----- Taxonomy -----
Unnatural			= yes
;----- Body -----
Strength			= 120					; 100
;----- Perception -----
Sight				= 2			; 6
;----- Weapons -----
Primary				= LeapAttack
Primary				= PoisonTeeth				; MadTeeth
IFVMode				= SPIT_POISON
;----- Armor -----
Armor				= light
Armor				= mutant_leather			; none
TiberiumProof			= yes
TiberiumHeal			= yes
;----- Availability -----
TechLevel			= 2
Cost				= 450
Points=5
;----- Sfx -----
; VoiceSelect			= FIEND1, FIEND2
; VoiceMove			= FIEND1, FIEND2
; VoiceAttack			= FIEND1, FIEND2
; VoiceFeedback			= FIEND1, FIEND2
; VoiceDie			= FIEND1
;----- UI -----
Pip				= green
;----- AI -----
ThreatPosed			= 25






;----- UI -----
ReselectIfLimboed		= yes
IsSelectableCombatant		= yes

TechLevel=4

;----- Movement -----
Speed				= 7

;----- Procuration -----
Owner				= YuriArmy,HeadQuarters,RoguePsykers,ScorpionCell
;RequiredHouses			= YuriArmy,HeadQuarters,RoguePsykers,ScorpionCell
Prerequisite			= YUMenagery,Any_Kennel
;Prerequisite.Lists		= 2
;Prerequisite.List1		= YUMenagery,UNBarracks
;Prerequisite.List2		= YUMenagery,SUBarracks

Cost				= 300
Soylent				= 150
AllowedToStartInMultiplayer	= no

;----- Scoring -----
Points=10

ThreatPosed=20	; This value MUST be 0 for all building addons
;----- Veterancy -----
VeteranAbilities		= STRONGER,FIREPOWER,ROF,SIGHT,FASTER,SCATTER
EliteAbilities			= SELF_HEAL,STRONGER,FIREPOWER,ROF

;------------------------------------------------------------------------------
; Attack dog
[FDog]
UIName				= Name:Drog				; "Frog Dog", was "Mad Dog"
Name				= Drog
Secondary			= StrangeTeeth
Strength			= 100
TechLevel=2
Pip=green
Sight=4
Speed=8
Owner				= YuriArmy,HeadQuarters,RoguePsykers,ScorpionCell
RequiredHouses			= HeadQuarters
Cost=200
Soylent=50
Points=10
IsSelectableCombatant=yes
VoiceSelect			= FrogSound
VoiceMove			= FrogSound
VoiceAttack			= FrogSound
VoiceFeedback			= FrogSound
DieSound			= 
MovementZone			= AmphibiousInfantry
ThreatPosed=20	; This value MUST be 0 for all building addons
ImmuneToRadiation=no
Bombable=yes
AllowedToStartInMultiplayer=no
Size=1
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER,SCATTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
;GEF going to be two dogs now DoubleOwned=Yes
ImmuneToPsionics=yes
ImmuneToPoison=yes
ImmuneToRadiation=yes
BerzerkAllowed=yes
IFVMode=0
Trainable=no
Natural=yes
Crushable=no
Cyborg=yes

Sight=9

; Attack dog
;Yuri not having a corresponding dog breaks our method for never having 2 dogs or 2 engineers on sidebar
[YADOG]
UIName=Name:DOG
Name=Allied Attack Dog (Yuri version)
NotHuman=yes
Image=ADOG
Category=Soldier
Primary=GoodTeeth
Secondary=VirtualScanner
NavalTargeting=6
Prerequisite=GAPILE
LeadershipRating=7
CrushSound=InfantrySquish
Strength=100
Armor=none
ReselectIfLimboed=yes ; If selected when limbo and attacking infantry, reseect when unlimbo
RejoinTeamIfLimboed=yes ; If in a team when limbo shooting infantry, write it down and try to rejoin when unlimbo
DefaultToGuardArea=yes ; the much awaited dog default to move and attack when resting
TechLevel=2
Pip=white
Sight=9
DetectDisguise=yes
Speed=8
Owner=Russians,Confederation,Africans,Arabs,YuriCountry,British,French,Germans,Americans,Alliance
RequiredHouses=YuriCountry
Cost=200
Soylent=50
Points=10
IsSelectableCombatant=yes
VoiceSelect=DogSelect
VoiceMove=DogMove
VoiceAttack=DogAttackCommand
VoiceFeedback=DogFear
VoiceSpecialAttack=DogMove
DieSound=DogDie
Locomotor={4A582744-9839-11d1-B709-00A024DDAFD1}
PhysicalSize=1
MovementZone=Infantry
;MovementZone=InfantryDestroyer ;GEF wow!!! copy paste bug from the original Disk Thrower!
ThreatPosed=20	; This value MUST be 0 for all building addons
ImmuneToRadiation=no
Bombable=yes
AllowedToStartInMultiplayer=no
Size=1
VeteranAbilities=STRONGER,FIREPOWER,ROF,SIGHT,FASTER,SCATTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
ImmuneToPsionics=yes
IFVMode=0
Trainable=no
Natural=yes







; dog ordered to attack
[DogJaw]
Damage=250
ROF=8
Range=1.5 ;2.83
Projectile=Invisible
Speed=100
Warhead=OrganicBlood
Report=IDOGATTA
Bright=no

[OrganicBlood]
Spread=0
Verses=100%,0%,0%,0%,0%
InfDeath=0
;AnimList=UCBLOOD
Particle=RedSparkSys
Bright=no

[RedSparkSys]
HoldsWhat=RedSpark
BehavesLike=Spark
ParticleCap=15
SparkSpawnFrames=5
LightSize=25
OneFrameLight=true
SpawnSparkPercentage=.2

[RedSpark]
BehavesLike=Spark
MaxEC=500
XVelocity=13
YVelocity=13
MinZVelocity=40
ZVelocityRange=15
ColorList=(255,0,0),(200,55,55),(155,100,100),(0,0,0)
ColorSpeed=.13

; chew on everything
[MetalJaw]
Damage=100
ROF=8
Range=1.5 ;2.83
Projectile=Invisible
Speed=100
Warhead=Super
Report=IDOGATTA
Bright=no

