;
;
;

;------------------------------------------------------------------------------
; [InfantryTypes]
;;; [CavalryTypes] TOT
;;; [UnitTypes] is not valid. 
[VehicleTypes];???
+				= Mountie

;------------------------------------------------------------------------------
; Royal Canadian Mounted Police
; Ranger type, Guard type
[Mountie]
$inherits			= Ranger, Guard
;----- Text -----
Name				= Mountie
UIName				= name:mountie
UIDescription			= desc:mountie
;----- Body -----
Size				= 
;----- Perception -----
Sight				= 10				; Ranger
DetectDisguises			= yes
DetectDisguiseRange		= 3
;----- Weapons -----
Primary				= RangerGun
; Secondary			= PreserveKit
;----- Armor -----
;----- Availability -----
Side				= Allies
; Owner				= 
; House				= 
RequiredHouses			= Canadians
;----- Movement -----
End

;------------------------------------------------------------------------------
[ArrestKit]
;----- Payload -----
DamageType			= subdual
Warhead				= Arrest_W
;----- Projection -----
Projectile			= InvisibleLow
ProjectileObject		= NONE
Range				= 1.5
Speed				= -1
CellRangefinding		= yes
;----- Sequence -----
ROF				= 40			; Something reasonable. 

;------------------------------------------------------------------------------
[Arrest_W]
Verses				= 100%, 100%, 100%, 0%, 0%, 0%, 0%, 0%, 0%, 0%, 0%
AttachEffect.Types		= Capture

;------------------------------------------------------------------------------
; You are under arrest! 
[Capture]
Duration			= 0
Duration.ApplyFirepowerMult	= yes			; Yeah, why not! 
Duration.ApplyArmorMultOnTarget	= no
Cumulative			= false                                   ; boolean
Cumulative.MaxCount		= -1
DiscardOn			= noneList of discard condition enumeration (none|entry|move|stationary|drain|inrange|outofrange|firing|receiveddamage|selling|undeploying|harvesting|invokerdie|ammo|health|mission|landtype|sequence|ownerchange)

DiscardOn.Health.AbovePercent=-1                   ; floating point value
DiscardOn.ReceivedDamage.Count=1                   ; integer
DiscardOn.ReceivedDamage.AffectsHouse=all          ; List of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|neutral|all)
DiscardOn.Missions=                                ; List of MissionTypes
DiscardOn.AIMissions=                              ; List of MissionTypes, default to [AttachEffectType] -> DiscardOn.Missions
DiscardOn.Sequences=                               ; List of Sequences (ready | guard | prone | walk | fireup | fireprone | secondaryfire | secondaryprone | down | crawl | up | idle1 | idle2 | die1 | die2 | die3 | die4 | die5 | deploy | deployed | deployedfire | deployedidle | undeploy | paradrop | cheer | panic | shovel | carry | fly | hover | firefly | tumble | airdeathstart | airdeathfalling | airdeathfinish | tread | swim | wetattack | wetidle1 | wetidle2 | wetdie1 | wetdie2)
DiscardOn.Sequences.Immediate=                     ; boolean, default to [General] -> DiscardOn.Sequences.Immediate
DiscardOn.RangeOverride=                           ; floating point value, distance in cells
DiscardOn.MoveBasedOnDestination=                  ; boolean, default to [General] -> DiscardOn.MoveBasedOnDestination
DiscardOn.ConsiderHarvestingAsStationary=          ; boolean, default to [General] -> DiscardOn.ConsiderHarvestingAsStationary
DiscardOn.OwnerChange.HumanToComputer=true         ; boolean
DiscardOn.OwnerChange.ComputerToHuman=true         ; boolean
DiscardOn.OwnerChange.IgnoreRevertOnExit=false     ; boolean
AllowTransfer=                                     ; boolean
AllowTransfer.Convert=                             ; boolean
PenetratesIronCurtain		= yes
PenetratesForceShield		= yes
AffectTypes=                                       ; List of TechnoTypes
IgnoreTypes=                                       ; List of TechnoTypes
AffectsTarget=all                                  ; List of TechnoType Enumeration (none|infantry|units|aircraft|buildings|all)
Animation=                                         ; AnimationType
Animation.ResetOnReapply=false                     ; boolean
Animation.OfflineAction=Hides                      ; AttachedAnimFlag (None, Hides, Temporal, Paused or PausedTemporal)
Animation.TemporalAction=None                      ; AttachedAnimFlag (None, Hides, Temporal, Paused or PausedTemporal)
Animation.UseInvokerAsOwner=false                  ; boolean
Animation.HideIfAttachedWith=                      ; List of AttachEffectTypes
Animation.DrawOffsetN=0,0                          ; X,Y, pixels relative to default
Animation.DrawOffsetN.RequiredTypes=               ; List of AttachEffectTypes
CumulativeAnimations=                              ; List of AnimationTypes
CumulativeAnimations.RestartOnChange=true          ; boolean
Tint.Color=                                        ; integer - Red,Green,Blue
Tint.Intensity=                                    ; floating point value
Tint.VisibleToHouses=all                           ; List of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|neutral|all)
SpeedMultiplier			= 0.25			; Captured infantry moves at reduced speed. 
ForceDecloak			= yes
DisableWeapons			= yes
