;
;
;
; There were various Vulture entries over the years. 
; This particular one was modded from the [ShikraBike] entry ("Shikra Outrider", formerly Kukhri Hoverbike (2015). 
; Subsumes [Bike_Lunar] (Moonracer). 

;------------------------------------------------------------------------------
[VehicleTypes]
+				= 

;------------------------------------------------------------------------------
; Correcamino Outrider
; Formerly [SpdrVult]. 
[SpdrChur]:[Bike]
;----- Text -----
Name				= Outrider Paisano
UIName				= name:paisano
UIDescription			= desc:paisano
;----- Body -----
Strength			= 
Size				= 
Weight				= 
;----- Weapons -----
Primary				= VultGrenade
; Secondary			= SpiderMine
;----- Armor -----
; "Boostable" means that this unit can be affected by the Nitro Boost ability. 
Armor				= light_small, hover, boostable
; ImmuneToRadiation		= yes
ImmuneToVeins			= yes				; hover
;----- Load -----
Crewed				= yes
Ammo				= 3
;----- UI -----
PipScale			= Ammo
;----- Movement -----
Locomotor			= Hover
MovementZone			= AmphibiousDestroyer

;------------------------------------------------------------------------------
[SpdrPaisE1]:[SpdrPais]
;----- Text -----
Name				= Outrider Paisano Veteran

;------------------------------------------------------------------------------
[SpdrVult3]:[SpdrVult2]
;----- Text -----
Name				= Vulture Outrider Elite

;------------------------------------------------------------------------------
[SpdrVult4]:[SpdrVult3]
;----- Text -----
Name				= Vulture Outrider Heroic
