;
;
;

;------------------------------------------------------------------------------
[VehicleTypes]
+				= Visc
+				= Visc2

;------------------------------------------------------------------------------
; Small Visceroid
; [VISC_SML] (TS)
; Formerly [Visceroid_1]. 
[Visc]
;----- Text -----
Name				= Visceroid Baby
UIName				= name:visc
UIDescription			= desc:visc
Nominal				= yes
;----- Taxonomy -----
Category			= none				; ts: Civilian
SmallVisceroid			= yes
;----- Gfx -----
Image				= VISSML
;----- Body -----
Strength			= 200
Size				= 1
;----- Weapons -----
Primary				= Smooch			; suckle, works like tag
;----- Armor -----
Armor				= light, SkinMutant		; TiberiumHeal does not work for weapon/particle damage. 
TiberiumHeal			= yes
ImmuneToVeins			= yes
;----- Availability -----
Side				= 
Owner				= Special			; ts: Civilian
House				= Incidental
TechLevel			= -1
;----- Score -----
Insignificant			= yes
Sight=0
Speed=8
AllowedToStartInMultiplayer=no
Cost=1
Points=50
ROT=16
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
Locomotor			= {4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone			= Normal
ThreatPosed=0	; This value MUST be 0 for all building addons

; Large Visceroid
[VISC_LRG]
Armor=heavy
TechLevel=-1
Sight=0
Speed=8
AllowedToStartInMultiplayer=no
Cost=1
Points=50
ROT=16
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=20	; This value MUST be 0 for all building addons
GuardRange=5

; Subsumes Nod Adult Visceroid [NAV] (Covert Ops II) 
; Subsumes Artificial Visceroid [ARTVISC]. 
[Visc2]
$Inherits			= Visc
;----- Text -----
Name				= Visceroid Adult
UIName				= name:visc2
UIDescription			= desc:visc2
Nominal				= yes
;----- Taxonomy -----
Category			= none			; monster, VISCLRG/Category = Civilian, NAV/Category = AFV. 
SmallVisceroid			= no
LargeVisceroid			= yes
;----- Gfx -----
Image				= VISLRG
AltImage			= VISLGATK
;----- Body -----
Strength			= 500
;----- Perception -----
Sight				= 2			; NAV/Sight = 2. VISC_LRG/Sight = 0. It effectively makes 
;----- Weapons -----
Primary				= SlimeAttack
;----- Armor -----
Armor				= heavy, SkinMutant
;----- Availability -----
Side				= 
Owner				= 
House				= 
TechLevel			= 10
Prerequisite			= NAWEAP,NATMPL

Sight=2
Speed=8
Owner=Nod
AllowedToStartInMultiplayer=no
Cost=850
Points=50
ROT=16
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
ThreatPosed=20	; This value MUST be 0 for all building addons
VoiceSelect=FIEND1,FIEND2
VoiceMove=FIEND1,FIEND2
VoiceAttack=FIEND1,FIEND2

UIName				= Name:visceroid_small
Name				= Baby Visceroid
Nominal=yes
Prerequisite=
Image=VISSML
Strength=200
Category=Civilian
Armor=slime
TechLevel=1
Sight=0
Speed=8
Owner=Special
AllowedToStartInMultiplayer=no
Cost=600
Soylent=600
Points=50
ROT=16
Explosion=DEMTEXPSML
VoiceSelect=InfantryMelt
VoiceMove=InfantryMelt
VoiceAttack=InfantryMelt
DieSound=DemoTruckExplode
CrushSound=InfantryMelt
MoveSound=InfantryMelt
MaxDebris=3
DebrisTypes=CRYSTAL04
TiberiumHeal=yes
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
SmallVisceroid=yes
ThreatPosed=0	; This value MUST be 0 for all building addons
ImmuneToVeins=yes
Size=1
Trainable=no
Bunkerable=no; Units default to yes, others default to no
Crushable=no
OmniCrushResistant=yes; so Crusher can crush Crushable, OmniCrusher trumps Crushable=no, and then OmniCrushResistant trumps OmniCrusher

;------------------------------------------------------------------------------
; Large Visceroid
[VISC_LRG]
UIName=Name:visceroid_large
Name=Adult Visceroid
;Insignificant=yes
Image=VISLRG
Nominal=yes
AltImage=VISLGATK
Strength=500
Category=Civilian
Armor=slime
TechLevel=-1
Sight=0
Speed=8
TiberiumHeal=yes
Owner=Special
AllowedToStartInMultiplayer=no
Cost=1200
Soylent=1200
Points=50
ROT=16
Explosion=DEMTEXPSML
VoiceSelect=InfantryMelt
VoiceMove=InfantryMelt
VoiceAttack=InfantryMelt
DieSound=DemoTruckExplode
CrushSound=InfantryMelt
MoveSound=InfantryMelt
MaxDebris=3
DebrisTypes=CRYSTAL04
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
LargeVisceroid=yes
ThreatPosed=20	; This value MUST be 0 for all building addons
Primary=SlimeAttack
GuardRange=5
ImmuneToVeins=yes
Size=1
Trainable=no
Bunkerable=no; Units default to yes, others default to no
Crushable=no
OmniCrushResistant=yes; so Crusher can crush Crushable, OmniCrusher trumps Crushable=no, and then OmniCrushResistant trumps OmniCrusher

;------------------------------------------------------------------------------
; NAV (Nod Adult Visceroid) (xxx)
[Visceroid_3]
Name= Ancient Visceroid
Insignificant=no
Prerequisite=NAWEAP,NATMPL
Image=VISLRG
Nominal=yes
AltImage=VISLGATK
Strength=500
Category=AFV
Armor=heavy
TechLevel=10
Sight=2
Speed=8
TiberiumHeal=yes
Owner=Nod
AllowedToStartInMultiplayer=no
Cost=850
Points=50
ROT=16
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
MaxDebris=0
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
MovementZone=Normal
ThreatPosed=20	; This value MUST be 0 for all building addons
Primary=SlimeAttack
VoiceSelect=FIEND1,FIEND2
VoiceMove=FIEND1,FIEND2
VoiceAttack=FIEND1,FIEND2
ImmuneToVeins=yes
