;******************************************************************************
;*** Sonic Tank ***************************************************************
;******************************************************************************
; The '''Sonic Tank''' is a unique weapon design, mounting a large directional speaker on a tank chassis. To attack, it will emit immensely loud directional blasts of sound in the target direction, creating vibrations that ripple matter, not to mention of melting the ears of infantry caught in the blast.

====Skills====
* '''Sound Pulse''' - Deals line-of-fire damage that increases in proportion to the armor of the victims. The blast of sounds disorients its victims, reducing their speed and firepower.
* '''Sound Blast''' - Emitts a weaker circular AoE blast around the tank.

;------------------------------------------------------------------------------
[VehicleTypes]
+				= TnkSonc
; 517998A873496

;------------------------------------------------------------------------------
; Super-Schall-Panzer
; Created by kehen6 as SSTNK. 
; Subsumes [SONC]. 
; Formerly [SonicTank], [TnkSonic]. 
[TnkSonc]:[TnkLgt]
;----- Text -----
Name				= Super-Schall-Panzer
UIName				= name:tnk_sonc				; Name:SSTNKD
UIDescription			= desc:tnk_sonc
;----- Body -----
Health				= 1880
Strength			= 235					; Rationalized as having a lighter turret. 
;----- Weapons -----
Primary				= SonicZap
Secondary			= Sonic
ElitePrimary			= SonicZapE
;----- Armor -----
TypeImmune			= yes					; new
;----- Perception -----
Sight				= 8
;----- Movement -----
Speed				= 4
ROT				= 6
;----- Availability -----
RequiredHouses			= British
TechLevel			= 7
Prerequisite			= UNFactory, RADAR, UNCenterTech
AllowedToStartInMultiplayer	= no
Cost				= 1200
; Soylent			= 1200
;----- Score -----
Points				= 20
;----- AI -----
AiTank				= no
AiSpecial			= yes
;----- Damage & Destruction -----
DebrisTypes			= 
; Explodes			= yes
; DeathWeapon			= SonicTankDeath	; New, causes a widespread, but not (terribly) strong concussion wave...
;----- Sfx -----
VoiceSelect=TankDestroyerSelect
VoiceMove=TankDestroyerMove
VoiceAttack=TankDestroyerAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
CrushSound=TankCrush
MoveSound=TankDestroyerMoveStart
AmbientSound=SonicTankAmbient			; added

;------------------------------------------------------------------------------
; [ATSonicTank] (ebfd)
[TnkSonc2]:[TnkSonc]
;----- Body -----
Health				= 2000
Strength			= 250
;----- Turrets -----
TurretAttach			= ATSonicTankGun
;----- Weapons -----
Primary				= ATSonicTankGun
;----- Armor -----
Armor				= medium_ebfd
Armour				= medium_ebfd
;----- Availability -----
House				= Atreides
PrimaryBuilding			= ATFactory    
SecondaryBuilding		= ATStarport, ORStarport, HKStarport
;----- Score -----
Score				= 4
;----- AI -----
AiSpecial			= yes

Cost = 1400
BuildTime = 648
Size = 2
Speed = 4.0      
TurnRate = 0.1     
ViewRange = 4,8,InfRock
TechLevel = 7
ReinforcementValue = 10
HitSlowDownAmount = 50   
HitSlowDownDuration = 100  
GetsHeightAdvantage = FALSE
AIThreat = 100
;----- Veterancy -----
VeterancyLevel			= 13
ExtraDamage			= 50
VeterancyLevel			= 30
ExtraArmour			= 50
VeterancyLevel			= 60
ExtraDamage			= 25
ExtraRange			= 50

;------------------------------------------------------------------------------
; Sonic Tank
; Disruptor [SONIC] (ts)
; Formerly [SonicTank_2]. 
[TnkSonc3]
;----- Text -----
Name				= Tank Sonic Heavy
UIName				= name:tank_sonic
UIDescription			= desc:tank_sonic
;----- Gfx -----
Image				= tank_sonic			; Formerly Panzer IV with Disruptor (TS) turret...
;----- Body -----
Health				= 4000
Strength			= 500
;----- Weapons -----
Primary				= SonicCannon
Secondary			= 
Elite				= SonicCannon_2
ElitePrimary			= SonicCannon_2
EliteSecondary			= 
NoMovingFire=true		; This MUST be set to true for the sonic tank
;----- Armor -----
TechLevel=6
Speed=5
;----- Availability -----
Prerequisite			= UNFactory, UNTechCenter
Cost=1000
Points=25
;----- Movement -----
ROT				= 4
ThreatPosed=15	; This value MUST be 0 for all building addons

Primary=SonicZap
TechLevel=9
Sight=7
Speed=4
Cost=1300
Points=25
AllowedToStartInMultiplayer=no
MaxDebris=5
ThreatPosed=60	; This value MUST be 0 for all building addons
NoMovingFire=true		; This MUST be set to true for the sonic tank
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=EXPLODES
ZFudgeColumn=12
ZFudgeTunnel=15

Speed=5
Accelerates=false




; Hover Disruptor
; 2005/9/6
[HoverSonicTank]
Primary=SonicZap
UIName=Name:SONIC
Name=Sonic Destroyer
Prerequisite=GAWEAP,GARADR,GATECH
Strength=300
MoveToShroud=yes
Category=Transport
DeployTime=.022
Armor=heavy
Turret=no
IsTilter=yes
TechLevel=8
Sight=6
Speed=6
;Naval=yes
Weight=1
CrateGoodie=no
Owner=British,French,Germans,Americans,Alliance
AllowedToStartInMultiplayer=no
Cost=1900
Points=15
ROT=5
Crusher=no ;gs yes
Passengers=12
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=LandingCraftSelect
VoiceMove=LandingCraftMove
VoiceAttack=GenAllWaterAttackCommand
VoiceFeedback=
DieSound=GenVehicleDie
MoveSound=LandingCraftMoveStart
Maxdebris=3

SpeedType=Hover
Locomotor={4A582742-9839-11d1-B709-00A024DDAFD1}
MovementZone=Amphibious ; gs AMphibiousDestroyer I can't have a destroyer zone without a weapon!

ThreatPosed=3	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
SpecialThreatValue=1
ZFudgeColumn=7
ZFudgeTunnel=13
Size=16
TooBigToFitUnderBridge=true
VeteranAbilities=STRONGER,FIREPOWER,SIGHT,FASTER
EliteAbilities=SELF_HEAL,STRONGER,FIREPOWER,ROF
Trainable=no
IsTilter=yes
TechLevel=9
Turret=yes
Sight=7
Owner=GDI
Cost=1300
Points=25
ROT=4
ThreatPosed=60	; This value MUST be 0 for all building addons
NoMovingFire=true		; This MUST be set to true for the sonic tank
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=EXPLODES



; Disruptor
; Formerly [RESONATOR]. 
[TnkReso]:[TnkHovrSonc]
;----- Text -----
Name				= Resonator
UIName				= name:
UIDescription			= desc:
;----- Body -----
; Strength			= 500
;----- Weapons -----
Primary				= ResonatorWave
;----- Armor -----

Prerequisite=NAWEAP,NATECH
IsTilter=yes
TechLevel=9
Turret=yes
Sight=7
Speed=4
CrateGoodie=yes
Owner=GDI
Cost=1300
Points=25
ROT=4
Crusher=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
AllowedToStartInMultiplayer=no
MaxDebris=5
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
Weight=3.5
MovementZone=Destroyer
ThreatPosed=60	; This value MUST be 0 for all building addons
NoMovingFire=true		; This MUST be set to true for the sonic tank
DamageParticleSystems=SparkSys,SmallGreySSys
EliteAbilities=EXPLODES
ZFudgeColumn=12
ZFudgeTunnel=15




; Covert Ops II's BULLFROG (Behemoth)
[BullfrogTank]
;----- Text -----
UIName				= Name:Tank_Bullfrog
Name				= Bullfrog Tank
;----- Availability -----
Prerequisite			= NAWEAP,NACITA
Cost				= 2250
CrateGoodie			= yes
;----- Weapons -----
Primary				= SonicCannon_2; UltimateSonic
Strength=1200
Category=AFV
Armor=heavy
TechLevel=10
Sight=6
Speed=4
Owner=Nod
Points=60
ROT=5
Crewed=yes
Crusher=yes
TypeImmune=yes
Explosion=TWLT070,S_BANG48,S_BRNL58,S_CLSN58,S_TUMU60
VoiceSelect=25-I000,25-I002,25-I004,25-I006
VoiceMove=25-I012,25-I014,25-I016,25-I018,25-I022
VoiceAttack=25-I014,25-I022,25-I024,25-I026
VoiceFeedback=
MaxDebris=6
SpeedType=Hover
Locomotor={4A582741-9839-11d1-B709-00A024DDAFD1}
Weight=3.5
MovementZone=AmphibiousDestroyer
ThreatPosed=0	; This value MUST be 0 for all building addons
DamageParticleSystems=SparkSys,SmallGreySSys
SpecialThreatValue=1
AllowedToStartInMultiplayer=no
ZFudgeColumn=12
ZFudgeTunnel=15
Image=MCV
